### ISSUE TITLE
Shipping Label: Should handle false $packages

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1004]
In line [229 of class-wc-connect-shipping-label.php](https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-shipping-label.php#L229) we iterate over `$packages`, but it may be set to `false`. We should check for that before iterating.

Right now, we get this warning:

`Warning: Invalid argument supplied for foreach() in class-wc-connect-shipping-label.php on line 229`

**Comment by nabsul** [comment]
I just fixed this experimenting with the pluging
