### ISSUE TITLE
Add WCS to a zone: Next Step tool tip

### ISSUE THREAD

**Issue by msdesign21** [Automattic/woocommerce-services#1007]
When I go to the **WooCommerce > Settings > Shipping** page before setting anything up, I'm shown this helpful tool tip telling me I need to setup a zone: 

<img src="http://cld.wthms.co/rtzpv+"/>

I think it would be good to add a "Next" option which would then highlight the "Add a Zone" button with a short explanation of why you need to setup a zone/explain what it is for: 

<img src="http://cld.wthms.co/mQXIM+"/>

Suggested text: 

> Shipping zones are geographical areas that can have their own shipping options applied. This can be based on select countries, states or zipcodes. For example, you can setup one shipping zone to be specific for your own country and one for international shipping. Add a zone to setup shipping today! 
> [Learn more about shipping zones](https://docs.woocommerce.com/document/setting-up-shipping-zones/)

**Comment by laurendavissmith** [comment]
Closing since we're not focusing on live rates at the moment
