### ISSUE TITLE
[NUX Flow] Add logic to auto-install WooCommerce and Jetpack

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#1011]
On startup, the plugin should check if WooCommerce and Jetpack are installed. If they're not, the admin should be able to install them with one click.

Note: I'll implement these as very simple admin notices for now, pending design by @olaolusoga 

@v18

**Comment by jeffstieler** [comment]
@nabsul

Look to the [Storefront NUX](https://github.com/woocommerce/storefront/tree/master/inc/nux) for inspiration.

Also, [Version 1.5.0](https://github.com/Automattic/woocommerce-services/milestone/20) is our current milestone. 👍

**Comment by v18** [comment]
Awesome! I'm sure you thought of this already, but mentioning this in case it slips through the cracks: I think it would be worthwhile to be able to run the code to download/install Jetpack separately from the admin notice / on install and from the WC install, so that we could use it in the WC setup wizard if we need to.

**Comment by nabsul** [comment]
> I think it would be worthwhile to be able to run the code to download/install Jetpack separately from the admin notice / on install and from the WC install, so that we could use it in the WC setup wizard if we need to.

@v18 Always good to double check and confirm, and yes that's the goal.

**Comment by jeffstieler** [comment]
@v18 - is there any remaining work for this?

**Comment by v18** [comment]
@jeffstieler no remaining work imo. We don't yet have a check to see if WooCommerce is installed, but I think we decided to forgo that. The Jetpack check is done.
