### ISSUE TITLE
invalid JSON returned with <feff> character

### ISSUE THREAD

**Issue by michaljurkowski** [Automattic/woocommerce-services#1030]
json response returned with invalid characters zero width no-break space and all requests fails

in line 335 in  class HttpClient
```
protected function processResponse()
    {
	// removed character <feff> from response
	$response = str_replace('', '', $this->response->getBody());<----- hotfix
        $parsedResponse = \json_decode($response, true);

        // Test if return a valid JSON.
        if (JSON_ERROR_NONE !== json_last_error()) {
            $message = function_exists('json_last_error_msg') ? json_last_error_msg() : 'Invalid JSON returned';
            throw new HttpClientException($message, $this->response->getCode(), $this->request, $this->response);
        }

        $this->lookForErrors($parsedResponse);

        return $parsedResponse;
    }
```

**Comment by jeffstieler** [comment]
@michaljurkowski are you referring to this line in `wc-api-php`? https://github.com/woocommerce/wc-api-php/blob/master/src/WooCommerce/HttpClient/HttpClient.php#L335

I just want to double check - are you posting an issue on the right repository?

**Comment by michaljurkowski** [comment]
Composer was blocked on version 1.1 after updating to version 1.2 everything works fine. Thanks for good helping question.
