### ISSUE TITLE
NUX banner: check Jetpack status using ajax at each step

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1034]
We have these steps in banner.js:

1. install
2. activate
3. connect

We rely on the initial status provided by ajax_data to figure out which steps should go through. Instead, we can rely on a separate ajax function to check the status at each step.

Why? Less brittle. More room for re-trying the flow if someone fails.

**Comment by laurendavissmith** [comment]
Closing, not sure this is relevant now?

**Comment by v18** [comment]
@laurendavissmith - agree. this was mostly a refactor request.
