### ISSUE TITLE
Add support for WordPress.com provided tax rates during checkout

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1035]
We've decided to use the existing TaxJar plugin for this, and proxy the requests.

Feature should

* require jetpack installed and connected + running on pressable as a wp.com site before showing/enabling this feature
* not do anything if the TaxJar plugin is installed and connected
* require WC 3.1 or the WC-API-DEV plugin (for store street level address)
* proxy TaxJar API requests through the WCS server

Old requirements for posterity:

> Feature should
> 
> - require jetpack installed and connected + running on pressable as a wp.com site before showing/enabling this feature
> - distinguish between stores in tax-free, origin-based and destination-based sales tax states.
> - have some simple UI in the tax settings tab to let people know it is working
> - store rates in orders in the same way as the TaxJar wordpress.org plugin
> - provide real-time rates during checkout for destination-based states
> - cache rates for a short while (e.g. 1 hour)
> - not do anything if the TaxJar plugin is installed and connected
> - require WC 3.1 or the WC-API-DEV plugin (for store street level address)

> See also https://github.com/woocommerce/woocommerce/issues/15602 and https://github.com/woocommerce/wc-api-dev/issues/12
> 
> Needs design cc @kellychoffman @jameskoster

**Comment by jameskoster** [comment]
> have some simple UI in the tax settings tab to let people know it is working

To keep things simple I'd rather we give an indication when it's _not_ working. We'd just use the cached rates in that case, correct? If so, something like this could work;

![taxjar-down](https://cldup.com/4FXyJMcKJq-3000x3000.png)
