### ISSUE TITLE
Updates to legal docs

### ISSUE THREAD

**Issue by jennyzhu** [Automattic/woocommerce-services#1037]
1) At https://woocommerce.com/terms-conditions/, we should change 

> Your use of Connect for WooCommerce is governed...

to 

> Your use of WooCommerce Services is governed…

2) At https://woocommerce.com/terms-conditions/services-terms/,  in 

> Please see this page for more information about what data is required and how this data is stored, transmitted, and used...

"this page" should link to https://woocommerce.com/terms-conditions/services-privacy/

**Comment by v18** [comment]
Thanks Jenny! I made those changes, closing this issue.

**Comment by jennyzhu** [comment]
Thanks for the speedy resolution!
