### ISSUE TITLE
Do not make extra DB call if previous call had >1 labels

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1045]
We can dismiss the edit order page pointer if we get a DB query that indicates the user is not new to labels using ([reference](https://github.com/Automattic/woocommerce-services/pull/1039#discussion_r123359158)):

`add_user_meta( get_current_user_id(), 'dismissed_wp_pointers', 'wc_services_labels_metabox' );`

**Comment by nabsul** [comment]
@v18 I thought I solve this here: https://github.com/Automattic/woocommerce-services/blob/q2-nux/classes/class-wc-connect-nux.php#L125

**Comment by nabsul** [comment]
I see, that misses one thing, which is that we might need to forcefully set the dismiss flag if the user is never to see it.
