### ISSUE TITLE
Weight input on the Purchase Label flow is ignored

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1056]
Steps to reproduce:
* Go to an existing order and go to purchase a label.
* On the `Packages` step, change the weight to something crazy, like 60lbs.
* Click the `Use these packages` button.
* See that the rates are the same, and the summary text in the `Packages` step still displays the previous weight.

Somehow the weight input field is being ignored both for UI purposes and when making the rates request. It's probably an easy fix, since it worked some time ago, but we should investigate.

**Comment by DanReyLop** [comment]
All the returned rates are exactly the same price with the original `1lbs` weight and for the edited `60lbs` weight. That doesn't feel right. Just for kicks, I've just tried putting `999lbs` and I got the same result: `1lbs` in the summary of the `Packages` step, and I got the same cheap rates. I haven't checked the server request, but the only explanation is that the input value is getting lost somewhere in Redux-land.

**Comment by jeffstieler** [comment]
After https://github.com/Automattic/woocommerce-services/pull/1070, I am unable to reproduce this.

I used a non-flat rate custom box, retrieved rates with ~2 lbs, then changed to 60 lbs, and the rates went up.

The `UPDATE_PACKAGE_WEIGHT` action is dispatching as expected.

@DanReyLop can you confirm that this has been fixed?

**Comment by DanReyLop** [comment]
Yeah, confirmed, it's fixed! :)
