### ISSUE TITLE
Order of checking TOS messaging needs fixing

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#1060]
![image](https://user-images.githubusercontent.com/11143071/27562552-dacc4ff8-5a81-11e7-8dd5-82cca188f849.png)

https://github.com/Automattic/woocommerce-services/blob/q2-nux/classes/class-wc-connect-nux.php#L186

I think we should first check that the TOS is accepted and return `tos_only_banner`, then return `after_jetpack_connection` if everything else is ok.

**Comment by jeffstieler** [comment]
Is this causing a problem, or is it an optimization?

**Comment by v18** [comment]
Can you outline the steps you took to see the bug & what you saw instead of what you expected? This function has some unit tests, so would be great to outline the bug in there.

**Comment by nabsul** [comment]
Looks like I misunderstood the flow. I guess we're fine here.
