### ISSUE TITLE
When switching package type, package weight should be remembered

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1071]
When switching package type, it goes back to 0 for items without a weight:

![package-weight-goes-back-to-0](https://user-images.githubusercontent.com/11487924/27649621-496b2824-5c00-11e7-84a2-50013c097d0c.gif)

**Comment by jeffstieler** [comment]
@v18 I'm having a hard time reproducing this. Does the product you're testing with have a weight defined?

**Comment by v18** [comment]
@jeffstieler yeh, no weight defined for the product. otherwise it would go back to the total weight (I'm guessing).

**Comment by dechov** [comment]
Can confirm it always returns to the original total weight.
