### ISSUE TITLE
toFixed is not a function

### ISSUE THREAD

**Issue by atarsha** [Automattic/woocommerce-services#1078]
I was receiving an error whenever opening an order after having purchased a label that prevented the tracking information or refund link to appear.

The error was that `toFixed` was not a function on `c.toFixed(2)`.

I am not great with minified JS, and not knowing this codebase at all, I simply did a search in woocommerce-services.js for `c.toFixed(2)` and replaced it with `Number(c).toFixed(2)`

This resolved the issue (for now.)

Like I said, I'm not good with minified JS, so if you need more troubleshooting information, please direct me to what you need, and I'll be happy to gather it.

**Comment by DustinHartzler** [comment]
Customer in 601546-zen is experiencing the same issue

**Comment by DustinHartzler** [comment]
Any thoughts on this one @jeffstieler?

**Comment by dechov** [comment]
Thanks for reporting this in detail! A patch (https://github.com/Automattic/woocommerce-services/pull/1113, casting the "refundable amount" to `Number` as you were doing) will be shipped in the next release, but so far I haven't been able to reproduce this to know if it indicates a more serious problem. If you're aware of anything unusual about the order or the label that might have trigger a peculiar state, do let us know — thanks again @atarsha and @DustinHartzler.
