### ISSUE TITLE
First Class Mail - should have a weight limit of 15.99999 ounces

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/woocommerce-services#1082]
First Class Mail should have a weight limit of 15.9999 ounces - but I'm seeing it returned for things that are heavier.

**Comment by jeffstieler** [comment]
@mikeyarce can you post dimensions / weight of a test product you're seeing this with?

I just tested a 3" x 2" x 1" product that weighs 1 lb (16 oz), and did not receive First Class Parcel as an option.

**Comment by mikeyarce** [comment]
I am not seeing this issue anymore today.  I've followed up with our users who had the problem to see if they are seeing it.

**Comment by jeffstieler** [comment]
@ahalekelly I see you reacted to @mikeyarce's issue - have you experience it as well? If so, are you still seeing the issue occur? Thanks!

**Comment by mikeyarce** [comment]
@jeffstieler I was able to see the issue when you have multiple items each weighing less than 15.99 ounces packed together.  You can see an example site with this problem here: 599353-zd-woothemes

Their product:
![screen shot 2017-07-12 at 10 41 29 am](https://user-images.githubusercontent.com/3220162/28131430-b03b6b9c-66ee-11e7-8210-cbb0005ccdf9.png)

Cart:
![screen shot 2017-07-12 at 10 41 57 am](https://user-images.githubusercontent.com/3220162/28131450-bfeda3f2-66ee-11e7-996b-d0018185e894.png)

**Comment by mikeyarce** [comment]
Also, on that same site, if I create ONE product with 16 oz weight, First class will not show up.

**Comment by jeffstieler** [comment]
@mikeyarce - I was able to reproduce this. The items aren't actually being packed together, which is why First Class Parcel is an option. That is the price for shipping them separately in their original packaging using First Class.

If you create a package that fits both items, they will be packed together and the combined weight will make the package ineligible for First Class.
