### ISSUE TITLE
Link back to Order Details after adding credit card

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1086]
The "create new label" button is hidden when a label payment method hasn't been selected.

![screen shot 2017-07-12 at 9 34 38 am](https://user-images.githubusercontent.com/63922/28126044-a83daa62-66e5-11e7-8070-e1b88b435d3a.png)

If a merchant leaves the Order Details page to add/select a credit card, we should provide an easy way for them to go back to the order.

![screen shot 2017-07-12 at 9 35 45 am](https://user-images.githubusercontent.com/63922/28126057-b0cad876-66e5-11e7-9550-4d6729b263f3.png)

@olaolusoga what's a good UX for this? Should we add a link to take them back? Should we automatically redirect? Something else?

**Comment by dechov** [comment]
Fixed by https://github.com/Automattic/woocommerce-services/pull/1300
