### ISSUE TITLE
Object structure: use object-centric structure, and use arrays instead of object collections

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1088]
We should re-think our object structure in two key ways:
1. Properties of one object are often divided up among many different 'property' objects:
```
// we want obj1 props:
 
weights = {
obj1: 1.2,
obj2: 1.3,
obj3: 1.4
};
 
heights = {
obj1: 10,
obj2: 11,
obj3: 12
};
 
weightWeWant = weights[obj1]
heightWeWant = height[obj1]
```
We should move to a structure where each object contains the properties we care about, like so:
```
obj1 = {
weight: 1.2,
height: 10
};
```
2. often we are using objects when we should be using arrays.

For example: we use an object to list all the packages in an order, but it really should be an array of package objects.

**Comment by jeffstieler** [comment]
> 1. Properties of one object are often divided up among many different 'property' objects:

@v18 can you pull some examples from our codebase where we're doing things inefficiently/incorrectly?

> 2. often we are using objects when we should be using arrays.
> 
> For example: we use an object to list all the packages in an order, but it really should be an array of package objects.

Can you elaborate why an array of package objects is better? IIRC we're creating a unique id for each package, which I assume is being used as the property in the packages object. This allows for direct retrieval of the package object, though off the top of my head I'm not sure that we're actually taking advantage of that structure.

**Comment by v18** [comment]
@jeffstieler my suggestions aren't yet fully formed, so I think this issue requires a bit of digging first, rather than immediately implementing. Maybe it should be labelled `spike`? Sorry that wasn't clear in the original description.

Here's an example of a place where we're talking about a single package (`pckg`, `pckgId`) but we have to look up its rate & errors from separate objects (`selectedRate = selectedRates[ pckgId ] || ''`, `serverErrors = errors.server && errors.server[ pckgId ]`:
https://github.com/Automattic/woocommerce-services/blob/master/client/shipping-label/views/purchase/steps/rates/list.js#L49

(These values are received from the very top parent component using Redux.)

> IIRC we're creating a unique id for each package, which I assume is being used as the property in the packages object

Yeh, you're right the current way is better.
