### ISSUE TITLE
Shipping label tooltip is obscured when pointer is present or dismissed

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1089]
Before and after dismissing the shipping labels pointer, the label details tooltip is obscured by the Shipping Label postbox:
<img width="226" alt="screen shot 2017-07-13 at 4 09 09 am" src="https://user-images.githubusercontent.com/1867547/28156514-1605ee4c-6781-11e7-8ce1-d412fcbc1cc1.png">
(To force pointer to show, remove "wc_services_labels_metabox" from `dismissed_wp_pointers` usermeta value.)

`target.css( 'z-index', '' );` on pointer close would solve the "after dismissal" case but not the "before dismissal":

<img width="251" alt="screen shot 2017-07-13 at 4 08 55 am" src="https://user-images.githubusercontent.com/1867547/28156708-d2091eca-6781-11e7-9abc-35de52c76675.png">
...which might require modifying the (calypso) Tooltip's z-index, or automatically dismissing when purchasing a label.

**Comment by jeffstieler** [comment]
@dechov did the "before dismissal" case occur for you before modifying `dismissed_wp_pointers` or after?

We have some handling of the initial pointer display that should prevent it from showing if labels have already been purchased.

Did you perhaps go through the label flow without dismissing the pointer? We should mark the pointer as dismissed when the "create new label" button is clicked.

**Comment by dechov** [comment]
@jeffstieler I didn't see or test the "before dismissal" case before modifying the usermeta, and yes, I believe the only way it's reachable is by purchasing labels before dismissing — which I agree should trigger automatic dismissal of the pointer.
