### ISSUE TITLE
Canada Post No Priority Rate

### ISSUE THREAD

**Issue by DustinHartzler** [Automattic/woocommerce-services#1097]
Customer in 605328-zen is not able to get a priority shipping rate with Canada Post.

Here are the settings:
<img width="686" alt="screen shot 2017-07-20 at 4 15 01 pm" src="https://user-images.githubusercontent.com/2293077/28437081-5189937e-6d67-11e7-8f7c-101119e983c8.png">

And the only rate that's returned is Regular Parcel, even though that option is not selected:
<img width="1251" alt="screen shot 2017-07-20 at 4 18 38 pm" src="https://user-images.githubusercontent.com/2293077/28437115-7546edca-6d67-11e7-913a-d3b8f8a42cb6.png">

**Comment by DustinHartzler** [comment]
@jeffstieler any thoughts on this one?

**Comment by jeffstieler** [comment]
@DustinHartzler sorry for the delay on this.

I'm unable to reproduce - I'm getting Priority rates from `H2N 2A2` to `M5P 2N7` using a test product (deck of playing cards).

**Comment by DustinHartzler** [comment]
Thanks for checking into it. It looks like the customer switched to FedEx. Marking it closed.
