### ISSUE TITLE
Remove "Package 1 (OF 1)" Header

### ISSUE THREAD

**Issue by ahalekelly** [Automattic/woocommerce-services#1098]
If you don't cut the labels out, the "Package 1 (OF 1)" header on the Letter size labels is rather ugly on the package. For some reason it doesn't show up when you reprint a label, but shows up on the first label. Is it possible to add a setting to not add the header?

And what would be really nice would be a setting to add my own logo in its place, or on the other side, below the label.

**Comment by dougaitken** [comment]
Adding a +1 here for adding custom logo from a [forum post](https://wordpress.org/support/topic/feature-roadmap/#post-9467342)

**Comment by jconroy** [comment]
Closing in favor of tracking the feature popularity on the ideas board [here](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747440-add-ability-to-add-a-custom-logo-to-labels) and [here](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747461-add-ability-to-remove-package-1-of-1-from-labe)
