### ISSUE TITLE
No USPS Ground Rates

### ISSUE THREAD

**Issue by DustinHartzler** [Automattic/woocommerce-services#1100]
User in 599975-zen is not getting USPS Ground Rates at checkout.

I've simulated their setup with my test site and get the same results.

<img width="725" alt="screen shot 2017-07-21 at 10 45 08 am" src="https://user-images.githubusercontent.com/2293077/28468700-bedf1e7c-6e01-11e7-8127-62b3c559ede7.png">

<img width="899" alt="screen shot 2017-07-21 at 10 45 26 am" src="https://user-images.githubusercontent.com/2293077/28468706-c2a81e82-6e01-11e7-84cd-34ebead8dda0.png">

Then, I disabled WooCommerce Services and enabled WooCommerce USPS Shipping premium extension. With this configuration, I was able to get Ground rates:
<img width="915" alt="screen shot 2017-07-21 at 10 41 45 am" src="https://user-images.githubusercontent.com/2293077/28468841-2b23c042-6e02-11e7-8a67-7bd72a899445.png">

The WooCommerce Services debug mode provides no additional information as it only shows which shipping zone has matched.

**Comment by dechov** [comment]
Hi Dustin— thank you for reporting this!

The issue is that the request we are currently making for USPS rates appears to only include those for which commercial rates (as well as retail) are available. We're now in the process of getting this fixed this on the server — thanks again.

**Comment by DustinHartzler** [comment]
@dechov I'm not able to get the rates to pull up. Since it's a server issue, I shouldn't have to update the plugin right?

**Comment by jeffstieler** [comment]
@DustinHartzler we had not yet deployed the server - the fix is now live.

**Comment by DustinHartzler** [comment]
I'm seeing the fix now 👍 

Just a question: is it typical to close an issue before the change goes live on the server? From our end it makes it hard to know when to respond to the customer as we don't know when the deploy is going to take place

**Comment by jeffstieler** [comment]
> I'm seeing the fix now 👍

Great!

> Just a question: is it typical to close an issue before the change goes live on the server? From our end it makes it hard to know when to respond to the customer as we don't know when the deploy is going to take place

It's not typical, and I apologize for that. We should be closing issues in this repo if the fix is completely server related. We should then communicate in Slack that a server deploy went out and what it fixes.

**Comment by ahalekelly** [comment]
I'm still having this issue. USPS Retail Ground shows up when I select Retail Rates, but not when I select Commercial Rates. And there is no option for Parcel Select Ground, the USPS commercial version of Retail Ground.

**Comment by jeffstieler** [comment]
> I'm still having this issue. USPS Retail Ground shows up when I select Retail Rates, but not when I select Commercial Rates.

@ahalekelly - that's expected behavior. There isn't commercial pricing available for the USPS Retail Ground service. See: https://www.usps.com/business/prices.htm

**Comment by ahalekelly** [comment]
I know, but the user experience would be much nicer if you included the Retail Ground rates along with all the other commercial rates when I select Commercial. Isn't that what was meant when @dechov said this?

> The issue is that the request we are currently making for USPS rates appears to only include those for which commercial rates (as well as retail) are available. We're now in the process of getting this fixed on the server

I had to switch to charging retail rates just so my customers could get choose Retail Ground.

**Comment by jeffstieler** [comment]
@ahalekelly if you want to show USPS Retail Ground alongside commercial USPS services, set up 2 USPS shipping methods in the same zone.

In the first method, select commercial pricing and all of the commercial services you'd like to support.

In the second method, only select USPS Retail Ground and make sure that retail pricing is selected.

This should provide the desired result.

**Comment by ahalekelly** [comment]
Thanks, that's a useful workaround.
