### ISSUE TITLE
Taxes: If the user hits save on the TaxJar settings page, tax rates provided by WordPress.com will stop working

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1106]
If the user goes to /wp-admin/admin.php?page=wc-settings&tab=integration&section=taxjar-integration and hits save while on that page, it will bork the filtering logic to insert the override token and tax rates will no longer work on the site 

It is necessary to delete the woocommerce_taxjar-integration_settings option manually to get the logic (and tax rates) working again.

**Comment by jeffstieler** [comment]
Closing - this is irrevelant with https://github.com/Automattic/woocommerce-services/pull/1154.
