### ISSUE TITLE
Import zip code if possible when adding a new instance of a shipping method

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#111]
USPS:
If no instances of WCC USPS exist and we add one, we should import the origin postal code from
1) the origin zip code provided in the purchase labels flow, if available OR
2) the appropriate WooThemes USPS shipping extension option, if available

If an instance of WCC USPS exists and we add another, we should import the origin postal code from that instance into the new instance of USPS.

Canada Post:
If no instances of WCC Canada Post exist and we add one, we should import the origin postal code from the appropriate WooThemes Canada Post shipping extension option, if available

If an instance of WCC Canada Post exists and we add another, we should import the origin postal code from that instance into the new instance of Canada Post.

**Comment by jeffstieler** [comment]
@olaolusoga Perhaps this should default to the store address zip, now that it's part of core?

**Comment by olaolusoga** [comment]
It should @jeffstieler . 

Only scenario I can think of that would break defaulting is if the store location is different from the shipping location, but that's an edge case.

**Comment by jeffstieler** [comment]
This was effectively taken care of in https://github.com/Automattic/woocommerce-services/pull/1165.
