### ISSUE TITLE
In shipping settings "Packages" tab name is not very unique

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#1110]
Other plugins appear to use this name. Should we considering making our tab name more distinctive?

![image](https://user-images.githubusercontent.com/11143071/28924155-8f716dca-7815-11e7-8fa8-33cba860a33f.png)

**Comment by dechov** [comment]
Is it also an option to disambiguate only in the event that we see there's already a "Packages" tab?

**Comment by v18** [comment]
Closing in favour of #1162
