### ISSUE TITLE
Canada Post Zip Code Error Message Typo

### ISSUE THREAD

**Issue by msdesign21** [Automattic/woocommerce-services#1122]
Go to WooCommerce Shipping Settings: 
Shipping zones > Canada > Canada Post (WooCommerce Services)

Says: 

> Origin Postcode is required and should a valid six-character Canadian postal code.

<img src="http://cld.wthms.co/EHwIqF+"/>

Should say: 

> Origin Postcode is required and should be a valid six-character Canadian postal code.

Missing the word `be`

**Comment by dechov** [comment]
Thanks! Fixed for next release.
