### ISSUE TITLE
Disable and hide if possible "Enable order downloads to TaxJar" when using WordPress.com for Tax Rates

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1123]
i.e. this setting:

<img width="628" alt="sales-tax-reporting" src="https://user-images.githubusercontent.com/1595739/29188409-d6d4a058-7dc7-11e7-8165-91de2682a805.png">
 
Why? Because when using WordPress.com for tax rates, 

1) we don't want connected merchant's orders flooding into our account (the intended purpose of the account was solely for real-time cart rates)
2) we don't want all the transactions that order syncing would cause to count against our transaction count
3) merchants will never have access to our account's dashboard

The intention is that, if a merchant wants to sync their orders (and use TaxJar to help them file their taxes) then at that point they get their own TaxJar account and use their own API key - then they can sync to their hearts content.

cc @pmaiorana @kellychoffman

**Comment by jeffstieler** [comment]
Closing - we are no longer using the TaxJar plugin.
