### ISSUE TITLE
Support shipping classes

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1130]
Restrict shipping calculations to specified shipping classes selected using https://github.com/Automattic/wp-calypso/issues/26198.

Note: the primary use case is to restrict Media Mail quotes, but we're taking a generic approach in solving for it.

User requests to support shipping classes in WCS shipping methods:

* https://wordpress.org/support/topic/how-to-tie-usps-shipping-to-specific-shipping-classes/
* https://wordpress.org/support/topic/usps-media-mail-restrictions-2/
* https://wordpress.org/support/topic/a-few-feature-requests-6/

**Comment by v18** [comment]
We need shipping classes so that users will feel confident switching from USPS to WCS:

> People like to use the USPS one instead as a) they can connect to their own USPS account and b) they can specific what category Media Mail is returned for.

From @joelwills

**Comment by laurendavissmith** [comment]
Closing for now since we arent focusing on rates
