### ISSUE TITLE
Disable Phone Number?

### ISSUE THREAD

**Issue by melindahelt** [Automattic/woocommerce-services#1131]
https://wordpress.org/support/topic/disable-phone-requirement-option/

> I am getting a lot of customers who are getting their orders rejected by “wrong phone number” or “bad phone” even though its a valid phone number.
> 
> USPS doesn’t require phone number for shipping, but WooCommerce Serviced plugin does require phone number, so it doesn’t make sense.
> 
> There should be an option to disable phone number in shipping, since its not needed anyways by USPS. Maybe Canada post does, not sure but I am not in Canada.
> 
> Few customs are getting very frustrated by this now, they can’t place the order, and the shipping plugin requires a phone number.

Is this possible to change, at least for USPS orders?

**Comment by keninbassart** [comment]
This was replied to here: https://wordpress.org/support/topic/disable-phone-requirement-option/#post-9515857

As the phone number is not a requirement added by WCS we can not remove that field or make it optional.
