### ISSUE TITLE
Receiving an error product_missing_weight

### ISSUE THREAD

**Issue by tuesdayjune** [Automattic/woocommerce-services#1134]
I am receiving this error, when my site is trying to calculate shipping cost.  All my products have weight indicated. But no matter what product is selected, system generates this error when calculating cost.  So no cost is given, so it reverts to 'fallback' rate.  

Error. Unable to get shipping rate(s) for wc_services_usps instance id 6. (calculate_shipping)
08-22-2017 @ 22:48:20 - product_missing_weight Product ( ID: 524 ) did not include a weight. Shipping rates cannot be calculated. (calculate_shipping)

**Comment by jeffstieler** [comment]
Hello @tuesdayjune,

Are you still experiencing issues getting rates?

**Comment by tuesdayjune** [comment]
Yes, but it appears to be happening because of caching . I need to call my
web provider.

**Comment by jeffstieler** [comment]
> Yes, but it appears to be happening because of caching . I need to call my
web provider.

Ok, I'll go ahead and close this issue then.

Please don't hesitate to open a new issue if you continue to have issues.
