### ISSUE TITLE
Add Tracking Number shortcode to be used in emails provided by WC Services 

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#1139]
Will be great to have the functionality where WC Services would provide a  shortcode for the tracking number once the shipping label is created. 

This shortcode can then be added to the email template to be sent to the customer of the site letting them know that the product was shipped and provide a tracking number.

**Comment by JamesJosephFinn** [comment]
I also created #1156 which is related to this

**Comment by jeffstieler** [comment]
> This shortcode can then be added to the email template to be sent to the customer of the site letting them know that the product was shipped and provide a tracking number.

@juliaamosova can you elaborate on your imagined usage of this shortcode? How would a store owner put the shortcode into their email template? etc..

**Comment by juliaamosova** [comment]
@jeffstieler I am sorry for the delayed response! 

Now that I think about it further, the shortcode idea may not necessarily work since there isn't an _easy_ way to modify the Completed Order Email Template and include shortcode (if any). What I think will be great is to have a Shipment Tracking Number automatically included in the Completed Order Email that is sent to the user upon order is marked as _Completed_. Much like it currently works with Shipment Tracking Number widget (extension). If there is a tracking number entered within the widget upon the order being marked as Completed, the number will be included in the email:

![](https://cloudup.com/cJxE-AJpU3h+)
Image Link: https://cloudup.com/cJxE-AJpU3h

![](https://cloudup.com/ciUH2-aRcbn+)
Image Link: https://cloudup.com/ciUH2-aRcbn

**Comment by JamesJosephFinn** [comment]
@juliaamosova this is my thinking exactly. PR #1158 is working on it.

**Comment by juliaamosova** [comment]
@JamesJosephFinn great, thanks for pointing out the PR!

**Comment by joshuaja** [comment]
@JamesJosephFinn - that PR is specific to integration with the Shipment Tracking plugin - I think isssue #391 is a better reference.

**Comment by joshuaja** [comment]
@juliaamosova - I'm about to submit a Pull Request for this - please see #391 for a screenshot.

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1173 - tracking numbers are now included in the Completed Order emails.
