### ISSUE TITLE
Print multiple order labels in one go

### ISSUE THREAD

**Issue by dougaitken** [Automattic/woocommerce-services#1150]
Couldn't find this proposed previously so here it is. 

From a [forum question](https://wordpress.org/support/topic/feature-roadmap/).

> My feature request is to print labels for multiple orders at once.

The customer would like to bulk print all labels rather than per order.

**Comment by v18** [comment]
Mentioned in p7bbVw-2rL-p2

**Comment by v18** [comment]
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/11051733-bulk-print-postage-labels-with-stamps-com-api

**Comment by v18** [comment]
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/6651149-add-bulk-printing-to-stamps-api-or-stamps-xml-plug

**Comment by laurendavissmith** [comment]
Closing since its on the ideas board

**Comment by dougaitken** [comment]
Fro reference - https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/33876214-bulk-printing-of-shipping-labels-in-woocommerce
