### ISSUE TITLE
UX messaging makes an impression that International shipping is not available

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/woocommerce-services#1151]
### Summary:

UX messaging on the checkout page makes an impression that International shipping is not available.

### What happened:

Even though international shipping is available, when only the foreign country is selected from the country dropdown we get a message that not shipping method is available which is not very accurate.

![](http://cld.wthms.co/wL31iv+)
[demo](http://cld.wthms.co/wL31iv+)

### Steps to replicate:

1. Add a product to cart.
2. Goto checkout page and select an international country [other than the home country].
3. Now you will see the message that no shipping method is available.
4. Please note that when the complete address is filled up then the rates are displayed but this scenario can cause confusion.

@allendav @jeffstieler 
670683-zd-woothemes

**Comment by jeffstieler** [comment]
@spraveenitpro this behavior is part of core WooCommerce, not WooCommerce Services.

The relevant code is here: https://github.com/woocommerce/woocommerce/blob/e143a51cc741c127476e4a919b75905f7408701f/templates/cart/cart-shipping.php#L50

Anyone experiencing this could add a filter to change the message. Note the `woocommerce_cart_no_shipping_available_html ` and `woocommerce_no_shipping_available_html ` filters applied to the message linked above.
