### ISSUE TITLE
Add insurance to shipment

### ISSUE THREAD

**Issue by duffk** [Automattic/woocommerce-services#1152]
It would be great to be able add insurance based on the cost of the product.

**Comment by stephhjacq** [comment]
another request for this via 1250731-HC

**Comment by jconroy** [comment]
Closing in favor of tracking popularity for this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38546338-add-additional-insurance-to-usps-shipping-methods)
