### ISSUE TITLE
Products are being packed into a box that won't fit them

### ISSUE THREAD

**Issue by spraveenitpro** [Automattic/woocommerce-services#1157]
### Summary:

Products are being packed into a box that won't fit them.

### Steps to replicate the issue:

1. Select the following options for WooCommerce services: ![](http://cld.wthms.co/yzgqA1+)
[Direct Link](http://cld.wthms.co/yzgqA1+)
2. Now create a product with these dimensions: ![](http://cld.wthms.co/vWsgbm+)
[Direct Link](http://cld.wthms.co/vWsgbm+)
4. Packaging setting ![](http://cld.wthms.co/S0v7jZ+)
[Direct Link](http://cld.wthms.co/S0v7jZ+)
3. As per [USPS](https://store.usps.com/store/browse/uspsProductDetailMultiSkuDropDown.jsp?productId=P_O_FRB1) the inner dimension of the Priority Mail Medium Flat Rate Box is `279.4 X 216 X 140`
4. When you add one of the product to cart we get one box for the shipping cost `$13.60`
5. When we add two of this product we need to get the costs `$13.60 X 2` as two boxes will be required, but we see that when we add two the 2 products are squeezed into one box: ![](http://cld.wthms.co/0RachG+)
[Direct Link](http://cld.wthms.co/0RachG+)

683622-zen
@allendav @jeffstieler

**Comment by jeffstieler** [comment]
@spraveenitpro - I can confirm that this is a bug in our box packer (in our server layer). We'll look at making an incremental improvement to avoid this issue, but know that work on the box packer is quite time consuming.

**Comment by spraveenitpro** [comment]
Thanks @jeffstieler ccing you on the zendesk ticket so that we both are on sync, hope that is fine.

**Comment by spraveenitpro** [comment]
Following up with @jeffstieler for any update on this [customer following up]

**Comment by DanielSantoro** [comment]
Customer also followed up in live chat, so we'll want to reach out to them in a ticket with news as soon as we get it

**Comment by spraveenitpro** [comment]
another one 711954-zen

**Comment by v18** [comment]
@dechov added a test for this in https://github.com/Automattic/woocommerce-connect-server/commit/56d13b0890b8aa2523fbcc7cb167d0ffa67282e0

**Comment by zwiesman31** [comment]
Checking to see if there are any updates here? Thanks!

**Comment by jeffstieler** [comment]
Not yet @zwiesman31. We'll keep you in the loop on any progress.

**Comment by jessepearson** [comment]
Pinging again here, the ticket has been and the customer has been patiently waiting since September.
