### ISSUE TITLE
Deleted product results in fatal error

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-services#1159]
see ticket: 686108-zen

To reproduce:

1. WooCommerce Services is enabled
2. An order exists with more than one item in the order
3. One of the order items has been deleted
4. Attempting to load the order results in a fatal error similar to:

>PHP Fatal error:  Cannot use object of type stdClass as array in .../wp-content/plugins/woocommerce-services/classes/class-wc-connect-shipping-label.php on line 203

**Comment by jeffstieler** [comment]
Thanks for the report @WillBrubaker! I was able to reproduce this. 👍

**Comment by jeffstieler** [comment]
Fixed in #1169.
