### ISSUE TITLE
How to change base address (return address) for Shipping labels?

### ISSUE THREAD

**Issue by ValeDeOro** [Automattic/woocommerce-services#1160]
Customer asks how to change the sender's address by default. 

The documentation only says to "enter your full address if this is the first time you are shipping" (https://docs.woocommerce.com/document/woocommerce-services/#section-6), but there is no indication as to where to change this address in the future. 

User says that changing it once does not carry over to subsequent labels. 

How and where can they change it?

**Comment by ValeDeOro** [comment]
@jeffstieler may I draw your attention to this? Feel free to tag anyone else that might be the source of all knowledge here.

**Comment by jeffstieler** [comment]
> User says that changing it once does not carry over to subsequent labels.

Hmm, that could be a bug. We'll try to reproduce it.

> How and where can they change it?

To change it, right now you'd have to go into an Order and click Create Label, change the Origin address and successfully receive Rates for that shipment. That's when we're updating the Origin address behind the scenes.

With WooCommerce 3.2 introducing a full address field in General Settings, we should revisit where this Origin address is managed.

**Comment by ValeDeOro** [comment]
> To change it, right now you'd have to go into an Order and click Create Label, change the Origin address and successfully receive Rates for that shipment

That still means you'd have to change this manually every time you have a new order, right?

**Comment by jeffstieler** [comment]
> That still means you'd have to change this manually every time you have a new order, right?

This should only change when the address the store is shipping **from** changes. Perhaps I'm not understanding the use case here - why does the origin address need to change with every order?

**Comment by ValeDeOro** [comment]
> This should only change when the address the store is shipping from changes.
That is exactly what happened and I can't figure out where they would put these changes in, because WooCommerce settings only ask for the country (and the state), but you don't put your real address anywhere.

**Comment by jeffstieler** [comment]
> And they need to update this for every new order

This sounds like a bug. Once rates are retrieved for one label using an origin address, it should be saved for future uses.

**Comment by jeffstieler** [comment]
@ValeDeOro - I just tried to reproduce this, but could not. Is there a ticket where I can see what the user is doing?

**Comment by ValeDeOro** [comment]
Here you go 695570-zen

**Comment by DanielSantoro** [comment]
Any updates on this one? User is asking. :)

**Comment by jeffstieler** [comment]
@DanielSantoro I can't access the ticket for some reason. :(

**Comment by DanielSantoro** [comment]
Hm, it doesn't look like there's much to it, really - what we've gotten is:

**Message 1:**
> How do I change my shipping label return label?

**Message 2:**
> That’s great but how do I change it by default so I don’t have to change it on every order? Where did it grab it from?

Then just checking in on status updates. ¯\_(ツ)_/¯

**Comment by ValeDeOro** [comment]
Just restating the question to maybe make this easier: 

Where do our shipping labels populate the senders address from? 

It looks like it always takes the address that was entered the first time a shipping label was created. 

If this is the case, how do I change that address (e.g. when my business has moved)?

Would uninstalling the plugin and reinstalling it (thus triggering a "first time" again) maybe do the trick?

**Comment by jeffstieler** [comment]
@ValeDeOro I know it's not very intuitive, but I outline the steps to change the address before:

> To change it, right now you'd have to go into an Order and click Create Label, change the Origin address and successfully receive Rates for that shipment. That's when we're updating the Origin address behind the scenes.

So to break that down further. The user should:

1. Go to an order that requires shipping (they can reuse an order they've already shipped)
1. Click "create label"
1. Expand "Origin address"
1. Change the address as desired
1. Click "Use this address"
1. Make sure that new Rates are retrieved
1. The new Origin address should be saved

After performing the steps above, the order details page can be refreshed to make sure the new address was saved. If it is not saved, there could be an issue.

**Comment by ValeDeOro** [comment]
> The new Origin address should be saved

Tested this again on our test site, and this time it worked! Back to the customer making sure that he actually buys a label (since that seems to be the confirming step), instead of just testing up to "print label" :)

Thank you for your patience!
