### ISSUE TITLE
[Labels] Can't print labels on iOS

### ISSUE THREAD

**Issue by joshuaja** [Automattic/woocommerce-services#1166]
When clicking on the "reprint" link, choosing the paper size, and clicking "Print" it does nothing on iOS. This is a non-starter for our business because the wifey prints her labels from her iPad while crafting her creations.

I'm assuming this is due to the call to `print()` within the React client component [here](https://github.com/Automattic/woocommerce-services/blob/b98ab1c14a2e93505f9448189107526551c21521/client/lib/utils/print-document.js#L46-L63)

Can we just load the PDF in a new tab instead of doing the whole iFrame thing and calling print()?

From a UX perspective it's an extra click but I think most people are used to previewing PDFs in a new tab before printing nowadays.

Help me understand the back story for the cases in the above client code and I can submit a Pull Request with a change if needed.

**Comment by DanReyLop** [comment]
> I'm assuming this is due to the call to print() within the React client component here

Yeah, you're totally right, that's causing it. If you want to look at more scary cross-browser logic, [check out this](https://github.com/Automattic/woocommerce-services/blob/b98ab1c14a2e93505f9448189107526551c21521/client/lib/utils/pdf-support.js). That's the "backstory" you were missing :)

> From a UX perspective it's an extra click but I think most people are used to previewing PDFs in a new tab before printing nowadays.

It's an extra click, as opposed to not being able to print the PDF at all. I think the decision is clear :)

We'll just add `iOS` as a special case (like Firefox is now) so it opens the PDF in a new tab (with an extra click). May be a good time to try it in an Android phone too.

**Comment by joshuaja** [comment]
@DanReyLop - Just a follow-up I tested this in Chrome on an Android phone (Samsung S6). It downloads the PDF to the device (I'm assuming it hits the `default` case).

**Comment by joshuaja** [comment]
@DanReyLop - Fixed and tested in PR #1185

**Comment by johndcoy** [comment]
Looks like this issue has resurfaced. Clicking Print on Safari using an iPad 7 does nothing other than close the reprint window.

I replicated this issue in browserstack but also on a physical iPad using two different sites.

**Comment by harriswong** [comment]
I gave a few iPad a test on browserstack. It seems like a few of them stopped including `iPad` in their `navigator.userAgent`. 
![image](https://user-images.githubusercontent.com/572862/96931832-2b9a5680-147b-11eb-9bab-5ef3a8c87fdc.png)

This causes the condition to fall back to `default` and use `print()` as it described originally in this issue.
