### ISSUE TITLE
Rework TOS banner to include non-shipping functionality

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1175]
<img width="1021" alt="screen shot 2017-10-06 at 10 38 35 am" src="https://user-images.githubusercontent.com/63922/31288700-40a4dc72-aa83-11e7-9fd0-99281e0c5d25.png">

Now that WCS include automated taxes, stripe account creation, and shipping - we need to rework this banner to be relevant for all users.

**Comment by kellychoffman** [comment]
Let's use a more generic illustration. The WP 'Create' one makes the most sense here. 

https://cloudup.com/coGMQtwIK4s
