### ISSUE TITLE
Typo: should be 'choose' not 'chose'

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/woocommerce-services#1184]
https://github.com/Automattic/woocommerce-services/blob/c06bb0e3a693a304e150086c28c0695da5476259/client/apps/settings/components/settings-form/index.js#L43

> Now add your zip code and chose which services you want to offer your customers.

Should say:

> Now add your zip code and choose which services you want to offer your customers.

**Comment by DanReyLop** [comment]
Thanks for reporting that! Fixed in https://github.com/Automattic/woocommerce-services/commit/3707637b8c99dc9b94cdab17dc2bc5aaeea24246
