### ISSUE TITLE
Show TOS-only banner for users who are already connected to Jetpack

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1188]
Steps to repro:

1. Ensure Jetpack is installed + connected
2. Uninstall all WooCommerce and WooCommerce Services things. Remove all DB options, etc
3. Go through WC wizard using a US locale, and make sure to enable Stripe + enter your email to create an account automatically
4. After you finish the wizard, go to the plugins page
5. See this banner:

<img width="1509" alt="screen shot 2017-10-13 at 8 28 18 am" src="https://user-images.githubusercontent.com/11487924/31535047-c2f3cbcc-aff9-11e7-8064-a077313c3741.png">

This banner directs users to connect to Jetpack. It's incorrect because in this case the user is already connected to Jetpack.

Instead, we should display this banner:

<img width="774" alt="tos-only-banner" src="https://user-images.githubusercontent.com/11487924/31535124-232035b2-affa-11e7-873f-c157538d242a.png">

This banner should save the TOS_accepted option.

**Comment by dechov** [comment]
👍 As I understand it, the idea behind merging them was to keep the wording of features consistent, but I believe that's moot now that [get_feature_list_for_country](https://github.com/Automattic/woocommerce-services/pull/1177/files#diff-02948c6603eae6cf021f42bde08b17c8R360) has been abstracted out, and they should be uncombined again.
