### ISSUE TITLE
TOS-only banner - are the words right?

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1192]
Is the text for the TOS-only banner we have correct for these types users:
1. Already have Jetpack connected
2. Already have WCS
3. Need to accept our TOS
4. May have come from the wizard & opted in to WCS-related options

Current verbiage:

> [title:] Connect your store to activate WooCommerce Services

> WooCommerce Services is almost ready to go! Once you connect your store you'll have access to automated tax calculation, live shipping rates, shipping label printing, and smoother payment setup.
By clicking "Connect", you agree to the Terms of Service and to share certain data and settings with WordPress.com and/or third parties.

> [button:] Connect

A screenshot:

<img width="726" alt="screen shot 2017-10-13 at 11 50 35 pm" src="https://user-images.githubusercontent.com/11487924/31567752-436ee2f6-b071-11e7-8ca6-bca044727d9d.png">

Some thoughts from @dechov about this from https://github.com/Automattic/woocommerce-services/pull/1190/files#r144597025

> The verbiage here in title, description, and button_text (and perhaps should_show_jp) still evokes something more involved than flipping the TOS bit — as in, if they've already connected their store to Jetpack, so what are they connecting it to now?

> Even if it doesn't say "Connect to Jetpack" in this case, why overload the term? I understand that we want to redisplay the terms, but in the event we do want the term "Connect" for accepting WCS terms, we should at least clarify that they're connecting to not-Jetpack in my opinion.

cc @dechov @jeffstieler @jennyzhu

**Comment by jennyzhu** [comment]
Regarding legal language, as long as those links direct to https://en.wordpress.com/tos/ and https://jetpack.com/support/what-data-does-jetpack-sync/ -- that works!

**Comment by v18** [comment]
@jennyzhu thanks! we've got https://wordpress.com/tos/ instead of https://en.wordpress.com/tos/ (it redirects to https://en.wordpress.com/tos/, though). Is that cool?

https://jetpack.com/support/what-data-does-jetpack-sync/  is exactly what we have, so all set there.

**Comment by jennyzhu** [comment]
@v18 Yes definitely, that's my bad! Thank you :)

**Comment by jeffstieler** [comment]
Pulling my comment from https://github.com/Automattic/woocommerce-services/pull/1190/files#r144597025 for posterity:

> In this scenario, the user is in effect connecting their store to WooCommerce Services (SaaS layer). Since they're now opting into WCS, more of the Jetpack TOS apply to them, so we redisplay those terms.

**Comment by dechov** [comment]
Small update to keep this relevant: the "connect to what" piece of it may no longer apply in light of https://github.com/Automattic/woocommerce-services/issues/1377, but I think there's still an aspect of "what does it mean to be setting up my store in this context / how is it different than what I've already done?"

**Comment by jeffstieler** [comment]
> I think there's still an aspect of "what does it mean to be setting up my store in this context / how is it different than what I've already done?"

Totally agree. Perhaps we can reword the already-connected-Jetpack flow so that it plainly explains what we actually need - merchants to acknowledge that more of the TOS (they previously agreed to) applies to them now.

cc: @allendav as I believe this would put us more inline with GDPR expectations

**Comment by c-shultz** [comment]
Reopening this because the wording is still (rightfully) confusing people: https://github.com/woocommerce/woocommerce-admin/issues/5089

@elizaan36, can you weigh on this one? Do you think we should update the wording on this? There's no connection taking place when the button is clicked. It's just agreeing to the ToS.

**Comment by elizaan36** [comment]
hey @c-shultz, the copy in this step of the onboarding wizard has already been updated to something else. This looks like an older version.

I had a look at the [linked issue](https://github.com/woocommerce/woocommerce-admin/issues/5089) and I think it's referring to a different problem:
> Once OBW is completed, note that there will be a notice throughout WooCommerce pages to Connect your store to activate WooCommerce Services which is now redundant since we already completed the connection.

It's not necessarily this step shown above but the banner that follows people around that's redundant.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/5121465/92193770-bb823380-ee2e-11ea-936a-9c88042008a3.png">

**Comment by c-shultz** [comment]
Thanks for taking a look! Yeah, I see I focused on the wording when the confusion was more around the fact that the banner didn't need to appear after going through that flow. Closing again! Sorry for the extra noise!
