### ISSUE TITLE
Shipping method init crashes when country's default service isn't supported by currency

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1193]
Services are limited by currency as of https://github.com/Automattic/woocommerce-connect-server/pull/984, which may be causing an error. Testing with country=USA and currency=GBP, this is the error:

> Notice: Trying to get property of non-object in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php on line 443
> 
> Fatal error: Uncaught Error: Call to a member function get_service_schema() on boolean in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php:448 Stack trace: #0 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php(466): WC_Connect_Loader->add_method_to_shipping_zone(0, 'usps') #1 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php(605): WC_Connect_Loader->init_core_wizard_shipping_config() #2 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php(515): WC_Connect_Loader->attach_hooks() #3 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(298): WC_Connect_Loader->after_wc_init('') #4 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /srv/www/wordpress-default/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /srv/www/wordp in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce-services/woocommerce-services.php on line 448

Setting high priority since GBP is the default and doesn't change when selecting country.

**Comment by jeffstieler** [comment]
This will also need to have a corresponding change in the core setup wizard. We can be defensive and check for the symptom here, but the root cause is that we're allowing `USA`+`GBP` stores to configure live rates.

**Comment by jeffstieler** [comment]
We should make sure `$instance` isn't `false` here: https://github.com/Automattic/woocommerce-services/blob/master/woocommerce-services.php?utf8=%E2%9C%93#L448

We should also align the check here (https://github.com/Automattic/woocommerce-services/blob/master/woocommerce-services.php?utf8=%E2%9C%93#L457) with the service side, which checks currency instead of country.
