### ISSUE TITLE
Automated taxes: 'Learn more' link doesn't give you specific info on taxes

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#1202]
Feedback from Product research lab at WooConf:

<img width="766" alt="screen shot 2017-10-27 at 1 57 32 pm" src="https://user-images.githubusercontent.com/5835847/32122772-cd5036ac-bb1e-11e7-9c9b-2e11cc3d3766.png">

If you want to learn more about taxes, the Learn More link goes to the Services extension page on .org repo, which doesn’t give you any specific info relating to taxes.

**Comment by MarinaWoo** [comment]
Two ideas for this would be to:

1. add a section on taxes to: https://docs.woocommerce.com/document/woocommerce-services/ 
2. create a page like we have for shipping (https://woocommerce.com/products/shipping/)

I think 1. should happen regardless, but 2. requires a bit more resource and not sure it's enough of a priority?

**Comment by pmaiorana** [comment]
Agree with your take @MarinaWoo. I don't think there's enough "meat" yet to justify a standalone page. Is Pi good to run with updating the documentation, or should Partnerships/Hydra take that?

**Comment by laurendavissmith** [comment]
Closing since the OBW is currently being looked at
