### ISSUE TITLE
Shipping labels: I am unable to deselect a payment method

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#1209]
Found in: WooCommerce > Shipping> Shipping Labels. We have highjacked normal checkbox behavior and made it impossible to deselect a payment method. I understand we don't want users to break things, but we should do this another way. 

I vote we: 

1. Add a toggle to match the calypso ui. This toggle turns the shipping labels feature on and off. This would look like: [toggle] Enable shipping labels. This would be defaulted to on if the user opted into WCS.
2. Allow users to deselect the payment method

**Comment by dechov** [comment]
1. There is now a toggle, which disables the create new label button, and https://github.com/Automattic/woocommerce-services/issues/1232 tracks the question of how else we might want the disabled state to appear.

2. Design change awaiting code review in https://github.com/Automattic/wp-calypso/pull/22504 removes hijacked checkboxes. What would be an appropriate interaction for deselecting the payment method? Just clicking the selected one?

<img width="790" alt="screen shot 2018-02-26 at 11 26 26 pm" src="https://user-images.githubusercontent.com/1867547/36738016-77500a2e-1baa-11e8-9862-948c97d678eb.png">

**Comment by kellychoffman** [comment]
> What would be an appropriate interaction for deselecting the payment method?

Good question. Should we allow someone to deselect a payment? I was thinking we would only allow adding, removing, or switching to another card. In the latter scenario, they'd just click on another card.

**Comment by dechov** [comment]
@kellychoffman Sounds fine to me — was the original concern specific to the hijacked checkbox behavior then, and doesn't apply in https://github.com/Automattic/wp-calypso/pull/22504?
