### ISSUE TITLE
Taxes: Add endpoint to expose tax subsystem state to authorized callers

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1210]
In support of https://github.com/Automattic/wp-calypso/issues/17110 it would be immensely helpful to let REST API clients know more about the environment WooCommerce Services tax subsystem is operating in. This information can then be used to decide how REST API powered clients can best display tax settings for the store.

For v1, the ideal endpoint would expose (to authorized callers) whether or not the TaxJar plugin is active and configured with an API key (and thereby performing tax calculations.)

**Comment by allendav** [comment]
@jeffstieler - please let me know if this is OK for me to provide a PR for, or if this is not desired in the client

cc @justinshreve

**Comment by jeffstieler** [comment]
@allendav it would make some sense to me to include this in WCS if it isn't available any other way.. but isn't this possible using Jetpack APIs?

**Comment by allendav** [comment]
@jeffstieler I don't think Jetpack APIs allow getting arbitrary options, but I will confirm that

**Comment by justinshreve** [comment]
> I don't think Jetpack APIs allow getting arbitrary options, but I will confirm that

If you can't do that and don't want it here, Then we could just add a basic custom endpoint exposed through https://github.com/Automattic/wc-calypso-bridge. (That's instead of `wc-api-dev`, since this isn't something we would want in core.)

**Comment by allendav** [comment]
@justinshreve wrote:

> If you can't do that and don't want it here, Then we could just add a basic custom endpoint exposed through https://github.com/Automattic/wc-calypso-bridge. (That's instead of wc-api-dev, since this isn't something we would want in core.)

We could add it there, but I still think woocommerce-services makes more sense for a couple reasons... 1) an active taxjar changes the behavior of woocommerce-services and 2) if we want to (eventually) support non-atomic stores in calypso, we won't want to have to have them install the wc-calypso-bridge plugin, so i'd rather not add this there now just to have to move it later

So... I'd still like to add it here

(BTW for perpetuity, I've confirmed that TaxJar does not expose its settings via the `GET /wc/v3/settings/tax` response, which is too bad and I've also confirmed that Jetpack cannot expose the `woocommerce_taxjar-extension_settings` option via its `sites` endpoint )

**Comment by allendav** [comment]
@justinshreve  @jeffstieler : idea - I noticed that the TaxJar plugin doesn't hook and force all the things unless the plugin is active AND the user has enabled it. Maybe we could change the client here

https://github.com/Automattic/woocommerce-services/blob/57f576b820a236bff0be04b603ee6e2f34a76864/classes/class-wc-connect-taxjar-integration.php#L30

to not just check the class (indicating plugin activation) but also check the integration's enabled setting.  We could then use the absence of the wc_connect_taxes_enabled key in the GET /wc/v3/settings/tax to detect that TaxJar plugin is managing taxes and use that to drive the changes needed for https://github.com/Automattic/wp-calypso/issues/17110

Its a little brittle, since it depends on TaxJar plugin internals staying the same (i.e. them not doing things unless the user checks that box), but I think the likelihood of that is small.

What do y'all think? How about we try that approach first before adding an endpoint? I can put this issue on ice and open a new issue to tweak that line if you're ok with it

**Comment by jeffstieler** [comment]
> What do y'all think? How about we try that approach first before adding an endpoint? I can put this issue on ice and open a new issue to tweak that line if you're ok with it

Much better than creating a new endpoint. Let's go for it.

**Comment by allendav** [comment]
Looks like you commented while I was editing my comment to say it wouldn't work - I'm going to probably have to move forward with the endpoint unfortunately (see rationale above.)

**Comment by allendav** [comment]
Closing this issue, at least for now, to keep the field open on how we want to solve the how-to-present it ( in clients like Calypso ) when we have WCS and TaxJar plugin both active on a site.
