### ISSUE TITLE
Create endpoint to validate a shipping method configuration

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1212]
Currently, we perform some extra validation in the Hydra server before saving a shipping method's settings. To accomodate the Calypso flow (validate **without** saving when the user closes the method modal), we'll need a new endpoint that only does validation.
Alternatively, we can modify the existing "save" endpoint to accept an extra optional flag to just do validation.

**Comment by jeffstieler** [comment]
Extra validation like having at least one service selected?

**Comment by DanReyLop** [comment]
> Extra validation like having at least one service selected?

Currently, yes, the only extra validation we do in the server (apart of validating against the JSON schema) is to check if the user has at least 1 service enabled.

We have left the door open for the server to perform more complex validations than the client, but on the other hand, the only one that we have is trivial to implement client-side. What do you think about it? Should the Calypso port just have client-side validation?

**Comment by jeffstieler** [comment]
> Currently, yes, the only extra validation we do in the server (apart of validating against the JSON schema) is to check if the user has at least 1 service enabled.
> 
> We have left the door open for the server to perform more complex validations than the client, but on the other hand, the only one that we have is trivial to implement client-side. What do you think about it? Should the Calypso port just have client-side validation?

IIRC we only implemented it on the server because it was either difficult or impossible to define that validation in JSON Schema. It would be nice to have it occur client side (in Calypso) so we can avoid a server hit we know will fail.

I'd look to see if it can be done in JSON Schema first. If not, we can discuss the merits of doing it client side since that would introduce more hard-coded/non-data-driven logic.

**Comment by DanReyLop** [comment]
> I'd look to see if it can be done in JSON Schema first. If not, we can discuss the merits of doing it client side since that would introduce more hard-coded/non-data-driven logic.

Sounds good. In any case, adding the validation logic client-side would be easier (by every possible meaning of the word) than creating a new endpoint and making sure it's hit before closing the "shipping method" modal.
