### ISSUE TITLE
Make the WCS shipping methods use the standard REST API for reading & updating

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1215]
Right now we are using a custom `GET`/`POST` REST endpoint. It would simplify the Calypso code if the method settings (and method instance settings) could be loaded the same way as the built-in shipping methods.

Note that this would only work in WC 3.0+, so if we implement it we would still need to maintain the custom endpoints, or drop WC 2.6 compatibility. Probably not worth it for initial release.

**Comment by laurendavissmith** [comment]
Closing for now since we arent focusing on rates
