### ISSUE TITLE
Lettermail not an option: is that intended?

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-services#1217]
Similar to #951 of Canada Post not having predefined options, when forced to create a custom package, then using the settings for Canada Post Lettermail - https://www.canadapost.ca/tools/pg/manual/PGletterml-e.asp doesn't result in targetting the prices of this option, it defaults to parcel services.

On the test site:

### Rubic picture has dimensions that fit in lettermail size: 

![http://cld.wthms.co/2cJkXu](http://cld.wthms.co/2cJkXu+)
Link to image here: http://cld.wthms.co/2cJkXu.

### Lettermail package is created with the right sizes:

Necessary sizes:

![http://cld.wthms.co/n3N5aS](http://cld.wthms.co/n3N5aS+)
Link to image here: http://cld.wthms.co/n3N5aS.

Package on test site: 

![http://cld.wthms.co/CyGDhe](http://cld.wthms.co/CyGDhe+)
Link to image here: http://cld.wthms.co/CyGDhe.

### The result is rather high prices for a letter size product to be sent within the same city

![http://cld.wthms.co/GfbjBb](http://cld.wthms.co/GfbjBb+)
Link to image here: http://cld.wthms.co/GfbjBb.

### Ticket

774752-zen

**Comment by jobthomas** [comment]
@jeffstieler any input on this?

**Comment by jeffstieler** [comment]
@jobthomas it was never intentionally excluded - it seems that the Canada Post API does not include Lettermail.

The extension we have states in the docs that it's a non-API implementation: https://docs.woocommerce.com/document/canada-post/#section-3

**Comment by jobthomas** [comment]
Ah, thanks for that clarification. Wow, and sorry for not reading that in the docs, I can't believe I looked over that. 😳

**Comment by jeffstieler** [comment]
No worries @jobthomas - in fact it's a good feature request. Do you mind opening an issue to request it?
