### ISSUE TITLE
Automated taxes not reflected in order total on WC 3.2.x

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1223]
https://wordpress.org/support/topic/automated-taxes-not-calculating/

> The automated taxes module appears to be working in calculating the tax, the trouble is, it will not add it to the cart’s total (despite displaying it in the cart)

**Comment by fastdivision** [comment]
@jeffstieler We updated the TaxJar plugin a couple weeks ago and ultimately decided to hook into [`woocommerce_calculated_total`](https://github.com/taxjar/taxjar-woocommerce-plugin/pull/40/files) to add tax to the grand total. WooCommerce 3.2 changed the cart totals calculation process, preventing us from getting the necessary data with discounts, creating a new tax rate in the system, and re-calculating the total solely from `woocommerce_calculate_totals`. To do that, we'd somehow have to instantiate [WC_Cart_Totals](https://github.com/woocommerce/woocommerce/blob/3.2.0/includes/class-wc-cart.php#L1248) again, which would call the [`calculate`](https://github.com/woocommerce/woocommerce/blob/3.2.0/includes/class-wc-cart-totals.php#L135) method and subsequently invoke [`woocommerce_calculate_totals`](https://github.com/woocommerce/woocommerce/blob/3.2.0/includes/class-wc-cart-totals.php#L785) at the end of the process.

https://github.com/taxjar/taxjar-woocommerce-plugin/pull/40

If your team has any proposals on how we can better handle this, please let me know.

My apologies for the delayed communication, we'll be sure to post an issue here if we see another breaking issue with WooCommerce and the TaxJar plugin in the future.
