### ISSUE TITLE
Feature request: Lettermail

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-services#1228]
As per #1217, Canada Post's Lettermail isn't a format that can be used through WCS, resulting in quite high prices to send something of a letter format (these prices were for a photograph product to be sent within the same city):

![http://cld.wthms.co/GfbjBb](http://cld.wthms.co/GfbjBb+)
Link to image here: http://cld.wthms.co/GfbjBb.

It would be great to have this added as an option.

cc @jeffstieler

**Comment by mikeyarce** [comment]
Also requested in a chat today

**Comment by kjsdraws** [comment]
Please add this feature. One of my clients regularly sends calendars by mail and if she sends one or two in the same package it qualifies as lettermail. Lettermail is almost $10 less than sending it as a parcel.

**Comment by laurendavissmith** [comment]
Closing since we're not focusing on live rates at the moment
