### ISSUE TITLE
Question: Canadian Store want to Ship via Canada Post but use USD as base currency

### ISSUE THREAD

**Issue by grapevinecs** [Automattic/woocommerce-services#1231]
There seems to be an issue with the shipping service selection, it's auto selected based on base currency of store. Our store is in Canada and shipping via Canada Post but want out base currency set to USD, if I set my base currency to USD, It then selects my shipping service as USPS and doesn't allow me to choose Canada Post instead.

![image](https://user-images.githubusercontent.com/33766712/32972056-1c11e36c-cba5-11e7-8845-768af0d90913.png)

above are the only options available when the store is set to USD. How can I use Canada Post instead?

Cheers

**Comment by jeffstieler** [comment]
Unfortunately, the reason we're not allowing Canada Post + USD is that the rates returned by the Canada Post API are in CAD.
