### ISSUE TITLE
Error notice says "Details are logged here." They aren't actually logged though...

### ISSUE THREAD

**Issue by ryanr14** [Automattic/woocommerce-services#1233]
I came across this issue when updating some documentation and making videos for both USPS & Canad Post.

The error I ran into was that the sample data that's installed by Storefront doesn't have any shipping details set. So when either of these shipping services tries to get rates based on the products they can't, no big deal as Services will give you this warning below.

![http://cld.wthms.co/71Wgea](http://cld.wthms.co/71Wgea+)

The only problem is if you follow that link there isn't anything in the Debug log. Which is where I expected to find how to fix my error notice. 📦 

![http://cld.wthms.co/K9Ozqt](http://cld.wthms.co/K9Ozqt+)

**Comment by dechov** [comment]
@ryanr14 I know some time has passed, but have you seen this issue since? I'm not sure why the log wouldn't have been written to — would you be able to confirm whether other WC logs were populated?

**Comment by ryanr14** [comment]
Hi @dechov! Thanks for the follow-up, I'm sorry I've been slow to respond.

This still happens to me on my Pressable site I originally created the issue from, but in doing more tickets I have seen the logs populate in customers sites. I do have all the other normal WooCommerce logs. :) 

![http://cld.wthms.co/qdtuPI](http://cld.wthms.co/qdtuPI+)
