### ISSUE TITLE
Canada Post predefined packages section should be hidden?

### ISSUE THREAD

**Issue by ryanr14** [Automattic/woocommerce-services#1234]
As no predefined packages are available with Canada Post, it seems to make sense that that section could be hidden if only using Canada Post for shipping. :)

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1216:

<img width="736" alt="screen shot 2017-11-22 at 5 22 49 pm" src="https://user-images.githubusercontent.com/63922/33154999-cd92aa38-cfa9-11e7-89d8-734d9c6286bf.png">

<img width="628" alt="screen shot 2017-11-22 at 5 21 06 pm" src="https://user-images.githubusercontent.com/63922/33154960-91d8d77e-cfa9-11e7-9c00-a72a7f5ca45e.png">

The "service package" tab will be empty, but it's only visible when clicking through "add a package".
