### ISSUE TITLE
Deactivated due to an error: Plugin file does not exist

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1238]
Observed just now on a test site of mine.  Plugin does NOT appear in the Plugins > All view in wp-admin. Subsequent attempt at installing WooCommerce Services again also fails. Maybe related to today's new release?

<img width="1432" alt="screen shot 2017-11-22 at 12 31 57 pm" src="https://user-images.githubusercontent.com/1595739/33148772-f35a77d2-cf81-11e7-9ca9-5be00f53aa86.png">

<img width="798" alt="screen shot 2017-11-22 at 12 33 46 pm" src="https://user-images.githubusercontent.com/1595739/33148771-f338c01a-cf81-11e7-8315-b85180a9b236.png">

**Comment by jeffstieler** [comment]
Were you able to reproduce this @allendav? I suspect this was an error during plugin update.

Are you OK with closing this? We can reopen if it happens again.

**Comment by allendav** [comment]
OK to close. P2'd you. Root cause unlikely WooCommerce Services.

**Comment by marcusquinn** [comment]
might help fix these kinds of issues: https://github.com/wpallstars/wp-fix-plugin-does-not-exist-notices
