### ISSUE TITLE
Clarification on expected behavior re: shipping tax

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-services#1240]
In ticket: 792757-zen it was reported that shipping tax is being added by automatic taxes via WooCommerce Services even though the shipping method tax status is set to none. e.g.
![see screen shot](http://cld.wthms.co/LxCUcD+)

![see screen shot](http://cld.wthms.co/pGYA31+)

and we're trying to get some clarification on whether or not this is intended/expected behavior. If it is expected, can the tax status help tip be filtered to reflect that this setting will be ignored with auto with automatic taxes?

**Comment by jeffstieler** [comment]
@WillBrubaker can you confirm that this is still an issue?

I was unable to reproduce (8.45% rate applied to $2):

<img width="611" alt="screen shot 2018-02-14 at 9 21 04 am" src="https://user-images.githubusercontent.com/63922/36215164-93f8464c-1168-11e8-872e-51e3ecdf7e7c.png">

**Comment by WillBrubaker** [comment]
@jeffstieler Tax not added to shipping when shipping method is set as non-taxable in my testing so, no, this does not appear to be an issue at this time.
