### ISSUE TITLE
Issue with Default Package Behavior in Shipping Label Generator 

### ISSUE THREAD

**Issue by jenlynnemc** [Automattic/woocommerce-services#1247]
User is receiving this error when trying to create a shipping label for a product that has proper dimensions:

Validation failed: Length is required when dimensions are supplied with parcel, Width is required when dimensions are supplied with parcel, Height is required when dimensions are supplied with parcel

Verified that the dimensions are added to that item.
Older orders were created the same way with the same item purchased and the shipping labels printed fine with the same dimensions. 

Ticket: 815433 -Zen

Thanks for your help. Please let me know if there is anything additional I can provide.

**Comment by jeffstieler** [comment]
My recollection isn't 100% on this issue, but after reviewing logs - I can no longer reproduce the issue on the latest version of WCS (1.11.0 as of this comment).

This should no longer be a problem! Don't hesitate to reopen the issue should this reoccur. Thanks!
