### ISSUE TITLE
Subscription sign-up fees are not being accounted for, making taxes incorrect

### ISSUE THREAD

**Issue by NickGreen** [Automattic/woocommerce-services#1250]
Internal Prospress ticket #2710

### Problem

The Signup Fee is not being accounted for in the total making taxes incorrect. This is being reported on several tickets.

### Duplication

WooCommerce Services: by Automattic - 1.9.0
WooCommerce Subscriptions: by Prospress Inc. - 2.2.15
WooCommerce: by Automattic - 3.2.5

Set up subscription product for a 16.99/month with 1 month free and a $600 dollar signup fee.

Cart totals

SUBTOTAL $16.99
TAX $1.32
TOTAL $18.31
RECURRING TOTALS
SUBTOTAL $16.99 / month
TAX $1.32 / month
RECURRING TOTAL $18.31 / month
First renewal: December 22, 2017

Confirmed that each product is marked as taxable with the standard rate.

**Comment by jeffstieler** [comment]
This was closed in [Version 1.10.0](https://github.com/Automattic/woocommerce-services/releases/tag/v1.10.0)
