### ISSUE TITLE
Enhancement Request: Allow renaming/editing of service titles

### ISSUE THREAD

**Issue by ldr2273** [Automattic/woocommerce-services#1251]
Currently, users can select which services they'd like to offer, but they cannot rename these titles. For example, a store owner wants to offer Priority Mail but they'd like it to display as "Priority Mail (1-3 days)", they cannot edit or adjust this information like they can with other shipping extensions.

![Edit Service Name](https://cloudup.com/cuI44NJg_TH+)

Also, when viewing this on the front end, the service title includes "Flat Rate" in addition to the service name, and this can be confusing:

![Flat Rate](https://cloudup.com/ctd-Eh2r3oZ+)

I would love to see if we can have these service titles behave like method titles that can be edited and customized. Thanks!

**Comment by formosattic** [comment]
+1 

The "Flat Rate" part is confusing, defaulting to the service title, or just "Priority Mail" would be clearer.

Ticket: https://woothemes.zendesk.com/agent/tickets/881886

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
