### ISSUE TITLE
Github page for woocommerce services appears broken

### ISSUE THREAD

**Issue by pranksteratom** [Automattic/woocommerce-services#1252]
is all of github down or is it just woocommerce services page isn't working cuz there's a ton of bugs in this code from weeks ago with no solution.  oh well.  i guess it's foolish to rely on anything open source for commerce?

**Comment by jeffstieler** [comment]
Hello @pranksteratom,

Congrats on making your first Github issue!

> is all of github down or is it just woocommerce services page isn't working

Github goes down from time to time - you can always check their status [here](https://status.github.com/messages), though I don't think you're being serious.

> cuz there's a ton of bugs in this code from weeks ago with no solution.

We take user feedback very seriously - can you please point me to the bugs that are affecting you? 

Our team has to balance new feature development with fixing bugs, so there's a triage system in place. Knowing that a bug has no workaround or is being experienced by several users helps us prioritize a fix over other responsibilities.

> oh well. i guess it's foolish to rely on anything open source for commerce?

I'm sorry you've had a bad experience. [Lots of people](https://trends.builtwith.com/shop) rely on open source Ecommerce software.
