### ISSUE TITLE
Zero Tax rate set to a non-zero rate

### ISSUE THREAD

**Issue by slash1andy** [Automattic/woocommerce-services#1256]
This came up with a VAT Disability Exemption chat. Turned out that the reason that the VAT wasn't being taken off is that it applies the Zero-rate tax rate to the order, and the Zero-rate was actually 20% VAT, like the regular rate. I had to turn off the automated taxes because it wouldn't let me manually change the rate. I could change the other settings on the rate, just not the actual rate (or it would revert).

All prices inclusive of tax, using automated taxes.

Shop location: ![](http://cld.wthms.co/cyOAzo+)
Standard Rates: ![](http://cld.wthms.co/nC6cAw+)
Zero Rates: ![](http://cld.wthms.co/2LDomR+)

**Comment by c-shultz** [comment]
Closing this stale issue. We can re-open if this comes back up.
