### ISSUE TITLE
Support for APO, FPO, MPO military addresses

### ISSUE THREAD

**Issue by JamesJosephFinn** [Automattic/woocommerce-services#1258]
The widget will not appear on order pages for orders that have a military post office shipping address, such as:

```
Joe Blow
PSC 1000 BOX 1000
APO, AE 10101
```

[The USPS processes](https://www.stamps.com/whitepapers/usps-military-mail-guide.pdf) packages destined for military post office locations for the same domestic rates, so this shouldn't be an issue.

**Comment by JamesJosephFinn** [comment]
I just noticed #979, which is labeled as "temporary", and was closed by #980, which makes this "missing widget" the expected behavior.

Since disabling the widget on military addressed orders is a "temporary" solution, any idea when support for military addresses will be shipped?

**Comment by jeffstieler** [comment]
> Since disabling the widget on military addressed orders is "temporary", any idea when support for military addresses will be woven in?

@JamesJosephFinn - customs form support is a prerequisite to supporting military shipments, so after that. 👍

**Comment by JamesJosephFinn** [comment]
Right, logical. I'm closing this then. Thank you!
