### ISSUE TITLE
Priority Boxes not used for Priority International

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#1272]
In the Packaging Manager, if you enable the Priority boxes for USPS they're used for domestic shipping but not International.

![Screenshot](http://joelwills.com/bNHSDp+)

Link to image: http://joelwills.com/bNHSDp

For International orders, items are not packed into these though as far as I can tell (and a customer mentions) you can use those boxes for domestic or international.

This causes international orders to pack items individually and return high costs unless custom boxes are added.

**Comment by jeffstieler** [comment]
@joelwills - we just deployed a server change that should resolve this issue. Can you verify?

**Comment by joelwills** [comment]
Sorry for the delay @jeffstieler 

Yes this is working for me now.

US Order:

![Screenshot](http://joelwills.com/BWhAxz+)

Link to image: http://joelwills.com/BWhAxz

International Order:

![Screenshot](http://joelwills.com/5IpMeM+)

Link to image: http://joelwills.com/5IpMeM

Many thanks!
