### ISSUE TITLE
Print return label

### ISSUE THREAD

**Issue by lindamork** [Automattic/woocommerce-services#1281]
902677zd

Customer writes:

> "Would you please add an option next to "Reprint" label button so we can also print return label for customer?
> 
> All it has to do is reversing the sender and receiver address and we can easily purchase return label for customer. And after purchasing return label, automatically email the label (pdf file) to the customer when we press the Update button. This is really important feature hope you implement it ASAP."

**Comment by jconroy** [comment]
Closing in favor of tracking popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747173-add-ability-to-print-return-labels)

**Comment by lovelacecreativeco** [comment]
For anyone seeing this on GH, I've created a way to easily swap Origin & Recipient Addresses with the WooCommerce Shipping Plugin. You can find the PHP script on my GitHub. 

[WooCommerce Shipping: Switch Addresses](https://github.com/lovelacecreativeco/woocommerce-shipping-switch-addresses)
