### ISSUE TITLE
How to generate shipping label if there is free shipping.

### ISSUE THREAD

**Issue by redsparkers** [Automattic/woocommerce-services#1287]
1. In one of our site we have also a free shipping option. when user choose this free shipping after that in admin we generate the shipping label the shipping package are still there  and apply rates from USPS Mail boxs
Refer the attachment - edit order wordpress 
![edit order wordpress 1](https://user-images.githubusercontent.com/35765884/35330265-e12e290e-0128-11e8-9295-fda84c0177cb.png)
2. if we added the first class mail in shipping , it doesnot show in Add a package service section 
Refer the attachemnt -woocommerce settings wordpress 2
![woocommerce settings wordpress 2](https://user-images.githubusercontent.com/35765884/35330360-4f9a5908-0129-11e8-9ccd-24540a986507.png)

**Comment by jeffstieler** [comment]
@redsparkers 

First Class mail doesn't have any predefined packaging. You'll need to either mark both items in the order as "ship in original packaging" or define a custom package that you'll use to ship both items together.

Once you define a custom package you can select it in the "Packages" step, and if it meets the criteria for First Class mail, you'll see that as an option in the "Rates" step.

**Comment by v18** [comment]
Hi @redsparkers - I'm going to close this issue since Jeff answered your question, and we haven't heard back from you in a while. I hope it worked for you :) Feel free to re-open this issue or open a new one if you have any more questions!
