### ISSUE TITLE
Free Shipping for Order Total of $50+

### ISSUE THREAD

**Issue by Krautshooter** [Automattic/woocommerce-services#1302]
We offer free shipping on orders over $50. 
We have it set up as an option in the "Shipping Zone" ... but on check-out the system still calculates shipping cost when the cart total is over $50 and only offers the "Free Shipping" as a clickable option (see snapshot). It should simple say "Free Shipping" and NOT offer it as a clickable option. Clients will mess this up when finalizing the order!
![capture](https://user-images.githubusercontent.com/34444563/35828133-14302906-0a84-11e8-8eba-93f9138bf92f.JPG)

**Comment by DanReyLop** [comment]
Hi,

We consider that behaviour you describe is out of scope for this plugin. For a given shipment, it just returns one or more USPS shipping options, which will then be added to the other shipping methods you have configured (in this case, `Free Shipping`). For more complex logic, you need custom code or a different plugin that alters the way the shipping methods are listed.

Fortunately, a plugin exists to do exactly what you want: https://wordpress.org/plugins/wc-hide-shipping-methods/

Hope that helps :)

**Comment by Krautshooter** [comment]
It does help! Thanks! And thanks for the very swift reply/solution! :)
