### ISSUE TITLE
GDPR: Add support for personal data export for a given email address

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1323]
In support of GDPR personal data export requirements, for each order created with the buyer's billing email, the personal data exported should include at least the following:

- any tracking number added by WooCommerce Services
- any WooCommerce Services shipping labels associated with the order*

* need to determine if label images are necessary here or if the # of labels or a list of label IDs would suffice (or something else?)

The ideal implementation will work in the same manner as any personal data export technique to be implemented by WooCommerce itself.

Related: https://github.com/woocommerce/woocommerce/issues/19277
Related: https://github.com/Automattic/woocommerce-services/issues/1324
Related: https://core.trac.wordpress.org/ticket/43438

**Comment by allendav** [comment]
Also interesting - https://github.com/woocommerce/woocommerce/pull/19330/files

**Comment by allendav** [comment]
Also need to export the stripe connect account email address collected from the merchant, if any

**Comment by jeffstieler** [comment]
Done in https://github.com/Automattic/woocommerce-services/pull/1392
