### ISSUE TITLE
Summary of total spent on labels

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#1327]
A customer was asking if it's possible to get a summary of all the postage purchased through WooCommerce Services.

While you can get it from your credit card company you have to sum up all transactions.

It would be nice to see a report totaling amount of money spent (and perhaps saved?!) through using WooCommerce Services label printing.

**Comment by jeffstieler** [comment]
Another: https://wordpress.org/support/topic/awful-reports-no-additional-services-or-return-labels/
