### ISSUE TITLE
No First-Class Mail - international letter rate returned

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-services#1344]
Or maybe it is and shouldn't be - we're getting different results on different sites.

See ticket: 1026343-zen for more context. 

On that site and at least two other test sites (my own and one belonging to @stephhjacq ) the following conditions cause this to happen:

1. A product exists with the following dimensions: 
![see screen shot](http://cld.wthms.co/bG8ASp+)
2. The store base location is set to somewhere in the U.S. (not sure how relevant this is)
3. A shipping method exists in the "Locations not covered by your other zones" - only the one, e.g.:
![see screen shot](http://cld.wthms.co/UU3haR+) 
4. That shipping method only has one service, "First-Class Mail - International Letter"
![see screen shot](http://cld.wthms.co/i98zX6+)

This results in "no shipping methods" on the customer site and the two test sites, however, a rate is returned on our test site here: https://a8c-wcs-support.mystagingwebsite.com (creds in secret store)

So...either there is something preventing the rate from being returned on the three sites OR the rate shouldn't be returned on the HE services test site (USPS 'value of contents cannot exceed $0') for that particular service but changing the product price to $0 doesn't seem to help.

**Comment by jeffstieler** [comment]
We aren't surfacing the error anywhere - but it appears that the `94101` zip code is invalid.

You can test zip codes here: https://tools.usps.com/go/ZipLookupAction_input#cityByZipCode

I used `90210` and was able to get rates, including First-Class Mail International Letter.

**Comment by WillBrubaker** [comment]
We have https://a8c-wcs-support.mystagingwebsite.com configured to use that same zip code for the "Locations not covered by your other zones" so...that shouldn't be returning rates then and yet, it does.

**Comment by jeffstieler** [comment]
I just checked the test store - it's set to `94104`, not `94101` like your above screenshot:

![screen shot 2018-03-20 at 9 50 20 am](https://user-images.githubusercontent.com/63922/37666043-312441b6-2c24-11e8-842a-a1d94af5feb8.png)

**Comment by madeincosmos** [comment]
Turns out to be a problem with package sizes - when I add an envelope of correct dimensions, the First Class International Letter works fine. Closing for now :)
