### ISSUE TITLE
Rename `normalized` prop

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1345]
See: https://github.com/Automattic/wp-calypso/pull/22499/files/bed9969f9332ed4222a757aad3c3a829c1c7a436#r175477842 & https://github.com/Automattic/wp-calypso/commit/8353a11207cbb5e7069d2567040cc27b99e28b00

The `normalized` prop passed around for address normalization is a bit vague - rename to `normalizedValues` or similar for clarity.

**Comment by laurendavissmith** [comment]
Closing since this will likely get outdated with architectural changes
