### ISSUE TITLE
Cart totals are incorrect when using Automated Taxes and manual Standard Rates simultaneously

### ISSUE THREAD

**Issue by shaunkuschel** [Automattic/woocommerce-services#1348]
Using Automated Taxes while also having manual tax rates entered on the Standard Rates page, causes the total calculations to be incorrect.

**Expected behavior:**

The 'Total' price displayed on the cart/checkout pages equals the costs of the products in the cart, any applicable shipping costs, and any applicable taxes.

**Actual behavior:**

When Automated Taxes should not be collected (due to the customer being in a different state than the shop location) and the store has Standard Rates entered for that state, the total cost is not correct.

Here is an example where taxes should not be collected, but there is a Standard Rate entered and it is added to the total:

![](http://cld.wthms.co/DMhTXn+)
(Link to screenshot: http://cld.wthms.co/DMhTXn+)

As seen in the screenshot, the Tax field correctly shows "0.00", but the total is including the unseen tax rate from the Standard Rates page.

![](http://cld.wthms.co/QQ0exm+)
(Link to screenshot: http://cld.wthms.co/QQ0exm+)

 If the Standard Rates are removed, the math is correct.

![](http://cld.wthms.co/0VCTZM+)
(Link to screenshot: http://cld.wthms.co/0VCTZM+)

**Steps to reproduce:**

- Set up a Standard Rate for any state other than where the shop is based
- Enable automated taxes
- Go through checkout flow
- Tax rate should be correct but total is incorrect
- Remove Standard Rate and retest
- Total should be correct now

Below are the rest of the tax settings used to reproduce:

![](http://cld.wthms.co/Y338To+)
(Link to screenshot: http://cld.wthms.co/Y338To+)

**Comment by jeffstieler** [comment]
I think we can mark this closed @shaunkuschel - we no longer allow access to the tax rates tables (as TaxJar does also) and https://github.com/Automattic/woocommerce-services/pull/1372 added the following message, set tax options to required values, and disabled the inputs:

![screen shot 2018-05-30 at 12 41 27 pm](https://user-images.githubusercontent.com/63922/40740727-d576404c-6406-11e8-84e8-78a931cef099.png)

**Comment by shaunkuschel** [comment]
Cool, marking it as closed. Thanks, @jeffstieler!
