### ISSUE TITLE
USPS Shipping: Regional Rate A & B not working

### ISSUE THREAD

**Issue by madeincosmos** [Automattic/woocommerce-services#1349]
### Affected tickets 

1039569-zen

### What I expected

To ship small items over Regional Rate A or B

### What happens instead

Even though the items fit into Rate A and B boxes, these rates are never returned from USPS

### Steps to reproduce

1. Only enable Regional Rate A & B as shipping methods:

![Screenshot](http://cld.wthms.co/H45sBB+)
Screenshot: http://cld.wthms.co/H45sBB

2. Create a small product that will fit into regional rate boxes with no problems (i.e. 12oz, 3.5 x 3 x 3 in)
3. Add the product to cart and observe there are no shipping methods returned.

This happens both when packing items individually and with box packer enabled. I also got the same results with the paid USPS plugin, which means there might be a problem with the API.

**Comment by jeffstieler** [comment]
It would be very helpful to know the origin and destination postcodes for diagnostic purposes.

Short of know those, make sure that "commercial" rates are selected in the shipping method. Regional Rates are only available to commercial/online customers.

![screen shot 2018-03-26 at 4 54 46 pm](https://user-images.githubusercontent.com/63922/37937379-a5cbcf74-3116-11e8-95d8-d561535441ae.png)

**Comment by madeincosmos** [comment]
Thanks @jeffstieler! Learning new things every day 😄 I never found this info in USPS docs.

Now that I switched to Commercial, regional rates work fine for me 👍

**Comment by austriker27** [comment]
> It would be very helpful to know the origin and destination postcodes for diagnostic purposes.
> 
> Short of know those, make sure that "commercial" rates are selected in the shipping method. Regional Rates are only available to commercial/online customers.
> 
> ![screen shot 2018-03-26 at 4 54 46 pm](https://user-images.githubusercontent.com/63922/37937379-a5cbcf74-3116-11e8-95d8-d561535441ae.png)

Hi, where exactly did you find this option in the WC settings? I cant locate it

**Comment by jeffstieler** [comment]
@austriker27 it's likely that you aren't finding the setting because [WooCommerce Services discontinued the Live Shipping Rates feature](https://docs.woocommerce.com/document/woocommerce-services/#section-11). If you were already using live shipping rates as of WooCommerce 3.5, you should be grandfathered in.

If you are grandfathered in, that setting can be found in the shipping method settings inside a shipping zone. For example: WooCommerce > Settings > Shipping > [Zone Name] > USPS (WooCommerce Services)

**Comment by austriker27** [comment]
> 
> 
> @austriker27 it's likely that you aren't finding the setting because [WooCommerce Services discontinued the Live Shipping Rates feature](https://docs.woocommerce.com/document/woocommerce-services/#section-11). If you were already using live shipping rates as of WooCommerce 3.5, you should be grandfathered in.
> 
> If you are grandfathered in, that setting can be found in the shipping method settings inside a shipping zone. For example: WooCommerce > Settings > Shipping > [Zone Name] > USPS (WooCommerce Services)

Great! Oh yeah, I forgot they removed live shipping rates (still blows my mind they did that). I'm grandfathered in so I'll look for that setting. Thanks!
