### ISSUE TITLE
Remove or change the blue "tutorial" notice that appears on top of the shipping method config page

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1350]
This notice:

![screen shot 2018-03-26 at 17 12 04](https://user-images.githubusercontent.com/1715800/37918492-10b81cd2-3119-11e8-9454-b3707ef94218.png)

It made sense when we started, but now when adding a shipping method, the ZIP code and some services are automatically prefilled. So, either remove it entirely, or tweak its text.

**Comment by jeffstieler** [comment]
Let's remove it. 👍
