### ISSUE TITLE
Label purchase with invalid phone number length fails without useful error message

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1351]
If the length of the phone number is greater than 0 but less than 10 (or else greater than 11, it appears), the label purchase fails with no indication of what went wrong:

<img width="987" alt="screen shot 2018-03-26 at 10 06 39 pm" src="https://user-images.githubusercontent.com/1867547/37942744-a304538e-3142-11e8-84e5-ffbc79e5ed01.png">

Logged by server:
```
2018-03-27 02:02:21.636, (1522116136877:dechov.local:46282:jf83xtxv:10769) [request,error] data: {"userId":37085615,"blogId":115506202,"isRawError":true,"message":"Error purchasing label 96: Unable to complete shipment purchase: Invalid FromAddress phone number: must be 10 digits."}
```

This part comes from the shipping service:
> Unable to complete shipment purchase: Invalid FromAddress phone number: must be 10 digits.

We should probably detect this case and send a more helpful message, if not the shipping service's error verbatim, to the client. Additionally, we could try to discover and enforce the shipping service's validation rule to catch this case earlier.

**Comment by DanReyLop** [comment]
Fixed by https://github.com/Automattic/woocommerce-connect-server/pull/1070
