### ISSUE TITLE
USPS Regional Rates in "retail" rates mode

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1352]
It's not at all obvious that USPS Regional Rates only work in commercial mode.

See: https://github.com/Automattic/woocommerce-services/issues/1349 for a step-by-step explanation of how the issue works from the user's perspective

Some possible solutions:
* Tailor the list of available services based on the rates display option (and perhaps move that option above the service selection)
* Show an info notice to the merchant when they have Regional Rates selected, but want to show retail pricing

_(cc: @madeincosmos)_

**Comment by v18** [comment]
@jeffstieler another possible solution (that you mentioned to me when I brought this up) is to show the 'commercial' rates in all cases, and then display the retail price if it's available for that rate, or fall back on displaying the commercial price if the retail price is not available.

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on rates currently
