### ISSUE TITLE
Shipping Labels stopped working with 1.12.3

### ISSUE THREAD

**Issue by rmuthukrishnan** [Automattic/woocommerce-services#1358]
Hi,

I am not getting the shipping labels option with the latest version: 1.12.3
Also, woocommerce -> settings -> shipping labels is empty.

![no_shipping_label](https://user-images.githubusercontent.com/33143676/38178741-f03221ba-35cd-11e8-8af3-a6485fc81f9a.JPG)

Could you take a look?

Thank you,
Raman

**Comment by DanReyLop** [comment]
Hi,

I'm trying to reproduce your issue but I need more information. Could you please open the JavaScript console (press `F12` if you're using Chrome) and see if there are any errors there related with the `woocommerce-services.js` file?

The latest 2 releases (`1.12.2` and `1.12.3`) have been extremely small fixes to problems unrelated to these parts of the plugin. Did the plugin work for you before, like in version `1.12.1` or `1.12.2`? In that case, probably something went wrong when updating the plugin. Could you please try removing the plugin and installing it again (all your settings will be preserved), or if it still doesn't work, just going back to a version that worked?

**Comment by rmuthukrishnan** [comment]
Hi Dan,

Thank you for your reply. You are right. I get the following error. I installed it by downloading the zip and unzipping it instead of using the wordpress dashboard. Can that cause the problem?


![image](https://user-images.githubusercontent.com/33143676/38220037-32064a2a-368d-11e8-9980-5afd4dfccb3f.png)

**Comment by rmuthukrishnan** [comment]
Hi Dan,
It is working now. I re-downloaded the zip from my woocommerce account and installed it.
Not sure why dist folder was missing the first time. I may have done some mistake. Thank you very much for the prompt help.

Thank you,
Raman

**Comment by DanReyLop** [comment]
Cool, glad to know it was an "easy" fix! :)

If you downloaded the ZIP from GitHub, that ZIP includes just the source code, same as if you cloned the repo. You would need to build it following [these instructions](https://github.com/Automattic/woocommerce-services#working-with-master) if you want to actually use it on your site. If you download it [from wordpress.org](https://wordpress.org/plugins/woocommerce-services/) then it's ready to use.
