### ISSUE TITLE
First Class - Large Envelope being retuned when product can't fit. 

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#1366]
1) Create a product that is too thick to got First Class - Large Envelope (anything over .75"):

![Screenshot](http://joelwills.com/oDNXrA+)

Link to image: http://joelwills.com/oDNXrA

2) Set USPS to return First Class - Large Envelope:

![Screenshot](http://joelwills.com/rtGwvX+)

Link to image: http://joelwills.com/rtGwvX

3) Get a shipping quote and First Class - Large Envelope is returned

![Screenshot](http://joelwills.com/Af2dGp+)

Link to image: http://joelwills.com/Af2dGp

However based on thickness it shouldn't be anywhere near to fitting.

1044011-zen

**Comment by v18** [comment]
@jeffstieler what should we do about fixing this? Seems like high priority since the wrong envelope is showing up for customers at checkout

**Comment by v18** [comment]
On this page, it says that the maximum height for a first class large envelope is 0.75 inches:

https://www.usps.com/ship/preparing-domestic-shipments.htm

Did we get different information saying that it could be larger?

**Comment by v18** [comment]
The customer's original issue was discussed here:
https://github.com/Automattic/woocommerce-services/issues/1157

**Comment by jeffstieler** [comment]
> what should we do about fixing this?

I honestly think the best solution is to stop using the USPS API.. though that isn't a quick fix.

I believe the problem stems from the USPS API ignoring dimensions for `All` and `Online` type requests, which is what we're using:

![](https://cldup.com/yaokgsXaV8-3000x3000.png)

We might be able to make several requests with different `<Service/>` values to get around the problem.

No matter what, the fix for this will be server side.

**Comment by ldr2273** [comment]
1113928-zen

Customer reached out with this issue in chat. Adding here so we can update them accordingly.

**Comment by iMazed** [comment]
1113928-zen is waiting for an update on this. Any news?

**Comment by amandasjackson** [comment]
1044011-zen is also still on-hold and awaiting a fix. Is there an ETA?

**Comment by jeffstieler** [comment]
@ldr2273 @iMazed @amandasjackson 

We don't currently have an ETA for a fix, but I think I've identified a path forward and I've created a server issue to track this since that's where it will be fixed: https://github.com/Automattic/woocommerce-connect-server/issues/1088
