### ISSUE TITLE
Canada Post: Allow negotiated rates

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1373]
The Canada Post extension (https://woocommerce.com/products/canada-post-shipping-method/) allows users to connect to their Canada Post Business account to use their negotiated rates as a paid feature. We could allow that as well.

This came up in 1065854-zd-woothemes

cc @jeffstieler @pmaiorana

**Comment by rwaynick** [comment]
Another request in 1186805-zen

**Comment by ryanr14** [comment]
+1 1451599-zen

**Comment by laurendavissmith** [comment]
Closing since we wont be focusing on Canada Post at the moment
