### ISSUE TITLE
Change "connect" language in NUX/TOS banners

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1377]
Change the use of "connect" to "set up" in these banners:

![screen-shot-2018-01-10-at-10-33-41-am](https://user-images.githubusercontent.com/63922/38814588-0f548ba0-414f-11e8-9460-f62d76384eb7.png)

![screen-shot-2018-01-10-at-10-40-59-am](https://user-images.githubusercontent.com/63922/38814590-109d984e-414f-11e8-8c75-b66de7454a09.png)

See: p1HpG7-51D-p2

**Comment by laurendavissmith** [comment]
@jeffstieler do you remember which use of "Connect" words you were referring to here?
