### ISSUE TITLE
Product Bundles weights/dimensions not pulled

### ISSUE THREAD

**Issue by melindahelt** [Automattic/woocommerce-services#1378]
zd-1095216

Product Bundles are not returning shipping rates.

Situations tested:

1. Three individual products, each with weights and dimensions. Bundle created. Shipped Individually option selected, no weight/size applied to bundled product as a whole -- no rates returned.

2. Same as above, Shipping individually NOT selected -- no rates returned

3. Give the product bundle a weight and dimension, check ship individually -- no rates returned

4. Give the product bundle a weight and dimension, do not check ship individually - rates returned!

What I expected:

For option #1, I expected the sizes/weights from the products to be passed into the bundle. When testing same option above with USPS extension, that proves true.

Products set up on test site.

**Comment by zwiesman31** [comment]
Just checking if there's an update on this? Thanks!

**Comment by madeincosmos** [comment]
@melindahelt is the Product Bundle itself virtual? If it's not, most shipping plugin will still attempt to ship the whole bundle along with its components.

**Comment by madeincosmos** [comment]
Thanks @melindahelt! If the `Virtual` box is unchecked, Product Bundles will pass shipping dimensions of the whole bundle to the shipping calculator. If these dimensions are not set the calculation will be aborted, so we always need to either set bundle dimensions or make it virtual. Here is an article that explains the whole logic behind this:

https://docs.woocommerce.com/document/bundles/bundles-configuration/#section-6

For cases 3 & 4, I'm getting Services rates returned correctly both when bundle components are **Shipped Individually** and not:

![Screenshot](http://cld.wthms.co/om0Rh1+)
Screenshot: http://cld.wthms.co/om0Rh1

Here is the product that I'm testing:

https://a8c-wcs-support.mystagingwebsite.com/product/bundle/

Closing this for now, but feel free to reopen if you're getting other errors shipping bundles that are either virtual or have all the dimensions set.
