### ISSUE TITLE
Shipping helper tip: Dismiss link is huge

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#1379]
Currently: 
![screen shot 2018-04-17 at 10 37 13 am](https://user-images.githubusercontent.com/5835847/38884208-22406da0-422c-11e8-9578-a42fa6c3127f.png)

Should be smaller. (Match the helper tips in the add-product page (first time you view the page)

**Comment by laurendavissmith** [comment]
Closing since this feature is deprecated
