### ISSUE TITLE
Label Printing:  Stamped Letter not available

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/woocommerce-services#1389]
I do see that First Class - Stamped Letter does have an available rate:
![screen shot 2018-05-07 at 4 32 39 pm](https://user-images.githubusercontent.com/3220162/39730070-47f974c2-5214-11e8-956b-fc26a742ea1e.png)

But when trying to purchase a label, I don't see it as an option:
![screen shot 2018-05-07 at 4 33 10 pm](https://user-images.githubusercontent.com/3220162/39730082-5b84a14c-5214-11e8-857a-8a5d4ddb2011.png)

![screen shot 2018-05-07 at 4 33 31 pm](https://user-images.githubusercontent.com/3220162/39730092-66edc54a-5214-11e8-9cc3-6ed842901adf.png)

It looks like $2.66 is the cheapest option I have, even though Stamped would be cheaper.  I also asked @shaunkuschel to test this and he saw the same result

**Comment by iMazed** [comment]
Hey folks, do we have an ETA on this? I'd like to be able to tell the user something :) thanks!

**Comment by spraveenitpro** [comment]
Just wanted to check this with @jeffstieler  thanks.

**Comment by yukikatayama** [comment]
This issue seems similar to 1209183-zd, except that the use case is for Metered Mail. I replicated user's setting on my test site and after purchasing as a customer and paying $.47 for Metered mail shipping, only option for label purchase is First Class Mail $2.66, nothing cheaper.

![](http://cld.wthms.co/U7byc2+)
Link to screenshot: http://cld.wthms.co/U7byc2

**Comment by liviopv** [comment]
Hey @dechov 👋 could you take a look at this one when you have some time?

**Comment by jeffstieler** [comment]
@mikeyarce @iMazed @spraveenitpro @yukikatayama @liviopv

We have an in-progress PR for this on the server side. No ETA for release though.

In the mean time, I'd suggest to merchants that they disable showing their customers the Metered/Stamped Letter rates, or send them using normal postage stamps, etc.

**Comment by AashikP** [comment]
@bor0 Just pinging here since the ticket 1209183-zd is back on top of the queue

**Comment by bor0** [comment]
@AashikP you might want to ping someone from Hydra instead :) we do not own this and I don't have much experience with the codebase

**Comment by AashikP** [comment]
@jeffstieler Pinging here to update that the ticket 1209183-zd is back on top of the queue

**Comment by zwiesman31** [comment]
@jeffstieler Any update on this? Is this now a low priority item? Need some clarity so we can let the user know if/when this will be addressed.

**Comment by jeffstieler** [comment]
@zwiesman31 sent you DM with some context. Sorry for the delayed response.

**Comment by jeffstieler** [comment]
This has been fixed server side - no plugin update needed! 😄
