### ISSUE TITLE
USPS rates not returned when items don't fit in a single box

### ISSUE THREAD

**Issue by madeincosmos** [Automattic/woocommerce-services#1390]
Note: this is not a bug because I'm unable to reproduce the same behavior on a test site. However, I've run out of ideas on what could possibly be wrong, so I'll need your help to figure this out.

#### Affected tickets 

1129855-zen

#### What I expected

To ship a large number of items in a single order, possibly split into multiple boxes

#### What happened instead

As soon as the items don't fit into my largest box, there are no shipping rates being returned.

#### Steps to reproduce 

1. Add 24 x this product to cart: http://bigjimsbowco.staging.wpengine.com/product/test-product/
2. Proceed to the cart page and enter a shipping address in US
3. Observe the Priority Mail rates are returned correctly
4. Increase product quantity to 25
5. Observe no more rates are returned.

I'm unable to reproduce same behavior on my test site, but for this user it happens on 3 different installations.

**Comment by v18** [comment]
@madeincosmos - one more thing, could you add more keys for getting the site credentials? I tried to log in but they're all expired.

**Comment by madeincosmos** [comment]
Thanks @v18! I saved a couple fresh Once keys on the ticket so you should have access to everything now :-) Right now there's only 3 Priority Mail and 5 Priority Mail International services enabled, but the same ones work on my site with the same configuration.

**Comment by v18** [comment]
The reason this happens is because the merchant has another box that's larger in size: 
"length":32,
"width":10,
"height":32,

This box is too large to be shipped using priority mail, and can only be shipped using ground mail. However, the merchant does not have ground mail selected, so no rates show up.

**Comment by v18** [comment]
I created #1397 so we make sure to let the user know if a box won't be able to be used during checkout.
