### ISSUE TITLE
Copy to clipboard: Tracking number for label

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-services#1400]
Another request for a fast copy to clipboard option:

> I was wondering if it was possible to add a “copy to clipboard” button next to the tracking number after the label has been purchased?

Request: https://wordpress.org/support/topic/feature-request-635/

In a lot of cases, you'll want to do something with the tracking number (e.g. send it to the customer), so this seems like a good feature to add.

**Comment by briancwelch** [comment]
Thanks for the help, Job.
👍

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747110-add-a-fast-copy-to-clipboard-option-for-tracking-n)
