### ISSUE TITLE
Emphasize label printing feature's connection to "Commercial" rates

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1402]
As of https://github.com/Automattic/woocommerce-services/pull/1329, we can now detect the case where the **customer paid a higher live shipping rate than the merchant is paying for shipping**, and make it clear that the merchant may want to switch their shipping method pricing from "Retail" (the default) to "Commercial". (If possible, we should specifically check for the "Retail" setting in the shipping method instance that was used.)

<img width="570" alt="Screenshot of Label purchase dialog's Rates step with customer rate shown" src="https://user-images.githubusercontent.com/1867547/40135478-78929946-5913-11e8-9cf9-804793ecb99f.png">

It could perhaps take the form of a tooltip/popover in the info notice, explaining that they can select commercial rates in the shipping method settings so as to not overcharge their customers. This would be timely context for that information, since we know this merchant will be getting the discount themselves. As of now, there is no indication of why the prices are different.

(Originally brought up in p1520534278000010-slack-hydra.)

---

For reference, here is the pricing input in the shipping method settings in its default state:

<img width="384" alt="Screenshot of price option in shipping method settings" src="https://user-images.githubusercontent.com/1867547/40133301-510063f0-590d-11e8-8d69-b9ba92f69abc.png">

Note: it is potentially already clear in this context that shipping label purchase via WCS uses the commercial rates, as this appears at bottom of the linked reference there:

> If you purchase and print shipping labels using WooCommerce Services, you will be getting this discounted commercial rate.

However, I think making it more clear upfront would be an improvement, either with an inline description, more verbose option labels, tooltips instead of external link, or something else.

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
