### ISSUE TITLE
OBW: When a user is already connected to Jetpack, ask them to agree to WCS TOS right away

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1403]
**Steps to repro:**
1. Start with a new WP install
2. Install JP & connect it
3. Install WC & go through wizard
4. Elect to have live rates on your store
5. Go to frontend, add a product to cart, go to cart, and see that no live rates are shown 😱 
6. Go to any WooCommerce > Settings page, see the WooCommerce Services note to connect. Click connect
7. Go to the cart page, see that live rates are on

**What should happen:**

We should ask the user to accept WCS TOS in the wizard. This helps in a few ways:
1. The setup for live rates is done during the wizard, as the user might expect after selecting the live rates options
2. The live rates show up right away on the site 🎉 
3. There is one less step for them to do after the wizard
4. There is one less admin notice cluttering up the space

**Comment by dechov** [comment]
Agree with "Bug" label – should be fixed via https://github.com/woocommerce/woocommerce/pull/18991 in WC 3.4 (finally!)

**Comment by v18** [comment]
Awesome! Thanks for linking the two things together.

**Comment by dechov** [comment]
I think this is now fixed via the WooCommerce release last week: the "Activate" step appears in the wizard for the sole purpose of accepting the TOS.
