### ISSUE TITLE
WooCommerce Services won't connect

### ISSUE THREAD

**Issue by ValeDeOro** [Automattic/woocommerce-services#1409]
Posting this here, since it's a weekend and the Janitor is hopefully enjoying the sun :)

1169801-zen
Site: https://www.edmunditemissionsenterprises.com/wp-admin/
Customer get's this message when trying to configure WooCommerce Services: 

<a href="http://heyhydra.files.wordpress.com/2018/05/woocommerceservices1.png"><img src="http://heyhydra.files.wordpress.com/2018/05/woocommerceservices1.png?w=776" alt="WooCommerceServices1" class="size-full wp-image" id="i-9830" /></a>

After confirming, this is the status: 
<a href="http://heyhydra.files.wordpress.com/2018/05/woocommerceservices2.png"><img src="http://heyhydra.files.wordpress.com/2018/05/woocommerceservices2.png?w=776" alt="WooCommerceServices2" class="size-full wp-image" id="i-9831" /></a>

When trying to access WooCommerce >> Status >> WooCommerce Services, they get the same error message. 

They did a plugin conflict check, disconnected and reconnected Jetpack and WooCommerce Services, but to no avail. 

System Status report and admin access are in the ticket.

**Comment by ValeDeOro** [comment]
Closing this - deconnecting and reconnecting AND THEN CLEARING CACHE did the trick :)

**Comment by v18** [comment]
@ValeDeOro, for posterity - did they disconnect & reconnect Jetpack? Can you tell me where they cleared the cache?

**Comment by ValeDeOro** [comment]
They first disconnected and reconnected WooCommerce Service, then did the same with Jetpack. 
It did not seem to work. 
15 min later they realized it DID work in another browser. So they cleared their main browser's cache and that solved it. 

Or that's how they explained it. I won't vouch that there wasn't other magic involved that I am unaware of.

**Comment by v18** [comment]
Thank you @ValeDeOro! That's really helpful feedback :)
