### ISSUE TITLE
Priority Mail Tyvek Envelope is missing in settings

### ISSUE THREAD

**Issue by ldr2273** [Automattic/woocommerce-services#1420]
Currently, the Priority Mail Express Tyvek Envelope (https://store.usps.com/store/product/shipping-supplies/priority-mail-express-tyvek-envelope-P_EP_13_C) is listed in the Service Package settings, but the Priority Mail Tyvek Envelope (https://store.usps.com/store/product/shipping-supplies/priority-mail-tyvek-envelope-P_EP_14) is not:

![Priority Mail Express](https://cloudup.com/coMyA4Ib0DP+)

![Priority Mail](https://cloudup.com/cq6o7CxEmpu+)

Wanted to see if we could add this. Thanks!

**Comment by DanReyLop** [comment]
@ldr2273 The Tyvek envelope has just been added to the server, the merchants will see it when the service schemas are fetched the next time (that happens every 24 hours).

**Comment by ldr2273** [comment]
Thank you so much @DanReyLop 👍
