### ISSUE TITLE
OBW: Make sure that origin zipcode is valid before adding new zone shipping methods

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1422]
Steps to repro:
1. Install WooCommerce on a new test site
2. Go through onboarding wizard
3. Enter a bad zipcode on the first screen (e.g. 'ABC') and the country 'US'
4. On the shipping screen, select to use live rates for your shipping zones
5. Go to a cart page and try to get rates
6. See that you cannot get live rates using WCS
7. See the error "data.origin pattern mismatch" in WooCommerce > Status > WooCommerce Services > Debug section

h/t @jeffstieler @dechov for this repro idea

Related: helping to surface and fix this issue for current users who have already gone through the OBW and have a bad zipcode entered in their shipping methods already - https://github.com/Automattic/woocommerce-services/issues/1423

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
