### ISSUE TITLE
Alert user when rate requests have bad origin zipcode

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1423]
When a store owner has a bad zipcode saved in their WCS shipping zone, shipping rates won't work on the frontend. This can happen when a user goes through the OBW and enteres a bad zipcode on the first OBW screen.

To fix this, we should alert users that this is happening. A few ideas to alert:
1. wp-admin notice
2. email
3. Better error message in WooCommerce > Status > WooCommerce Services

Related: fix the original error so that new users don't get this error on their site in the future - https://github.com/Automattic/woocommerce-services/issues/1422

**Comment by dechov** [comment]
👍 Can start with a simple approach to idea 3: adding a postcode validation check to the service health status ([code](https://github.com/Automattic/woocommerce-services/blob/85588593871774fd573304df6fa34202a010931b/classes/class-wc-connect-help-view.php#L182-L194))?

**Comment by v18** [comment]
Another way to create a shipping method with a bad zipcode:

if a bad zipcode is entered in the general WooCommerce settings, then WCS copies it over when creating a new USPS (WCS) shipping method

**Comment by jeffstieler** [comment]
Can we consider this resolved since `#3` was implemented server-side?

**Comment by v18** [comment]
@jeffstieler - it would be better if we alerted users using an admin notice, not only an error in the error log.

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
