### ISSUE TITLE
Shipping tax amount is still being reflected in the total tax charged when shipping marked as being non-taxable

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#1429]
Shipping tax amount is still being reflected in the total tax charged when shipping marked as being non-taxable. 

**Affected Tickets:**

1197035-zen

**Testing Environment:**

- WooCommerce - 3.4.1
- WooCommerce Services - 1.14.1

**Steps to reproduce:**

- Create a product with the price $2.00
- Set the Flat Rate to be $4.99 and non-taxable:

![screen shot 2018-06-01 at 2 53 09 pm](https://user-images.githubusercontent.com/19143190/40858205-91b26628-65ab-11e8-96c6-fbf08d5aedaf.png)

- Shop Origin address:

16 Inverness Place East
Bldg D-200
Englewood, CO, 80112, US

- Enable automated taxes

- Place an order with the following shipping address:

1300 N. Burlington Dr.
Castle Rock, CO 80104

- You will see the following:

![screen shot 2018-06-01 at 12 56 09 pm](https://user-images.githubusercontent.com/19143190/40858386-26011d88-65ac-11e8-8258-de9efb59c27c.png)

Explanation of the charges:

- $2.00 (wristband)

- $4.99 (shipping)

- $0.20 cents (2.9% sales tax) on the total amount of product + shipping

- $7.19 Total

- $7.05 Woo Commerce charged

- $0.14 cents discrepancy - which is the tax on shipping that is supposed to be non-taxable

In order to fix it, `CO Tax:` line should say `$0.06`.

**Comment by DanReyLop** [comment]
This will be fixed when we bring our TaxJar integration up to date, in this PR: https://github.com/Automattic/woocommerce-services/pull/1398

The bug was fixed a few months ago in the TaxJar plugin, here: https://github.com/taxjar/taxjar-woocommerce-plugin/pull/64 , we just need to port the changes back.

**Comment by juliaamosova** [comment]
Hi @DanReyLop, I am following up on this bug. Was it fixed in the recent WC Services release by any chance? It looks like it could be from the changelog. Thanks!

**Comment by DanReyLop** [comment]
@juliaamosova Yes, this is fixed in `1.15.0`, we updated the TaxJar integration and that included a fix for this (and many others, too many to put in the changelog, we were around 6 months behind).
