### ISSUE TITLE
Shipping rates not recalculating after product price change

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1432]
It seems cached live rates per address are not invalidated in every case when shipping options are reset, as a product price change results in no live rates being calculated even after requesting recalculation.

To reproduce:
- Add product to cart
- Get live rates in cart
- Change product price
- Reload cart, and see no live rates
- Click "Calculate shipping", then "Update totals", and still see no live rates
- Click "Calculate shipping", change the address, then click "Update totals", and see live rates

You can see essentially the same behavior in checkout (except that there is no way to recalculate rates after verifying the address is correct).

**Comment by jeffstieler** [comment]
@dechov - I didn't realize this until now.. but why should a product price change have an effect on shipping costs?

**Comment by dechov** [comment]
Good question again :-) – AFAIK there's no reason to reset those rates in this case. No idea off hand where and why it's being done.

**Comment by jeffstieler** [comment]
> there's no reason to reset those rates in this case

**Comment by dechov** [comment]
This can be closed if we're tracking somewhere else the issue of those rates being reset when the price changes, and/or if we're pretty confident this is a WC core issue. I haven't investigated why the rates are being reset or why it's only the live rates (as far as I can tell) that are being reset.

**Comment by jeffstieler** [comment]
Oh - I think I misunderstood the original issue.

If a product's price changes and it's in someones cart, if they recalculate shipping rates they no longer receive live rates from WCS?

**Comment by dechov** [comment]
As far as I could tell from my testing: if they simply reload the cart _or_ if they recalculate shipping rates with the last address they used, they see no live rates. They'd have to recalculate shipping rates with a different address in order to start getting live rates again.

**Comment by v18** [comment]
@dechov so the steps to repro are:

1. put some product in a cart, calculate live rates using WCS
2. change product price
3. refresh cart
4. see that product price is updated, but there are no rates shown for the WCS shipping method

is that right?

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
