### ISSUE TITLE
Items are not being calculated correctly to combine in one box

### ISSUE THREAD

**Issue by blake12377** [Automattic/woocommerce-services#1438]
When testing WC services, I ran into a bit of bugs. 

Here is the packaging manager setup: http://prntscr.com/jstch8
Here is the product setup: http://prntscr.com/jstcvz
Debug message: http://prntscr.com/jsthf9

The plugin is attempting to put 6 mugs into a 8x8x8 box and 12 mugs in a 12x12x12 box. No matter what settings I change, it wont calculate correctly. 

Thanks for your help in advanced and please let me know if you have any additional questions.

**Comment by zwiesman31** [comment]
Hi Blake! I'm closing this as it was handled via chat (transcript #4218684).
