### ISSUE TITLE
When adding a new WCS shipping method, validate settings

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1441]
There are 2 cases where the settings are not validated when adding a WCS shipping method:

## OBW
Steps to repro:
1. Go to the WC setup wizard
2. Enter a bad zipcode on the first page
3. On the shipping page, add live rates
4. See that a bad zipcode is saved

Proposed solution: validate zipcode when entering it on the first page

## WC > Settings
Steps to repro:
1. Enter a bad zipcode in the general WooCommerce settings page
2. Add a WCS shipping method to a shipping zone
3. See that there are settings saved for it, but the zipcode entered in # 1 above is used

Proposed solution: validate zipcode when entering it on the first page

Possible issues / questions:
- users may not have WCS installed so we may not be able to use our own validator. WC has its own validator.
- was the validator used before and removed? if so - find out why so we don't repeat earlier issues

Related: https://github.com/Automattic/woocommerce-services/issues/966

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
