### ISSUE TITLE
Allow multiple shipments (packages) at multiple times

### ISSUE THREAD

**Issue by kenmg77** [Automattic/woocommerce-services#1449]
Currently, all items must be shipped at the same time.   Allow for items to be saved to be shipped at a later date by adding a save for later option when creating shipping boxes. 

When viewing an order under my account show items that are shipped separately from items that have yet to ship.  Allow for viewing of the tracking number for each of the shipments similar to how Amazon shows you multiple packages on one order.

**Comment by briancwelch** [comment]
👍

**Comment by v18** [comment]
Hi @kenmg77 - thanks for opening this issue! Have you wanted to ship items at separate times like you mentioned, since opening this issue?

As for tracking numbers - we list them separately in the section right under the 'Create new label' button. Are you able to see that? If not, can you add a screenshot of where you're taking a look? Thanks!

**Comment by kenmg77** [comment]
Thanks for checking in. Yes everyday!  We had not found a work around yet.

To your success-
Ken
[image: BrandCo / Ken Granger, Founder & CEO / 407.999.0009 Call Me!]
<407-999-0009>




On Oct 23, 2018, at 8:49 PM, Valerie K <notifications@github.com> wrote:

Hi @kenmg77 <https://github.com/kenmg77> - thanks for opening this issue!
Have you wanted to ship items at separate times like you mentioned, since
opening this issue?

As for tracking numbers - we list them separately in the section right
under the 'Create new label' button. Are you able to see that? If not, can
you add a screenshot of where you're taking a look? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Automattic/woocommerce-services/issues/1449#issuecomment-432472366>,
or mute the thread

**Comment by kenmg77** [comment]
We are able to see multiple tracking numbers, however, there is no way to tell which item is in which package.

**Comment by v18** [comment]
@kenmg77 - I'm curious to hear more about your workflow. Can you tell me a bit about what happens right before you decide you want to ship an item at a later time within one order?

You can tell which item is in which package by clicking the 3-dot menu:

<img width="292" alt="3-dot-menu" src="https://user-images.githubusercontent.com/11487924/47399958-1ca43080-d709-11e8-85a0-c88ea9fe6e5d.png">

And then clicking "View Details":

<img width="293" alt="view-details" src="https://user-images.githubusercontent.com/11487924/47399973-24fc6b80-d709-11e8-85df-25d6a68b52d4.png">

On the next screen, the items are listed:

<img width="481" alt="items-in-package" src="https://user-images.githubusercontent.com/11487924/47399980-2b8ae300-d709-11e8-8d2c-3e6dfe40cfd6.png">

**Comment by v18** [comment]
@kenmg77 - thank you, that illuminates a lot for me :) Do the steps I mentioned for getting the tracking number from under 'View details' work for you for now?

**Comment by kenmg77** [comment]
They do not work in our case since the tracking numbers are added to WooCommerce via the ShipStation plugin.  I image that piece would work if the shipping were done through WooCommerce.   We do not want to use the ShipStation plugin but that is our only option at this point... we would like to remove that from our workflow and just use the WooCommerce labels.

**Comment by kenmg77** [comment]
Correct!  the missing piece is the ability to ship a partial order via WooCommerce Shipping. :D

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747065-allow-multiple-shipments-packages-at-multiple-ti)
