### ISSUE TITLE
Display prompt to connect inline on Edit Order page

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1453]
Currently, we have an admin banner asking users to connect to WCS:

<img width="950" alt="banner-to-connect-wcs" src="https://user-images.githubusercontent.com/11487924/42095214-f67766be-7b7f-11e8-8218-0900d9855758.png">

We can display the 'Shipping Label' meta box at all times, and display a nudge to connect there, where the user will look to get started with label printing, similar to how we display a credit card nudge:

<img width="303" alt="shipping-label-meta-box" src="https://user-images.githubusercontent.com/11487924/42095801-aa0ab6c6-7b81-11e8-8c0e-6c30b1efb4c7.png">

This new nudge will be a just-in-time nudge ✨

**Comment by laurendavissmith** [comment]
Closed since we've already implemented a new design around this
