### ISSUE TITLE
Add Customer-Facing Order Note upon Shipping Label Creation

### ISSUE THREAD

**Issue by joshuaja** [Automattic/woocommerce-services#1455]
A customer-visible note should be added to the order that contains tracking info when a shipping label is created.

This will ensure that tracking info shows up automatically in the `/my-account/view-order/` view.

Here's an example of how it would show up in the View Order screen for the customer (where I entered this in as a manual note).

![image](https://user-images.githubusercontent.com/9004029/42243740-59427a96-7ee0-11e8-83f2-ba3ee265acfe.png)

**Comment by jconroy** [comment]
Closing in favor of tracking popularity for this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747014-add-customer-facing-order-note-upon-shipping-label)
