### ISSUE TITLE
Support Pre-packed items. [Type] Enhancement

### ISSUE THREAD

**Issue by sardesign** [Automattic/woocommerce-services#1461]
I've run into the need of being able to mark a product as pre-packaged or Ready to Ship.

Essentially bypassing the need to be placed in another box and using the assigned product shipping size and weight directly.

Perhaps as a checkbox within the product shipping settings.

![readytoship](https://user-images.githubusercontent.com/41026771/42479804-8991405c-83a8-11e8-87c0-9651b86b7811.jpg)

**Comment by v18** [comment]
Hey @sardesign, thanks for opening an issue! This option exists when you are printing labels.

When you're in the Packages step, click "Move" for the item you'd like to ship separately:

<img width="1229" alt="packages-move-item" src="https://user-images.githubusercontent.com/11487924/47398022-178eb380-d700-11e8-9a07-b8f21860198b.png">

And then select "Ship in original packaging":

<img width="400" alt="ship-in-original-packages" src="https://user-images.githubusercontent.com/11487924/47398034-27a69300-d700-11e8-9e3e-636f761c6df1.png">

We don't have a way to mark an item as 'ready to ship' when calculating rates in the cart, though. Right now, we don't have plans to add that.

I'm going to close this issue for now, but feel free to re-open if you have any more comments or questions :)
