### ISSUE TITLE
Return shipping rates based on zipcode alone, and not require the state

### ISSUE THREAD

**Issue by melindahelt** [Automattic/woocommerce-services#1462]
zd-1264428

Customer mentioned:

>  FYI, the WooCommerce Services USPS rate lookup only works when state AND zip are entered. Most shipping quote systems work on zip code entry alone. Can you help with this as well?

After talking with @jeffstieler we determined this was a new change to allow this within WooCommerce Core with some filters that will allow you to remove the state option. This is an official enhancement request  to add that. Thanks!

**Comment by jconroy** [comment]
Closing in favor of tracking popularity for this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38746984-return-shipping-rates-based-on-zipcode-alone-and)
