### ISSUE TITLE
Suggestion:  Tracking Numbers on Other Emails (Besides 'Completed')

### ISSUE THREAD

**Issue by lpable** [Automattic/woocommerce-services#1463]
I appreciate this product and the work you all have done to bring it to us.  

I found [this thread](https://github.com/Automattic/woocommerce-services/issues/391) about the addition of tracking information to the Completed email, because I have a custom status called 'Shipped' and an email sent for that status, and I wanted it to include tracking information.

I have worked around my issue by commenting the check for 
>|| ! $order->has_status( 'completed' ) 

but it would be nice to have a setting with emails that include tracking.  Perhaps a checkbox to include tracking on the WooCommerce > Settings > Emails page under the Manage option for each email type.  Obviously this wouldn't make sense for many of the emails, but it would be very intuitive and easy for users there.  Then just change the check for Completed to a check of the email's checkbox.

On a related note, tracking info links are in the order detail page.  It would be nice if there was a column in the WooCommerce > Orders page to show tracking numbers for all orders.  

Thanks again for all you do!

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38746900-add-ability-add-tracking-numbers-to-emails-with-st)
