### ISSUE TITLE
International labels: make sure to send `value` with the default package

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1465]
We are not sending `value` with the default package here:

https://github.com/Automattic/woocommerce-services/blob/ec8db8844c05f33d44d66b9de2077bc48727c839/classes/class-wc-connect-shipping-label.php#L148-L155

This happens when the customer did not select a WCS shipping rate at checkout, so there are no pre-calculated packages to use.

This causes an issue when calculating product costs.

Related: https://github.com/Automattic/woocommerce-services/pull/1382

**Comment by DanReyLop** [comment]
Fixed with a one-line change in https://github.com/Automattic/woocommerce-services/pull/1382/commits/806e5820ba6c95ff24e2ff76b98e46e099f7c377

Do you want to keep this issue open for tracking purposes?

**Comment by v18** [comment]
Fixed
