### ISSUE TITLE
Can we get Canada Post rates in USD, e.g. different currencies than CAD?

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1480]

**Comment by v18** [comment]
Or we could do the conversion! We already have different currency support in BD!

**Comment by v18** [comment]
User flow: the user wants to quote label rates in USD on checkout, but pay in CAD. Doesn't have to be perfect - losing or winning a few cents is acceptable, but the merchant needs to be aware of it.

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
