### ISSUE TITLE
OBW: move 'additional payment methods' to the bottom

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1485]
From @bmccotter :

> [move] the “additional payment methods can be installed later” to below the offline payments section. We want the merchant to stay focused during setup process. 

<img width="549" alt="screen-shot-2018-08-13-at-12-33-24-pm copy" src="https://user-images.githubusercontent.com/11487924/44057725-0b8cd2f6-9f1a-11e8-94bc-b52b62642722.png">

**Comment by laurendavissmith** [comment]
Closing since OBW is being looked at holistically
