### ISSUE TITLE
Onboarding: Stripe - Enable Payment via Saved Cards should be auto toggled on.

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1486]
From @bmccotter : 

> Within the Payments Settings for Stripe, Enable Payment via Saved Cards should be auto toggled on.

<img width="583" alt="screen-shot-2018-08-13-at-12-28-27-pm" src="https://user-images.githubusercontent.com/11487924/44058031-dc43e74a-9f1a-11e8-8412-ee6d9cfbf02a.png">

**Comment by jeffstieler** [comment]
Should we just do this on the Stripe extension instead of WCS? @v18 @bmccotter

**Comment by bmccotter** [comment]
I think thats fine!

**Comment by v18** [comment]
Sure - whichever way is best :)

**Comment by jeffstieler** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/758.
