### ISSUE TITLE
When adding a shipping method, redirect to the shipping method setting pages immediately

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1488]
From @rachelmcr while testing:

> I just didn’t find this settings page before so I didn’t realize how customizable these options were. 

So - we had the default settings saved, but it wasn't obvious what those settings even were, so when strange things happened, it wasn't clear where to look for them.

**Comment by v18** [comment]
Related: https://github.com/Automattic/woocommerce-services/issues/966

**Comment by DanReyLop** [comment]
I'll repeat what I said before: This should be a core issue. Our shipping method is consistent with how the built-in methods work, we shouldn't hack around that just because the behaviour is not ideal.

To be clear, I think this change makes a lot of sense, it would be great if we (Hydra) implemented it, but in Core, not in WCS.

**Comment by DanReyLop** [comment]
Or is this specific to the shipping zones/methods that are auto-created in the OBW? In that case, maybe a text in that wizard step telling where can the merchant change those settings after installation.

**Comment by v18** [comment]
@DanReyLop - yeh, I agree this change should probably be done in core. I say probably because I'm not 100% what settings other shipping methods have, so not sure if they need always need to redirect to settings, etc.

But, I think it's worth keeping the issue in our repo since we're the team responsible for the UX on our own project. Whether the code gets written in our plugin or core doesn't matter (similar to how we keep OBW issues here).

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
