### ISSUE TITLE
Remove or disable predefined boxes from the Purchase Label flow when they can't be used

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1498]
Some packages make no sense for international shipments. `Regional Rate Box A1-A2-B1-B2` come to mind, but I'm not sure if there are other situations where knowing the origin and destination, we could safely exclude some kinds of boxes.

When the user interacts with the `Packages` step of the Purchase Label modal, the origin and destination are already known. It makes sense to remove from the `Package` dropdown (or at least disable) the options that don't apply. For example, a `Regional` box will never work if the origin and destination are in different countries.

Things to note:
* Double-check what's a "domestic" and "international" shipment for USPS, specially when it involves those non-US territories that have USPS offices.
* What happens if the user had selected an "incorrect" box? Edge case, but since the merchant can change the destination address at label-purchase time, it's something we need to address, and show an error or something (or maybe just keep going with the bogus box and let the error in the `Rates` step inform the user).

**Comment by v18** [comment]
> What happens if the user had selected an "incorrect" box?

This is now solved by https://github.com/Automattic/wp-calypso/pull/26979

**Comment by jeffstieler** [comment]
Reopening until we update the Calypso dependency here.

**Comment by laurendavissmith** [comment]
@jeffstieler what needs to be done here to close this one out?

**Comment by jeffstieler** [comment]
@laurendavissmith I believe at the time of my comment we hadn't updated the `wp-calypso` dependency version in this repo, but it looks like it's a git submodule now that's up to date as of `4/11/19` with calypso. This can be closed.

**Comment by laurendavissmith** [comment]
thats what it seemed like, thanks!
