### ISSUE TITLE
Remove "debug" control on status, use core setting

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#1512]
I believe we actually missed this change in WC 2.7: https://github.com/woocommerce/woocommerce/commit/84487d0f4b01eeb6ea3b227e8ae3c2f18378acd2

![](https://cldup.com/KEuazhqc6i-3000x3000.png)

Let's use the core WC shipping debug setting instead of our own on the Status page.

Open question: should we migrate the setting from our status page to the core option?

**Comment by laurendavissmith** [comment]
Closing until we make a decision on this
