### ISSUE TITLE
Default "Packages" step to packing results from shipping carrier extensions

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1516]
The integration we currently have between rates and labels offerings consists of defaulting the merchant-facing label purchase form values to the customer-selected rate and packaging. These defaults result in a smooth flow (with potentially zero manual input required).

It would be good to have a similar integration with carrier extensions (so far just USPS), _particularly with regard to box packing results_, which are not currently indicated to the merchant as part of the purchase flow at all, only directly on the order page:

<img width="814" alt="screen shot 2018-10-17 at 1 35 40 pm" src="https://user-images.githubusercontent.com/1867547/47105726-c1f36c00-d212-11e8-9067-290334e4965e.png">

WooCommerce Services converts between package/rate identifiers used by the rating service and by the label purchase service, and I'm not sure how much more effort it would be to do this conversion for the USPS extension. Besides that, the [`get_packaging_from_shipping_method ` function](https://github.com/Automattic/woocommerce-services/blob/1682bf418645d93f2acaf4ef3b189c36586425c9/classes/class-wc-connect-shipping-label.php#L83-L117) will need to be modified to adapt to the way the USPS extension stores the packing results (i.e. not in `meta_data` [like WCS](https://github.com/Automattic/woocommerce-services/blob/1682bf418645d93f2acaf4ef3b189c36586425c9/classes/class-wc-connect-shipping-method.php#L439), but on the `packages` property.)

**Comment by laurendavissmith** [comment]
Closing since we'll be revisiting this in later designs
