### ISSUE TITLE
Don't display notice in Stripe settings if account is connected directly

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-services#1526]
Currently, when an account is directly configured through Stripe, and not through WCS, this notice shows:

"No account connected via WooCommerce Services."

This is quite confusing especially if the customer already was struggling to configure Stripe. See for example 1504690-zen.

So either that notice needs to be a button that allows them to connect their existing account that way, or it needs to be hidden if Stripe creds are added below. 

![http://cld.wthms.co/X5AlVs](http://cld.wthms.co/X5AlVs+)
Link to image here: http://cld.wthms.co/X5AlVs.

**Comment by madeincosmos** [comment]
Also reported in 1526195-zen

**Comment by EricaKuschel** [comment]
Also reported in 1538409-zen

**Comment by dougaitken** [comment]
Adding a few I've had 
1535582-zen
1523915-zen

**Comment by orhanfernandes** [comment]
Got one here: 1558937(zen)

**Comment by yukikatayama** [comment]
reported 1562196-zen

**Comment by vajrasar** [comment]
One here: #5564151-hc

**Comment by orhanfernandes** [comment]
got another one, here: 1573006-zen

**Comment by harishankerr** [comment]
Another report in 6176348-hc (1544871-zen)

**Comment by dphyled** [comment]
Also reported in 1586237-zen

**Comment by mouligreenlaw** [comment]
And another one here 1589814-zen

**Comment by madeincosmos** [comment]
Bumping priority as there's a lot of users confused about this message

**Comment by AtrumGeost** [comment]
Another report here 7627673-hc

**Comment by orhanfernandes** [comment]
1601981 - Zen

**Comment by harishankerr** [comment]
Another report in 8441312-hc.
