### ISSUE TITLE
Display connection health on the WooCommerce Admin dashboard

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1533]
The idea would be to display the green/yellow/red Jetpack, Services Server, schema health status (i.e. currently displayed on the WooCommerce Services Client dashboard) on the new WooCommerce Admin dashboard: https://github.com/woocommerce/wc-admin

cc @LevinMedia @timmyc

**Comment by timmyc** [comment]
Or perhaps we can just create a "Store Alert" for this instead - I'm guessing day-to-day the items shown in the Status section won't change often, and if they are red it seems like they should be an alert

![image](https://user-images.githubusercontent.com/22080/47970162-84764780-e036-11e8-9638-4b72726f0341.png)

**Comment by laurendavissmith** [comment]
Closing, not sure how useful this would be right now
