### ISSUE TITLE
How to add customer into memberships extension

### ISSUE THREAD

**Issue by souri84** [Automattic/woocommerce-services#1537]
Hi,

I would like to record my customer after payment into the memberships woocommerce plugin... I don't find how to do this...

Could someone respond me ?

Thanks,

Thibaut

**Comment by jeffstieler** [comment]
Hi @souri84,

I think you've perhaps opened this issue in the wrong place.

You can see documentation for the WooCommerce Memberships plugin here: https://docs.woocommerce.com/document/woocommerce-memberships/

If you're still having trouble with WooCommerce Memberships, you can open a ticket with our support team here: https://woocommerce.com/my-account/create-a-ticket

If this is in fact an issue you're having with WooCommerce Services (https://wordpress.org/plugins/woocommerce-services/), please re-open this issue and provide more information about what you're attempting to do.

Thanks.
