### ISSUE TITLE
Decode shipping method HTML entities in label purchase rates step

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1551]
The shipping info – noted in the rates step of the label purchase screen – is encoded (by React) upon being rendered as HTML content [[code](https://github.com/Automattic/wp-calypso/blob/6ddea4e1f1476f731a1265b488cf1d7067f7d878/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/index.js#L110)], which results in broken rendering of service titles from the USPS extension.

<img width="895" alt="screen shot 2018-11-30 at 12 55 13 am" src="https://user-images.githubusercontent.com/1867547/49271721-deeba380-f43c-11e8-99d6-31966fed335f.png">

Possible solutions:
- Consider if it's secure enough to `dangerouslySetInnerHTML` in this case
- Decode HTML entities in the rendered string
  - Use a library (like [he](https://github.com/mathiasbynens/he))
  - Hard-coded string replacement for `&#0174;` and `&#8482;`, which are the only entities that appear in the USPS extension (see `includes/data/data-services.php`) and _may well be the only ones we need to worry about_

Thanks @jeffstieler for reporting.

**Comment by RadoslavGeorgiev** [comment]
If it is just the text that we care about, why not do something like this:

```js
const html = "<div>Priority <strong>Mail</strong> &#0174;</div><script>alert('test')</script>";
const element = document.createElement( 'div' );
element.innerHTML = html;
const text = element.textContent;
text; // Priority Mail ®alert('test')
```

AFAIK there is no risk as long as the element is not actually rendered on the page. In the worst case, there might be some strange output, but only when someone would try to do something malicious.

Of course, if we need this server-side, things change :)

**Comment by dechov** [comment]
Thanks – I think we should go ahead with that approach.

> Of course, if we need this server-side, things change :)

Time to `import 'jsdom'` 😁 Nah, this is client-only.

**Comment by RadoslavGeorgiev** [comment]
I think I can implement this tomorrow, assign it to me if you'd like me to.
