### ISSUE TITLE
Manual Sanity Test: Develop a first cut

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1552]
Props @dechov for the idea: " a sequenced inventory of all the 'critical' plugin functionality. Could consider having it inside the repository, and updated in tandem with the changelog. Could also double as a demo script."

**Comment by DanReyLop** [comment]
If we deem the release to be high.risk, we should also test the minimum versions of everything we support, just in case we made a regression:
- WooCommerce 3.0
- WordPress 4.6 (maybe not needed, we've never had any problems with WordPress releases)
- PHP 5.2 (runs on TravisCI but we don't have a 100% PHP test coverage, even syntax errors can go unnoticed)

**Comment by laurendavissmith** [comment]
Closing, no longer relevant
