### ISSUE TITLE
Broken links for variable products in the Packages step of the Purchase Label modal

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1556]
### Steps to reproduce:
* Create a product with variations.
* Create an order with a variation of that product.
* Go print a label for that order.
* Open the `Packages` step on the label modal.
* Click on the product name (see the screenshot below).
![screenshot 2018-12-06 at 10 12 37](https://user-images.githubusercontent.com/1715800/49577565-8dad4980-f93f-11e8-9b18-04b3f5394dae.png)

**Expected behaviour:** The product page opens in a new tab.
**Current behaviour:** A "permission denied" page opens up instead.

### Cause:
In my case, the product has `ID = 30`, and the variations are `93, 94, 95`. I purchased the variation `94`. The link is generated using the variation ID, so the resulting link is: `http://[...]/wp-admin/post.php?post=94&action=edit`, which doesn't work (should use the product ID instead). This issue happens in Calypso too.

The plugin's endpoint returns [a correct WP-Admin URL](https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-shipping-label.php#L73), but it's ignored and instead a URL is constructed using the product ID (which in this case it's the variation ID) [[Calypso](https://github.com/Automattic/wp-calypso/blob/b35f5b8090fa5c44d4e0bb5692dc9b65312a015e/client/extensions/woocommerce/woocommerce-services/lib/utils/get-product-link.js#L15)] [[WP-Admin](https://github.com/Automattic/woocommerce-services/blob/9b735cbc9c848dd0f2be92d9b0150c1dc80e5b83/client/calypso-stubs/extensions/woocommerce/woocommerce-services/lib/utils/get-product-link.js#L2)]. In order to not break compatibility, I think the `get-product-link.js` logic should be rewritten to:
- In WP-Admin, just use the returned URL.
- In Calypso, parse the returned URL to get the product ID, and build the link using that ID.

**Comment by bor0** [comment]
For this product:

<img width="510" alt="Screen Shot 2019-12-09 at 13 59 34" src="https://user-images.githubusercontent.com/1620929/70437598-3bd85b80-1a8c-11ea-858d-3a70bdd773ae.png">

Calypso seems to work fine:

<img width="484" alt="Screen Shot 2019-12-09 at 13 58 59" src="https://user-images.githubusercontent.com/1620929/70437615-4561c380-1a8c-11ea-9898-9fafd6722c14.png">

As part of this issue the PR will fix `woocommerce-services`.
