### ISSUE TITLE
Add APV credits / debits to label report

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1562]
Note: No planned release for this. Mostly capturing it here to collect any user feedback we get along these lines (our competition's reports includes this)

If we end up charging (or crediting) a user for postage, it would be ideal to show that as part of the postage reports we added to WooCommerce > Reports > Shipping Labels

<img width="704" alt="screen shot 2018-12-10 at 10 58 19 am" src="https://user-images.githubusercontent.com/1595739/49754427-e4ca5b80-fc6a-11e8-8bcb-e9e168e04d19.png">

**Comment by laurendavissmith** [comment]
Closing since there hasn't been any feedback around this yet
