### ISSUE TITLE
Priority Mail Military rates not returned

### ISSUE THREAD

**Issue by madeincosmos** [Automattic/woocommerce-services#1563]
#### Affected tickets

1604718-zen

#### What I expected

To ship to military addresses over Priority Mail, as showing in the USPS calculator:

![Screenshot](http://cld.wthms.co/yjvnAQ+)
Screenshot: http://cld.wthms.co/yjvnAQ
https://postcalc.usps.com/Calculator/MailServices?country=0&ccode=US&oz=73301&omil=False&dz=09626&dmil=True&mdt=12%2F12%2F2018&mdz=15%3A59&m=12

#### What happened instead

The plugin only returns First Class and USPS Ground rates for military addresses, despite all Priority Mail & Priority Mail Express services being turned on. 

There's a note inn the USPS calculator saying:

> The origin and/or destination ZIP Code supplied is an APO/FPO/DPO ZIP code. Service standards, except for Priority Mail Express, to this location are not available at this time

It's possible services code for Priority Mail Military are different than regular Priority Mail, and that we'll need to add these as a separate option

#### Steps to reproduce

1. Enable all Priority Mail and Priority Mail Express services
2. Ship a test product (ie. 10 x 6 x 0.5in) to:

```
PSC 809 BOX 2394 
FPO, AE 09626
```

3. Observe no Priority Mail rates are being returned:

![Screenshot](http://cld.wthms.co/uVt6CG+)
Screenshot: http://cld.wthms.co/uVt6CG

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
