### ISSUE TITLE
Bundle all the needed assets with the plugin

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1573]
After fixing https://github.com/Automattic/woocommerce-services/issues/1571 in https://github.com/Automattic/woocommerce-services/pull/1572, it's clear that our current build system is quite fragile. Changes in Calypso can destroy our plugin, even if we don't update the actual `w-calypso` dependency. The reason is that we're using CSS rules that include URLs like `https://wordpress.com/images/checkmark.svg`, so that file could stop being there at any moment.

We are using [https://github.com/postcss/postcss-url](postcss-url) to rewrite those URLs, and that gives us a bit of flexibility. we can:
* Inline all the URLs into the `style.css` generated file, using the `url('data:.....')` syntax. I tried it and our CSS file goes from less than 200KB to more than 900KB. That seems excessive considering we're just including the checkmark SVG icon and the credit card symbols.
* Copy the SVG files into a folder in the plugin, at build-time.
* A combination of both (maybe only inline the images if they are smaller than X KB, copy the files otherwise).

**Comment by laurendavissmith** [comment]
Closing since this could become outdated with architectural changes
