### ISSUE TITLE
Can't select the credit card checkbox for purchasing labels

### ISSUE THREAD

**Issue by madeincosmos** [Automattic/woocommerce-services#1580]
When trying to select the credit card to save for shipping labels, the checkbox svg image loaded from https://wordpress.com//calypso/images/checkbox-icons/checkmark.svg returns a 404:

![Screenshot](https://cld.wthms.co/KOkJMX+)
Screenshot: https://cld.wthms.co/KOkJMX

Because of this, the interface doesn't indicate whether the field has been checked or not:

![Screenshot](https://cld.wthms.co/sDKkGC+)
Screencast: https://cld.wthms.co/sDKkGC

If I select the option and save the credit card is correctly used for purchasing labels, but the interface is utterly confusing.

**Comment by madeincosmos** [comment]
Reported in 1816739-zen

**Comment by dechov** [comment]
Thank you for reporting – this was fixed in https://github.com/Automattic/woocommerce-services/pull/1572 and we are planning to release this week.
