### ISSUE TITLE
Provide access to the "Add package" screen from label purchase "Packages" step

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1585]
Currently if a new merchant were to reach the "Packages" step of the label purchase dialog, and then realize that the box they wanted to use is not in the dropdown, it is not immediately clear:
- that it's possible to add custom and preset packages
- where to add them
- that the order page must be refreshed + purchase flow restarted before seeing the added package

<img width="617" alt="screen shot 2019-02-20 at 10 41 41 pm" src="https://user-images.githubusercontent.com/1867547/53142105-bae1bf00-3560-11e9-85fd-e22bf517abd4.png">

Could/should we import the "Add package" modal – accessible from the WooCommerce » Settings » Shipping » WooCommerce Services screen only – into this view as well (perhaps refactoring as a connected component first)?

**Comment by laurendavissmith** [comment]
Closing since the new design changes this flow
