### ISSUE TITLE
Move from TravisCI to CircleCI

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#1587]
TravisCI has been recently acquired and its future is uncertain, specially as a free product. They're expeciencing layoffs already (for more context: [Twitter](https://twitter.com/reinh/status/1098663375985229825), [HN](https://news.ycombinator.com/item?id=19218036), [Reddit](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/))

We are using CircleCI for the WCS server already, and other projects at Automattic that are bigger than us (for example, Calypso) are using CircleCI too. This would be a good opportunity to migrate to CircleCI and be consistent all over our stack.

Right now, the only downside I see for CircleCI is that it's lacking the `matrix` feature. There are ways to emulate, but it's quite verbose: https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml

@beaulebens Jetpack is using TravisCI too, pinging you here in case you want to consider this too. Do you know of any other project at Automattic that uses Travis, so we can at least notify them and they can make their own decisions?

**Comment by beaulebens** [comment]
Thanks for the heads up -- @dereksmart this sounds like something you/ @brbrr and team want to look at. Definitely seems like a chance to coordinate around some shared tooling across products.

**Comment by dereksmart** [comment]
@DanReyLop 

> specially as a free product

FWIW we already pay for it

**Comment by laurendavissmith** [comment]
Closing, will reopen if we decide to pursue this but no plans currently
