### ISSUE TITLE
Deferred Stripe Connect Accounts No Longer Available after 2020 May

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1590]
p7bbVw-38w-p2

Starting in July, Stripe Connect accounts created using the deferred flow will be unable to accept payments from buyers until the seller/merchant completes Stripe on-boarding. This is due to the new [CDD (Customer Due Diligence) Rule](https://www.fincen.gov/resources/statutes-and-regulations/cdd-final-rule).

The existing flow prompts users to verify their email but allows them to accept payments. This will not be the case after July and we can expect some merchants to be surprised that the Stripe payment method isn't working.

We'll want to return more than just `payouts_enabled` for the sake of determining if the account is fully activated - we will also need `charges_enabled`

https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-stripe.php#L88

We'll also need to update our prompts/UI. Some suggested language that could be copied/leveraged is available in https://github.com/Automattic/wp-calypso/issues/31082

See also https://stripe.com/docs/connect/identity-verification-api#determining-if-identity-verification-is-needed

cc @dechov @pmaiorana

**Comment by allendav** [comment]
Note: Hold for now. See referenced P2 post.

**Comment by allendav** [comment]
Update from Stripe - deferred flow will become unavailable now on May 31 2020

cc @bmccotter

**Comment by allendav** [comment]
@laurendavissmith - I took the liberty of adding this to the next upcoming milestone - we don't want to miss the May 2020 deadline

cc @bmccotter

**Comment by c-shultz** [comment]
This should be addressed by https://github.com/Automattic/woocommerce-services/pull/2008
