### ISSUE TITLE
WC tested up to 3.6

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1603]
Test with 3.6 and update the `WC tested up to:` header in woocommerce-services.php

**Comment by RadoslavGeorgiev** [comment]
I tested WCS with core 3.6 RC1 and later RC2, everything seemed to work fine.

Considering some issues, which are currently being reported by our customer(s), it would be a great idea for someone else to also do a full test with 3.6 (no RC) and update the header.

**Comment by allendav** [comment]
Not sure why this didn't auto close. Closing.
