### ISSUE TITLE
"postal code is invalid"

### ISSUE THREAD

**Issue by JessicaVictoria24** [Automattic/woocommerce-services#1606]
I've had my store for about a week now. Everything's working great, except I've had a couple people say when they try to order something on my store, it says "postal code is invalid". They tried multiple times. What could this be? How can I fix it?

Other info:
I have taxes disabled
Calculations disabled
This has only happened to two customers (that I'm aware of)
I got the attached email from woocommerce support
![email](https://user-images.githubusercontent.com/49800096/56449639-4326db00-62ea-11e9-9977-99172552592b.jpg)

**Comment by laurendavissmith** [comment]
Please [contact support](https://woocommerce.com/my-account/create-a-ticket/) to get further assistance on debugging this issue
