### ISSUE TITLE
Blank, Gray (empty) create new label button on Edit Order (500)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1609]
WooCommerce 3.5.7
WooCommerce Services 1.19.0

Opened Edit Order on an order in Pending Payment state with a Billing and a Shipping address and a product. Noted that the Create New Label button was blank (gray) and never initialized, never saw the "Labels will be purchased" prompt in the Shipping Label meta box either.

Noted the following in the console:
```
/wp-json/wc/v3/data/continents:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/wp-json/wc/v1/connect/packages:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

Unfortunately, WP_DEBUG was false on this site, so the PHP error logs contained very little:

```
[Fri Apr 26 07:29:40 2019] [warn] [client 73.59.80.90] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 07:29:40 2019] [error] [client 73.59.80.90] Premature end of script headers: index.php, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 07:29:41 2019] [warn] [client 73.59.80.90] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 07:29:41 2019] [error] [client 73.59.80.90] Premature end of script headers: index.php, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 07:29:42 2019] [warn] [client 73.59.80.90] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 07:29:42 2019] [error] [client 73.59.80.90] Premature end of script headers: index.php, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
```

Refreshing the page got the meta box to render properly. I refreshed a few times and could not reproduce the problem.

**Comment by allendav** [comment]
It happened again. Even with WP_DEBUG on, only the following was logged:

```
[Fri Apr 26 13:49:58 2019] [warn] [client 73.59.80.90] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
[Fri Apr 26 13:49:58 2019] [error] [client 73.59.80.90] Premature end of script headers: index.php, referer: https://www.allendav.com/wp-admin/post.php?post=331&action=edit
```

Again, this was a 500 for wp-json/wc/v3/data/continents

Edit: Note: Part of the trick seems to be in waiting a while before opening the Edit Order page. In both this case and the original one above, it was only the first time entering Edit Order after hours had passed that I could get this to happen.

**Comment by allendav** [comment]
This could be procwatch on the shared hosting on my test site. I have opened a ticket with them to see if that is the case here.

**Comment by allendav** [comment]
Dreamhost confirms procwatch was killing those requests:

> Thanks for reaching out DreamHost support. I will be glad to assist you
with this request.

> Upon reviewing this site logs I was able to confirm your theory. Yes, the
errors you are seeing are PHP memory limits being hit. When this happens
the server is configured to kill all the processes to avoid an overload,
hence the 500 errors or ¨Premature end of script headers¨ as you may see
them in the error log.

> In order to correct this, we recommend optimizing the site with the steps
listed, here: https://help.dreamhost.com/hc/en-us/articles/215300867

> Also, there are a few pending plugin updates, which can also cause the
PHP memory limits to be hit. Please try to install these updates as part
of the optimization process. 

> Lastly, we recommend updating the PHP version from 7.0 to 7.2 fast CGI,
to have the site in better shape, hence a faster site. 

> I hope you find this information useful. Please feel free to reply to
this message if you have any other questions, we will gladly assist you
further.

**Comment by v18** [comment]
@allendav  - were you able to resolve this by following your host's suggested steps?
