### ISSUE TITLE
Test and Update for WP 5.2

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1621]
in 2048636-zen a customer said that Woo Services is not tested up to WP 5.2, looks like it’s at `Tested up to: 5.0.4` in the .org repo

**Comment by dechov** [comment]
Do we know why it currently says 5.0.4? The tag in the readme.txt reads 5.0.3:

https://github.com/Automattic/woocommerce-services/blob/3d61af6769930a17a0f64da3c64cf2da720eea09/readme.txt#L5

…and it's unchanged in svn.

**Comment by allendav** [comment]
We should also update the WooCommerce compatibility value too

**Comment by allendav** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/commit/0e01a6dea5c06f40427e7b71119c78b8d85e7de9
