### ISSUE TITLE
Choosing "Cancel and go back" when connecting to Stripe.com results in 400 error

### ISSUE THREAD

**Issue by dougaitken** [Automattic/woocommerce-services#1624]
## Steps to reproduce the issue

1. Install and go through WooCommerce Onboarding Wizard
2. Remove email address in Stripe setup
3. Include Jetpack
4. Deselect Automated Taxes
5. Install WCS manually
6. Connect Jetpack
7. Go to WooCommerce > Settings > Payments > Stripe and see message to connect to Stripe.com
8. Press "Cancel and go back" 

Error message:
`{"statusCode":400,"error":"Bad Request","message":"child \"code\" fails because [\"code\" is required]","validation":{"source":"query","keys":["code"]}}`

Gif of experience on a JN site:

![stripe_wcs_connect_400_bug](https://user-images.githubusercontent.com/52214/59446562-a66c4f80-8df9-11e9-83b0-cfd853a0110f.gif)

## Expected/actual behavior

When pressing "Cancel and go back" I'm returned to `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`

## Isolating the problem

- [x] This bug happens with only WooCommerce, Jetpack, WCS, and Stripe plugins active
- [x] I can reproduce this bug consistently using the steps above

**Comment by dechov** [comment]
Server-side fix being tested – re-opening this until it's deployed.
