### ISSUE TITLE
Non-roman characters are printed as question marks (?) on labels

### ISSUE THREAD

**Issue by fhaps** [Automattic/woocommerce-services#1625]
Non-roman characters are not accepted by the extension, when creating labels.

To test this, I entered the following set in the Name field: `Test 서울특 Testing`.

This was printed as `Test ??? Testing` on the actual label after it was purchased. See below:

![](https://cld.wthms.co/3OUGRj+)
Image Link: https://cld.wthms.co/3OUGRj

**Comment by superdav42** [comment]
I tested this when working on #1862 and I think it's not a problem we can fix because it's a limitation of the way USPS generates the labels. Their software just cannot render most unicode characters.
See https://www.easypost.com/blog/2013-05-20-foreign-language-support
I tested Piña colada and it was correctly converted to Pina colada so it wouldn't have '?'s but there no converting the asian characters so I think there's nothing we can do.

**Comment by c-shultz** [comment]
@aleftick, any thoughts on this one?

Are foreign characters in the destination address an important use case? Maybe we need some input validation when they're entering a destination address to warn them if the characters they're entering cannot be displayed on the label?

**Comment by aleftick** [comment]
Indeed, it can be a scenario, especially for international orders. Although the items are delivered to the address and not the person so postal carriers don't usually need a person's name. However, they are needed in some scenarios (for example, proof of ID) or for the recipients (for example to distribute in an office).  

I suggest that we email `support@easypost.com ` and ask them. We can't be the first to encounter this issue. They can guide us to a solution.

**Comment by jessLundie** [comment]
We have another report of this in 2992714-zen.

In this case, the character is °. This symbol is ascii code 248, so possibly there is a workaround here? 

The degree character is used in many addresses in Spain, and this is affecting the merchant's ability to ship to a number of addresses.

**Comment by tijosh** [comment]
> I suggest that we email support@easypost.com and ask them.

@aleftick did we reach out to easypost at all? Is that something you'd like Happiness to do?

**Comment by aleftick** [comment]
I just sent EasyPost an email.

**Comment by phillipcornwell** [comment]
@aleftick Has there been any update on this?

**Comment by aleftick** [comment]
EasyPost responded. In short, the carriers don't support those characters and EasyPost will replace them with "?".

> We support encoding with UTF-8, which allows 2 million+ characters. Unfortunately, most carriers cannot handle all the characters in UTF-8, and these unsupported characters show up as '?' on the carrier's labels. This is a problem with each carrier and not something we can fix on our end. When printing labels, all carriers support ASCII which has 128 characters (characters 'a' through 'z' and numeric values 0 through 9). The terms "ASCII" and "ISO-8859-1" (sometimes "ISO-8859 Part 1") tend to refer to one of the more limited character sets that are commonly accepted by all carriers. 

The address validation would signal the issue with a non-roman character issue in the address. It wouldn't for the addressee but that doesn't impact deliverability. 

@c-shultz - At some point, we could have better error messaging to inform users to switch the non-roman characters to roman characters.

**Comment by Sultan91** [comment]
Hello, do you know if easypost support auto-translation (transliteration) from non-roman to latin alphabet as it was mentioned in their [blog](https://www.easypost.com/blog/2013-05-20-foreign-language-support)?

**Comment by namiokuzono** [comment]
5179905-zen

**Comment by namiokuzono** [comment]
@FangedParakeet Could you please take a look at this issue and revisit when you have a chance? I see that the tag has been changed from Bug to Enhancement 2 years ago. 

Currently referred in this thread: p1651638028309889-slack-C7U3Y3VMY

**Comment by FangedParakeet** [comment]
I've added this to Fulfill Codeable's work queue. 

I think a good goal here to resolve this issue would be to warn customers that they are entering an address containing unicode characters that may not be presentable on a printed label and perhaps to offer the closest transliteration that we are able to muster as a compromise. It looks like this is definitely an issue for USPS labels, but likely we should provide the same validation for all labels, just in case.

**Comment by alana314** [comment]
+1 still having this issue
