### ISSUE TITLE
Alert user when using Media Mail

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#1626]
Users may not be aware there are restrictions on using media mail. It's the shipper's responsibility, but we could be nice and alert them about it.

A possible solution:
- on the server, add warning/error/note property to rates response when fetching rates for purchase
- if there's a warning/note/etc present for a rate, display it in the purchase flow in the plugin

h/t @jaclync

**Comment by laurendavissmith** [comment]
Closing since we're not focusing on live rates at the moment
