### ISSUE TITLE
Update Travis: Minimum PHP Version Required to Run WordPress 5.2 Is Now 5.6.20

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1629]
This test can no longer succeed:

<img width="1076" alt="Screen Shot 2019-06-19 at 1 44 49 PM" src="https://user-images.githubusercontent.com/1595739/59799068-71984680-9298-11e9-87e8-08203e611b47.png">

**Comment by v18** [comment]
Fixed in #1628
