### ISSUE TITLE
Switch APV Adjustments over to Extendables

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1636]
We ( Extendables ) need to begin handling the APV Adjustments. This story is to get systems to switch the emails over to the team email address ( look in the team page in Matticspace to find ours ) and to also ensure the janitorial responsibilities are updated to reflect that this is now part of the weekly janitorial duties.

More info here, https://wcship.wordpress.com/2019/07/12/usps-apv-adjustment-6-22-19-6-28-19-40-08/

**Comment by c-shultz** [comment]
Janitorial process added here: https://extendomattic.wordpress.com/janitorial/#process-apv
Emails now being sent to team alias: https://systemsrequests.wordpress.com/2019/08/02/hello-woocommerce-services-is-moving/
