### ISSUE TITLE
Spike: How we'll handle feature flags

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1637]
For multi-carrier support we need have the ability to ship code prior to having partnership agreements in place and then at a later date without doing a deployment turn those features on.

Deliverable: P2 on wcship p2

**Comment by superdav42** [comment]
P2 made https://wcship.wordpress.com/2019/08/05/i-have-investigated-different-ways/
TLDR just update the config of WooCommerce Connect Server.
