### ISSUE TITLE
Spike: Research how to add new carrier

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1638]
This is a technical spike to dig into the WCS codebase and start figuring out what we'll need to do to add additional carriers (UPS/FedEx/etc..). The goal is to be able to use this research once we're ready to create stories for the implementation of the new carriers.

Deliverable: P2 post on wcship, discussion at dev roundtable

**Comment by superdav42** [comment]
Is the scope of this to add a new carrier to use to generate and print shipping label? Or to get live rates form? or both? I'm not sure what the future of live rates is.

**Comment by laurendavissmith** [comment]
It will need to get rates for the label but the scope is for generating and printing shipping labels, so anything that the current USPS label can do now is in scope for additional carriers.

Having live rates show up to the customer on the front-end is not in scope, those will remain with our other extensions for now

**Comment by roykho** [comment]
https://wcship.wordpress.com/2019/08/09/how-to-add-a-new-carrier-on-wcs/
