### ISSUE TITLE
Spike: Determine if we can begin putting features directly into WCS 

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1640]
We are going to phase out our support of the Calypso dependency but until we do that it would be ideal if our feature work can begin going directly into WCS without having to remove Calypso yet or if that work needs to remain in Calypso until we remove the dependency.

Deliverable: discussion at dev roundtable, p2 post on wcship

**Comment by roykho** [comment]
Based on our roundtable talk, we decided the best course of action to add new features without affecting core Calypso is to copy WCS code into the core WCS structure and add new features into that.

This way we keep Calypso the way it is now without having to deploy anything for that and will keep the way Store.com works.

Here are some overlapping discussions https://wcship.wordpress.com/2019/08/28/explore-removing-calypso-dependency-from-woocommerce-services/
