### ISSUE TITLE
Introduce custom package setting into the create label flow

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1647]
Currently the ability to create custom packages is only available buried deep in the settings. We want to add this to the create label flow.

Work with @olaolusoga on how to incorporate this into the accordion

**Comment by dechov** [comment]
See also https://github.com/Automattic/woocommerce-services/issues/1585

**Comment by superdav42** [comment]
PR is started at https://github.com/Automattic/woocommerce-services/pull/1661 if anyone wants to work in this while I am AFK
