### ISSUE TITLE
Spike: Determine how to handle our dev process

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1649]
Should we use Git Flow? If yes, how will that work given that there are multiple repos in play currently ( WCS, WCS Server, Calypso )

How does Calypso affect our release process?

We need to fully understand how we will develop, merge, and release

Deliverable: p2 on wcship, discussion at dev roundtable

**Comment by bor0** [comment]
I feel like this issue should probably start at the roundtable (instead of discussing it there being a deliverable)

**Comment by c-shultz** [comment]
Some questions to kick off the roundtable discussion:
- Will others outside of our team be working in WCS repo (e.g. for taxes/payments stuff)?
- Can we move the the frontend out of Calyspso? (some discussion on that has started here: https://wcship.wordpress.com/2019/08/28/explore-removing-calypso-dependency-from-woocommerce-services/)

The biggest blocker to running with gitflow will be the fact that the frontend lives in Calypso, so all releases will depend on when Calypso can be released. If we can drop Store support, then that will likely free us up a lot.

**Comment by c-shultz** [comment]
Gitflow should work great since we're copying frontend code into repo: #1652 
Team is agreeable to using when we discussed at team meeting and dev roundtable.
