### ISSUE TITLE
Incorrect tax rates for Quebec

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/woocommerce-services#1654]
Tax rates for Quebec are charged as GST only 5%, they are not adding PST (QST) 9.975 
Total should be 14.975%

https://canadabusiness.ca/government/taxes-gst-hst/federal-tax-information/overview-of-charging-and-collecting-sales-tax/

Tax log for billing/shipping to Quebec City, Quebec G1R 3X2 shows QST as 0 instead of 9.975

![https://cld.wthms.co/OhHxDK](https://cld.wthms.co/OhHxDK+)
Full Image: https://cld.wthms.co/OhHxDK+

Rates table generated from automated taxes:

![https://cld.wthms.co/iBTpB9](https://cld.wthms.co/iBTpB9+)
Full Image: https://cld.wthms.co/iBTpB9+

**Comment by orhanfernandes** [comment]
Similar issue on 3112814-zen

**Comment by RWSyk** [comment]
Why is this still an outstanding issue? Has everyone just stopped selling to Quebec?! Otherwise this should have been fixed a long time ago.

**Comment by martindubenet** [comment]
Again, why is this issue still pending !? Please fix it and/or update the status of this important issue for non geek online retailers

**Comment by drwpcom** [comment]
Other cases in 4825848-zen, 4307382-zen. We also have questions about this on the forums.

The issue seems specific to Quebec. Both federal and provincial taxes are charged for British Columbia, Saskatchewan, Manitoba.

**Comment by dustinparker** [comment]
Hey everyone, just a quick update:

I've done some digging into this and it appears to be an issue on TaxJar's end. I've tested the API externally and get the same result, so it doesn't looks like it's caused by WC Shipping & Tax.

I've opened a ticket with TaxJar explaining the issue and will hopefully hear back from them soon. I'll keep you posted.
