### ISSUE TITLE
`Create shipping label` button not on top for mobile view

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1662]
In latest `develop`, when the width of the order page is reduced, the shipping label button is no longer on top:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/6209518/65071297-81d5c580-d95c-11e9-92fc-c15c10dfea83.png">

Where desktop layout (correctly) has it on top:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/6209518/65072656-30224080-d946-11e9-9492-14bdb9455198.png">

**Comment by roykho** [comment]
I believe this is fine and behaving correctly. In mobile view, WP puts the sidebar meta on top first and then the main content after. And if you look closely, you can see the "Create Label" meta box is still the top meta box in the main content.

The user will have to scroll down anyhow to reach the order details area in which they will see the "Create label" meta box first.

**Comment by c-shultz** [comment]
@roykho makes a good point. I'm marking this for discussion so we can decide as a team.

**Comment by c-shultz** [comment]
We discussed at roundtable and we decided it's fine as is.
