### ISSUE TITLE
Tooltip blocking "Create shipping label" for first time use

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1694]
### Reproduce
1. Setup base account country to US and currency to USD. 
2. Navigate to an order
3. Tooltip shows up
4. But the tooltip blocks part of the create shipping label

![image](https://user-images.githubusercontent.com/572862/66113492-8beef980-e5d5-11e9-8345-6640217b5efb.png)

Is this expected?

**Comment by laurendavissmith** [comment]
@olaolusoga what are your thoughts on this one?

**Comment by superdav42** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/pulls?q=is%3Apr+is%3Aclosed
