### ISSUE TITLE
Dropdown rates missing items.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/woocommerce-services#1696]
This is a follow-up Issue to the #1659. The rates dropdown design has elements not present in the #1659 implementation. This elements are not present in the connect server message. Before we will be able to add them to the UI we need to update connect server: https://github.com/Automattic/woocommerce-connect-server/issues/1301

**Comment by bor0** [comment]
@budzanowski I think #1659 referenced is the wrong issue. Perhaps you meant #1695?

**Comment by c-shultz** [comment]
I believe this is blocked until some or all of these issues are resolved:
https://github.com/Automattic/woocommerce-connect-server/issues/1303
https://github.com/Automattic/woocommerce-connect-server/issues/1304
https://github.com/Automattic/woocommerce-connect-server/issues/1305

**Comment by bor0** [comment]
@c-shultz good catch, but we can probably even close this, as we broke down https://github.com/Automattic/woocommerce-connect-server/issues/1301. Should be covered by the newly created woocommerce-connect-server's issues?

For example, for https://github.com/Automattic/woocommerce-connect-server/issues/1303 I have both https://github.com/Automattic/woocommerce-connect-server/pull/1306 and https://github.com/Automattic/woocommerce-services/pull/1720.

No strong preference, but we can probably avoid creating duplicate issues.

**Comment by c-shultz** [comment]
@bor0, I see that in each those three issues you said, `Might require changes on both connect-server and extension.` So I think those issues should cover everything. We can open extension-side issues from any of those three issues if needed.

I'll go ahead and close this.
