### ISSUE TITLE
Delivery date and guaranteed date.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/woocommerce-services#1726]
Based on information found in:
https://www.easypost.com/can-i-set-an-expected-delivery-date-with-your-api

We should display the delivery date as :
Approximate when `delivery_date_guaranteed` is false and a certain when this field is true.

**Comment by laurendavissmith** [comment]
@aleftick will provide the verbiage for this, there is a certain language used in the carrier world

**Comment by aleftick** [comment]
_I did quite a bit of research to see if we could approach this in a different way (like using USPS SLAs) and to avoid the EasyPost response increase. All things considered, I believe this is the best path forward_ 

For Priority Mail Express, EasyPost provides USPS's guaranteed delivery date. For every other service, we get the expected number of days it will take to make the delivery.

We should use the following verbiage:
- When there is a `delivery_date_guaranteed`, we should display "[date]". For example "November 13".
- When there is a `delivery_days`, we should display "[number of days] business days". For example "3 business days" and "1 business day".

We may be required to have footnote (I'm getting Legal to review):
> *Delivery timelines provided by USPS and not guaranteed by Automattic Inc. For exceptions and details visit [USPS.com](https://www.usps.com).

**Comment by aleftick** [comment]
FYI: Request to Legal about any legalize is [here](https://wp.me/p2y3YZ-3LH).

**Comment by aleftick** [comment]
Legal responded and they will update the TOS. We don't need to add any footer note.

**Comment by superdav42** [comment]
I was looking at implementing this but `delivery_date_guaranteed` is always false for all rates returned at least in USPS. USPS Priority Mail Express is the only USPS service with guaranteed delivery dates but it is returning:
```
  delivery_days: null,
  delivery_date: null,
  delivery_date_guaranteed: false,
```
Which means it displays nothing where it should say a delivery date. Not sure why we are not getting a date back from easypost but I believe it's related to not specifying a shipping date and time.  USPS [official calculator](https://postcalc.usps.com/) requires there is no way I can see to specify a shipping date and time in the easypost API request.

**Comment by superdav42** [comment]
EasyPost seems to be saying it's all USPS's fault and there's nothing they can do. To avoid showing nothing for delivery days for Express I suggest we show the same delivery days as Priority. Express is the fastest so it will be under promising and over delivering.

**Comment by aleftick** [comment]
I actually think he's misinformed and it's simply because our account doesn't have the "flag" turned on to return delivery dates for PME.

This is a reply from them on another exchange:

> First, that field is not always expected to be populated; whether or not it is is dependent on the carrier and the service level in particular. This leads to my second note: The service level of the rate you've provided, USPS Express, is a sort of special case. We'd need to set a flag to populate that value for Express shipments, because doing so slows down the API response by as much as 500ms.

We should turn on the flag but I suspect it will affect our current version as soon as we turn it on. Let's coordinate on slack before we make the request.
