### ISSUE TITLE
JS tests are not being run by Travis

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1749]
#1747 introduces JS test infrastructure. We should get the `npm run test-client` added to our .travis.yml so we're always running the tests.

**Comment by c-shultz** [comment]
#1747 and a fix for #1748 should get merged ahead of this one getting merged so we're not failing our build on all PRs

**Comment by bor0** [comment]
Thanks for creating this @c-shultz. I think this should have a higher priority - it's a simple fix and also at the same time will prevent us from creating and resolving issues like #1748 (which may take more time to fix).

I'd go as far as to prevent PRs from being merged if a build is red.

cc @laurendavissmith

**Comment by laurendavissmith** [comment]
Always feel free to raise the priority on any issues, I agree with your assessment here btw

**Comment by bor0** [comment]
Sorry, I wasn't clear, I pinged you specifically about the preventing of merge of red PRs. Maybe we can discuss it at the team meeting :)
