### ISSUE TITLE
Changing packages too many notifications

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1757]
When you change your package settings a lot you end up with a bunch of notifications that you have to dismiss. It'd be nice to have these disappear automatically after a few seconds.

<img width="458" alt="Screen Shot 2019-10-29 at 3 37 18 PM" src="https://user-images.githubusercontent.com/879137/67807052-08a0b680-fa62-11e9-845b-0c96e51d1573.png">

**Comment by bor0** [comment]
@laurendavissmith these automatically disappear [after 5 seconds](https://github.com/Automattic/woocommerce-services/blob/154c871/client/apps/shipping-settings/view-wrapper.js#L42). Do we want to lower the duration or just close this issue?

**Comment by laurendavissmith** [comment]
that wasn't happening for me 🤔 that screenshot i took after about a min

**Comment by bor0** [comment]
Was it for the Settings screen?

**Comment by laurendavissmith** [comment]
no it was the modal screen, sorry terrible screenshot 😄

**Comment by laurendavissmith** [comment]
actually this may just be on my end? all through wp.com i'm seeing those notifications never disappear so if its working for you then no worries on this one we can just close it

**Comment by bor0** [comment]
@laurendavissmith good catch! It's indeed happening on the modal :)
