### ISSUE TITLE
Missing USPS logo

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1758]
I setup a site on Jurassic Ninja and I cannot see the USPS logo

<img width="159" alt="Screen Shot 2019-10-29 at 3 39 48 PM" src="https://user-images.githubusercontent.com/879137/67807236-6f25d480-fa62-11e9-8f99-59a2cd4620d7.png">

<img width="501" alt="Screen Shot 2019-10-29 at 3 41 29 PM" src="https://user-images.githubusercontent.com/879137/67807337-9ed4dc80-fa62-11e9-8170-32c415101fb8.png">

**Comment by harriswong** [comment]
It would be good if we can use `webpack-merge`. We can then split the above easily into
- webpack.common.js
- webpack.dev.js
- webpack.prod.js

**Comment by harriswong** [comment]
Almost marked it as can't reproduce since I do see the image. But upon inspection, it is using `localhost`
![image](https://user-images.githubusercontent.com/572862/67981567-8f7e9c00-fbe6-11e9-8572-9c22a4c12d20.png)

**Comment by laurendavissmith** [comment]
@harriswong i'm going to close this for now since we've decided to have no logo until we get official consent
