### ISSUE TITLE
Deleting custom package after label is started causes button to no longer work

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1759]
1) Create a new label
2) Add a custom package
3) Close modal
4) Go to WooCommerce > Settings > Shipping > WooCommerce Services
5) Delete custom package
6) Go back to order
7) Click create label button
8) Modal will no longer open

<img width="770" alt="Screen Shot 2019-10-29 at 4 39 36 PM" src="https://user-images.githubusercontent.com/879137/67811415-b57f3180-fa6a-11e9-9069-aebdaa1b6316.png">

**Comment by laurendavissmith** [comment]
Bumped to critical because after this happens all orders get affected, they can launch the modal but as soon as you click `Use Package` it closes the modal with the same JS error

**Comment by bor0** [comment]
After 1acb176986ebca00beab91154f31ad96d424e1cb this will be tricky to reproduce since there is no longer `Create shipping label` button once you create a label - it turns to `Track packages`.

But I still think it's worth fixing this. To test, apply this patch:

```
diff --git a/client/apps/shipping-label/view-wrapper-label.js b/client/apps/shipping-label/view-wrapper-label.js
index 0fe02b42..36d417db 100644
--- a/client/apps/shipping-label/view-wrapper-label.js
+++ b/client/apps/shipping-label/view-wrapper-label.js
@@ -92,6 +92,14 @@ class ShippingLabelViewWrapper extends Component {
 				);
 			}
 
+return (
+	<Button
+		 className={ className }
+		 onClick={ this.handleCreateLabelButtonClick } >
+		 { translate( 'Create shipping label' ) }
+	</Button>
+)
+
 			return (
 				<Button
 					onClick={ this.handleTrackPackagesButtonClick }
```

**Comment by laurendavissmith** [comment]
@bor0 you can test it with a new order, because this also affected future orders where the modal would launch but as soon as you clicked `use packages` it would close with a js error, that was actually why i ended up bumping the priority otherwise it wasnt a huge deal

**Comment by bor0** [comment]
@laurendavissmith ah, that is correct.
