### ISSUE TITLE
Discounted shipping label tooltip is pointing at "Design your store"

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1760]
First time user experience user tool tip for discounted shipping label seems to be pointing at the wrong thing

To reproduce, go create a fresh store in Jurassic ninja. 
1. Setup a new store
2. Install WooCommerce and WooCommerce Service
3. Setup store
4. Add product, checkout order
5. Go to orders page and tooltip not pointing to shipping label button

![image](https://user-images.githubusercontent.com/572862/67814240-2887a880-fa69-11e9-9f37-caa110b64e83.png)

**Comment by bor0** [comment]
That's odd. I get this:

<img width="1203" alt="Screen Shot 2019-11-05 at 11 25 56" src="https://user-images.githubusercontent.com/1620929/68199842-0fc64800-ffbf-11e9-972d-a3e4c76c87dc.png">
<img width="856" alt="Screen Shot 2019-11-05 at 11 25 49" src="https://user-images.githubusercontent.com/1620929/68199844-0fc64800-ffbf-11e9-9020-28cd2ae763e4.png">

**Comment by Ferdev** [comment]
I think it's because you don't have the "Design your store" card. I think that card is moving the tooltip down. Trying to reproduce it right now.
