### ISSUE TITLE
Certain rates are filtering out signature required even if its included

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1771]
Certain rates include signature required as part of their rate but this is being filtered out on our rates screen. We need to not filter these rates and allow them to set signature required if its included in the rate and also say in the text that its included at no charge.

**$0 doesn’t necessarily mean that is include for free. Some services might not offer it (like international). Is there a way to know from the API response? Or should look to usps sla and we hard code it?**

@aleftick we'll need the verbiage for this

Slack thread with more info: https://a8c.slack.com/archives/CAKN301C3/p1572396322381400

More info from @c-shultz 

> I specifically filtered out the signature option when the price difference was $0. I made a (maybe wrong) assumption that if there was no price difference, then signature was not available.
The fix may be as simple as removing that check if I’m understanding the option correctly

**Comment by aleftick** [comment]
The verbiage for when "signature required" is included in the service (such as PME):
1. `Includes USPS tracking` to `Includes USPS tracking, and signature required`
2. What is for the other services `Signature Required (+$2.60)`, will be `Signature required (Free)` when it's included with the service.
 
Additionally, where we currently have`Signature Required (+$2.60)` it should be `Signature required (+$2.60)`. No capitalization to the `r`.

It doesn't seem likes USPS offers any signature confirmation options for international shipments but I am curious what the API returns. Let me know I can dig deeper into the USPS product details to find out.

**Comment by budzanowski** [comment]
@laurendavissmith  we hard code it. API response offers no information if the rate was offered with a signature or not. I did manually queried the EasyPost API and there is no information about signature there. Rates objects are exactly the same except the rate itself. I think that this is something that we need to discuss with EasyPost.

I have attached two example responses for the same setup with the only difference of requesting or not requesting a signature.

[signature_and_no_signature_rates_api_response.zip](https://github.com/Automattic/woocommerce-services/files/3793996/signature_and_no_signature_rates_api_response.zip)

@aleftickIs this is something that should be discussed first with EasyPost imo. One thing is the USPS SLA ( which would be good to know ) and another thing is what EasyPost does with the request and can they provide feedback if the Rates object if a signature is available ( and included in the rate, and maybe a separate cost field with signature cost ) or not.

**Comment by budzanowski** [comment]
Setting this as blocked until we will figure out more.

**Comment by laurendavissmith** [comment]
will you ping @aleftick in Slack so he is aware (if you haven't already) we have a dev contact at easypost so we need to get an email over to them

**Comment by aleftick** [comment]
I emailed EasyPost and cc you @budzanowski.

**Comment by laurendavissmith** [comment]
@aleftick will you add the-extendables@matticspace.com to the email chain and use that for these types of emails, we can't always be certain that the person currently assigned will be the person which finishes the issue out

**Comment by aleftick** [comment]
Based on EasyPost answers I think we need to hard code it. What do you think @budzanowski?

Hence:
- **International Services**: In our current version, we offer it as an option but I don't believe we actually offer it; in fact, I can't even confirm that USPS even offers internationally. The price never changes. I also notice Shopify and Stamps.com don't offer it. **Hence I am concluding that we shouldn't offer it.** 
- **Domestic Services & Signature Required**: `Signature Required` is an option for all USPS domestic services but **not** for `First-Class Mail` (however it's available for `First-Class Package Service`) and for `Media Mail` if not a package. Cost $2.60 (vs $3.05 at a Post Office, so we could add the saving total). For `Priority Mail Express`, it's included for free.
- **Domestic Services & Adult Signature Required**: In our current version, we offer the `Adult Signature Required` option however I don't see it in the new mockups. Hence we shouldn't stop offering it. `Adult Signature Required (+$6.40)` should be added under `Signature Required (+$2.60)`. `Adult Signature Required` is an option for all USPS domestic services but **not** for `First-Class Mail` (however it's available for `First-Class Package Service`) and for `Media Mail`. The cost is $6.40.

Here is Q&A with EasyPost.

Q:
> In our effort to update our UI to WooCommerce Shipping, we're improving the flow for merchants to request a "Signature required". For context here is a mock-up:
> Here are our questions:
> 1. Is there a way to know if "Signature required" is an option for that shipment service via the Rate object in the API return?
> 2. Is there a way to know if "Signature required" is included or an extra fee (and what that fee is) via the Rate object in the API return?
> 3. And if not in the Rate object, what should we hard code. Are there some set "rules" by USPS that we can use?

A: 
> Thanks for the question! Information about requiring signatures can be found in our documentation under the options object with the attribute of delivery_confirmation. An example of how to do this is below:
> 
> ```
> options: {
>   delivery_confirmation: "SIGNATURE"
> }
> ```
> 
> This doesn't return anything additional on the rate object, it just passes the information to the carrier that a signature is required. If they charge extra, it's likely just included in the shipment cost that's returned in the rate.

Q:
> Looking at the documentation for "delivery_confirmation" it says "limited for international shipments". How do we know those limitations? If we make a shipment request for a carrier/service that doesn't offer that option, do we get an error message back?

A:
>It actually says "some options may be limited for international shipments". The limitations would depend on the carrier and location, which we don't unfortunately have on hand. If this is something that you are concerned about, you can reach out to the carrier you are questioning and see if they have limitations for delivery confirmation in specific countries.

Q:
>So if we make a shipment request for a carrier/service that doesn't offer that option, we won't get any error message back? The label would still be printed with that option, and it's to the shipper to know directly from the carrier if that option was available or not?

A:
>I've been trouble shooting this and couldn't find an example of when it didn't work, but it's probably safe to assume that you would get an error message if an option is passed and isn't available from the carrier. I couldn't find an example of when we would pass this error, so it seems like it would come from the carrier directly on the response.body.

**Comment by laurendavissmith** [comment]
removing the blocked label since we should have enough info to keep pushing this forward now

**Comment by laurendavissmith** [comment]
Need to go through the USPS docs to see what rates should be hardcoded, we'll want to hardcode this on the connect server side of things so that we can update it down the road without having to release the extension again

**Comment by c-shultz** [comment]
>Adult Signature Required (+$6.40) should be added under Signature Required (+$2.60)

For adult signature required, we would need some design direction on how that looks. We probably need radio buttons or a dropdown for the none, signature and adult selection.

**Comment by c-shultz** [comment]
I just opened #1787 so we can address the adult signature required separately.

**Comment by laurendavissmith** [comment]
@c-shultz lets just move forward with a dropdown, we wont have time to get a designer for this issue
