### ISSUE TITLE
WCS 1.22.0 Testing

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1784]
[Test Case 1](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#1)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [x] @superdav42 

[Test Case 2](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#2)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [x] @superdav42 

[Test Case 3](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#3)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [ ] @superdav42 

[Test Case 4](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#4)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [x] @superdav42 

[Test Case 5](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#5)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [x] @superdav42 

[Test Case 6](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#6)
- [x] @bor0 
- [ ] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [x] @roykho 
- [x] @superdav42 

[Test Case 7](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#7)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [x] @superdav42 

[Test Case 8](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#8)
- [x] @bor0 
- [x] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [ ] @superdav42 

[Test Case 9](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#9)
- [x] @bor0 
- [ ] @budzanowski 
- [ ] @c-shultz 
- [ ] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [ ] @superdav42 

[Test Case 10](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#10)
- [x] @bor0 
- [ ] @budzanowski 
- [ ] @c-shultz 
- [ ] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [ ] @superdav42 

[Test Case 11](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#11)
- [x] @bor0 
- [ ] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [ ] @superdav42 

[Test Case 12](https://hackmd.io/Go_7yLRmSFuS7atL5NrcVQ#11)
- [x] @bor0 
- [ ] @budzanowski 
- [ ] @c-shultz 
- [x] @Ferdev 
- [ ] @harriswong 
- [ ] @laurendavissmith 
- [ ] @roykho 
- [x] @superdav42

**Comment by Ferdev** [comment]
Test Case 11: not sure if international addresses are not supported, but I only could make it work with an US address.
