### ISSUE TITLE
Task to create .po/.mo files

### ISSUE THREAD

**Issue by bor0** [Automattic/woocommerce-services#1785]
`npm run release` was failing after fa39cf38e50d583b247534d5157ad283ab568dcb.

Not a big deal - I reverted it in 9b4c50c960cbbd85020a901fcafe98e7ceaf540b. However, we need to create tasks that will generate .po/.mo files. We already have something like this in `woocommerce-bookings` that can be re-used.

**Comment by Ferdev** [comment]
hey @boro! :wave: I've created a PR that generates the `.pot` file. For the `.po`/`.mo` files, Bookings downloads them from translate.wordpress.com, but this project isn't there. How do other projects get their translations?
