### ISSUE TITLE
'Adult signature required' is no longer available

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1787]
From @aleftick in https://github.com/Automattic/woocommerce-services/issues/1771#issuecomment-549642519 :
>In our current version, we offer the Adult Signature Required option however I don't see it in the new mockups. Hence we shouldn't stop offering it. Adult Signature Required (+$6.40) should be added under Signature Required (+$2.60). Adult Signature Required is an option for all USPS domestic services but not for First-Class Mail (however it's available for First-Class Package Service) and for Media Mail. The cost is $6.40.

**Comment by c-shultz** [comment]
Design support needed. Question from original issue:
>For adult signature required, we would need some design direction on how that looks. We probably need radio buttons or a dropdown for the none, signature and adult selection. Do we want to do that for this release?

Design support requested: https://a8c.slack.com/archives/CKNC7KACA/p1572987380139900

**Comment by c-shultz** [comment]
We'll use a dropdown for now (https://github.com/Automattic/woocommerce-services/issues/1771#issuecomment-550416956)

**Comment by aleftick** [comment]
Ola provided design elements for the UI: https://a8c.slack.com/archives/CKNC7KACA/p1573087613140400?thread_ts=1572987380.139900&cid=CKNC7KACA

**Comment by laurendavissmith** [comment]
@aleftick is there a use case where you have both sig required and adult sig required? we've already implemented the dropdown so if there isnt a use case here i'm not sure why we'd go down this road

**Comment by aleftick** [comment]
No, it should be one or the other. You can't have both.

As I understood Ola's design is that only one checkbox could be selected (or none).

**Comment by aleftick** [comment]
However, if it's already implemented and time is an issue, we can address this in a future release as we add more options.

**Comment by laurendavissmith** [comment]
Ok cool well in that case we should stick with a dropdown or radio buttons moving forward anyways, there isnt a UX pattern to use checkboxes when only one can be selected
