### ISSUE TITLE
Missing ownerName, email in "Email the label purchase receipts" option

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1798]
To reproduce, go to WooCommerce > Settings > Shipping > WooCommerce Services

http://localhost/wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings

![image](https://user-images.githubusercontent.com/572862/68436376-15688d00-017b-11ea-9b94-4bb9bf1f649a.png)

**Comment by bor0** [comment]
@harriswong is that website Jetpack connected? I assume not, according to this code: https://github.com/Automattic/woocommerce-services/blob/4def2cb/classes/class-wc-rest-connect-account-settings-controller.php#L34-L48

Here's what I get (e-mail redacted by me)

<img width="524" alt="Screen Shot 2019-11-08 at 13 55 13" src="https://user-images.githubusercontent.com/1620929/68478142-82d5f580-022f-11ea-8eb9-b33c0aec00f8.png">

**Comment by harriswong** [comment]
Just checked plugin settings, mine is in development mode so probably not connected. 

![image](https://user-images.githubusercontent.com/572862/68513091-5d4cea00-0237-11ea-9c08-31e437b58a70.png)

**Comment by harriswong** [comment]
My `$master_user` is `false`

**Comment by bor0** [comment]
@harriswong would you agree this is a non-issue? Or is there something we want to address?

**Comment by harriswong** [comment]
@bor0 I think it is a non-issue since Jetpack is required to install WooCommerce Service (i think). So that means this will never be a problem because Jetpack will always return those fields.

**Comment by laurendavissmith** [comment]
just saw this, yeah this is a non-issue because jetpack is always required right now
