### ISSUE TITLE
Add a means of notifying merchants when the WCC connection has stopped working

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#18]
Since merchants will be relying on WCC for shipping rates, possibly exclusively, we should notify the merchant in wp-admin and via at least one other non wp-admin method (e.g. email) when N successive calls to the WCC server fail, and possibly in other situations as well.

**Comment by jeffstieler** [comment]
Related to, if not dependent on: https://github.com/Automattic/woocommerce-connect-server/issues/217

**Comment by allendav** [comment]
Moving this out of Alpha and into Beta

**Comment by laurendavissmith** [comment]
Close pending new reports of this issue, if it continues to persist its something we should look into it on the connection side instead of notifying the user about it
