### ISSUE TITLE
You save value no longer clear when signature option is selected. Price summary is confusing.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/woocommerce-services#1801]
![image](https://user-images.githubusercontent.com/17271089/68480139-6092a680-0234-11ea-8a8b-16962c96d4e9.png)

The You save value does not reflect the additional cost of signature request.

**Comment by c-shultz** [comment]
I closed #1805 in favor of this issue, some details from #1805:

> This was discussed here: #1802 (comment)
> 
> For signature required rates, the retail rate is $3.05, but EasyPost returns $2.60, so the "You save" amount in the order summary is missing $0.45
>
>This is not new. 1.21.1 also displays the summary without the $0.45 savings.

**Comment by elizaan36** [comment]
Posted a solution for this here: https://github.com/Automattic/woocommerce-services/issues/1909
as part of differentiating the services better.

**Comment by Ferdev** [comment]
I'm closing this issue because as @elizaan36 said, this is covered by #1909.
