### ISSUE TITLE
Allow user to see the benefit of "free" "signature required" during label creation process

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1819]
Currently, we default to "No signature required", so the user can't easily compare the service benefits. Maybe we can default it to "signature required" if it's free. 

Need designer to take a look. 
cc @aleftick 

![image](https://user-images.githubusercontent.com/572862/68805037-42f08300-0620-11ea-9341-b7fdd324987f.png)

**Comment by c-shultz** [comment]
I'm closing this in favor of #1909 so it can be addressed more holistically.
