### ISSUE TITLE
US country and currency notices

### ISSUE THREAD

**Issue by bor0** [Automattic/woocommerce-services#1820]
After #1765, it seems we caused some [customer confusion](https://wordpress.org/support/topic/only-us-support/).

This error is specific to printing labels, so we either want to reword it or completely remove it.

**Comment by bor0** [comment]
I think we need to remove these notices to avoid customers being panicked about it.

This behavior was already documented https://docs.woocommerce.com/document/woocommerce-services/#the-create-shipping-label-button-is-missing-from-the-order-details-screen so, in my opinion, adding these notices were redundant.

**Comment by erikgeurts** [comment]
I agree that this is a very confusing message, and I'm surprised that this wasn't caught before v1.2.0 was released.
