### ISSUE TITLE
No USPS live rates for products without dimensions or weight

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1826]
## Problem
If a customer adds to the cart a product without weight or dimensions, they won't get shipping rates.

## Steps to reproduce it
1. Enable live rates for the site.
2. Add WooCommerce Services USPS provider to a shipping zone.
3. Create a product without dimensions or without weight.
4. Add the product to the cart, and try to get shipping rates to an address withing US.

## Notes
Tested in WooCommerce Services `1.21.1` and `1.22.1`

**Comment by johndcoy** [comment]
This is the expected behavior. USPS cannot return a rate if it does not know how big the product is.

**Comment by Ferdev** [comment]
Hey @johndcoy! :wave: Thanks for the info! The issue is the user has to enter both dimensions & weight in order to get rates from USPS. If either of them are missing, it won't return the rates. Is this behaviour still expected?

Thanks!
