### ISSUE TITLE
Insufficient first-class postage charged when using rigid envelopes

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#1827]
Rigid envelopes, like photo mailers, should be assessed a "Non-Machinable Surcharge" but aren't. This results in insufficient postage being calculated for first-class, e.g.:

![IMG_1469](https://user-images.githubusercontent.com/1595739/68984596-d1523980-07c5-11ea-936a-7ce58221150b.jpeg)

<img width="888" alt="Screen Shot 2019-11-15 at 4 26 59 PM" src="https://user-images.githubusercontent.com/1595739/68984623-f0e96200-07c5-11ea-9443-351b429ae4e2.png">

**Comment by laurendavissmith** [comment]
@allendav thanks for the report, we'll take a look at what's going on

**Comment by frosso** [comment]
Moved to feature for discussion: https://github.com/Automattic/woocommerce-shipping-issues/issues/123
