### ISSUE TITLE
Shipping Label metabox remains in the sidebar on the order edit screen

### ISSUE THREAD

**Issue by mikkamp** [Automattic/woocommerce-services#1830]
In the update to version 1.22 the Shipping Label metabox was moved from the sidebar to the main content area. However in WordPress it's possible to drag and drop metaboxes. If we do this then the order is saved in the user meta data. For example for the order edit screen it's saved in the user meta with the key `meta-box-order_shop_order`. Besides defining the order it also saves whether a metabox is displayed in the sidebar or not. If this is saved it will override the default, and can cause it to remain in the sidebar.

Steps to reproduce:

- Install WooCommerce Services 1.21
- Edit an order and drag and drop the Shipping Label meta box to a different location (ex. after the order notes)
- Upgrade to WooCommerce Services 1.22
- Notice that the Shipping Label remains in the sidebar (which makes the text go outside it's box)

![image](https://user-images.githubusercontent.com/11388669/69138195-21771780-0ab6-11ea-9210-1bd137917d10.png)

Because of the newly added CSS rule to hide the title we are unable to drag and drop it back to the main content location. One workaround for this is to temporarily unhide the metabox `<h2>` title so we can drag it back to the right location.

If there is a different value saved in the user meta `meta-box-order_shop_order`, should we override this to force it to end up in a different location?

**Comment by superdav42** [comment]
Seems the best fix would be to show the header always. Then update the meta box so it will reformat itself responsibly when it's moved to the sidebar. So merchants will be able to move the sidebar back and forth to the header or sidebar and it will still look OK and it won't move from where merchants have previously moved it to.
