### ISSUE TITLE
Spike: Utilizing Calypso as a build tool

### ISSUE THREAD

**Issue by laurendavissmith** [Automattic/woocommerce-services#1831]
As part of our research into the architecture of WCS its been brought up that we should possibly leverage Calypso as a build tool. This spike needs to research this in-depth, talk to some of the teams that have done this already and determine what that would entail for this extension.

More info here: https://extendomattic.wordpress.com/2019/10/05/woocommerce-services-architecture/#comment-4001

Deliverable: p2, dev roundtable discussion

**Comment by c-shultz** [comment]
I'm going to leave some notes on this before getting things more fully compiled in a P2 post:

Current situation: WCS currently extends the `wp-calypso` submodule build tooling. The dependencies are messy and the whole thing is hard to maintain, so I think it's clear that we want to move away from this.

Possible directions to go:
1. Copy build configuration from`wp-calypso` repo to WCS repo.
    - Pros:
        - This is probably the least disruptive choice in the short term since we still have a lot of Calypso component dependencies.
    - Cons:
        - We'll need to maintain this over time so we'll fall behind the latest and greatest build features.
        - Maintaining a separate set of build configurations is a waste of resources for Automattic

1. Use `calypso-build` (exploratory PR: #1846)
    - Pros:
        - Share build configuration and development resources with other teams
        - Stay more up-to-date as `calypso-build` is improved
        - Appears to include most necessary features (including the ability to import styles from .js files)
    - Cons: 
        - It's going to take some work to get it implemented

1. Use [wp-scripts](https://developer.wordpress.org/block-editor/packages/packages-scripts/) 
    - Pros:
        - Many of the same pros as using `calypso-build`
    - Cons: 
        - More limited functionality (no style imports from .js)
        - Potentially slower moving development because it's part of WordPress

**Comment by c-shultz** [comment]
P2 Post: https://wcship.wordpress.com/2019/12/02/building-woocommerce-services/
