### ISSUE TITLE
Add option to change Paper Size back to the label print screen

### ISSUE THREAD

**Issue by davischris** [Automattic/woocommerce-services#1832]
In version 1.22.0, the "redundant" Paper Size dropdown was removed from the label screen since it's configurable from the Settings screen.  This was not redundant.  When shipping domestically I print 4"x6" labels on a thermal printer, when shipping internationally I print on letter size adhesive paper.  It is very beneficial to be able to select the paper size (thus label type) when creating a label.  Returning to the settings page each time I want to print a label is very inconvenient.

**Comment by dougaitken** [comment]
Also discussed in 15197880-hc

**Comment by aleftick** [comment]
We see how useful it was to have that setting as part of the label creation process. Let's reintroduce it. We'll need to review the placement with Design since the page layout has changed.

We should add label the paper size options as:
- `Letter (8.5" × 11")`
- `Label (4" × 6")`

**Comment by LevinMedia** [comment]
@aleftick Here's an updated placement for the paper size select: 

![printlabel](https://user-images.githubusercontent.com/4500952/69985451-09f55100-14f0-11ea-9399-3d9358be154f.jpg)

**Comment by budzanowski** [comment]
@aleftick @laurendavissmith what is the status of this item? I am asking about when we are targeting a release with this change?

**Comment by aleftick** [comment]
@laurendavissmith can speak to a specific date but the idea is to release this sooner vs later.

**Comment by laurendavissmith** [comment]
We are releasing Monday so it will go out in the next release which date is still TBD
