### ISSUE TITLE
Ability to print second label

### ISSUE THREAD

**Issue by davischris** [Automattic/woocommerce-services#1833]
In previous versions of the plugin, I was able to return to the order page and print a second (or more) mailing labels.  This was often beneficial because I may have to ship a replacement part or subsequent item to a customer at a later time.  Version 1.22.0 and later changes the "create shipping label" button to a button to view tracking, removing the capability of printing a second label.

**Comment by thuautp** [comment]
Also reported in 2516317-zd

**Comment by aleftick** [comment]
Thanks for sharing this use case. We'll reintroduce the ability for users to print another label after a first one is printed. That function will be displayed in the top shipping bar beside the `Track Package` button. We're actively working on it (#1844).

**Comment by budzanowski** [comment]
Closed via #1884.

This will be released soon.
