### ISSUE TITLE
 Check if we need PHP 7.3 coverage in Travis' tests

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1837]
Original issue #1698

**Comment by superdav42** [comment]
I assume you're talking about PHP 7.3 coverage with e2e tests? Looks like they just run with PHP 7.2 now. Why not run e2e tests on all supported versions of PHP? Or does the test framework require php 7.2+?

**Comment by Ferdev** [comment]
Not sure, to be honest I just copied it from the original issue. @c-shultz or @harriswong do you have more info about it?

**Comment by harriswong** [comment]
@superdav42 @Ferdev I created this TODO because `.travis.yml` didn't include PHP 7.3. I noticed PHP 7.3 and 7.4 are added a month-ish ago:
https://github.com/Automattic/woocommerce-services/blob/develop/.travis.yml#L39-L46

Strange how both `WP_VERSION=trunk` and `WP_VERSION=latest` work.

**Comment by Ferdev** [comment]
Ok, thanks @harriswong! I'm closing this then.
