### ISSUE TITLE
Update .travis.yml notification to team email

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1838]
Related branch: `new/e2e-test-infrastructure`

Original issue #1698

**Comment by superdav42** [comment]
Changed email in travis.yml here https://github.com/Automattic/woocommerce-services/commit/004a72159114e55d3e328f9636c1ac28d6829481
Not sure if it will work as travis seems to indicate it needs to be a verified email address.
https://docs.travis-ci.com/user/notifications#configuring-email-notifications
We'll see. 
I'd like to see a better notification system which only notifies the commit authors in case of failures, ideally using Slack. Travis can notify a slack channel but this is something that could became full of noise and we may not pay attention to. If it pinged a author directly it'd be much more effective.
I see https://pullpanda.com/ was created just to do this but was acquired by github and now is no longer usable. Maybe there is something else we can use?

**Comment by Ferdev** [comment]
That'd be awesome. I don't know about any hooks that could send that notification via Slack, but that's definitely worth investigating. Can you create an issue with all the info you have about that? Thanks sir!

**Comment by superdav42** [comment]
> That'd be awesome. I don't know about any hooks that could send that notification via Slack, but that's definitely worth investigating. Can you create an issue with all the info you have about that? Thanks sir!

It's looking like it could turn into a hack week project and something we could implement A8C wide.
