### ISSUE TITLE
Spike: Automating test data creation for E2E tests

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1840]
Currently the e2e suite in branch `new/e2e-test-infrastructure` has a `beforeAll` step where it creates the test data the tests need by going through the WooCommerce UI. This process is very slow and prone to errors. Test data should be created and destroyed automatically in each test run, and completely independent from the test cases.

Deliverable: p2 on wcship, roundtable discussion, actionable GH issues

**Comment by Ferdev** [comment]
P2 post: https://wcship.wordpress.com/2019/11/25/generating-test-data-for-e2e-tests/

**Comment by Ferdev** [comment]
A new approach explained in this P2 post: https://wcship.wordpress.com/2020/01/27/another-take-on-generating-test-data-for-e2e-tests/

**Comment by c-shultz** [comment]
Besides the roundtable discussion, I think we can close the work on this Spike now, @Ferdev. I opened #1896 to track the implementation
