### ISSUE TITLE
Re-purchasing a shipping label is no longer available

### ISSUE THREAD

**Issue by treibalen** [Automattic/woocommerce-services#1843]
As confirmed in Slack convo p1574089383152300-slack-C0D9EC4H0, re-purchasing shipping labels is no longer available.

We have a customer who reported that they need to re-purchase their labels all the time in case the originally shipped order gets lost, damaged or dies (they sell bees).

Creating this report to make sure other complaints are logged too.

Reported in:
2510063-zen
2513759-zen
2516317-zen
2491642-zen
15197880-hc
12969458-hc

**Comment by bernattorras** [comment]
Another customer reported this issue here 2513759-zen

**Comment by thuautp** [comment]
Also reported in 2516317-zd

**Comment by corsonr** [comment]
reported in 2491642-zd as well

**Comment by aleftick** [comment]
Thanks for sharing this use case. We'll reintroduce the ability for users to print another label after a first one is printed. That function will be displayed in the top shipping bar beside the `Track Package` button. We're actively working on it.

**Comment by orhanfernandes** [comment]
reported also in 12969458-hc

**Comment by jobthomas** [comment]
@thuautp @corsonr  I updated your shortform from `-zd` to `-zen` as per this FG: https://fieldguide.automattic.com/public-github-repo-shorthand/

**Comment by jobthomas** [comment]
@orhanfernandes I added your HC to the original post (please do so from now on - that makes it easier to track)

**Comment by anant1811** [comment]
Also reported here: https://wordpress.org/support/topic/cant-print-multiple-labels-per-order/

**Comment by anant1811** [comment]
Also reported in 2531183-zen.

**Comment by jobthomas** [comment]
@aleftick do we have an ETA for this?

**Comment by laurendavissmith** [comment]
Its in final testing and will be released Monday, Nov 9th

**Comment by EtiennePoolman** [comment]
> Its in final testing and will be released Monday, Nov 9th

@laurendavissmith  I presume that will be December 9, correct ;-)

**Comment by laurendavissmith** [comment]
@EtiennePoolman lol yep fixed, thanks!

**Comment by c-shultz** [comment]
This fix is now released in 1.22.2.

**Comment by EtiennePoolman** [comment]
Followed-up with all users in this report
