### ISSUE TITLE
WooCommerce Admin plugin causing high CPU/Memory spikes & 500 server error

### ISSUE THREAD

**Issue by GWS13** [Automattic/woocommerce-services#1848]
I was in a chat with WooCommerce last night about a problem with CPU and memory spikes. Similar issue as described by @vitorbtorres in another GitHub thread: https://github.com/woocommerce/woocommerce-admin/issues/2908 The WooCommerce agent I chatted with today suggested I report our issue to you.

Since upgrading our website to WordPress 5.3 and WooCommerce to 3.8.1 4 days ago, we had been getting 500 Internal Server errors and then the website would go down.

We put the site in maintenance mode, disabled all plugins except for WooCommerce and then enabled the other plugins one at a time while watching the server stats. We found the CPU/memory spikes occurred when navigating to the WooCommerce Admin plugin dashboard itself. Anywhere else in WooCommerce (Orders, Settings, Status, etc) was fine. Once we deactivated the WooCommerce Admin plugin the server stats stay normal. We decided to remove the plugin altogether to avoid future problems. 

I would be interested in hearing if this is a known problem and/or if we can try using the plugin again the future.

**Comment by c-shultz** [comment]
Closing since this is not the repo for [WooCommerce Admin](https://github.com/woocommerce/woocommerce-admin)
