### ISSUE TITLE
CSS: .dialog__backdrop z-index value issue

### ISSUE THREAD

**Issue by bradlypressable** [Automattic/woocommerce-services#1850]
Issue:

The <code>z-index</code> value for <code>.dialog__backdrop</code> in <code>woocommerce-services.css</code> is not high enough to cover the WooCommerce order status and customer fields:

<img width="1006" alt="Screenshot 2019-12-09 14 45 27" src="https://user-images.githubusercontent.com/58047707/70459563-2dda0900-1a93-11ea-962e-f65a241ff294.png">

Solution:

We increased the <code>z-index</code> value from <code>100200</code> to <code>10020000</code> in order to get <code>.dialog__backdrop</code> to cover the order status and customer fields.

**Comment by c-shultz** [comment]
I can no longer reproduce this issue.
