### ISSUE TITLE
Incorrect reported size for Medium USPS Priority Mail flat rate box

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1860]
Customer printed a couple of labels for two medium size USPS Priority Mail flat rate boxes, which size were 11 x 8.5 x 5.5.

They were later charged additionally due to "incorrect packaging", as the reported dimensions were not the ones in the box, but a bit bigger:

```Adjustment for Order #51156
Tracking #: 9405536897846151260131
Reported as 10.60 lb, 11.0 x 8.5 x 5.5 in.; verified as 8.17 lb, 11.3 x 8.8 x 6.0 in.; incorrect packaging

Adjustment for Order #51156
Tracking #: 9405536897846151260124
Reported as 7.20 lb, 11.0 x 8.5 x 5.5 in.;

verified as 5.53 lb, 11.3 x 8.8 x 6.0 in.; incorrect packaging
```

I haven't been able to reproduce it in my development environment, but we should check in their account if WC Services is creating the correct label.

**Comment by c-shultz** [comment]
Closing this to wait to see if we get additional reports so we can try to reproduce it better.
