### ISSUE TITLE
Unnecessary character escaping in shipping label origin

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-services#1862]
The apostrophe character (`'`) is being entity-encoded as `&#039;` in the top line ("name") of the shipping label's return address.

I believe this name is originally grabbed from the WP user name [[code](https://github.com/Automattic/woocommerce-services/blob/7be77b3200dba5093c12b2cf69a2d7abfc34bbd5/classes/class-wc-connect-service-settings-store.php#L116
)] but is getting escaped somewhere along the way (plugin, server, or label provider API).

Props @dphyled for raising the issue.

**Comment by dphyled** [comment]
Thank you very much for opening this @dechov !

Tentatively marking as `High`, since it makes all business owner's shipping labels sent to customers look a bit odd/sketchy -- i.e. `KEL&#039;S GUITARS`

**Comment by c-shultz** [comment]
This is likely closely related to https://github.com/Automattic/woocommerce-services/issues/1625
