### ISSUE TITLE
Unable to submit refund for label purchase

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-services#1866]
**Affected Tickets**
2629148-zen

**Describe the bug**
Multiple purchases were made during outage, and one does not have a tracking number or proper link to Payments Admin in the customer RC, so it is not possible to refund properly. Relevant data relating to RC and receipt number are in ticket and were not included here due to this is a public repo. 

**Expected behavior**
To be able to use the _Refund via provider_ button under the transaction in the RC.

**Comment by amandasjackson** [comment]
Another issue to report here 2629431-zen

It's for order 19588

![Screenshot](https://d.pr/i/lA2qcO+)
Screenshot direct link: https://d.pr/i/lA2qcO

**Comment by dougaitken** [comment]
@aleftick @laurendavissmith are you able to have someone look at this one, please? 

Looking at the Payments Admin link that Amanda noted in 2629148-zen, it shows refunded but that refund isn't showing on the User RC side.

Thanks!

**Comment by laurendavissmith** [comment]
added to our sprint

**Comment by harriswong** [comment]
Hi @jessepearson , I am going to resolve this since the user has been refunded for the labels that weren't used. 

> To be able to use the Refund via provider button under the transaction in the RC.
Since this is outside the scope of WCS, I am going to create a separate issue in that repository instead.
