### ISSUE TITLE
Can activate WooCommerce Services plugin when WooCommerce plugin is deactivated

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-services#1873]
**Describe the problem**
When installing WooCommerce Services on my test site, I was able to activate the plugin while WooCommerce was deactivated. 

<img width="1449" alt="Screen Shot 2019-12-18 at 12 05 23 PM" src="https://user-images.githubusercontent.com/5121465/72750627-fd51b880-3b82-11ea-83a8-5a282d9d5ef0.png">

This is confusing since the WCShip plugin is dependent on the WooCommerce plugin, and merchants may expect to see functionality that's not there. In the screenshot above it shows Jetpack as activated, but the WCShip plugin will also activate when Jetpack is deactivated.

<img width="1552" alt="Screen Shot 2019-12-18 at 11 34 49 AM" src="https://user-images.githubusercontent.com/5121465/72750654-10fd1f00-3b83-11ea-9d51-3f55cae0cebf.png">

After trying with a few more extensions, I found that ones that are dependent on WooCommerce being activated show this error screen. For example, here's what happens when I try to activate the Mailchimp plugin with WooCommerce deactivated. The "WooCommerce" link goes to the download page on the .org site.

**Describe the solution you'd like**
We should show the same error message above when merchants try to activate the WCShip plugin if WooCommerce isn't activated.

Side note: This error message isn't ideal considering there's no back button or clear path forward, but for a quick win we could use it for now.

For a bit more context, here's a [thread](https://a8c.slack.com/archives/CKE7FGHB4/p1576692201006700) in Slack where this was discussed.

**Comment by superdav42** [comment]
The pattern we have been using is to add an admin notice when the required plugins are not activated or installed like:
![Screenshot from 2020-01-20 16-46-58](https://user-images.githubusercontent.com/1534605/72764247-7f9ea480-3ba4-11ea-93d1-f8f609ff6b2a.png)
We'll do something similar for WooCommerce Services.
