### ISSUE TITLE
Documentation updates are needed for 1.22.3 changes

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1878]
@aleftick mentioned that the WCS docs need to be updated based on the changes in 1.22.3:

* Add   - Preselect rate when there is only one rate available for given shipping configuration.
* Add   - Paper size selection into purchase modal sidebar and reprint modal which was previously removed.
* Add   - Show notice when WooCommerce is not installed or activated.
* Fix   - Use correct URL for variation products in Packages section.

Slack thread: https://a8c.slack.com/archives/CKNC7KACA/p1579720756015500

At a minimum, some screenshot updates are needed on this page now that the shipping label modal includes the paper size selection (but there may be others):
https://docs.woocommerce.com/document/woocommerce-services

**Comment by aleftick** [comment]
I believe that only `Add - Paper size selection into purchase modal sidebar and reprint modal which was previously removed.` would affect the steps.

**Comment by superdav42** [comment]
Updated two screenshots which included the "Buy shipping label" button
