### ISSUE TITLE
Typo in add credit card link

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1880]
Should probably read `Choose a credit card to add to your account`:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/6209518/73032011-9e927600-3df2-11ea-8bae-3b42fe84de6a.png">

**Comment by laurendavissmith** [comment]
That wording in general is odd, I think `Add` would be more appropriate here, might be worth having @elizaan36 take a look

**Comment by elizaan36** [comment]
oh yeah, I agree! `Choose a credit card to **add** to your account` makes much more sense.

Or if there aren't any cards to choose from yet, it could say just `To print this shipping label, add a credit card to your account`.
