### ISSUE TITLE
Correct messaging when single or plural

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1883]
Plural is used when there is only one package:
![image](https://user-images.githubusercontent.com/6209518/73216900-c5f78480-410b-11ea-999f-bb2608c4f38d.png)

And plural on a single label:

![image](https://user-images.githubusercontent.com/6209518/73216982-eb848e00-410b-11ea-97fb-68ca1bcfb6c2.png)

**Comment by harriswong** [comment]
👀
