### ISSUE TITLE
Spike: Determine how/where to implement static service features (insurance/pickup/signature/tracking)

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1884]
We have several upcoming enhancement issues for displaying differentiating information about the different services types (e.g. how much insurance USPS includes or if free pick-up is available). As far as I've seen, this info is not available from EasyPost so we'll need to come up with a plan to hardcode the values in some way if they're really not available from the API.

**The issues that depend on this Spike:**
Tracking: https://github.com/Automattic/woocommerce-services/issues/1865
Insurance: https://github.com/Automattic/woocommerce-services/issues/1818
Free signature: https://github.com/Automattic/woocommerce-services/issues/1819
Free pickup: https://github.com/Automattic/woocommerce-services/issues/1885

**The goal of this Spike is to:**
- Find reliable docs as sources for all the data needed for the above issues
- Make a plan for how we should store/serve the data (store it on the Connect Server as a CSV and send it to WCS with the other rates?). Our approach should not be overly USPS-specific if possible so we can provide similar data for other carrier rates in the future.
- P2 findings

**Comment by superdav42** [comment]
Some notes on each of these issues.

We are getting the price for signature required from easypost but it does not handle the cases when adding the signature required requirement is a free option. Which appears to only be true for Priority Mail Express. See https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/lib/special-rates/index.js#L40
Currently we are hard coding this in the WCS client which is not ideal. Best to keep these things on the server where we have more control.

For the other issues we need to know which services offer a tracking number. 

Which services offer insurance and how much.

Which services offer free pickup. Or maybe how much the pickup would be. Perhaps we should hold off on displaying this until we add the schedule pickup feature?

Putting this info in a CSV or json file that is included in the connect server code is probably the best option. We could put it in a db and create a webinterface to update it but as often as these information will change I do not think that would be necessary.

**Comment by superdav42** [comment]
Free Package Pickup Information: https://usps.force.com/faq/s/article/What-is-Package-Pickup#eligibility
Insurance Info https://pe.usps.com/text/dmm300/503.htm#ep1063624 and https://support.shippingeasy.com/hc/en-us/articles/203082859-USPS-Insurance-Coverage-Included-with-Service-Overview
Tracking and other info https://www.usps.com/ship/mail-shipping-services.htm#quickcompare

**Comment by superdav42** [comment]
P2 done https://wcship.wordpress.com/2020/01/31/spike-determine-how-where-to-implement-static-service-features/
