### ISSUE TITLE
Label creation E2E test not passing

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1897]
The create shipping label E2E test does not work. The test is implemented here: https://github.com/Automattic/woocommerce-services/blob/develop/tests/e2e-tests/specs/admin/create-shipping-label.test.js

As part of this issue, we should also make sure our Travis setup will fail if this test fails.

Note: One known issue is that not all required endpoints are mocked. @budzanowski suggested as a first step to make API mock class cause an immediate failure if an endpoint is missing

**Comment by c-shultz** [comment]
The setup phase will be much better and faster after #1896 closes, so I'm marking this as blocked until then.

**Comment by Ferdev** [comment]
Closing this as #1895 fixes this as well.
