### ISSUE TITLE
Label purchase status polling happens too early.

### ISSUE THREAD

**Issue by budzanowski** [Automattic/woocommerce-services#1900]
When we start the label purchase process the WCS plugin asks the connect server to purchase the label. Then the WCS asks the server for the purchase status. The status asking is a process repeated every second until the server tells us that the label was purchased or there was an error. This is a fairly simple process. It has one simple flaw in my opinion. When we inspect the endpoints delay we can see that the majority ( or basically always ) the first time WCS asks about the purchase status it will receive a status that the purchase is ongoing. Billing daddy and EasyPost is not fast enough. In my opinion, we should delay the first status asks API call. We should save this way a lot of unnecessary calls. 

Alternatively, we can consider building a more sophisticated system using webhooks. Connect server would notify WCS when purchase process has ended. Polling the connect server would not be necessary. WCS frontend could ask WCS backend for the status.

**Comment by c-shultz** [comment]
I want to try addressing this in the next sprint to help reduce server load however we can. I would suggest we keep it simple for now and add a delay before the first check.

**Comment by harriswong** [comment]
Added https://github.com/Automattic/woocommerce-services/issues/1928 for follow-up tests

**Comment by harriswong** [comment]
Blocked until https://github.com/Automattic/woocommerce-services/pull/1895 is merged.
