### ISSUE TITLE
Create E2E test for the settings screen

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#1916]
We need to create a test for the settings screen in `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`

**Comment by harriswong** [comment]
## Test can include

### Settings
- Toggling, save change
- Changing paper size, save change
- Email Receipts, save changes

### Adding/removing/choosing card
* _need to figure out how to mock the API for cards_
- Choose a different card 
- Add a new card 
- Remove card when there is 1 card
- Remove card when there is 2+ cards
- 0 card

### Packaging
- Add new package
- Edit package
- Init view when there is no package
- Delete package
