### ISSUE TITLE
Add 180 day warning message for labels

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1941]
We should warn users that labels will only be available for 180 days. Something like:
>“Label images older than 180 days are deleted by our technology partners for general security and data privacy concerns”.

See: https://wcship.wordpress.com/2020/03/02/180-day-limit-for-label-images-starting-next-month/

**Comment by superdav42** [comment]
Is this a warning we need to show before customers purchase a label?
It seems a little unnecessary and I think we want to keep the label purchase flow as clean as possible. I suggest we put it on the label reprint dialog:
![image](https://user-images.githubusercontent.com/1534605/77345213-ec93ff00-6cf9-11ea-88eb-b9e4370f4ab8.png)
@elizaan36 @aurélien for guidance

**Comment by elizaan36** [comment]
Looks like from the P2 we're putting this note in the error message, but lemme know if you still want me to take a look at anything.

**Comment by superdav42** [comment]
Actually when I updated the expiration date to be 180 days from the label created time there is already code in the WCS plugin which [hides the reprint label](https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js#L57) option from the dropdown. 

So with the expiration date set correctly no errors will show at all, the reprint option will just disappear which may cause some some confusion. I think we may want to show the reprint option with a disabled or grayed out state that will display some kind of explanation when users hover or click it. What are your thoughts?

**Comment by elizaan36** [comment]
oh good call. As you suggested let's display a tooltip on the disabled button with the error message.

**Comment by superdav42** [comment]
Server changes merged but not released yet. Once they are released we need to run the query:
```SQL
update wcc_shipping_label set expiry_date = date_add(created_date, INTERVAL 180 DAY) WHERE expiry_date IS NULL LIMIT 10000;

```

**Comment by superdav42** [comment]
Here's how the tooltip will look:
![Screenshot from 2020-03-27 13-01-24](https://user-images.githubusercontent.com/1534605/77790848-267f4100-702b-11ea-81df-41adadbbd69a.png)
