### ISSUE TITLE
Shipping modal locks up if closed before purchased label is printed

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1950]
If I purchase a label, and then, instead of clicking `Print`, I try to close the modal, the whole modal locks up. I can only recover from this by refreshing the page.
![2020-03-06 15 25 04](https://user-images.githubusercontent.com/6209518/76130189-c7478700-5fbe-11ea-8cb1-080cc49d4388.gif)

**Comment by harriswong** [comment]
To reproduce, note that this `Print` button is only required for PDF support. Look for `WOOCOMMERCE_SERVICES_SHIPPING_LABEL_SHOW_PRINT_CONFIRMATION` reducer that sets `needsPrintConfirmation` to true.

**Comment by harriswong** [comment]
Confirmed when clicked dismiss, the modal slightly refreshed and then go back to "purchasing" even though it has purchased. Then it's stuck there.
