### ISSUE TITLE
GB no longer included in EU causing automated taxes to be removed

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-services#1954]
**Affected customers**
19436393-hc

**The bug**
GB was removed from [the EU countries](https://github.com/woocommerce/woocommerce/blob/4.0.0/includes/class-wc-countries.php#L356-L365) in WC 4.0, causing automated taxes to be disabled for GB, according to [this check](https://github.com/Automattic/woocommerce-services/blob/1.22.4/classes/class-wc-connect-taxjar-integration.php#L212-L223). GB is still on the TaxJar supported list here: https://developers.taxjar.com/api/reference/#countries .

Set this as Critical since it was something that was working and now is not and can cost customers a significant amount of money if taxes are not collected properly.

**Comment by superdav42** [comment]
Fix should be released soon but anyone affected by this bug can use this filter as a work-around:
```php
add_filter( 'woocommerce_european_union_countries', function( $countries ) {
	$countries[] = 'GB';
	return $countries;
});
```
