### ISSUE TITLE
PHPUnit not running in travis

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-services#1965]
For some reason our php unit tests are not runnig in travis https://github.com/Automattic/woocommerce-services/pull/1964
They appear to run but phpunit is obviously doing nothing:
```
$ phpunit
The command "phpunit" exited with 0.
```
They run fine on my local machine so we need to do some more troubleshooting

**Comment by harriswong** [comment]
Closed by https://github.com/Automattic/woocommerce-services/pull/1964
