### ISSUE TITLE
Style tweaks 

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#1971]
Couple of style tweaks

1. Remove the gap left of the green checkbox
![image](https://user-images.githubusercontent.com/572862/77688787-3da82b00-6f66-11ea-9f0f-18eb9068f53e.png)

2. The "Notify the customer with shipment details" text should be vertically middle with the checkbox button
![image](https://user-images.githubusercontent.com/572862/77688820-4c8edd80-6f66-11ea-8a17-011160534791.png)

3. The button background colour should be pink instead of blue. Pink to match the "Create shipping label" background
![image](https://user-images.githubusercontent.com/572862/77688863-5ca6bd00-6f66-11ea-8af3-c7078c8e90ab.png)

**Comment by bborman22** [comment]
I addressed number 1 in the #2130 PR and number 3 in the #2129 PR.

For number 2 though, I wasn't able to see the same vertical alignment issue. In fact in the screenshot provided it appears to be misaligned to the top, while what I see looked better, but if anything was misaligned to the bottom. 

![Notify-Customer-option](https://user-images.githubusercontent.com/68524302/89948244-c19c4000-dbf3-11ea-8f2a-677a77531dcb.png)

I had checked this on Chrome 84 and Firefox 79. I was wondering if this alignment issue is still present in the latest develop branch or if there is a particular browser or set up that got that vertical alignment?

**Comment by harriswong** [comment]
@bborman22 I just checked my local, looks like the `Notify the customer with shipment details` text is aligned vertically with the checkbox. 

@elizaan36! I think I created this issue from one of our round tables demos. For the second comment in the issue regarding vertical aligned text, I just want to double check if this looks ok now?

**Comment by elizaan36** [comment]
> regarding vertical aligned text, I just want to double check if this looks ok now?

hey, I just checked on my test site and it looks like it's been fixed. Thanks for remembering these tweaks @harriswong and @bborman22 for taking it on🎉

**Comment by bborman22** [comment]
With #2130 and #2129 merged, this issue can be closed.
