### ISSUE TITLE
Update docs for Tungsten

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1974]
Docs: https://docs.woocommerce.com/document/woocommerce-services/

New process for updating docs: https://fieldguide.automattic.com/woocommerce-woothemes-documentation/using-publishpress-on-woocommerce-docs/

We should update this screenshot since the service info has been changed:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/6209518/77698137-58ca6900-6f6d-11ea-8dd0-30a02ce1a3ab.png">

These screenshots are outdated as well:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/6209518/77698239-857e8080-6f6d-11ea-854c-353b3dcf155f.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/6209518/77698266-90d1ac00-6f6d-11ea-840f-95b998fa7d19.png">

**Comment by superdav42** [comment]
Updated screenshots and it's pending review.

**Comment by superdav42** [comment]
Updates live

**Comment by c-shultz** [comment]
Awesome! Thanks for doing the doc updates and coming back to close this out!
