### ISSUE TITLE
First label created for an item shows "Invalid date"

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1984]
If I create and print a label on an order that doesn't have any labels, I see the following invalid label information appear:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/6209518/78155523-6d39b600-73f2-11ea-99ed-9fe161eed31e.png">

This does not happen for subsequent labels created for the order and refreshing the order page clears this up:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/6209518/78155763-ba1d8c80-73f2-11ea-926f-2c182aced01f.png">

**Comment by harriswong** [comment]
👀
