### ISSUE TITLE
Incorrect tax rate for zip code+4 in West Virginia

### ISSUE THREAD

**Issue by jrick1229** [Automattic/woocommerce-services#2001]
### Issue

Forum: https://wordpress.org/support/topic/incorrect-tax-for-zip/

> zip code 26452-8086 should be 6% not 7% as calculated in the woo tax, it is outside the city and does not get the extra 1%. could you fix this

When calculating tax for `26452`, it seems there's an added **1%** within the city limits. The `8086` +4 puts this particular zip code outside city limits, so the rate should conform to the state's standards.

**Comment by asuh** [comment]
Sounds like this is similar to another issue I opened https://github.com/Automattic/woocommerce-services/issues/1934 with Colorado state tax.

**Comment by superdav42** [comment]
It appears the zipcode 26452-8086 is at least partially in the city limits of Weston. Using the zipcode 26452-8529 WCS does not apply the city tax. For the most accurate results use the full street address. You can use the [taxjar tool](https://www.taxjar.com/sales-tax-calculator/) to easy test many different address. If you still believe the rates to be in error please provide the seller address, buyers address and expected rates.

**Comment by c-shultz** [comment]
Based on @superdav42's research, I am closing this. Feel free to reopen if there appears to be an issue still.
