### ISSUE TITLE
When automated tax calculation is enabled there is no way to disable tax calculation in general

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#2006]
**Describe the bug**

When automated tax calculation is enabled there is no way to disable tax calculation in general. 

**To Reproduce**
1. Enable WooCommerce Services plugin (that provides automated tax calculation)
2. Enable automated tax calculation:

![tax1](https://user-images.githubusercontent.com/19143190/79795294-b01be900-8321-11ea-8afe-6038416d242b.jpg)

3. Navigate to General settings and try to disable tax calculation. Save the changes and note that they did not take effect. The tax calculation box is still selected - see gif below:

http://g.recordit.co/Pbd0jRF6Lt.gif

I checked back in WC 3.8 and it works the same there so it is not new. 

**Screenshots**

See above. 

**Expected behavior**

I expect to be able to disable tax calculation in general settings even if the automated tax calculation is enabled. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
It looks like the behavior is intended which IMO shouldn't:

https://github.com/Automattic/woocommerce-services/blob/57789a195603ff9b7a6ad9c90d2250c122af04d5/classes/class-wc-connect-taxjar-integration.php#L19

I think we should allow users to disable tax calculation in general if the automated tax calculation is enabled. But I don't know why historically it was not the case.

**Comment by AashikP** [comment]
Another report in 4425043-zen

**Comment by JS-fashion** [comment]
Thank you very much for your maximum help, after your intervention everything was working as it should, now I notice that the shipping calculation and delivery date was disabled again after I installed peyement woocommerce.
