### ISSUE TITLE
Make it clear automated taxes only work in one nexus

### ISSUE THREAD

**Issue by superdav42** [Automattic/woocommerce-services#2019]
We need to add a bit of text to the automated taxes setting like so
![Screen Shot 2020-04-28 at 11 24 59](https://user-images.githubusercontent.com/1534605/80498691-47d49500-8929-11ea-89c8-85ba778ac01c.png)
This will help with merchant confusion as to why out of state taxes are always 0.

**Comment by elizaan36** [comment]
Could we make use of the tooltip to have less noise on the screen? 
<img width="903" alt="Screen Shot 2020-04-28 at 5 56 59 PM" src="https://user-images.githubusercontent.com/5121465/80545812-d96bf300-8979-11ea-8c03-a328d8cf3edf.png">

Here's potential copy for the tooltip:
Your tax rates and settings will be automatically configured for New York. [Learn more about setting up tax rates for additional nexuses](https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-12)

Then the copy below the dropdown can be just "Powered by WooCommerce Services".

**Comment by c-shultz** [comment]
Looks good to me! I'm moving this into this week's sprint since it looks like it could be a quick win to reduce some support tickets around this issue.

**Comment by c-shultz** [comment]
Does this have a reviewer @superdav42? I just wanted to make sure this was in the right sprint queue

**Comment by superdav42** [comment]
No, I accidentally moved it to under review and have been wondering why no one had reviewed it yet. 
It's ready to review.
