### ISSUE TITLE
Incorrectly taxed on shipping

### ISSUE THREAD

**Issue by klishb** [Automattic/woocommerce-services#2020]
I have a very long ticket with support on this (2865426).  They recommended I post here.

The Taxjar API returns:

“freight_taxable”: false,

This response is not used correctly by WooCommerce Services.  For example, in New York state shipping should only be taxed when taxable items are in the cart.  Even with no taxable items in the cart shipping is getting taxed.

**Comment by klishb** [comment]
Since posting this I have learned more about the nature of this problem.  I believe the issue lies in the caching that WooCommerce Services does with the Taxjar responses.  For the reasons stated above this response cannot be cached. Whether or not the shipping should be taxed needs to be determined at the time of sale since it's based on whether or not there are items in the cart that are taxable.  That's just the rule in NY - not sure about other states.  WooCommerce Services needs to leave those calculations up to the TaxJar API since they know all the state rules.  Caching may be reasonable option for some states, but not all.

If you delete the tax tables that got cached then WooCommerce Services uses the API response on the next transaction which will be the correct shipping tax calculation for that particular sale.  Future sales may or may not be correct based on what response was cached and written to the tax tables for the shipping tax option.

**Comment by superdav42** [comment]
@klishb Can you provide more specific details on how to reproduce the problem?

We use the line items in the cart as part of the cache key so if a customer adds/removes an item it will perform a new request for tax rates.

**Comment by klishb** [comment]
@superdav42 very interesting to hear that.  I suspected that may have been the cause, but maybe not.  It's been a long time since I looked at this problem, but I just confirmed it's still a bug.  To reproduce this you could:

1. Create the following "additional tax classes" under WooCommerce tax options
Candy - 40010
Food - 40030
2. Create a product in WooCommerce and set it to taxable with a tax class of "Candy - 40010"
3. Create a product in WooCommerce and set it to taxable with a tax class of "Food - 40030"
3. Set your store's address to NY
4. Set your customer address to NY
5. Put your candy product in the cart.  Both the candy and the shipping should be taxed in the cart.
6. See API request and response to TaxJar API in the taxes log.  Notice TaxJar API responded saying to tax both product and shipping.  This response was used in the cart calculation.
8. Clear the cart
9. Put a food product in your cart.  Your food will not be taxed, but shipping will (this is the problem).
10. See API request and response to TaxJar API in the taxes log.  Notice TaxJar API responded saying "taxable_amount": 0.0 for both product and shipping.  This response was not used in the cart calculation for some reason.

At one point someone from your support team told me the tax classes were not used, but TaxJar support disagrees and you can see it being sent in the API requests.  TaxJar support also specifically told me to set all items tax status to "taxable" and use the tax classes to let the API make the proper determination since that gets submitted in the API request.  Setting this up was not well documented by the WooCommerce Shipping And Tax docs at the time and I just checked to confirm it still doesn't mention using tax classes at all.  That's the whole reason I contacted TaxJar support to get more information on how to set it up properly.

**Comment by klishb** [comment]
Also, you will notice that when you put candy in the cart the WooCommerce tax table populated both the Candy and the Standard tax table with your zip code's rates and the option is checked to tax shipping.  If you delete those rows in the tax tables and then go back to refresh the cart with food in it you'll see the API response gets used properly and the shipping does not get taxed.  This is why I think it's a caching problem.  You'll also notice at this point that no tax tables are showing tax information for your zip code.  Not sure why that didn't get cached...
