### ISSUE TITLE
Taxes for specific products

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-services#2024]
Hi there, I've got a question based on 2951723-zen and our docs aren't clear on this. 

* Question: How can I set up different taxes per product category?
* They haven't clarified where they are yet, but I did find this example of NY taxes: https://blog.taxjar.com/the-new-york-clothing-sales-tax-exemption-demystified/

>     New York state doesn’t require state sales tax (4%) on clothing items sold for under $110
>     Some counties also exempt clothing under $110 from local tax rates
>     Some counties do NOT exempt clothing under $110 from local tax rates. In this scenarios, you may find yourself not charging New York’s 4% sales tax rate, but charging local rates
>     In a few counties, local rates also include New York’s 0.375% Metro Commuter Transportation District (MCTD) tax
>     Clothing sold for $110 or over is always fully taxable in New York
>     New York is a destination-based sales tax state, so if you sell online you’d always charge the sales tax rate at your buyer’s location
>     You can read more about the New York clothing sales tax exemption in this publication.
>     If you run a shopping cart or marketplace, the TaxJar API can take care of this complexity for you.

So it seems that the TJ API allows for this case, but I don't really see a way to add this specific tax code `20010` to the products: https://developers.taxjar.com/api/guides/#product-exemptions

Is this a feature request? Something that won't get attention? Or something that is possible but not available in our docs?

**Comment by GeoJunkie** [comment]
After a discussion with @harriswong in p1589989244110000-slack-CTYKKGC1Y , we determined that these product-based tax rates will work with WCS by passing the tax code to TJ, so if a tax class of `Clothing-20010` is created, that will be passed along.

The user in 2951723-zen is still seeing taxes charged, so we are troubleshooting that.

**Comment by GeoJunkie** [comment]
We were able to get the taxes working properly. The tax class must not have spaces before and after the dash, so `Clothing–20010` works but `Clothing – 20010` doesn't. I'll open a new issue for that, since its functionality should parallel TJ (which has the spaces)

**Comment by jobthomas** [comment]
@GeoJunkie would it be possible to add these instructions to the automated taxes doc?
