### ISSUE TITLE
Warning: getenv() expects exactly 1 parameter, 2 given

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2025]
`Warning: getenv() expects exactly 1 parameter, 2 given in woocommerce-services/woocommerce-services.php on line 55`

This is caused by https://github.com/Automattic/woocommerce-services/blob/develop/woocommerce-services.php#L55 and the second parameter is only available to PHP `5.5.38, 5.6.24, 7.0.9`+. 

Since we support PHP 5.3 (https://github.com/Automattic/woocommerce-services/blob/develop/readme.txt#L5), we should handle without the second parameter.

Although we support PHP 5.3 (https://github.com/Automattic/woocommerce-services/blob/develop/readme.txt#L5), WooCommerce itself is going to be bumping PHP version to 7.0+ (https://github.com/woocommerce/woocommerce/blob/master/readme.txt#L6). Should we also bump ours?

**Comment by c-shultz** [comment]
Let's go ahead and fix this so we don't see the warning in 5.3
