### ISSUE TITLE
UPS logo for UPS rate responses

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2029]
After https://github.com/Automattic/woocommerce-connect-server/issues/1370 is finished, enabled sites will receive UPS carrier rates. We'll need to display the rates with the UPS logo in the rates list:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/6209518/82267120-59a1ca80-9920-11ea-9614-d4577ce4f5d5.png">

https://wcship.wordpress.com/2020/05/15/adding-a-carrier-account-in-wcs-i4-design/

**Comment by c-shultz** [comment]
The exact label image is currently being discussed via P2 above

**Comment by superdav42** [comment]
Work on this has started at https://github.com/Automattic/woocommerce-services/compare/fix/issue-2029 but we're holding off to make sure we have permission to use the USPS logo

**Comment by c-shultz** [comment]
@elizaan36 to provide link for images

**Comment by c-shultz** [comment]
Logo images: [UPS_USPS logos.zip](https://github.com/Automattic/woocommerce-services/files/4929328/UPS_USPS.logos.zip)
