### ISSUE TITLE
Flat Rate Envelope packs items that shouldn't fit in an envelope

### ISSUE THREAD

**Issue by fhaps** [Automattic/woocommerce-services#2030]
Site is grandfathered into the live rates feature. When they enable `Priority Mail - Flat Rate Envelope` along with its corresponding package, items that shouldn't fit in this package are added to it.

These are the sizes of the package when adding it in the backend:

![](https://d.pr/i/BRlara+)
Image Link: https://d.pr/i/BRlara

These are the dimensions of the product that should NOT fit into an envelope:

![](https://d.pr/i/uqzfJv+)
Image Link: https://d.pr/i/uqzfJv

However, on the front-end, the item is packed into the envelope:

![](https://d.pr/i/KfjmQ0+)
Image Link: https://d.pr/i/KfjmQ0

The plugin seems to be returning several envelope packages that have different dimensions than the one I added. The height of these "envelopes" seems to be wrong, as they are larger than 0.5 – which is the standard height used for envelope packages.

Reported in 2986256-zen.

**Comment by brezocordero** [comment]
@fhaps 
Thanks for the report.
I have opened a new issue on the server to update the preset flat envelopes.

**Comment by harriswong** [comment]
Hi @fhaps, this issues should be fixed now. Please reopen if this continues to be an issue.
