### ISSUE TITLE
Cannot refund orders

### ISSUE THREAD

**Issue by FreshPhil** [Automattic/woocommerce-services#2044]
**Describe the problem**
On WCS version `1.23.1`, we have had multiple cases where administrators are not able to refund orders. Instead, the page will endlessly load.

In these cases, downgrading to `1.23.0` resolved the problem, so this may be linked to the changes made for #2039 as we've noticed this error in the browser console:

![](https://d.pr/i/OAv0cv+)
Image Link: https://d.pr/i/OAv0cv

**Steps to replicate**
- install and activate WooCommerce Services v `1.23.1`
- place an order with automated taxes enabled
- try to refund the order while WooCommerce Services is still active
- Note the order will not refund

Next
- Deactivate and remove WooCommerce Services
- Reinstall version `1.23.0`
- Try to refund and note that it goes through normally

**Comment by FreshPhil** [comment]
The current workaround is for users to remove the WCS plugin and then reinstall using the previous version. Since this is an open repo, they would have access to doing that.

**Comment by c-shultz** [comment]
Fixed in 1.23.2.
