### ISSUE TITLE
Hide Label Printing if Virtual Product is Purchased

### ISSUE THREAD

**Issue by DustinHartzler** [Automattic/woocommerce-services#2054]
Managing my wife's site (where she only sells digital products:

![Screen Shot 2020-06-17 at 12 47 05 PM](https://user-images.githubusercontent.com/2293077/84926358-3f7f1780-b099-11ea-86ab-5cb5143c357e.png)

It doesn't make sense to have the Shipping Label area, when there's nothing to fulfill for a digital product.

**Comment by bborman22** [comment]
I was unable to reproduce this issue with a Virtual product. I also confirmed that the check for the Create Shipping Label option is only displaying when the product is not marked virtual. One thing I did find that may be an explanation here is it will still display the Create Shipping Label option if the product is marked as Downloadable, but is not marked as Virtual. If you confirmed that the product is marked virtual and is still displaying the Shipping Label prompt, would you be able to provide a screenshot of the Product settings and we can see if there is another issue that is causing that.

As for why the Downloadable option still prompts for a Shipping Label, this documentation goes in to that a little further: https://docs.woocommerce.com/document/digital-downloadable-product-handling/#section-6

**Comment by DustinHartzler** [comment]
Sorry about that! Looking at the product settings, the one variation displayed in the order is the one that didn't have the *Virtual* box checked.
