### ISSUE TITLE
Get the correct link for the "Learn more about adding carrier accounts" help link in carrier settings form.

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#2065]
The current link it's just a test.

![image](https://uc9c0fdf0fd0593a149dd749d034.previews.dropboxusercontent.com/p/thumb/AA1DMsVz7opNRUylZeWr0LSadT1iNvWq_pIAo1gDIZ09o-877R4gIHGTKtM5GvGgJEk2u4P7LPZRDErt-P7_Si7iElBPlQzc0uYpXXt6XrpEQIlerlVanXEC3nwx5LQ04BQ6KQDQS-Bif-9INER2vTS1kJ3OxY1BUJDdLaLhhKTpFyxk_3BYw0QRe0XtJqHJkaws5-M2qX7ZY3N-i1xdEUn98CXUAi_Yj0s-56Av8HZpkZ9jdzJGZMOUP5dUQnqB3V6fEz4d-AKUWKNc4fbhgnFh8DmJhDMAaSNiP4cDfPs95_PkoM5Q2Wh0TR41p5ukhO_Q94I8XY_HRUXXR0z1kTMvcfquvM4KYkYJcV2BqpVsdxetUI2bequ_6CnpP8XT8URo1t3Jt-CWnxXcrv0DFZA8/p.png?fv_content=true&size_mode=5)

**Comment by c-shultz** [comment]
@elizaan36, where was this link going to go? If I remember right, we were going to create a doc page for this?

**Comment by elizaan36** [comment]
Yeah, I'll work with the docs guild to try and get [this doc](https://docs.google.com/document/d/1rULx2FbJ4vo1-dd_GI21VvF1yOF4Mln8Eq1c7vnrqcs/edit) published before rollout. 

I may need to go in at the last minute and update the link.

**Comment by c-shultz** [comment]
How about we just remove the copy and link for now and then add it again once the doc is ready?

**Comment by elizaan36** [comment]
> How about we just remove the copy and link for now and then add it again once the doc is ready?

Sounds like a good plan

**Comment by Ferdev** [comment]
Just removed the link temporally in this commit: https://github.com/Automattic/woocommerce-services/pull/2049/commits/edf2e73c6792df6d54569dde33f67027c804032c

**Comment by c-shultz** [comment]
I'm marking this as blocked until we have a doc to link to. This will be pretty minor tweak, so we don't need it ready to begin testing, but we'll want to have it before the targeted July 29th release date.

**Comment by c-shultz** [comment]
The link will be `https://docs.woocommerce.com/document/using-your-own-ups-account-in-woocommerce-shipping`. Unblocking
