### ISSUE TITLE
JS console error regarding taxjar js

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2072]
On the latest `develop`, I see an error message in the console on the order page:

<img width="2120" alt="image" src="https://user-images.githubusercontent.com/6209518/87829872-b80dfb00-c834-11ea-8072-ee8caea8eb1a.png">

**Comment by harriswong** [comment]
In `develop`, I think this revert is now missing https://github.com/Automattic/woocommerce-services/pull/2047.

**Comment by harriswong** [comment]
I compared `develop` to the changes in https://github.com/Automattic/woocommerce-services/pull/2047/files, and manually updated codes to match https://github.com/Automattic/woocommerce-services/pull/2047/files.
