### ISSUE TITLE
`en.js` module error

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2073]
On the latest `develop`, whenever I load any page where WCS assets load, I see this in the console (testing on Firefox):
<img width="2544" alt="image" src="https://user-images.githubusercontent.com/6209518/87829900-c52aea00-c834-11ea-9221-0c090d684cd8.png">

**Comment by harriswong** [comment]
Related to https://github.com/Automattic/woocommerce-services/pull/2057/files. 
```
	import( 'moment/locale/' + localeFileSlug + '.js' ).catch( () => {
		import( 'moment/locale/' + localeSlugParts[0] + '.js' );
	});
```
The above code throws an error on not finding `moment/locale/en.js`
