### ISSUE TITLE
UPS logo ratio on the Carrier Account setting page

### ISSUE THREAD

**Issue by aleftick** [Automattic/woocommerce-services#2087]
The UPS logo in the _Carrier Account_ settings is compressed. As we go public, we should fix it as we will need to comply with their brand guidelines and approval. 

![image](https://user-images.githubusercontent.com/2545592/88240362-de78cf80-cc54-11ea-99ab-60ffa8fc3e01.png)

cc: @elizaan36

**Comment by aleftick** [comment]
The same is true for when we present the rates when a merchant buys a label.

**Comment by elizaan36** [comment]
Ah yes good catch, I noticed this in testing too. We were only doing visual QA on the USPS logo, which is square so this didn't show up.😅 I've resized the image and will create a new PR for the fix today.

**Comment by elizaan36** [comment]
Hey @c-shultz, I was just looking for the images folder that gets compiled into the dist folder and can't find it. I'll attach the image here and let me know the best way to switch out the current image.

![ups_logo](https://user-images.githubusercontent.com/5121465/88809852-32664580-d17a-11ea-8575-0d2586a3e2e3.png)
[ups_logo.png.zip](https://github.com/Automattic/woocommerce-services/files/4995274/ups_logo.png.zip)
