### ISSUE TITLE
Order notes and UPS

### ISSUE THREAD

**Issue by aleftick** [Automattic/woocommerce-services#2089]
The order notes have the tracking number but don't mention it was shipped by UPS. 

<img width="303" alt="Screen Shot 2020-07-22 at 10 29 11 PM" src="https://user-images.githubusercontent.com/2545592/88247209-e9d6f580-cc6a-11ea-8f28-715a25e5eed2.png">

There is a similar issue on the email sent notifying that a note has added. Which I only start seeing 3 days ago, is this something new? This email goes out when the user sends an additional label ("Create new label"). Didn't we use to send the same email as when the order is marked completed when the first label is printed?  

cc: @elizaan36  

![screencapture-mail-google-mail-u-1-2020-07-22-22_31_00](https://user-images.githubusercontent.com/2545592/88247280-2e629100-cc6b-11ea-9b58-1503c4ddcfac.png)

**Comment by elizaan36** [comment]
To clarify, is the issue that the text "Shipped **with UPS**" is missing in the order notes and email?

> There is a similar issue on the email sent notifying that a note has added. Which I only start seeing 3 days ago, is this something new? Didn't we use to send the same email as when the order is marked completed when the first label is printed?

To clarify here, you started seeing the additional note at the top of the confirmation email very recently? I'm not sure if or when the email was changed, maybe @c-shultz and team has more context on that.
