### ISSUE TITLE
Missing the tracking link in the emails for UPS

### ISSUE THREAD

**Issue by aleftick** [Automattic/woocommerce-services#2090]
In the email sent to the customer, the tracking number doesn't link to the page for UPS but it does for USPS.

![screencapture-mail-google-mail-u-1-2020-07-22-22_47_06](https://user-images.githubusercontent.com/2545592/88247883-5e129880-cc6d-11ea-8709-0a43719d5df2.png)

The same thing happens on the email invoice.

![screencapture-mail-google-mail-u-1-2020-07-22-22_48_56](https://user-images.githubusercontent.com/2545592/88247987-a2059d80-cc6d-11ea-8c08-2de182173353.png)

**Comment by harriswong** [comment]
Nice catch @aleftick !
