### ISSUE TITLE
"Postal code" vs "ZIP code" vs "Postcode"

### ISSUE THREAD

**Issue by aleftick** [Automattic/woocommerce-services#2091]
We use different terminology in different places (not just in WCShip but also in Core). It would be good to be consistent and have a global mindset. 

I did some research and it wasn't very conclusive; I haven't found a standard approach. However, the best I have seen has been "ZIP/Postal code".

<img width="1553" alt="Screen Shot 2020-07-22 at 11 07 13 PM" src="https://user-images.githubusercontent.com/2545592/88248751-3bce4a00-cc70-11ea-872d-03fcfc41053c.png">

**Comment by c-shultz** [comment]
>However, the best I have seen has been "ZIP/Postal code".

Ok cool, let's go with that for both the strings there.
