### ISSUE TITLE
Check nonces before consuming any querystring

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#2096]
The PHP code is consuming query-string params without a previous nonce check in a couple of places at least. We should check the whole PHP code base and fix all of them.

**Comment by frosso** [comment]
@Ferdev and I worked on this together. We noticed that an app-wide nonce it already generated at https://github.com/Automattic/woocommerce-services/blob/3ae5e58a21ee792c8530d6a6acc11368fb5f8406/woocommerce-services.php#L1437 (through `wp_create_nonce( 'wp_rest' )`).
The nonce is then set in the app through https://github.com/Automattic/woocommerce-services/blob/3ae5e58a21ee792c8530d6a6acc11368fb5f8406/client/main.js#L42 and sent as a `X-WP-Nonce` header through https://github.com/Automattic/woocommerce-services/blob/3ae5e58a21ee792c8530d6a6acc11368fb5f8406/client/calypso-stubs/extensions/woocommerce/state/sites/http-request.js#L51

The `X-WP-Nonce` header is then checked by WordPress [when making AJAX requests](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/).

We checked the application to make sure the authentication was done correctly, which it is.
We checked by overwriting the generated nonce with an invalid one.

It doesn't look like we need to open new PRs as part of this ticket 🎉
