### ISSUE TITLE
Invalid Zip code causes wc-ajax=update_order_review loop

### ISSUE THREAD

**Issue by aarondemolder** [Automattic/woocommerce-services#2099]
Went through the usual steps to find this bug and disabling woocommerce-service fixes this issue.

Production site with the issue - https://ver-te.com/

Reproduce bug:

- Add product to cart
- Go to checkout page 
- Fill all fields with dummy info
- Add incorrect Zip code (doesn't happen with non US addresses)
- Untick ship to different address
- Scrolling gets stuck, wc-ajax=update_order_review loops trying to verify address, whilst also preventing text entry as it takes away focus.

Any other info needed please let me know.

**Comment by iyut** [comment]
Hi @aarondemolder , I seems cannot replicate this issue in the latest version ( 1.25.19 ). 

I have tested this in their production site ( https://ver-te.com/checkout/ ), and on my local as well using storefront, twenty twenty-one, and twenty twenty theme.

Do you have more information to replicate the issue?

**Comment by aarondemolder** [comment]
Hey @iyut 

You're right, it seems this is bug no longer occurs, fixed purposefully or not! I couldn't replicate in production either - it originally occurred over a year ago so I assume it got caught somewhere else. 

I'll close this - thanks for checking it out.
