### ISSUE TITLE
Multi-carrier label orders create an incorrect note

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2113]
A label order with both USPS and UPS results in an incorrect order note that says both have been shipped with USPS:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/6209518/88956604-73318d80-d252-11ea-81e5-544613247de8.png">

To reproduce:
Create label order with multiple items and packages:
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/6209518/88956738-a4aa5900-d252-11ea-8df8-851929caec36.png">

Choose USPS for one package:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/6209518/88956764-b3910b80-d252-11ea-84e3-1caf7484ad25.png">

And UPS for for another:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/6209518/88956791-bc81dd00-d252-11ea-87ef-93b04b0bcea6.png">

Print label with this checked:
![image](https://user-images.githubusercontent.com/6209518/88956626-7b89c880-d252-11ea-8541-d1634dd8bdb6.png)

**Comment by c-shultz** [comment]
@elizaan36, this is a bit of a corner case for a label order with multiple packages where one is USPS and one is UPS.

Since this will be a bit unusual, I'm thinking we should come back around and fix this in a patch.

What do you think on wording? Maybe --

>Your order consisting of 2 packages has been shipped. The tracking numbers are 9449000205309044702569 (USPS), 1Z1261E70332503088 (UPS).

**Comment by elizaan36** [comment]
> Your order consisting of 2 packages has been shipped. The tracking numbers are 9449000205309044702569 (USPS), 1Z1261E70332503088 (UPS).

Sounds perfect👩🏻‍🍳
