### ISSUE TITLE
Incorrect tax rate for 94563/Orinda

### ISSUE THREAD

**Issue by jrick1229** [Automattic/woocommerce-services#2115]
### Issue

Tax rate returned for zip code `94563` is calculating at **9.250%** as expected: https://d.pr/i/GLj11Q

If using the zip code `94563` along with the city, Orinda, the rate should then return **8.750%** (WCS still returns 9.750%): https://d.pr/i/7zfi0C

Reported in: https://wordpress.org/support/topic/automated-tax-california-zip-codes/ & 21464995-hc

**Comment by asuh** [comment]
I created a GH issue for Colorado https://github.com/Automattic/woocommerce-services/issues/1934 and saw your other GH issue for West Virginia https://github.com/Automattic/woocommerce-services/issues/2001.

I wonder what's going on?

**Comment by superdav42** [comment]
[Now the taxjar tool](https://www.taxjar.com/sales-tax-calculator/) is returning the same rate 9.750% regardless if the city Orinda is included or not so it makes it hard to tell for sure what was going on. I'm guessing same tax laws recently changed in the region. 

I believe there was not a problem with WCS. I can confirm that WCS send the full address of the seller and the buyer. I believe the original dependencies between the taxjar tool and the rates returned from WCS were not really a bug but simply the difference between selling items at a certain locator or selling items in an ecommerce store were some taxes to not apply. 
See [this comment](https://github.com/Automattic/woocommerce-services/issues/1934#issuecomment-697916695) for a full explanation.
