### ISSUE TITLE
Customer selected shipping does not show anymore. 

### ISSUE THREAD

**Issue by anant1811** [Automattic/woocommerce-services#2116]
Customer selected shipping method and cost used to show in previous version of the extension, it doesn't show with 1.24.0.

Example, an order with version 1.23.0:
![https://d.pr/i/NuNN5z](https://d.pr/i/NuNN5z+) 
Full Size: https://d.pr/i/NuNN5z

Same order with version 1.24.0:
![https://d.pr/i/jipuRO](https://d.pr/i/jipuRO+) 
Full Size: https://d.pr/i/jipuRO

Affected ticket:
3191664-zen

**Comment by fevered** [comment]
Had another report of this in 3201074-zen

**Comment by tijosh** [comment]
Another report in 3194617-zen

**Comment by dphyled** [comment]
Another report in 3191736-zen

**Comment by johndcoy** [comment]
Another 10048733-hc
