### ISSUE TITLE
WP 5.5 compatibility

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2118]
We need to test WCS for compatibility with WP 5.5. It's releasing August 11th.

WP 5.5 change fieldguide: https://make.wordpress.org/core/2020/07/30/wordpress-5-5-field-guide/

For reference, the Extendables are doing some checks related to the REST endpoints: https://github.com/woocommerce/woocommerce-extension-library/issues/145

Task:
- Review changes in 5.5 that may be relevant
- Update this issue with notes about relevant changes
- Test WCS with WP 5.5 (paying special attention to areas that may be impacted by 5.5 changes)
- Open issues if any large issues are present
- Release WCS with WP tested version bumped up to 5.5

**Comment by harriswong** [comment]
Is there a WooCommerce Core version that we should use for 5.5 compatibility? I am assuming latest stable? Or Should we use 4.4 RC?

**Comment by c-shultz** [comment]
Latest stable would be best for WC, in my opinion

**Comment by harriswong** [comment]
### Env
WP 5.5
WC 4.3.2
WCS 1.24.0

### Summary
- Tested against the WP 5.5 test plan. Ran through 1-11 and they are fine
- Tested with live rates and they still show up in checkout
- Tested using calypso repository. I was able to print a label.
- Tested the usual label checkout, refund flow (UPS/USPS), works fine.
- Checked [REST API changes](https://make.wordpress.org/core/2020/07/22/rest-api-changes-in-wordpress-5-5/), double checked usage of `permission_callback`. Seems to be fine except our submodule in calypso.
- Checked usage of `wp_send_json`, nothing found.

Looks good to me. 👍

**Comment by bborman22** [comment]
**Env**

WP 5.5
WC 4.3.2
WCS 1.24.0

**Summary**

- Ran through test plan 1-9 with no issues.
- Ran through common checkout and fulfill flows with different product types (Virtual, Downloadable, Standard) with no issues.
- Nothing in the WP 5.5 changelog caught my eye.

Looks good to me as well. 👍
