### ISSUE TITLE
Disable the refund button for USPS letters

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#2120]
Per USPS policy, letters are not eligible for refunds, so we should probably disable the refund button for letters to avoid false expectations to our customers.

I would ping @elizaan36 here because disabling the button just in this case may confuse the store owners. Maybe a message with the reasons why the button is disabled should be displayed instead to avoid confussions.

**Comment by elizaan36** [comment]
As a quick fix, we could use the disabled button style with a tooltip on hover.

> USPS letters are not eligible for refund

Thoughts?
