### ISSUE TITLE
WP-CLI Integration

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-services#213]
Just an idea for now, but would be cool to have some WP-CLI integration eventually so that you could more quickly setup all the WCC settings (especially useful if managing several stores at once).

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38750476-add-wp-cli-support-for-woocommerce-services-shipp)
