### ISSUE TITLE
Update minimum requirements to match our support policy

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2131]
### Description
Our support policy is based on https://docs.woocommerce.com/document/frequently-asked-questions/#section-62. We are supporting the following:

**WooCommerce**: latest - 2. (the latest version, plus 2 previous ones. For example, if current version is 4.3, then we should support 4.2 and 4.1)

**WordPress version**: latest - 2

**PHP version**: 7.0+

### Task
- Update travis.yml matrix for the above combinations.
- Update minimum versions in readme.txt and woocommerce-services.php plugin header
- Update minimum requirements in docs: https://docs.woocommerce.com/document/woocommerce-services/#section-1
- Update `phpcs.xml.dist` for the [minimum required WP version](https://github.com/Automattic/woocommerce-services/pull/2212/files#diff-05ae9cddcaec1e845771a7db224961439f83ef5939ec67d3a48744cb34d7e58bR13-R15) [Added Oct 19, 2020]

**Comment by c-shultz** [comment]
I tweaked this to include bumping the overall minimum requirements beyond just the Travis config

**Comment by harriswong** [comment]
https://github.com/Automattic/woocommerce-services/pull/2329 has updated this repo to use GitHub Actions. We are now testing against WP latest minus 2 and WC latest minus 2. Closing.
