### ISSUE TITLE
Incorrect tax rate for 90232/Culver City

### ISSUE THREAD

**Issue by jrick1229** [Automattic/woocommerce-services#2132]
### Issue

Tax for 90232 / Culver City charged a rate of 9.51%: https://snipboard.io/5rFJCR.jpg

Correct rate should be 10.25%: https://snipboard.io/1FolRN.jpg

Reported in: https://wordpress.org/support/topic/automated-tax-california-zip-codes/

**Comment by superdav42** [comment]
I believe there was not a problem with WCS. I can confirm that WCS send the full address of the seller and the buyer. I believe the original dependencies between the taxjar tool and the rates returned from WCS were not really a bug but simply the difference between selling items at a certain locator or selling items in an ecommerce store were some taxes to not apply. 
See [this comment](https://github.com/Automattic/woocommerce-services/issues/1934#issuecomment-697916695) for a full explanation.
