### ISSUE TITLE
Packages directory filenames are too long

### ISSUE THREAD

**Issue by Stoyan0v** [Automattic/woocommerce-services#2141]
Describe the bug
I'm one of the developers of Siteground Migrator plugin, and we have issues migrate sites which have WooCommerce Services Installed.

The problem is that the filenames generated in packages folder are too long, and we cannot create tar archive when we migrate sites to our servers.
Here is an example: `woocommerce-services/dist/chunks/vendors~plugin-status~print-test-label~settings~shipping-label~shipping-settings.3e5c5184b6d45dc8c6e9.min.js`

We are using Phar::buildFromDirectory, but we get the following error when we try to archive the a plugin directory:
`[message] => Uncaught PharException: tar-based phar "/home/customer/www/*/public_html/wp-content/uploads/1597612370-fb1d81a286496977c83270c37ed7f569ea1d43fe/plugins/woocommerce-services.tar" cannot be created, filename "dist/chunks/vendors~plugin-status~print-test-label~settings~shipping-label~shipping-settings.3e5c5184b6d45dc8c6e9.min.js" is too long for tar file format`

Is there any chance to change how filenames are generate, so they can become shorter?

We had similar issues with WooCommerce Admin. Please refer to :https://github.com/woocommerce/woocommerce-admin/issues/4512

**Comment by c-shultz** [comment]
To add an additional note to this, we've seen some reports that the `~` in the paths causes issues with some server's security settings, so let's look into removing that when we address this.
