### ISSUE TITLE
 Incorrect tax rate for 92592/Temecula

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/woocommerce-services#2145]
Tax for 92592 / Temecula charged a rate of 7.75%: https://snipboard.io/t2QgGa.jpg

Correct rate should be 8.75%: https://d.pr/i/dbYBXu

Reported in: https://wordpress.org/support/topic/automated-tax-california-zip-codes/#post-13195912

**Comment by superdav42** [comment]
I believe there was not a problem with WCS. I can confirm that WCS send the full address of the seller and the buyer. I believe the original dependencies between the taxjar tool and the rates returned from WCS were not really a bug but simply the difference between selling items at a certain locator or selling items in an ecommerce store were some taxes to not apply. 
See [this comment](https://github.com/Automattic/woocommerce-services/issues/1934#issuecomment-697916695) for a full explanation.
