### ISSUE TITLE
Customs forms missing with UPS labels

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-services#2157]
For international orders, the customs forms should print with UPS labels in the same way they do for USPS. I tested this on my site and the customs form appears for international shipments and I'm able to fill it out, but it doesn't print with the label.

USPS - with customs form attachment
<img width="1015" alt="Screen Shot 2020-08-24 at 9 23 47 AM" src="https://user-images.githubusercontent.com/5121465/91056779-0066c880-e5ec-11ea-8af5-51d586165636.png">

UPS - no customs form
<img width="1005" alt="Screen Shot 2020-08-24 at 9 41 14 AM" src="https://user-images.githubusercontent.com/5121465/91058516-2a20ef00-e5ee-11ea-834e-233761433009.png">

A UPS beta customer flagged this issue. Here's his message:
> Just a heads up, but for international orders, the UPS option doesn’t print all the required documentation like the USPS option does. Please take a look into that as it’s absolutely needed for someone like me when shipping. Thanks!

**Comment by Ferdev** [comment]
I've performed several test to try to make UPS print the customs info in their labels. Since I couldn't make it work, and the docs didn't say anything about UPS needing special parameters to make it work, I contacted Easypost support and they replied this:

> The Commercial Invoice is provided as a courtesy, UPS labels do not include a print-out of the entered customs information for UPS as it does for the USPS. 

Apparently, this is something UPS don't provide, and their behavior is different from USPS labels. Some kind of customs info is provided with the UPS commercial invoice, but I'm not sure this would be useful for our customers.

Maybe this is something we could include in the future as added value for our customers.

**Comment by elizaan36** [comment]
Hey @Ferdev that's interesting and it does make sense that it would be a different process to USPS. I suppose it's a separate form to the UPS shipping label and we'd have to set up as such.

Since the customs forms won't print for our merchants in the process of creating a UPS shipping label, we should remove the custom form step. I think that will be the biggest point of confusion, if people fill out the info in the customs form then it's not there when they print. 😆

**Comment by elizaan36** [comment]
Just reached out to the original customer to shared the feedback and asked what his experience is printing on UPS.COM. Here's what he shared:

> When I create a label on UPS.com I am informed I also need to fill out a document that lists what products I am shipping and their costs. Attached is a recent shipment I made and what the forms look like.

Shared the labels separately in [this thread](https://a8c.slack.com/archives/CU6SYV31A/p1598992662033900).

**Comment by Ferdev** [comment]
I got a new answer from Easypost support about this issue. The commercial invoice the customer shared with us, is generated by Easypost and provided to us through their API when a new shipment is created. It lives aunder the `forms` property of the shipment object returned by the API. We should probably merge both the label and the commercial invoice in those carriers that don't add the customs info in their shipping labels.

So when printing labels, we should do some more checks:

1. If it's not an international shipment, or if it is USPS, do nothing, just print the label.
2. If it's UPS and it's an international shipment, print the `comercial_invoice` form along with the shipping label.

I'll create an issue to take care of this.

**Comment by c-shultz** [comment]
This should be finished off by https://github.com/Automattic/woocommerce-services/pull/2213
