### ISSUE TITLE
Usage of deprecated `WC_Abstract_Legacy_Order::get_product_from_item`

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2161]
It looks like there's usage in the codebase of the deprecated `WC_Abstract_Legacy_Order::get_product_from_item`.

This is creating a `Deprecated` notice when placing an order.

![Screen Shot 2020-08-31 at 12 37 50 PM](https://user-images.githubusercontent.com/273592/91749353-f6fad480-eb86-11ea-8251-88d38b1b1385.png)

**Comment by bborman22** [comment]
I wasn't able to reproduce this issue, I was wondering if there was any particular steps or configurations to reproduce this? 

I noticed that `get_product_from_item` only gets called from two spots in WCS and both were for WooCommerce version 3.0 or less and neither seemed to be called while placing an order.

**Comment by frosso** [comment]
Connected with Brian offline.

Can confirm that now with the latest `1.24.2` I also cannot reproduce it anymore.

Closing 👍
