### ISSUE TITLE
[DHL] Add DHL logo in rates list

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2162]
When a merchant sees rates in the order page shipping modal, they should be displayed with the DHL logo.

For reference, the UPS logo was added here: https://github.com/Automattic/woocommerce-services/pull/2068

**Comment by c-shultz** [comment]
@aleftick has emailed DHL about which file we should use. This will be blocked until they respond.

**Comment by c-shultz** [comment]
DHL confirms that the logos from their [branding page](https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim.html) are the right ones. This square image should be thes best fit for our rates list: https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim/_jcr_content/parsys/dosanddonts/images/image/image.coreimg.100.1024.png/1591963889007/logo-dodont-1-do.png

Their email highlights the following rules for displaying the logo: 

> Please make sure to always use the logotype in its original form.
> 
> •             No modifications or distortions are permitted. Solely a proportional resizing is allowed.
> 
> •             The logo width should not go below 100 pixels.
> 
> •             Furthermore, it is necessary to respect the "buffer zone" of the logotype which is 1/7 of the logo width. No text or graphical elements shall be placed within this area surrounding it.

**Comment by harriswong** [comment]
Hi @elizaan36 @c-shultz, I went to DHL's [logo download section](https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim.html) and tried using the standard DHL logo. It is a bit hard to read in our rate step: 
![image](https://user-images.githubusercontent.com/572862/92139486-066b5f00-edcd-11ea-8b17-e395d615fc93.png)

In their [branding guide](https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim.html) under "Responsive Logo", we could use a smaller responsive logo
> Our responsive logo makes it possible to showcase our Brand in small places. It may only be used in digital media where space is limited:
> 
> If it’s not technically possible to display our standard logo with a width of at least 84 pixels.
>
> If our standard logo is too small to be clearly seen or recognized because of its width.

It would look like this:
![image](https://user-images.githubusercontent.com/572862/92139868-9b6e5800-edcd-11ea-8dc3-ac0cbdeaa08c.png)

Which logo should we use?

**Comment by aleftick** [comment]
Shopify built their solution a while ago so the brand guideline might have been different. The DHL logo looks like this:

![image](https://user-images.githubusercontent.com/2545592/92160846-aa6cfe80-edfd-11ea-9126-c348d4dc043a.png)

If we prefer that logo format, I can ask Rachel at DHL to look into it. However, it might take time so probably should pick an option pre-approved by DHL.

**Comment by harriswong** [comment]
Thanks @aleftick . I will use this logo https://www.dpdhl-brands.com/dhl/en/guides/design-basics/logo-and-claim/_jcr_content/parsys/dosanddonts/images/image/image.coreimg.100.1024.png/1591963889007/logo-dodont-1-do.png @c-shultz attached.

Here is how it looks:
![image](https://user-images.githubusercontent.com/572862/92164911-67a62900-edf3-11ea-9a3e-0b3f111a7cab.png)

**Comment by elizaan36** [comment]
hey @harriswong just getting a chance to peek at this, was afk these couple days. 

I like the most recent logo you've got there, but it's appearing off center horizontally.
<img width="400" alt="DHL logo alignment" src="https://user-images.githubusercontent.com/5121465/92193337-aeb11000-ee2d-11ea-89db-0848f84445d7.png">

I'd only make sure it's horizontally centered with the radio control and text similar to the other rows, rather than aligned to the top of the text.

**Comment by harriswong** [comment]
No worries, thanks for taking a look @elizaan36! I created another issue to fix the alignment of the logo: https://github.com/Automattic/woocommerce-services/issues/2170
