### ISSUE TITLE
Select all posts checkbox doesn't work when plugin is active

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-services#2165]
To reproduce:

1. Spin up a new test site.
2. Install WC and WCS, activate both.
3. Go to the Pages menu in wp-admin, or any other page that lists posts (of any type).
4. Click here: https://d.pr/i/EaRtXo/E1smvFSjcr

As you can see, the posts are not actually select. No JS errors in console.

Deactivating WC Services makes it work again.

EDIT: From this forums thread: https://wordpress.org/support/topic/issue-with-wp-admin-select-all-feature/?view=all

**Comment by peterfabian** [comment]
We also got a report on the developer blog and I could reproduce with WP 5.5.1 + WC 4.4.1 + WCS 1.24.1

**Comment by c-shultz** [comment]
Thanks for the report! I'll slate this for next week's sprint

**Comment by harriswong** [comment]
I can reproduce this on the latest WP 5.5.1, WC 4.5.1, and WCS 1.24.2. To reproduce, create a clean site, download and install WCS and WC through store. Activate but do not go through onboarding or any setups.

**Comment by harriswong** [comment]
Another note is deactivating either WC or WCS will allow the select-all checkbox to work again.

**Comment by harriswong** [comment]
One thing that seems to be different is that when both WC and WCS are activated, it has different events listeners bound to the checkbox
When both WC and WCS are activated, there is 1 listener
![image](https://user-images.githubusercontent.com/572862/92805131-14ddeb80-f376-11ea-865b-2a539c5c85b8.png)

When only either WC/WCS is activated, there are 5 listeners, and the 4th one seems to be responsible for the check-all box
![image](https://user-images.githubusercontent.com/572862/92805286-37700480-f376-11ea-83f6-9ef5b5d6fd8d.png)

**Comment by harriswong** [comment]
The problem seems to be coming from the `wc_connect_banner` script in [here](https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-nux.php#L441).

This code is use for this banner:
![image](https://user-images.githubusercontent.com/572862/92815968-08f82680-f382-11ea-9828-8daa283070eb.png)

**Comment by harriswong** [comment]
In source, we can see the following error:
```html
<script id='wc_connect_banner-js-extra'>
--
  | var wcs_nux_notice = {"nonce":"***","initial_install_status":"activated","redirect_url":"https:***wp-admin\/plugins.php?plugin_status=all&paged=1&s","translations":{"activating":"Activating...","connecting":"Connecting...","installError":"There was an error installing Jetpack. Please try installing it manually.","defaultError":"Something went wrong. Please try connecting to Jetpack manually, or contact support on the WordPress.org forums."}};
  | </script>
```
