### ISSUE TITLE
 Option to select not working

### ISSUE THREAD

**Issue by Eugene-pro-19** [Automattic/woocommerce-services#2183]
when using woocommerce services plugin option to **select** all products or plugins or else don't work.I deactivated all plugins finally woocommerce services plugin bug came up.theme child theme storefront theme.

**Comment by frosso** [comment]
Hey @Eugene-pro-19 ,

Thanks for tracking. This seems a duplicate of https://github.com/Automattic/woocommerce-services/issues/2165 , can you please confirm?
If so, the issue will be fixed by the next release patch: https://github.com/Automattic/woocommerce-services/pull/2181

Thanks again!

**Comment by c-shultz** [comment]
This appears to be fixed now by #2181
