### ISSUE TITLE
Introduce DHL "pointer"

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#2196]
We want to highlight the availability of DHL for sites where it's been enabled.

For new users (if DHL is enabled on the site), let's update the copy here to `USPS or DHL`:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/6209518/93830338-c9a0c400-fc24-11ea-83f0-abc5c918f25c.png">

For existing users that have already dismissed the above pointer (different pointers have unique IDs, and the above is `wc_services_labels_metabox`), we want to introduce a new pointer to tell them we've added DHL.

The pointer should show when:
- DHL is enabled on the site
AND
- `wc_services_labels_metabox` has been dismissed
AND
- The order has an international destination (so is eligible for DHL)

**Comment by c-shultz** [comment]
@elizaan36 , for the DHL-specific pointer, I took a first pass at some copy:
Title: `Discounted DHL Shipping Labels`
Body: `WooCommerce Shipping now supports DHL. When you're ready, purchase and print discounted labels from DHL or USPS right here."

**Comment by elizaan36** [comment]
> for the DHL-specific pointer, I took a first pass at some copy:
Title: Discounted DHL Shipping Labels
Body: WooCommerce Shipping now supports DHL. When you're ready, purchase and print discounted labels from DHL or USPS right here.

Yeah, that sounds great. I'd take out "When you're ready" to make it less wordy, and use "and" rather than "or" for a sense of more.

> Title: Discounted DHL Shipping Labels
Body: WooCommerce Shipping now supports DHL. Purchase and print discounted labels from DHL and USPS right here.

**Comment by elizaan36** [comment]
> For existing users that have already dismissed the above pointer

Once a "new user" dismisses the first pointer, do they become an existing user that will then immediately see the DHL one?😆 Do we need to add logic so that once the new user pointer is dismissed after rollout, the DHL one doesn't pop up at all?

**Comment by c-shultz** [comment]
Thanks for the copy tweaks! 

And you're right, we'll need to handle new users better. We should be able to pre-dismiss the DHL-specific one when they dismiss the new user one. Thanks for the catch!

**Comment by brentmackinnon** [comment]
@c-shultz for consideration: 

> Title: Discounted DHL Shipping Labels
> Body: WooCommerce Shipping now supports DHL Express labels for international shipments. Purchase and print discounted labels from DHL and USPS right here.
