### ISSUE TITLE
Incorrect Taxes in Pennsylvania

### ISSUE THREAD

**Issue by melindahelt** [Automattic/woocommerce-services#2203]
Discovered a few tax issues for Pennsylvania while testing something else

In PA, sales tax varies by county: https://www.revenue.pa.gov/GeneralTaxInformation/Tax%20Rates/Pages/default.aspx

![](https://d.pr/i/LcqIrM+)Image Link: https://d.pr/i/LcqIrM

TaxJar appears to account for this, but our plugin does not.

**Butler County (should be 6% - showing 7%)**

![](https://d.pr/i/RzC8m8+)Image Link: https://d.pr/i/RzC8m8

![](https://d.pr/i/AtoZuB+)Image Link: https://d.pr/i/AtoZuB

**Greene County (should be 6% - showing 7%)**

![](https://d.pr/i/u2yFFY+)Image Link: https://d.pr/i/u2yFFY

![](https://d.pr/i/g25qzj+)Image Link: https://d.pr/i/g25qzj

Did not check any other counties, but this should be looked at.

**Comment by c-shultz** [comment]
Thanks for the report!

@FreshPhil, have you run across anything similar before? I'm trying to tell if this could be a similar situation to the Colorado issue: https://github.com/Automattic/woocommerce-services/issues/1934#issuecomment-697916695

**Comment by FreshPhil** [comment]
Hey @melindahelt - what is the base address you used for your shop? Can you please insert that on https://www.taxjar.com/sales-tax-calculator/ and check if the rate matches what is shown on the checkout page.

PA is an origin-based tax state. So taxes are calculated based on your shop's base address.

**Comment by melindahelt** [comment]
Interesting. I did not know that about my home state  :) Given this, then the rates I was seeing is correct based on my shop address.
