### ISSUE TITLE
[WC 4.6 RC1]  WooCommerce Services name needs to be updated in the Jetpack connection notice

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#2208]
**Describe the bug**

WooCommerce Services name needs to be updated from `WooCommerce Services` to `WooCommerce Shipping & Tax` in the Jetpack connection notice. We already use the new name in the onboarding but the notice reflects the old name:

Onboarding - where we use the new correct name - `WooCommerce Shipping & Tax`:

![shipping tax](https://user-images.githubusercontent.com/19143190/94969798-5c691a80-04d1-11eb-8364-044949cec3b7.jpg)

Jetpack connection notice - where we use the old incorrect name - `WooCommerce Services`:

![serv](https://user-images.githubusercontent.com/19143190/94972647-c08edd00-04d7-11eb-91b6-33240f4808b7.jpg)

<hr>

 cc @pmcpinto

**Comment by c-shultz** [comment]
Thanks @juliaamosov! @frosso has a PR for this one here: https://github.com/Automattic/woocommerce-services/pull/2179/files and is tracking all the updates here: https://github.com/Automattic/woocommerce-shipping-issues/issues/104

**Comment by juliaamosova** [comment]
Great, thanks @c-shultz!
