### ISSUE TITLE
Test build compatibility with composer 2.0

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2225]
### Summary
WooCommerce Services uses `composer` to install development packages, such as phpcs and phpunit.

On running composer update

> You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.

From https://github.com/composer/composer/releases/tag/2.0.0-RC2

> "The current plan is to release a 2.0 final before end of October."

and

> "The lock files from v1 can be used by v2 and vice-versa, so don't worry about that."

### Other issues
Relates to https://github.com/Automattic/woocommerce-payments/issues/1034

**Comment by c-shultz** [comment]
Done! No issues found: https://wcship.wordpress.com/2020/10/30/composer-2-compatibility-audit/
