### ISSUE TITLE
Tax reports don't break down taxes with enough detail

### ISSUE THREAD

**Issue by FreshPhil** [Automattic/woocommerce-services#2226]
This is a follow up to a Slack conversation: p1603061005032000-slack-CTYKKGC1Y

## Problem
When using Automated Taxes, the `WooCommerce > Reports > Taxes` report does not show a break down of the tax rates that were used/charged.

All transactions within a state are shown as a single rate. For example, all sales for a California based company would be filed under the `US-CA-CA TAX-1` tax.

This is because we use the same naming scheme for all taxes within a given state/province.

![standard_tax_rates_added_by_wcservices](https://user-images.githubusercontent.com/52214/106674772-cdb5f880-65ab-11eb-891a-99a432a6af18.png)

The problem with this is that it's a common practice to have different rates by `county` within the same state in the US. Users can't report on their taxes charged by county though, since all tax rates for their state are grouped under the same name.

If someone were manually entering in rates (not using WCTax), this wouldn't be an issue as each counties tax rate could be name for that county.

## Solution

TaxJar returns `county` in their request-response. If we append that to the end of the tax name, this would give users a way to see the different taxes charged in their tax report.

While this isn't a "bug". I think this is a very important quality of life improvement that we should prioritize as it severely limits the reporting effectiveness for users.

**Comment by mouligreenlaw** [comment]
Closing the original ZD ticket and adding the number here so they will get notified hopefully:
3411927-zen

**Comment by zwiesman31** [comment]
3653299-zen

**Comment by zhollenbeak** [comment]
Another in 3892911-zen

**Comment by zhollenbeak** [comment]
Another report of this problem in 29040201-zen
