### ISSUE TITLE
Updating store's product's dimensions unit does not update WCS' package settings

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2227]
### Summary
When we update the "Dimensions unit" in WooCommerce's Settings, the package dimensions in WCS does not get updated.

### How to reproduce
1. Create a shipping label, click "add package" and create a package box. In my example, I named my box 10x10x10 inches. My store's dimensions are in `cm` so the box is 25.4cm.
![image](https://user-images.githubusercontent.com/572862/96798913-211a8700-13bf-11eb-87de-d5d808c93512.png)
2. Go to `wp-admin/admin.php?page=wc-settings&tab=products`
![image](https://user-images.githubusercontent.com/572862/96798757-c8e38500-13be-11eb-844d-eca8cb35b297.png)
3. Change "Dimension unit" to `inch`
4. Go to WooCommerce Services Settings page `wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`, or the label printing page, you can see the dimension unit is updated, but the values stay the same.
![image](https://user-images.githubusercontent.com/572862/96799140-adc54500-13bf-11eb-9ba5-20aa7177eb98.png)
![image](https://user-images.githubusercontent.com/572862/96799147-b0279f00-13bf-11eb-8919-527f8b2f2fc3.png)

In the above example, when we update the WooCommerce unit settings, the package dimensions should display `10 in x 10 in x 10 in` instead of `25.4`.

**Comment by frosso** [comment]
I noticed this as well. The same thing happens with product dimensions.
When changing the units, the product dimensions are also not updated. Should it be happening in both places?

**Comment by harriswong** [comment]
I think it makes sense that if the unit is updated, the whole platform's existing values should be converted. The flip side is that, I can see that someone saved the wrong unit in settings, they want to change the unit without all the conversions. I am not sure if WC core had already talked about that. Maybe there should be a extra checkbox "convert all values to this unit". :D

For WCS, maybe we should also decide if we should follow how WC core handles unit settings update.

**Comment by harriswong** [comment]
We had a team discussion about this. To avoid confusion, WCS should do the same thing as what core is doing. If the product dimension doesn't get updated, we shouldn't update as well.

If this started becoming the problem for the users, we should explore options to include an option for user to convert all units when they update store unit settings.

We will continue to leave this as is. Closing.
