### ISSUE TITLE
Physical product with no shipping dimension in the cart

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/woocommerce-services#223]
One of the most common shipping issues we encounter is when customer's don't input shipping dimensions for any or all of their products.

If the current account is an admin, could we display a notice like this: http://cld.wthms.co/19Rx4/crRossy5 ? Maybe with some simpler wording, and some links to edit the products in question and/or a link to a guide on how to add product dimensions (perhaps an FaQ item in our connect docs).

**Comment by jeffstieler** [comment]
Partially handled in https://github.com/Automattic/woocommerce-services/pull/803

The remainder of the work (front end) will be done in https://github.com/Automattic/woocommerce-services/issues/878.
