### ISSUE TITLE
Shipment tracking meta box shows up even when shipping label options disabled

### ISSUE THREAD

**Issue by fylgjur** [Automattic/woocommerce-services#2235]
A user in 3441996-zen noticed that with the extension Shipment Tracking enabled, the shipment tracking meta box shows up twice. I can reproduce this even with the shipping label function of WooCommerce Shipping and Tax disabled:

![double shipment tracking](https://user-images.githubusercontent.com/65490337/97347062-2f1b4c80-1884-11eb-874d-4e08a5a5e391.png)

@c-shultz via A8C Slack says: "It looks like we may not be respecting the label setting on the order page.
There's a toggle at `wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings` that looks like it should allow the order page label options to be hidden."

![image (5)](https://user-images.githubusercontent.com/65490337/97346977-101cba80-1884-11eb-99e6-c13b79a79fb8.png)

"But turning this off is not hiding the label printing meta boxes."

Although this is largely cosmetic rather than functional, it does raise questions and doubt in the mind of users so would be good to include in an upcoming release.

**Comment by c-shultz** [comment]
I just also noticed that the toggle does disable the ability to print labels by removing the button: 
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/6209518/97452402-f023e000-18f1-11eb-942a-f36c056477c4.png">

I think we can safely hide the top meta box along with the "Shipment Tracking" meta box when the toggle is disabled.
