### ISSUE TITLE
Initiating a label refund for Priority Post labels generated an error regarding USPS First Class Letter refunds

### ISSUE THREAD

**Issue by mouligreenlaw** [Automattic/woocommerce-services#2242]
Requesting refund on labels for Priority Mail via WooCommerce Shipping and Tax results in an error saying:

`First Class Mail letters are not eligible for refund by USPS`

They are using
WooCommerce Shipping & Tax: by Automattic – 1.25.1
and the changelog indicates that:
`Add - Disable refunds for USPS letters.`

I can initiate a refund on the same label from the users RC without the issue

**Original chat;**
https://mc.a8c.com/support-stats/happychat/transcript.php?id=11346418
**Ticket:**
3447040-zen
**Asked devs;**
https://a8c.slack.com/archives/CTYKKGC1Y/p1603941949062500

**Comment by mdmoore** [comment]
Just noting here that this is possibly preventing First Class Package refunds as well.  The same error is occurring, but the label is not a letter.  Gathering more details in 3470714-zen

**Comment by katinthehatsite** [comment]
we have another report in 3476407-zen

**Comment by mdmoore** [comment]
Another report in 3482600-zen.

**Comment by stephhjacq** [comment]
Another report in 3493533-zen

**Comment by aleftick** [comment]
This is related to #2223. 

USPS First Class Mail and First Class Mail International letters aren't refundable. However, everything else is refundable including:
- Letters shipped with other USPS services (such Priority and Priority Express)
- Letters shipped using USPS's flat rate envelopes (pre-define packages) - They all use Priority and Priority Express.
- Letters shipped with other couriers
- Any First Class shipment that is [considered a package and not an envelop](https://pe.usps.com/text/dmm100/mailing-domestic.htm). 

Based on my research and tests, if there is a tracking number, it is eligible for a refund. Could that be the best way to know when to deactivate the "request refund" option?
