### ISSUE TITLE
Add a description paragraph to dynamic carrier registration form

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2250]
Blocks by https://github.com/Automattic/woocommerce-services/issues/2234

### Summary
In #2234, we create a registration form dynamically for each carrier. We need to include a paragraph on the left for each of them:
![image](https://user-images.githubusercontent.com/572862/98282227-251bdc80-1f5b-11eb-85f2-a9c6697d7a3a.png)

### Proposed solution
1. Use a generic paragraph for all carriers. Find out what this paragraph will be. Use UPS as a reference. 
![image](https://user-images.githubusercontent.com/572862/98282333-50063080-1f5b-11eb-8bf1-bc49693782ac.png)

2. Each carrier will have its own unique message and its own ahref link. In this case, it may be better to retrieve the paragraph from the server the same way we retrieve the `carrier-types`. We will also need to create another ticket for the server side work.

**Comment by c-shultz** [comment]
Let's start with a generic solution on this and we can enhance it with carrier-specific links/text in the future if needed.
