### ISSUE TITLE
Add carrier_id to REST connect controller's payload

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2252]
As we support more carriers, the `carrier` param can not be assumed to be just `usps`. We will need to add the missing `carrier` property in the payload that's sent through connect controller's. `carrier` should be the name and value is the carrier_id, ie. usps.

I found [2 end points](https://github.com/Automattic/woocommerce-services/blob/da175ed6b473fa7b9cfc1c232a752a9921bbca26/client/extensions/woocommerce/woocommerce-services/api/url.js#L4-L5) in our React app that is missing `carrier` in its payload: 
`orderLabels` and `getLabelRates`

For example, in the `orderLabels` end point, it will be handled by this [controller](https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-rest-connect-shipping-rates-controller.php#L40-L77). In this `post` request, this [$payload](https://github.com/Automattic/woocommerce-services/blob/da175ed6b473fa7b9cfc1c232a752a9921bbca26/classes/class-wc-rest-connect-shipping-rates-controller.php#L68) needs to have a `carrier=>$carrier_id` or something similar.

Same applies to the `getLabelRates` controller.

**Comment by c-shultz** [comment]
Do you know if this is still an issue, @harriswong? It seems like this may have been resolved already through the carrier work that was done.

**Comment by harriswong** [comment]
I think this is no longer an issue. The available carriers are controlled on the server side. The client doesn't need to pass in a carrier_id property to retrieve individual carrier rate. The `'connect/label/(?P<order_id>\d+)/rates'` end point will return all available rates, as long as they are configured properly and enabled.

**Comment by harriswong** [comment]
Closing.
