### ISSUE TITLE
PHPUnit tests with PHP 8

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-services#2258]
While testing WooCommerce Shipping & Tax with PHP 8 and WP 5.6 I ran into an issue with running PHPUnit with PHP 8. The summary is that WordPress only supports up to PHPUnit 7.x, but PHPUnit 7.x doesn't support PHP 8. You can see the [WP core issue](https://core.trac.wordpress.org/ticket/50902) and their solution was to essentially [override the problematic pieces](https://core.trac.wordpress.org/changeset/49037) of PHPUnit. And there is the proposed WooCommerce solution, mentioned at the bottom of that WP core issue, of [forking PHPUnit](https://github.com/woocommerce/phpunit/pull/1) and [using that fork for unit testing](https://github.com/woocommerce/woocommerce/pull/27844).

This issue is being created to make sure that once a solution is implemented in WP 5.6 and the latest WooCommerce, we confirm that the PHPUnit tests are working as expected on PHP 8.

**Comment by dustinparker** [comment]
hey @bborman22,

I tested implementing the changes from [WP Core's Changeset 49037](https://core.trac.wordpress.org/changeset/49037) and running PHPUnit 7.5 with PHP 8.0 and all tests passed using WP 5.6 and WC 5.9.0.

**Comment by bborman22** [comment]
That's great to hear! I'm a little bit fuzzy on all the details from this. Are those changes something we can commit in to the repo or could we get them from WC in some way? Would our update be similar to https://github.com/woocommerce/woocommerce/pull/27844/files? Thanks for looking in to this one!

**Comment by dustinparker** [comment]
I just tested running the compatibility fork with PHP 8.0 [as instructed here](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#running-tests-in-php-8) and it also works. That is actually the simpler way to do it.

**Comment by dustinparker** [comment]
hey @bborman22, was there anything else related to this issue you'd like me to look into?

**Comment by bborman22** [comment]
Thanks! No I don't think there is anything else to verify at this point since we're able to get tests in PHP 8 to work. @harriswong I see you had a linked issue around adding PHP versions to the GH actions, looks like that item is unblocked now and we could look in to [this solution](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#running-tests-in-php-8) linked above. Seems like this could be a good cooldown / janitorial task at some point?

**Comment by harriswong** [comment]
Thanks @dustinparker 

@bborman22 I agree! It would be good for the pipeline to cover both PHP 7 and 8 tests. Glancing over [the setup instructions](https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/tests#running-tests-in-php-8), I feel a little hesitant about the locally modified composer.json and the PHPUnit fork. But maybe I'll just need to read into what the fork changes are. 
+1 on a good cooldown/ janitorial task as well!
