### ISSUE TITLE
Does this plugin work with WooCommerce Blocks?

### ISSUE THREAD

**Issue by seb86** [Automattic/woocommerce-services#2290]
The WooCommerce Blocks store REST API is blocked from what I understand reading the code currently. There is no condition to allow the calculation of totals should the cart and checkout blocks be used.

I have yet to test and verify as I don't have a US store but I think this is important to address.

JetPack is allowed but then all other REST API requests are ignored so I pushed a PR to allow `wc/store/`. https://github.com/Automattic/woocommerce-services/pull/2289

If I am mistaken and it does work then please ignore this issue and PR. I just thought it was strange while working on another issue.

**Comment by c-shultz** [comment]
Support was added here: https://github.com/Automattic/woocommerce-services/pull/2325
