### ISSUE TITLE
Should be allowed to request shipping/tax API for third-party REST API

### ISSUE THREAD

**Issue by seb86** [Automattic/woocommerce-services#2292]
This issue is an enhancement request to allow third-party REST API's request shipping/tax API via a filter.

I have pushed a PR for this. https://github.com/Automattic/woocommerce-services/pull/2291 It will allow me to support automated shipping and taxes in my REST API [CoCart](https://cocart.xyz).

In addition, another filter also had to be added to allow third-party plugins check if we should skip calculating the totals. https://github.com/Automattic/woocommerce-services/pull/2288

**Comment by seb86** [comment]
Example of use.

```php
add_filter( 'woocommerce_send_cart_api_request', 'wc_connect_send_api_request' );
add_filter( 'woocommerce_skip_calculate_totals', 'wc_skip_calculate_totals' );

/**
 * Allow WooCommerce Connect Shipping/Tax API requests to be sent.
 *
 * @return string|bool
 */
function wc_connect_send_api_request() {
	if ( false !== strpos( $_SERVER['REQUEST_URI'], 'cocart/v1' ) ) {
		return 'cocart/v1';
	}

	else if ( false !== strpos( $_SERVER['REQUEST_URI'], 'cocart/v2' ) ) {
		return 'cocart/v2';
	}

	return false;
}

/**
 * Allow CoCart to make a request to calculate the totals via the REST API.
 *
 * @param  bool $default Default value
 * @return bool
 */
function wc_skip_calculate_totals( $default ) {
	if ( 
		( false !== strpos( $_SERVER['REQUEST_URI'], 'cocart/v1' ) ) ||
		( false !== strpos( $_SERVER['REQUEST_URI'], 'cocart/v2' ) )
	) {
		return true;
	}

	return $default;
}
```

**Comment by seb86** [comment]
Any updates would be appreciated. Thank you.

**Comment by c-shultz** [comment]
See note here: https://github.com/Automattic/woocommerce-services/pull/2291
