### ISSUE TITLE
UPS Account registration - Invoice Number should allow letters

### ISSUE THREAD

**Issue by brezocordero** [Automattic/woocommerce-services#2296]
When connecting your own UPS account, the form validation for the invoice number only allows digits. 
It should allow letters and digits.

To reproduce:
1. With WooCommerce and WooCommerce Services and Tax active on a site
2. The site needs to have the flag active to use UPS rates
2. Got to WooCommerce > Settings > Shipping > WooCommerce Services
3. Scroll down and click on Connect next to UPS
4. Enter a valid invoice number (13 characters, numbers and letters.)
5. Check that there is an error because letters are not allowed.

Coming from additional checks we added on this PR: https://github.com/Automattic/woocommerce-services/pull/2244
Looks like we were too strict on the Invoice number field.

**Comment by c-shultz** [comment]
I'm bumping to critical since it's blocking a user from signing up as seen in the other bug report
