### ISSUE TITLE
Activating Automated taxes wipes a previously entered standard rates table

### ISSUE THREAD

**Issue by fylgjur** [Automattic/woocommerce-services#2311]
Experienced in 3667607-zen

## To reproduce:

* Have automated rates disabled
* Enter some rates into the standard rates table
* Enable automated rates
* Return to standard table - it is empty.

## Why this is a problem

* Customers who need to override certain automated rates may, before activation, create a standard rates table which is then wiped - there's currently no guidance or warning that this is the case
* Customers may have manual rates all set up, but wish to 'try' automated rates and unwittingly wipe all their previous settings.

I will also submit a documentation change request to warn customers, but ideally this would be altered in the UX or at least a warning 'are you sure' box could alert customers to the effect of activating the automation.

**Comment by DustinHartzler** [comment]
Removed the Enhancement tag, since I think it's a bug. At least a warning or something needs to be added as a short term fix to let the store owner know that their table is about to be wiped out.

**Comment by ldr2273** [comment]
I've been able to reproduce this as well, and I suspect that could be playing a factor in 3819973-zen.

**Comment by melek** [comment]
This appears to be the same issue as #2471 - I'll note that there it is noted that rates are backed up:

> before overwriting, the tax rates are backed up in the WP site's upload directory, in a CSV file with name `taxjar-wc_tax_rates-{YYY-MM-DD}-{time}.csv`, where `{YYY-MM-DD}` is the current date and `{time}` is the current Unix timestamp.

In [our documentation](https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#automated-tax-calculation) there is now this notice:

> When Automated taxes are in use, this overrides any tax rates you have manually added for locations where you have a tax nexus, as well as the “Compound” and “Shipping” toggles for those tax rates.

> After switching to automated rates, a backup of your previous tax rates is created and can be found in your sites wp-content/uploads folder.

I like the idea in this issue to add a warning in the UI when enabling the taxes (likely with a note like in the documentation and instructions on how to export their rates) would be good.

**Comment by dustinparker** [comment]
Hey everyone,

We've come up with a solution for this with some added messaging and the ability for merchants to simply click a link to download one of the backed-up tax rate tables so they can import via CSV. I've attached screenshots highlighting the new messaging and was hoping to get some feedback. Please let me know if you think any of the wording should be changed. Thanks!

This is the message that displays before a user enables automated taxes:
![tax-settings-messaging-auto-taxes-disabled](https://user-images.githubusercontent.com/11618203/180149999-8d7ff82a-bb82-4f44-b01b-37b5ba8407d7.png)

This is the message that displays after a user enables automated taxes:
![tax-settings-messaging-auto-taxes-enabled](https://user-images.githubusercontent.com/11618203/180150002-7ee13cc3-2306-49a5-a96d-f7a302a67846.png)

This is the section on the `/wp-admin/admin.php?page=wc-status&tab=connect` page where the merchant can click and download any of the backed-up tax rate tables as a CSV:
![wcs-connect-tab-tax-rate-backup-downloads](https://user-images.githubusercontent.com/11618203/180150007-5e0c95f6-aa7e-4bfe-87f2-6df651ac3ed6.png)

**Comment by harriswong** [comment]
I like the message there!
