### ISSUE TITLE
Site name is illegible on sidebar when viewing Products

### ISSUE THREAD

**Issue by worldomonation** [Automattic/woocommerce-services#2312]
### Steps to reproduce the behavior

1. Set up an eCommerce site.
2. On `wp-calypso` sidebar, click on Products.
3. Once WooCommerce plugin UI loads, visually inspect the sidebar.

#### What I expected to happen
Site name is legible.

#### What actually happened
Site name is white against an off-white background, rendering the text illegible.
text color: rgb(255, 255 ,255)
background color: rgb(44, 51, 56), but it does not appear to be the case.

### Context
User scenario manual testing.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
![Screen Shot 2021-01-27 at 17 26 37](https://user-images.githubusercontent.com/6549265/106185121-46095d80-6157-11eb-8677-4a295204a8c3.png)

**Comment by c-shultz** [comment]
Closing because Store on WP.com has been discontinued.
