### ISSUE TITLE
Radio button display issue on Rates step

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2321]
## Description
With https://github.com/Automattic/woocommerce-services/issues/2279 we fixed an issue where the radio button was not displayed correctly.
This fix seems to be working well until `WC@5.0.0-beta.1`. Starting from `WC@5.0.0-beta.2`, a similar issue happens again.

Radio button displayed until `WC@5.0.0-beta.1`:
![Screen Shot 2021-02-05 at 10 17 42 AM](https://user-images.githubusercontent.com/273592/107060642-d588bf00-679c-11eb-8608-b939e8fc9787.png)

Radio button displayed `WC@5.0.0-beta.2...5.0.0-rc.2`:
![Screen Shot 2021-02-05 at 10 16 58 AM](https://user-images.githubusercontent.com/273592/107060716-eb967f80-679c-11eb-891a-a53a3a091249.png)

We'll need to find a backwards compatible solution.

**Comment by superdav42** [comment]
I don't see the Radio button display issue on RC2 or RC3.
