### ISSUE TITLE
Refunded line items present in package selection

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-services#2371]
Reported in 3807410-zen

When an order contains refunded items, the items are still displayed in the "items to fulfill" table of the label purchase interface e.g.:
![see screen shot](https://d.pr/i/fcks2C+)
https://d.pr/i/fcks2C

Is this expected behavior?

**Comment by artypineda** [comment]
Thank you for this. I have been attempting to refund the client and print a new shipping label. However as you can see, this populates still at the "items to fulfill" level. Please let me if this gets resolved as this may or may account for weight. -Art.

**Comment by tijosh** [comment]
3813536-zen

**Comment by WillBrubaker** [comment]
4011674-zen
