### ISSUE TITLE
Inconsistent shipping rates between staging and live

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-services#2376]
I have a Mix and Match Products support ticket that I think it crossing over into a shipping issue. Original discussion:
https://a8c.slack.com/archives/C07414X4N/p1615651978306700

So Mix and Match allows a customer to pick X number of items to form a box/bundle.

I have 2 shipping modes:
1. per-item shipping- every item is treated just like a regular line item in the cart
2. or _not_ - effectively all selected items are placed into a single box and we calculate shipping based on that box's dimensions. 

So my support ticket person has a bunch of variable products. And they have a single mix and match product where you can choose from a bunch of the 1ml variations.

The mix and match product is set to per-item shipping and the container product itself is set to virtual. And all the 1ml variations for all the different flavor products have the same dimensions. So this means that shipping 6 items as part of a mix and match container should be exactly the same as shipping the same 6 items outside of the container.

And on his staging site it looks completely correct. Here's the mix and match grouping with $29.55 shipping to Montreal.

![image](https://user-images.githubusercontent.com/507025/111043585-8ae40d80-8400-11eb-9557-278a804f6764.png)

And here's the regular no-mix and match cart with the same selections and same quantities with the same $29.55 flat rate price:

![image](https://user-images.githubusercontent.com/507025/111043616-ae0ebd00-8400-11eb-83b5-35240ecb79d5.png)

So far so good, this is exactly what it _should_ be and what I'd expect given the Mix and Match settings. 

On his live site, outside of the Mix and Match context the same 6 items are showing $29.55 again as expected, but in the Mix and Match context the same items are showing shipping is **$37.60** for the same products! With the Mix and Match settings the way they are... the items should be treated the same as any other line item in the cart and in staging this appears to be correct. 

![image](https://user-images.githubusercontent.com/507025/111043709-368d5d80-8401-11eb-971d-9f30165c3d4c.png)

The staging site was re-created yesterday since I asked him to re-create it after I couldn't reproduce the issue in staging but it exists in live. I've not changed anything in the staging site (And presumably neither has the customer since that's what I suspected the first time around) but I can still see the shipping rates coming back differently in the live site versus the staging site. 

I'm beyond stumped. Does anyone have any idea as to why the shipping rates would come back differently on the live site?

**Comment by bborman22** [comment]
That is odd to be getting those different results! One thing that might be helpful to check is the shipping debug information: https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#section-11

With the debug turned on, the cart will display information about box packing and which rates were retrieved. By comparing the live site and staging site with debug on, it could help determine where the different prices are coming from.

**Comment by helgatheviking** [comment]
hi @bborman22 does the debug info show for every user or admins only? Can you turn it on for the live site without every visitor seeing it? That's the thing that's held me back from turning it on already.

**Comment by bborman22** [comment]
Yes, unfortunately it would display publicly. It should be possible to turn it on, test the cart shipping calculation, then turn it off. It's definitely not ideal, but minimizes exposure while still getting us the information we need as long as the cart page doesn't get refreshed after getting the debug information displayed.

**Comment by helgatheviking** [comment]
As a suggestion... maybe it should only show for store managers and admins?

Here's the result from the staging site. First, for the bundle... which is now showing a different price than it did when I made the above screenshots! 

> Received rate: Priority Mail International ($37.60)
> 
>     Individual packaging
>         (ID: 17821) Terpene Bundle (3 x 2 x 2 in, 1 oz)
> 
> Packing log:
> 
>     These products are individually packed: 17821
> 
> (USPS:5) 

![image](https://user-images.githubusercontent.com/507025/111179430-b1758600-8571-11eb-9490-65bf532df809.png)

But the package rate debug info tells me it's shipping the Bundle as a unit, so I checked the mix and match settings. For this product they are set to "bundled shipping" which would of course result in different packages and shipping costs. But it also means that shipping results match the expectation given the product settings.

That's different from the other day though... so following that down the rabbit hole a little further, I've _finally_ noticed there are actually **TWO** products named "Terpene Bundle" and only 1 of them is configured correctly. 

I don't usually like to poke around in a customer's live site but I may need to at least take a look. He's shown me a screenshot of the settings, but now knowing about the duplicate mix and match product... he could be editing one and looking at the other as I was just doing. 

Here's the shipping data for for the same 2 items individually:

> Received rate: Flat Rate: Priority Mail International ($29.55)
> 
>     Small Flat Rate Box (8.63 x 5.38 x 1.63 in, 1.2 oz)
>         3 x (ID: 16707) Alaskan Thunder Terpene Liquidizer – 1ml (2 x 2.5 x 0.75 in, 0.2 oz)
>         3 x (ID: 17786) Hybrid Strawberries Terpene Liquidizer – 1ml (2 x 2.5 x 0.75 in, 0.2 oz)
> 
> Packing log:
> 
>     # Fitting these product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – large_flat_box (12 x 12 x 5.5 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – medium_flat_box_top (11 x 8.5 x 5.5 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – medium_flat_box_top has better fit than large_flat_box
>     – small_flat_box (8.625 x 5.375 x 1.625 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – small_flat_box has better fit than medium_flat_box_top
>     Winner: small_flat_box with product IDs packed: 16707, 16707, 16707, 17786, 17786, 17786

(USPS:5) 
![image](https://user-images.githubusercontent.com/507025/111179011-488e0e00-8571-11eb-82d8-2239e00ad16f.png)

But for the mix and match product with the recommended settings, we're back to seeing the expected prices...

> Received rate: Flat Rate: Priority Mail International ($29.55)
> 
>     Small Flat Rate Box (8.63 x 5.38 x 1.63 in, 1.2 oz)
>         3 x (ID: 16707) Alaskan Thunder Terpene Liquidizer – 1ml (2 x 2.5 x 0.75 in, 0.2 oz)
>         3 x (ID: 17786) Hybrid Strawberries Terpene Liquidizer – 1ml (2 x 2.5 x 0.75 in, 0.2 oz)
> 
> Packing log:
> 
>     # Fitting these product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – large_flat_box (12 x 12 x 5.5 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – medium_flat_box_top (11 x 8.5 x 5.5 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – medium_flat_box_top has better fit than large_flat_box
>     – small_flat_box (8.625 x 5.375 x 1.625 in) fits product IDs: 16707, 16707, 16707, 17786, 17786, 17786
>     – small_flat_box has better fit than medium_flat_box_top
>     Winner: small_flat_box with product IDs packed: 16707, 16707, 16707, 17786, 17786, 17786
> 
> (USPS:5) 

![image](https://user-images.githubusercontent.com/507025/111182052-2b0e7380-8574-11eb-94c1-f9a4de64668e.png)

-----

So far (again at least on staging) the rates look like they match the settings. I'll see if I can look around on the live site to confirm that this is a face palm issue rather than shipping rates coming back inconsistently. Thanks for letting me air it all out. :)

**Comment by bborman22** [comment]
The two products issue could definitely be the difference. Thanks so much for digging into that to confirm!

**Comment by c-shultz** [comment]
It looks like this has been resolved, so I'm closing it out. We can reopen if this is still relevant!
