### ISSUE TITLE
Determine proper location for service data.

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#238]
In addition to form layout and data schema, some services will have data that will effect what is rendered on the client. For example - predefined boxes for shipping methods.

Currently, the client expects these values in `definitions`, though we've agreed this is not the correct place for such data.

Once a new location is determined, an issue on the server will need to be opened.

**Comment by allendav** [comment]
@nabsul @jeffstieler  - with predefined boxes being removed, is this issue still needed? Or is there anything else we'd like to remove from `definitions`

**Comment by nabsul** [comment]
The list of services also falls under this category, and it's not going away.

**Comment by laurendavissmith** [comment]
Closing pending architectural improvements
