### ISSUE TITLE
Rendering problem with label purchase modal checkboxes

### ISSUE THREAD

**Issue by Ferdev** [Automattic/woocommerce-services#2380]
The `checked` state in the label purchase modal checkboxes is not aligned with the checkbox borders:

https://dl.dropboxusercontent.com/s/dvzq1sqdwy8cumm/shot-2021-03-15-13-58-45.png

**Comment by frosso** [comment]
Looks like we have a duplicate :) https://github.com/Automattic/woocommerce-services/issues/2321

**Comment by Ferdev** [comment]
Sorry @frosso , I wasn't aware of that issue when I created this one. I'll close both issues :+1:

**Comment by frosso** [comment]
No need to be sorry :D Sounds great! Thanks for working on fixing that!
