### ISSUE TITLE
Correct tax not calculated

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-services#2428]
I've got a user in 4026754-zen who is selling from BC Canada and shipping to Alberta. Some of their products are grocery items and are not subject to tax, however, the shipping portion is taxed as a service. Since the latest update, their shipping tax is no longer calculating on these items and I suspect that is due to something that was done to fix #2020 

As near as I can tell, it had been working in the past because they have tax rates configured for shipping to AB. We tell people in the [Troubleshooting](https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#section-3) documentation for similar type cases that:

>If you need to charge tax for any other state, you can add a tax rate for that state in addition to using automated taxes to charge customers from that state tax as well.

So, I guess I expect that rates entered would still work but instead they got blanked out and ignored.

https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/4-3/basic-groceries.html#_Toc155586101
https://sellercentral.amazon.com/forums/t/sales-tax-on-shipping-and-handling-canada/257410/2

**Comment by dustinparker** [comment]
hey @WillBrubaker, I've done some testing from a BC address to an Alberta address and everything appears to work correctly as long as the grocery product has a tax class of "Zero Rate" and a tax status of "Shipping Only". Could you please confirm that the merchant has the following settings on their grocery products:

![screenshot-localhost_8050-2022 05 30-09_23_41](https://user-images.githubusercontent.com/11618203/170939651-37f50a0c-f1f9-4971-8ecf-04f4071a1b9c.png)

If the issue persists, it would be great if we could get the following for further debugging:
1. From address
2. To address
3. Example products including tax class/status settings
4. WC Tax rate table export

**Comment by WillBrubaker** [comment]
From the ticket:

>we have had the all of the products Tax Status set to shipping only,

**Comment by dustinparker** [comment]
I haven't been able to replicate this issue and it seems the tax is correctly being applied to shipping for grocery items (tax status = shipping only). I'll go ahead and close this issue out, but if the issue persists for ticket 4026754-zen please feel free to reopen.
