### ISSUE TITLE
Customs info required for DHLExpress international rates

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2430]
## Description

Originally reported in p1623260566339800-slack-C7U3Y3VMY

User cannot create shipping labels to Puerto Rico.
I can confirm that I am not seeing the DHL Express rates. I also tried a few DHL Express addresses, this seems to be working:
> 1077 AVE ASHFORD, SAN JUAN, 00907-1128, Puerto Rico

In my testing, it seems that the error is that DHL Express requires customs info to have rates returned. We are not displaying the customs info form.
https://github.com/Automattic/woocommerce-services/blob/81126df5a43a156871554087bae3271dad2f1729/client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js is the piece of code that decides whether the customs info form should be submitted.

Once the customs form is available and it has valid values, DHL will return rates.

The check seemed to be ok for USPS shipments, but we should maybe remove it.

**Comment by igotdes** [comment]
Thanks again for looking into this so quickly, @frosso!

I'll just note the user's ticket here too: #4056793-zen
