### ISSUE TITLE
Unable to Print Shipping Label 

### ISSUE THREAD

**Issue by kliff-tech** [Automattic/woocommerce-services#2440]
When i am trying to create shipping label getting an unexpected error occured message.
Is there any resolution to this?

**Comment by frosso** [comment]
Hi @kliff-tech ,

We handle support requests in the plugin's support forum, can you please create a new topic there instead? https://wordpress.org/support/plugin/woocommerce-services/
Please also provide site's URL you're using in the new forum thread.

Have a good one!

Thank you!
