### ISSUE TITLE
Clearer messaging about WooCommerce Taxes' Single Tax Nexus functionality

### ISSUE THREAD

**Issue by dphyled** [Automattic/woocommerce-services#2442]
WooCommerce Taxes handles a single tax nexus, based on the shop's base address. For US-based merchants, this means the Automated Taxes will only calculate taxes for their home state. For most businesses, this meets their needs -- we have more info about this in our documentation here:
https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/#section-4

However, many shop owners are unaware of this, so when customers from other states place orders and taxes are not charged, they think things are broken and reach out to support. A note was added to the Automated Taxes setting tooltip in [this GitHub issue](https://github.com/Automattic/woocommerce-services/issues/2019), however we still get a large number of support requests about this. After some discussion with @c-shultz @dougaitken @rootjosh, @jarekmorawski suggested a new design to make things clearer while merchants are setting up their taxes:
![WooTaxesMessaging](https://user-images.githubusercontent.com/12789821/124063011-dd5b3f80-da6c-11eb-8e55-1b6cd02bba58.png)

This will help ensure they are aware of what to expect up front, along with a link to our docs for more information.

**Comment by dphyled** [comment]
(changed to "Bug" after re-reading our discussion 😅 )

**Comment by frosso** [comment]
This messaging was implemented in https://github.com/Automattic/woocommerce-services/pull/2484

Unfortunately, the UI doesn't match because the styling capabilities for the section are very limited and cannot vary too much from the "default" WooCommerce styles.
