### ISSUE TITLE
Fix E2E tests

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2454]
E2E tests stopped running by the time commit b868d4d792c9f04fa4e230b6cdb692d520a9939a was pushed. 36ec834b28c7625a6644508fb1d6d2ea62b1bc52 is the last commit that had working tests.

The issue was caused by the GitHub action being stuck as the `npm run docker:ping` script. It seems the script is checking if a page with slug `ready` exists and it doesn't because WP installation fails.

I did some digging and [thought that updating](https://github.com/Automattic/woocommerce-services/pull/2449) `@woocommerce/e2e-environment` from 0.2.0 to 0.2.2 has resolved this but it hasn't.

Then I found that [updating `WP_VERSION` used by the tests](https://github.com/Automattic/woocommerce-services/pull/2450) resolves this and while it does allow the `npm run docker:ping` script to pass somehow, it actually doesn't resolve the issue - [the E2E tests now run, but fail](https://github.com/Automattic/woocommerce-services/runs/3019262091?check_suite_focus=true).

Here is some more information on why the `npm run docker:ping` job is there courtesy of @harriswong: p1616021602049200/1615928526.043400-slack-CU6SYV31A

**Comment by waclawjacek** [comment]
I have received some pointers on Slack from @rrennick: p1625752183439400-slack-C01BWDDTGKX

**Comment by waclawjacek** [comment]
Some other ideas shared with me/links that might help:

- Try running the tests in non-headless mode.
- https://solarisp2.wordpress.com/2021/03/11/e2e-container-error-with-wordpress-5-7/
- https://make.wordpress.org/core/2021/02/16/login-registration-screens-changes-in-wordpress-5-7/

**Comment by frosso** [comment]
Fixes here: https://github.com/Automattic/woocommerce-services/pull/2467
