### ISSUE TITLE
Media Mail Option - Missing / Disappeared?

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-services#2472]
Hello Team 👋 

Media Mail is currently not a shipping option that we can choose.

Steps to replicate:

1. Configure [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038)
2. Note that you'll not find Media Mail as an option while attempting to print shipping label

---

I reached out via p1631159483216100-slack-C7U3Y3VMY where @tommyshellberg  could replicate the issue too, and was recommended to move this here for further troubleshooting.

**Customer  Report**

> I don’t see Media Mail as an option for shipping. I know it was in the past but I don’t see it under this new user account. How do I make that an option for myself again?

4251417-zen

**Comment by frosso** [comment]
I've been testing this on both staging and production.
I can confirm that Media Mail is still present - example:
![Screen Shot 2021-09-14 at 3 49 43 PM](https://user-images.githubusercontent.com/273592/133331865-769de5dd-8b30-44b4-aadc-2e0b6959d272.png)


Please note that Media Mail is not eligible for all shipping destinations, it also includes some restrictions on size and weight.
Also, make sure that the selected package type is not a restricted "service" package (i.e.: a "Small Flat Rate Box" will not display Media Mail rates)
I can't find the dimensions used in the original ticket - however, these are the eligibility rules: https://pe.usps.com/text/dmm300/173.htm#ep1113500


Closing this for now, but feel free to reopen in case there are new developments.

**Comment by AashikP** [comment]
@frosso  Thank you for checking. The Follow-up question is, shouldn't we also see them as one of the packaging options? We're looking at the shipping rate section on your screenshot.

**Comment by frosso** [comment]
@AashikP my apologies, can you please clarify?

USPS Media Mail is present in the "shipping rates" section of the screenshot as the second (selected) option.

Media Mail doesn't have any preset boxes, the merchant would need to create a custom box/envelope with their dimensions through the UI.
![Screen Shot 2021-09-20 at 12 47 44 PM](https://user-images.githubusercontent.com/273592/134049654-2e78e021-e054-4907-b350-c7e70cba3733.png)

Please let me know if I'm missing anything!

**Comment by tbarlow03** [comment]
Thank you for the help with this. I was able to finally get it working by creating and adding the custom package. After that was created and I could select it when shipping I was able to see the Media Mail option for shipping. Thank you!

**Comment by AashikP** [comment]
> Media Mail doesn't have any preset boxes, the merchant would need to create a custom box/envelope with their dimensions through the UI.

My bad. Thank you for clarifying, @frosso  👍
