### ISSUE TITLE
Currency compatibility with WooCommerce Payments

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2474]
## Description

I noticed that when the multi-currency functionality of WooCommerce Payments is enabled with a currency !== USD, the shipping purchase flow is failing, saying that only USD is accepted.

## Steps to reproduce
- Install WC Shipping & Tax
- Ensure your store's location is in the US, store's currency is USD
- Install & Configure WooCommerce Payments
- In WC Pay, "Enable the new WooCommerce Payments checkout experience" at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=woocommerce_payments`
![Screen Shot 2021-10-05 at 11 22 59 AM](https://user-images.githubusercontent.com/273592/136063361-bce95eb2-d845-431d-a7d0-38e2aa678879.png)
- In WooCommerce Payments, add some EU payment methods for the checkout
![Screen Shot 2021-10-05 at 11 22 29 AM](https://user-images.githubusercontent.com/273592/136063293-4dc08071-2edc-4fa3-bb40-cf7b3a65e5be.png)
- Go to `/wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`, ensure that the multi-currency has USD and EUR, with default to USD
![Screen Shot 2021-10-05 at 11 24 39 AM](https://user-images.githubusercontent.com/273592/136063626-94b21430-c5ca-4219-8ced-dd7b51975995.png)
- Place an order on the frontend
- Order can ship US>US or US>EU
- Go to the backend, to fulfill the order via WooCommerce Services and print a label
- After selecting a shipping rate and paying, the error message appears
![Screen Shot 2021-10-05 at 9 18 15 AM](https://user-images.githubusercontent.com/273592/136041533-037795a0-1145-4bc0-8418-307875fcf85e.png)

**Comment by bborman22** [comment]
I haven't been able to reproduce this with the latest WCS&T trunk and WooCommerce Payments 3.0. I set up the latest WCPay and turned on the currency switcher widget. I went through a checkout flow using Euros and then purchased the shipping label for the order and it seemed to all work.

 I was wondering if there were more details to reproduce and/or perhaps a WCPay update fixed the issue?

**Comment by frosso** [comment]
@bborman22 thanks for checking on this!
Unfortunately, I can still reproduce this, with WCPay 3.0.0 and WCS 1.25.18. Disabling WCPay makes the problem go away:
![Screen Shot 2021-10-05 at 9 18 15 AM](https://user-images.githubusercontent.com/273592/136041533-037795a0-1145-4bc0-8418-307875fcf85e.png)

These are my currency settings:
![Screen Shot 2021-10-05 at 9 20 27 AM](https://user-images.githubusercontent.com/273592/136041753-54654bd4-d191-41c5-8176-44e7f5092325.png)

The order is shipped from US to Italy. I also tested US > US with an order placed in EUR and another order placed in USD, the problem still persists in my case.

**Comment by iyut** [comment]
Hi @frosso , 

I seems cannot replicate the issue with WC Payments 3.1.0 and WCS&T 1.25.18. This is how I created the order using EUR currency : 
![screenshot-localhost_8050-2021 10 13-17_35_15](https://user-images.githubusercontent.com/631098/137117912-9c100f76-8f81-4ab8-9fc5-b528c9b1ef37.png)

These are my multi-currency settings : 
![screenshot-localhost_8050-2021 10 13-17_36_10](https://user-images.githubusercontent.com/631098/137118042-c1735940-f247-4740-af73-59a9b377493b.png)

These are the screenshots when creating the shipping label : 
![screenshot-localhost_8050-2021 10 13-17_37_16](https://user-images.githubusercontent.com/631098/137118140-fbf845f9-1443-4450-8d5a-02fc823a9f64.png)

The shipping label is successfully created : 
![screenshot-localhost_8050-2021 10 13-17_38_16](https://user-images.githubusercontent.com/631098/137118229-79d9181a-6462-4bd1-a76e-1e5a4a88f011.png)

Can you confirm if you still have an issue after updating WC Payments plugin to 3.1.0 ?

**Comment by frosso** [comment]
I haven't been able to reproduce this on a brand new site either - I tried on a couple of brand new sites with no luck.
However, I can still consistently reproduce this issue on my original site:
- Currency: https://d.pr/i/nvXCmJ
- Multi-currency: https://d.pr/i/IKQ8aM
- Error:https://d.pr/i/WX6R2k

I'm not sure what can be the cause of this issue. In any case, additional steps to reproduce are needed.

I'm going to close this, we can either re-open it or open a new ticket when (and if) we have more details on how to reproduce 👍
