### ISSUE TITLE
Default Shipping Option Changes on iPhones Only

### ISSUE THREAD

**Issue by cre8tivediva** [Automattic/woocommerce-services#2495]
Priority Mail is the default shipping. On iOS devices, the default shipping is **switching** to Local PU. I've had two other developers test this with me. It happens to one and not the other. We're using California as an address and the same product for testing. Is this a bug? Priority Mail should just be the default no matter what and someone would need to manually select Local Pickup. We cannot see why it's switching. Is this behavior a bug? (If this is not the proper place for this inquiry, please remove it.)

[Screenshot](https://snipboard.io/2SseNj.jpg)

**Comment by dustinparker** [comment]
Hi @cre8tivediva, could you please try deleting the Local Pickup method from the shipping zone by following the steps in this screenshot:

![screenshot-localhost_8050-2021 12 02-15_11_59](https://user-images.githubusercontent.com/11618203/144438676-470dfba1-1ceb-410b-a6cd-7a07f5eca1f1.png)

Then please add the Local Pickup method back to the shipping zone and save again. This should change the default checked method.

**Comment by dustinparker** [comment]
Hi @cre8tivediva, I've been trying to replicate the issue on iPhone and haven't been able to do so yet. USPS Priority is selected by default as long is it has the highest priority in the shipping method list for the shipping zone. Could you please send me some screenshots of the shipping zone settings as well as the USPS method settings so I can try to replicate? Thank you!

**Comment by dustinparker** [comment]
Hi all, as we weren't able to replicate the issue and haven't heard anything in a while, we'd like to go ahead and close this issue out. Please feel free to reopen if needed.
