### ISSUE TITLE
Create Support FAQ

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#25]
cc @mikeyarce - could you prime this issue with a few questions you think merchants and developers/agencies would have?  Anything goes.

cc @samhotchkiss too :)

**Comment by allendav** [comment]
Let's also add:

* What currency, weight and dimension settings does the USPS (Powered by WooCommerce Connect) shipping method support?
* What currency, weight and dimension settings does the Canada Post (Powered by WooCommerce Connect) shipping method support?

**Comment by californiakat** [comment]
@allendav Added to my To Do list

**Comment by jeffstieler** [comment]
Closing - https://docs.woocommerce.com/document/woocommerce-connect-faq/ exists. :D
