### ISSUE TITLE
Fix broken DHL T&C link in docs

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2500]
The DHL T&C link in [the "How do I submit an insurance claim for lost or damaged shipments?" section of the docs](https://woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#section-38) is broken.

![Markup on 2021-11-08 at 20:12:01](https://user-images.githubusercontent.com/1759681/140803141-4f9e2ef6-2e75-44f0-9ac5-3970d014602f.png)

**Comment by waclawjacek** [comment]
Clicking other links to the DHL T&C in that documentation page, I noticed some of them redirect to https://mydhl.express.dhl/us/en/legal.html where the T&C seem to be now:

![Markup on 2021-11-08 at 21:27:06](https://user-images.githubusercontent.com/1759681/140814026-93c26339-9476-44c1-bd3a-64f103ba5abf.png)

Although the T&C open in a modal now, right-clicking this section and selecting "Copy Link" reveals this link: https://mydhl.express.dhl/us/en/legal/terms-and-conditions.html

**Comment by frosso** [comment]
I don't have edit access.
[Reported to Team Fire](11788-gh-Automattic/woocommerce.com), following these steps: p6JqRr-4NX-p2
