### ISSUE TITLE
USPS labels no longer scale correctly

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2505]
## Description
After the update in https://github.com/Automattic/woocommerce-services/issues/2256, user reports to have a bigger sized labels that would cut off during print. The only way to print correctly is to set scale to “fit to printable area” or “fit to paper.”

Forum post: https://wordpress.org/support/topic/usps-labels-no-longer-scale-correctly/

## Expected behaviour
- The issue described here https://github.com/Automattic/woocommerce-services/issues/2256 is resolved
- User does not need to manually adjust scale everytime.

**Comment by drwpcom** [comment]
Also in 4533104-zen

**Comment by senff** [comment]
4466572-zen

**Comment by shaunkuschel** [comment]
4466916-zen

**Comment by melek** [comment]
4537332-zen

**Comment by darcie** [comment]
4559225-zen

**Comment by nagpai** [comment]
4558449-zen

**Comment by nagpai** [comment]
I have set the priority as high, @harriswong  since there seem to be quite a few users affected. Feel free to revise it if needed.

**Comment by harriswong** [comment]
The background of this is that fixing the blurry issue (https://github.com/Automattic/woocommerce-services/issues/2256) bumped up the dimensions here. 
I had a chat with @dustinparker regarding this. We tried to address this by changing the dpi directly (72->300) instead of scaling the dimensions. But it leads to some other issues (page cut off, etc) @dustinparker can add to this.

I think we are left with 2 immediate solutions. 
1. rollback but we will re-open the blurry problem here https://github.com/Automattic/woocommerce-services/issues/2256. The original author there didn't reply so we can't confirm if this fixed their issue or not. Rolling back may be okay?
2. We close this and update the documentation page to say that “fit to printable area” or “fit to paper” is the new way to go.

@dustinparker, thoughts?

**Comment by dustinparker** [comment]
@harriswong, it's hard to say because I am fairly certain the DPI change will fix the blurry issues, but we haven't been able to get confirmation from the merchants that had experienced that issue. Since the workaround for this scaling issue is pretty simple (just clicking on "fit to printable" on the browser's print modal), I would lean toward leaving the DPI change and just adding documentation.

**Comment by harriswong** [comment]
There are some replies in the forum thread https://wordpress.org/support/topic/usps-labels-no-longer-scale-correctly/ . Do we need to set both dimensions (scale up by *300/72) and dpi (the config setting) to 300 to fix the issue?

**Comment by harriswong** [comment]
Another note, I was just checking how shipstation handle this. https://help.shipstation.com/hc/en-us/articles/360025853212-Labels-Print-Too-Big-or-Too-Small#adjust-printer-preferences-windows--0-1. It looks like zebra has different DPI settings? In the screenshot there, it seems to be 203 dpi.

**Comment by dustinparker** [comment]
> There are some replies in the forum thread https://wordpress.org/support/topic/usps-labels-no-longer-scale-correctly/ . Do we need to set both dimensions (scale up by *300/72) and dpi (the config setting) to 300 to fix the issue?

Yes, this is already the case. The paper sizes are all scaled by the new DPI of 300 as well. The paper sizes have to use the same DPI otherwise the PDF would be cut-off even when you select fit to printable. That is interesting that one person said it was blurry for them even with the changes. It would be nice to know what printer they were using and what settings.

> Another note, I was just checking how shipstation handle this. https://help.shipstation.com/hc/en-us/articles/360025853212-Labels-Print-Too-Big-or-Too-Small#adjust-printer-preferences-windows--0-1. It looks like zebra has different DPI settings? In the screenshot there, it seems to be 203 dpi.

The 300 DPI should work fine for printers with lower DPI settings because scaling down to fit the printable area is not a problem. It's when the provided DPI is less than what the printer requires that the blurry label issue happens. If the zebra printers can be set to 72 DPI (which may be the case based on that screenshot), that should also fix the problem, then we wouldn't need to change the DPI for everyone else.

**Comment by nicholasjeberlin** [comment]
22248278-hc

**Comment by jrick1229** [comment]
4564667-zen

**Comment by martynmjones** [comment]
4604120-zen

**Comment by waclawjacek** [comment]
Can we get someone with an actual label printer to test out both 72 DPI and 300 DPI?

**Comment by waclawjacek** [comment]
I have looked into this and discovered the following:

In all tests the paper size is set to Legal. I think this issue doesn't happen on all paper sizes but it does on this one.

**Printing on Chrome**

![Chrome Production](https://user-images.githubusercontent.com/1759681/146391802-8936167f-d788-4a0a-893e-c84db9609ccc.png)

**Printing on Firefox**

![Firefox Production](https://user-images.githubusercontent.com/1759681/146391817-5bba680e-757c-4509-ad7c-f5bc5915fe2c.png)

Posted a PR to revert this for now: 1874-gh-Automattic/woocommerce-connect-server

**Comment by harriswong** [comment]
Should we also respond to the forum (https://github.com/Automattic/woocommerce-services/issues/2505#issuecomment-984831461) so that they know this is reverted? The authors probably need to undo the work-around they did.

**Comment by waclawjacek** [comment]
We should post an update there but I don't think reverting this will disrupt the workarounds in the forum thread - it looks like one was to set the page size to "Fit" and another was to open PDFs in Adobe's client.

**Comment by phillipcornwell** [comment]
33003534-hc
4618695-zd

**Comment by waclawjacek** [comment]
A fix has just been deployed on the Connect Server so merchants should not experience this issue anymore. We will be working to resolve the blurry printouts on Zebra printer issue but in the meantime, label printing should be back to the previous state.
