### ISSUE TITLE
Invalid address - "Name" is required even when it is present

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2511]
## Description

When validating the origin address, the message "We were unable to automatically verify the address — Name is required." could appear even when the "name" is already filled.
![Screen Shot 2021-12-02 at 2 47 54 PM](https://user-images.githubusercontent.com/273592/144500706-e26b2a79-051a-471e-86fb-846fb9a130a4.png)

It looks like in https://github.com/Automattic/woocommerce-services/blob/a0b068d3124dc661c48cbdaf29e0f2f7ad8fc125/classes/class-wc-rest-connect-address-normalization-controller.php#L16-L25 we are stripping out the `name` field from the validation - maybe that's related?

## Steps to reproduce
- Go to the order's page
- Click "Create new label" to open the modal
- In the "Origin" address, enter ` ` (space) on the "name" field
- Click "Verify address"
- Click "Edit address" again, to edit the address
- Fill in the details of the "Name" field with "Test Tester"
- Click "Verify address" again
- The message "We were unable to automatically verify the address — Name is required." appears, even tho the "name" field is populated

**Comment by frosso** [comment]
After looking into it a bit more, it looks like the issue might be on the connect server side of things.

**Comment by frosso** [comment]
Reported on:
- https://wordpress.org/support/topic/address-verification-issue-name-is-required-error/
- 26275371-hc
- 30835613-hc

**Comment by darcie** [comment]
4564218-zen

**Comment by mouligreenlaw** [comment]
4565191-zen

**Comment by solstudioim** [comment]
32150771-HC

**Comment by ldr2273** [comment]
4564319-zen

**Comment by nagpai** [comment]
30489971-zen

**Comment by c-shultz** [comment]
We're looking to create a short term fix for this by reverting some API server changes. This should resolve the immediate issue.

**Comment by frosso** [comment]
The fix has been released on the server side, no plugin update is necessary.

The issue still persists in the server's staging environment, but won't affect merchants.

**Comment by nicholasjeberlin** [comment]
22248278-hc

**Comment by wpniall** [comment]
4566495-zen

**Comment by thracefulton** [comment]
4566938-zen

**Comment by felipevelzani** [comment]
4567062-zen

**Comment by csmcneill** [comment]
4564300-zen

**Comment by waclawjacek** [comment]
It seems that there were some support tickets created after the server-side fix was deployed. @frosso, do you have any idea why this might have been the case?

**Comment by frosso** [comment]
@waclawjacek I'm not 100% sure, but looking at the dates on the tickets it seems they were created when the issue was present (and reported later)?

**Comment by waclawjacek** [comment]
Awesome, thank you! I am marking this ticket as high priority rather than critical as the changes have been reverted.
