### ISSUE TITLE
Tax rates for Kenai, Alaska, USA are above maximum tax rate limits

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-services#2518]
### Issue

Tax rates in Kenai, Alaska, USA, are limited in a unique way. Customers are charged on the first $500 of a purchase or $15.00. When using WooCommerce Tax, the tax applies to the whole purchase, and customers in Kenai are charged higher than the limit.

Additionally, the tax rate should be 3%.

### Expected Results

Customers charged tax in Kenai, Alaska, are only charged a 3% on the first $500 of a purchase or $15.00.

### Actual Results

Customers are charged a 6% tax rate, and they are charged more than these ceiling amounts.

### Screenshots

<img width="407" alt="Markup 2022-01-14 at 12 00 28" src="https://user-images.githubusercontent.com/82999806/149827410-c73e769d-e686-4970-9fec-c8c37e05c734.png">

<img width="473" alt="Screenshot on 2022-01-14 at 12-21-14" src="https://user-images.githubusercontent.com/82999806/149827419-85813430-1bde-4e11-acaf-261f2cfb781a.png">

### Documents

- [PDF on Droplr](https://d.pr/f/Qgw25G)
- [PDF on kpb.us](https://www.kpb.us/component/easyfolderlistingpro/?view=download&format=raw&data=eNpNT0sOgjAQvUsvXDCoQR12LkiMidHovhlhgMbySVuUxHh3ByvBVWde328QogheFmIQRatzMlwisbAKQagaS7LB4bQL0v0xuKAmK684zJNMW1Pbkc8WordkvIOHQITTV9mTdbP7GoSUX2zcNl7aYE3jysnjE3tU5VwiURB6kSHdoav-WKwtlKZJu-Csud25V9ldppi5b6ElCBrcb-ry4teEhk4ZslNMxM7oHGZVTQ2zbxAxumWFoYeip7-A25VtW2pOfX9cMFYjZk4)

### Links

Conversation on Slack: p1642439875075700/1642191706.036600-slack-C7U3Y3VMY
Ticket: 4678136-zd-woothemes

**Comment by bbrink-MN** [comment]
To clarify, WooCommerce automated taxes uses 3% as it should, but only if the customer enters in full 9 digit zip code. This is the way it must be, as parts of the 5 digit zip are in the city and subject to different rate.

**Comment by superdav42** [comment]
We recieved a response from TaxJar:

> We are aware of the maximum sales tax amount of $500 for Kenai, as noted here, in section 5.18.100. Unfortunately, this tax rule is not yet supported by TaxJar.
> In this scenario, adjusting the amount of sales tax that you collect from these customers manually (i.e., issue a refund of the over-collected sales tax). 
> Although, we don't yet support the max tax in Kenai at this point, I really appreciate you taking the time to reach out to us about this. Additionally, I have added you to a list of customers requesting support for this.
> I can't promise that this is something we'd add (or that support for this is on our immediate roadmap), but we are always listening to customer feedback and many of our new features are driven by customer requests. We will definitely let you know if we have an update about this in the future!

Unfortunately I think this means there's nothing we can do from the WCS&T plugin. If TaxJar ever implements support for these It will probably just start working automatically. 

I'm going to close this issue but feel free to open it if there's new information.
