### ISSUE TITLE
Auto-trigger of print dialog is an issue

### ISSUE THREAD

**Issue by King-Rings** [Automattic/woocommerce-services#2528]
The most recent version of WooCommerce plugin (6.2.0) introduced an annoying glitch while purchasing and printing shipping labels. It looks to me like the devs were trying to improve a feature but missed the mark. I'd like to provide some end-user feedback on how this change effects my UX in the browser of my choice. Please see screen recording at [https://kingrings.com/downloads/PrintDialogIssue.mp4](https://kingrings.com/downloads/PrintDialogIssue.mp4)

**Comment by csmcneill** [comment]
We may have a similar issue in 4799644-zen where the merchant cannot print directly from their browser—instead, they have to send the label to a different program, and then print their label from there.

**Comment by rashedripon** [comment]
4819851-zen reported the same. Print didn't work on Chrome. Firefox works but first the label needs to be saved as a PDF.
