### ISSUE TITLE
Better error when auth fails

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-services#253]
We need a better error on the client side when authentication with the server fails

**Comment by jkudish** [comment]
Assigning to Kelly to get some design here

**Comment by kellychoffman** [comment]
Can we take advantage of the global notices as mentioned in https://github.com/Automattic/woocommerce-connect-client/issues/322 ?

<img width="915" alt="screen shot 2016-05-16 at 8 46 31 pm" src="https://cloud.githubusercontent.com/assets/5835847/15309804/5003200a-1ba7-11e6-808f-e245ed0243bc.png">

**Comment by kellychoffman** [comment]
On further thought, this might look 👎 in non-wcc pages. Lets stick with regular ol' wp-admin notices and link to the self help dashboard / health page.

**Comment by v18** [comment]
@jeffstieler - I think this issue can be closed since we now do display an error when communication with the server fails.

**Comment by jeffstieler** [comment]
Thanks for circling back @v18 - let's take care of this as part of the larger "user facing errors" effort.
