### ISSUE TITLE
BUG: TAX: Florida sales tax on shipping if NO local delivery is available.

### ISSUE THREAD

**Issue by sverleis** [Automattic/woocommerce-services#2531]
We have [a forum user](https://wordpress.org/support/topic/tax-shipping-cost-in-florida/#post-15422906) who's nexus is in Florida. For shipping, tax should be added if there is **no option given** to pick up locally. Automated taxes always defaults to no shipping tax. 

>Delivery charges are not subject to tax when the charge is separately stated on an invoice or bill of sale **and** the purchaser has the option of picking the item up or arranging for third-party  #transportation services on its own.
https://wordpress.org/support/topic/tax-shipping-cost-in-florida/#post-15422906

Is there a way of allowing this specification into the automated taxes?

**Comment by dustinparker** [comment]
Hi @sverleis, unfortunately there is no way to do this via the admin settings.

I did some digging to see if there are any filters the merchant could use to override the TaxJar response before it's added to the database, but there are none. We'd have to add a special handling case for Florida to add the shipping tax to TaxJar's rates in the case where "local pickup" isn't an option.

**Comment by dustinparker** [comment]
Hey @sverleis, just wanted to let you know we've created a fix for this which will hopefully be available in the next release.
