### ISSUE TITLE
Remove `colors` package

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2536]
## Description
Background: p6jPRI-5cd-p2

Some time ago, the author of some popular npm packages [Marak](https://href.li/?https://www.npmjs.com/~marak) decided to delete some packages they authored. To prevent future incidents, let's see if we can find an alternative.

It looks like this package is only used in the `tasks/release.js` task.
Maybe it can be as simple as finding an alternative package or just duplicating the `colors.cyan`/`colors.green`/`colors.red` wrappers behavior.

**Comment by bartech** [comment]
Resolved in #2566
