### ISSUE TITLE
Investigate issues related to taxed vs. untaxed shipping based on cart items.

### ISSUE THREAD

**Issue by brettshumaker** [Automattic/woocommerce-services#2544]
It seems there are at least a few open issues related to errors in how shipping is taxed (or not) based on cart contents and various states' rules about tax on shipping services.

There was a recent report that if the user's store is based in PA, the cart contains a non-taxable product, and the customer is shipping to PA, there is tax incorrectly charged for shipping. [Pennsylvania law](https://www.taxjar.com/blog/retail/shipping-pennsylvania-taxable) states that shipping should only be taxed if _any_ of the cart contents are also taxable.

Possible related issues:
#2428 
#1226
And it looks like this desired behavior was added in #2424 but I'm not sure if something else has changed in the codebase to cause a regression, or if that fix didn't quite fix all of the edge cases here.

cc @harriswong

**Comment by JSdesigNerd** [comment]
More specifically it appears (as of 4/21/22) based on link I will provide that if a checkout contains taxable and tax-exempt items that sales tax should be provided proportionally to those taxable items. So if 65% of the order total is taxable, 65% of the shipping will also be taxable. My understanding is that is applied by cost, not weight or other factor. 

Here is a link to the PA DOR website - [link](https://revenue-pa.custhelp.com/app/answers/detail/a_id/214/~/are-shipping-and%2For-handling-charges-subject-to-sales-tax%3F)

Currently, in our cart, sales tax is being applied to all shipping within PA even though the website is exclusively tax-exempt goods.

The text from the page reads as follows: 
**Are shipping and/or handling charges subject to Sales Tax?
If multiple items are shipped on a single invoice, the shipping and handling charge must be proportionately allocated to each item ordered subjecting the shipping and handling charges of taxable items to Pennsylvania Sales Tax and excluding Sales Tax on the shipping and handling charges attributable to exempt purchases. If no breakout is provided, the entire shipping and handling charges are subject to Pennsylvania Sales Tax.**

**Comment by csmcneill** [comment]
This issue is also occurring with some ZIP codes in Washington state.

Identified in 4965394-zen

**Comment by iyut** [comment]
Hi @csmcneill , does the Washington state have the same shipping tax rule as Pennsylvania? The reason I ask is because I don't have the access to 4965394-zen.

**Comment by iyut** [comment]
Hi @brettshumaker  @JSdesigNerd @csmcneill, I have created a potential fix for the issue in this [PR](https://github.com/Automattic/woocommerce-services/pull/2546). Can someone on your end review and test the PR to confirm we fixed the issue? We have already done an internal review but we figured it would be a good idea to have another pair of eyes on this one.

**Comment by JSdesigNerd** [comment]
Hello @iyut - appreciate the work. I am unfamiliar with the process of testing a "PR" but would do anything I can to help out and be a part of the solution. If you can point me in the right direction I may be able to to review it though I have no dev sandbox per sé for this website. If I can be of assistance please let me know and thank you for working to solve this.

**Comment by JSdesigNerd** [comment]
Please forgive my lack of github dev fluency but I'm not sure if I'm expected to be doing anything to move this forward or if simply keeping an eye on it is enough. Please let me know if there is anything I can do to assist.

**Comment by drwpcom** [comment]
> Please forgive my lack of github dev fluency but I'm not sure if I'm expected to be doing anything to move this forward or if simply keeping an eye on it is enough. Please let me know if there is anything I can do to assist.

@JSdesigNerd You can ignore this ping and we'll do some testing internally.

**Comment by csmcneill** [comment]
Howdy @iyut! I tested this on my end and it looks good!
