### ISSUE TITLE
Notice: Undefined index: `from_country` in `class-wc-connect-taxjar-integration.php:1187`

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-services#2547]
## Description

The issue seems to be happening at checkout since the last update on v1.25.27.
Possibly related to changes in https://github.com/Automattic/woocommerce-services/pull/2545

Report: https://wordpress.org/support/topic/error-message-showing-on-checkout-page-since-last-update/

**Comment by recyborg** [comment]
Hi im the one experiencing problem with this. Also noticed that it loads forever now when changing shipping option on the checkout page. Thanks

**Comment by iyut** [comment]
Hi @recyborg , can I confirm that the issue exists when shipping address is set to Quebec, Canada?
