### ISSUE TITLE
Tax configuration leads to excessive price precision for line_items in Orders REST response with coupons 

### ISSUE THREAD

**Issue by joshheald** [Automattic/woocommerce-services#2550]
## Description
Under particular tax configurations, in combination with a coupon, the `line_items` in the `/orders/` and `/orders/{id}/` responses have excessively precision on fields such as `price`. This has led to issues refunding orders based on these values, as often they are slightly higher than the order total.

These fields are more currency-like when the settings are different, or when no coupon is applied to the order. The fields that are affected are:

* line_items.taxes.total
* line_items.taxes.subtotal
* line_items.price

Note that the tax total and subtotal are always at least one place more precise than USD.

## Impact

The impact of this on Woo Mobile app users is that orders cannot be refunded in full if they include a coupon discount and these tax settings.

The refunds fail because the apps use the totals from `line_items.price` to build the amount for a refund, and in this scenario the sum will be slightly over the total for the order, which fails the refund API validation. I will also log issues in the apps to have more resilient use of this endpoint.

For full context, see p91TBi-8K2-p2.

## Repro steps:
1. Configure a store with a non-automated catch-all tax rate. I used 2%.
2. Set `Prices entered with tax` to `Yes, I will enter prices inclusive of tax`.
3. Place an order including a `Fixed cart discount` coupon for some amount. I tried with $0.20, $1, and $1.55.
4. Fetch the order from the REST API
5. Observe the fields in the list above for precision.

N.B. Previously I thought that the `Display Prices in Shop` setting was responsible, but while verifying today that seemed not to be the case. It could be to do with the interplay between these two settings, but I can't reproduce that. If you're having difficulty verifying, changing these too and fro may help. I have verified on multiple test sites though.

![tax settings](https://user-images.githubusercontent.com/2472348/168777399-42072860-73c9-485b-b19c-523c95fa307e.jpg)

### With $0.20 coupon

```
{
...
  "line_items": [
    {
      "id": 709,
      "name": "Beanie",
      "product_id": 16,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "subtotal": "17.65",
      "subtotal_tax": "0.35",
      "total": "17.45",
      "total_tax": "0.35",
      "taxes": [
        {
          "id": 2,
          "total": "0.34902",
          "subtotal": "0.352941"
        }
      ],
      "meta_data": [],
      "sku": "woo-beanie",
      "price": 17.45098,
      "parent_name": null
    }
  ],
  "tax_lines": [
    {
      "id": 711,
      "rate_code": "TAX-1",
      "rate_id": 2,
      "label": "Tax",
      "compound": false,
      "tax_total": "0.35",
      "shipping_tax_total": "0.30",
      "rate_percent": 2,
      "meta_data": []
    }
  ]
...
}
```

### Without coupon

```
{
...
  "line_items": [
    {
      "id": 724,
      "name": "Beanie",
      "product_id": 16,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "subtotal": "17.65",
      "subtotal_tax": "0.35",
      "total": "17.65",
      "total_tax": "0.35",
      "taxes": [
        {
          "id": 2,
          "total": "0.353",
          "subtotal": "0.353"
        }
      ],
      "meta_data": [],
      "sku": "woo-beanie",
      "price": 17.65,
      "parent_name": null
    }
  ],
  "tax_lines": [
    {
      "id": 725,
      "rate_code": "TAX-1",
      "rate_id": 2,
      "label": "Tax",
      "compound": false,
      "tax_total": "0.35",
      "shipping_tax_total": "0.00",
      "rate_percent": 2,
      "meta_data": []
    }
  ]
...
}
```

### With item price reduction by $0.20 to match coupon

```
{
...
  "line_items": [
    {
      "id": 746,
      "name": "Beanie but a bit cheaper",
      "product_id": 418,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "subtotal": "17.45",
      "subtotal_tax": "0.35",
      "total": "17.45",
      "total_tax": "0.35",
      "taxes": [
        {
          "id": 2,
          "total": "0.349",
          "subtotal": "0.349"
        }
      ],
      "meta_data": [],
      "sku": "woo-beanie-1",
      "price": 17.45,
      "parent_name": null
    }
  ],
  "tax_lines": [
    {
      "id": 747,
      "rate_code": "TAX-1",
      "rate_id": 2,
      "label": "Tax",
      "compound": false,
      "tax_total": "0.35",
      "shipping_tax_total": "0.00",
      "rate_percent": 2,
      "meta_data": []
    }
  ]
...
}
```

**Comment by dustinparker** [comment]
Hi @joshheald,

I did some digging into this issue. I tested with WC Shipping & Tax, but also tested with just WooCommerce and am getting the same results. The issue appears to be a rounding issue coming from the WooCommerce plugin itself when calculating the cart totals. Could you please copy the issue details you provided into a new issue (assuming there isn't already an open issue on this topic) in the WooCommerce plugin repo so their team can look into this?

As this issue isn't coming from WC Shipping & Tax, I'll go ahead and close this out.
