### ISSUE TITLE
Priority Mail Rates Not Returned.

### ISSUE THREAD

**Issue by briancwelch** [Automattic/woocommerce-services#2569]
Stopped returning rates on July 10th.

**Comment by nicholasjeberlin** [comment]
Hi @briancwelch,

This issue should have been resolved by the latest update to the WooCommerce Connect Server (Issue 1947/Fix 1948 for internal reference).

Can you please verify that rates are being returned now?

**Comment by briancwelch** [comment]
Hey @nicholasjeberlin.  Checked at 8:30AM PST and can confirm rates are being returned again.  I apologize if I've wasted any of your time.

**Comment by nicholasjeberlin** [comment]
Hi @briancwelch, 

Glad to hear it's working for you again! No time wasted. We appreciate the report! :)
