### ISSUE TITLE
E2E tests failed to run 

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2590]
### Description

It looks like the `Run npm run test:e2e-docker-up` ran fine and the containers are up in the log. But the ping check failed. Blocking pipeline to merge.

https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:56
```
Run npm run test:e2e-docker-ping

> woocommerce-services@1.26.3 test:e2e-docker-ping /home/runner/work/woocommerce-services/woocommerce-services
> bash ./tests/bin/wait-for-e2e-build.sh

Testing URL: http://localhost:8084

Thu Nov  3 18:23:2[7](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:8) UTC 2022 - Docker container is still being built
Thu Nov  3 1[8](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:9):23:38 UTC 2022 - Docker container is still being built
Thu Nov  3 18:23:48 UTC 2022 - Docker container is still being built
Thu Nov  3 18:23:58 UTC 2022 - Docker container is still being built
Thu Nov  3 18:24:08 UTC 2022 - Docker container is still being built
Thu Nov  3 [18](https://github.com/Automattic/woocommerce-services/actions/runs/3381059588/jobs/5630020528#step:8:19):24:18 UTC 2022 - Docker container is still being built
```

**Comment by dustinparker** [comment]
While looking into possible causes, this came up:

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

It looks like Calypso is using Node 16.17.0: https://github.com/Automattic/wp-calypso/blob/trunk/.nvmrc

Maybe we need to look into updating WC Services to the Node version Calypso is using?

**Comment by harriswong** [comment]
🤔 If it's related to Calypso, then there is more reason for us to prioritize removing it. I have been picking at this for the past couple of days: https://github.com/Automattic/woocommerce-services/issues/2333

**Comment by dustinparker** [comment]
@harriswong it appears the issue was caused by Jetpack not installing due to using WP 5.9.3 in the e2e_tests.yml. We tried bumping the version to 6.1.0 and the tests passed: https://github.com/Automattic/woocommerce-services/actions/runs/3411216440/jobs/5675142026

We'll go ahead and create a PR for the fix.

**Comment by harriswong** [comment]
Thank you so much for looking into this!
