### ISSUE TITLE
Warning (class-wc-connect-taxjar-integration.php) on check page

### ISSUE THREAD

**Issue by Splagov** [Automattic/woocommerce-services#2611]
Warning: Trying to access array offset on value of type bool in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1074

Warning: Trying to access array offset on value of type bool in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1077

Warning: Attempt to read property "tax" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1078

Warning: Attempt to read property "rate" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 913

Warning: Attempt to read property "rate" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 915

Warning: Attempt to read property "freight_taxable" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1081

Warning: Attempt to read property "has_nexus" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1082

Warning: Attempt to read property "rate" on null in www/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 1083

----
Here are a lot topics marked as solved. But issue still appear.
easy chance to reproduce - define ZIP Code does not match the selected state.

**Comment by waclawjacek** [comment]
Thank you for the report! I'm assigning the low priority label because this is not a severe issue but definitely something that should be improved.

**Comment by Splagov** [comment]
> Thank you for the report! I'm assigning the low priority label because this is not a severe issue but definitely something that should be improved.

I have fix for this issue, but I don't have permission to push my fix/ branch.

**Comment by waclawjacek** [comment]
Could you please post it in a fork and create a pull request from your fork to this repo?

**Comment by Splagov** [comment]
@waclawjacek how I can proceed with fix?

**Comment by waclawjacek** [comment]
Hi @Splagov, please give [this guide a look for information on how to fork a repository.](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)

**Comment by Splagov** [comment]
@waclawjacek https://github.com/Automattic/woocommerce-services/pull/2612
I did. But
2 workflows awaiting approval
First-time contributors need a maintainer to approve running workflows

**Comment by waclawjacek** [comment]
Thank you for the PR, @Splagov! I have just merged it to `trunk`. It will be released in the next version.
