### ISSUE TITLE
Upgrade e2e-tests's workflow to a newer ubuntu version

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-services#2632]
### Description

GitHub is deprecating Ubuntu 18.04 (https://github.com/actions/runner-images/issues/6002). 

> Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01

Our workflow (https://github.com/Automattic/woocommerce-services/blob/trunk/.github/workflows/e2e_tests.yml#L8) uses Ubuntu 18.04. We should bump this up. We should also check other workflows.

### Acceptance criteria
A higher version of Ubuntu such that pipeline continues to run

**Comment by waclawjacek** [comment]
Fixed by #2644
