### ISSUE TITLE
PHP 8.2 Errors when using Automatic Tax

### ISSUE THREAD

**Issue by iyut** [Automattic/woocommerce-services#2647]
There is a PHP Warning when testing out the automatic tax : 

```
[07-Apr-2023 02:07:48 UTC] PHP Warning:  Undefined array key "id" in /home/u1572733/public_html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-taxjar-integration.php on line 216
```

After a couple of tests, I found out that this issue happen only when tax rates row is empty : 
<img width="1330" alt="Screenshot 2023-04-07 at 10 03 05" src="https://user-images.githubusercontent.com/631098/230532645-07bbae45-4441-4c06-b379-189a810bbb83.png">

### Steps to reproduce
1. Make sure all tax rates settings is empty.
2. Enable automated tax.
3. Add product into the cart in the frontend.
4. Go to checkout page to let the automated tax do their work.
5. PHP warning above will be listed in debug.log.

**Comment by alopezari** [comment]
Thanks for reporting this @iyut!

I just wanted to add that this message also shows up on the `WooCommerce > Settings > Tax` page after enabling automatic tax:
![image](https://user-images.githubusercontent.com/45979455/231401204-06ab223c-bc0b-4c52-ba45-c2fb91c5b5d2.png)

**Comment by brucea8c** [comment]
Had a user report on this today. Is this something that will be addressed in a future release?
