### ISSUE TITLE
id key is not found in array error, when taxjar automattic taxes enabled

### ISSUE THREAD

**Issue by juslintek** [Automattic/woocommerce-services#2651]
I want to report a bug either of woocommerce or Automattic woocommerce-services, that causes id key not found error, when automatic taxes calculation is enabled and P.S. Query monitor always shows that requests to taxjar are failing with 406 HTTP response:
[woocommerce/includes/admin/settings/views/settings-tax.php:100](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/admin/settings/views/settings-tax.php#L100)
snippet of code there at the moment (it prepares settings array):
```php
	array( 'type' => 'conflict_error' ), // React mount point for embedded banner slotfill.
```
causes an error of id key not found at:
[woocommerce-services/classes/class-wc-connect-taxjar-integration.php:224](https://github.com/Automattic/woocommerce-services/blob/trunk/classes/class-wc-connect-taxjar-integration.php#L216)
snippet of the code there at the moment:
```php
				if ( ! array_key_exists( $tax_setting['id'], $this->expected_options ) ) {
```
Either `isset($tax_setting['id']) &&` has to be added or this key has to be assigned to a variable in a loop with null coalesce and default value. Or that conflict_error should not exist there. I guess the error is in the latter. :smile:
Branches are main ones. :slightly_smiling_face:

**Comment by waclawjacek** [comment]
Thank for the report, @juslintek! We will look into it.
