### ISSUE TITLE
Flaky e2e tests

### ISSUE THREAD

**Issue by samnajian** [Automattic/woocommerce-services#2665]
We've have quite flaky [end2end tests ](https://github.com/Automattic/woocommerce-services/actions/workflows/e2e_tests.yml).

- Find what's causing it
- Fix and make sure the same issues are not happening anymore. 
- Try to document the fix if it's something that can happen in future for the same reasons.

**Comment by samnajian** [comment]
@harriswong as you're on Janitorial and the tests are failing again, would like to take over this issue or should I try to fix the currently failing tests?

**Comment by harriswong** [comment]
Please leave it to the janitor to prioritize.

**Comment by iyut** [comment]
Since E2E tests has been fixed by [this PR](https://github.com/Automattic/woocommerce-services/pull/2681). Should we close this issue?

**Comment by samnajian** [comment]
@iyut Yes, let's close this.
Closed in https://github.com/Automattic/woocommerce-services/pull/2681
