### ISSUE TITLE
FCMI shipment containing anything except documents not allowed (must use FCPIS, PMI or PMEI)

### ISSUE THREAD

**Issue by asuh** [Automattic/woocommerce-services#2697]
There appears to be an issue with USPS - First Class Mail International.

> FCMI shipment containing anything except documents not allowed (must use FCPIS, PMI or PMEI)

My understanding is First Class Mail International is valid and should be available for purchase.

If you search WordPress search forums, I don't think it's a coincidence that lots of people are experiencing the same thing so this seems like something either in code or the API?

**Comment by paulostp** [comment]
Reported in the WordPress.org forum:

* https://wordpress.org/support/topic/cant-ship-with-usps-first-class-mail-international/
* https://wordpress.org/support/topic/woocommerce-is-not-allowing-me-to-print-a-first-class-international-label/
* https://wordpress.org/support/topic/unable-to-send-documents-with-usps-first-class-international/

**Comment by paulostp** [comment]
Also reported via the Woo.com support form. For internal reference only: 7310595-zen, 7296762-zen, 7273660-zen, 7275590-zen

**Comment by rykener** [comment]
I am having the same issue. Please address ASAP as I'm unable to ship internationally.

For the customs form, when "Contents type" is set to Merchandise, and then trying to purchase a First Class label, an error message pops up saying only documents can be shipped via First Class. 

I'm shipping a book, so I change the customs form to say "Documents" and then I go to but  the First Class label and it says the value of documents has to be $0. 

So I try to change the value of the documents to $0 but the form validation says the value must be greater than $0.

--- 

As far as I can tell there's no way to buy First Class international labels right now. I have a large backlog of international orders that I'm unable to ship.

**Comment by ThisSucksWithWoo** [comment]
I am able to ship via First Class International by going to the Post Office, standing in line,  and paying for First Class. Yes, it's a pain and really stupid considering how many years I've been able to print the labels right in my home office. 

It's also gaslighting when at every place I have posted about this issue, they think they need to interview each individual about this problem, as if it's a problem with individuals?? Really?? A growing body of businesses are posting about this stupidity.

**Comment by harriswong** [comment]
> I am able to ship via First Class International by going to the Post Office, standing in line, and paying for First Class.

Hi @ThisSucksWithWoo, when you were at the post office and purchased "First Class International", did you purchase [First Class **Package** International Service](https://www.usps.com/international/first-class-package-international-service.htm) or [First-Class **Mail** International](https://www.usps.com/international/first-class-mail-international.htm)? First class **mail** requires flats. and the custom form should declare it as a document.

**Comment by harriswong** [comment]
👋 Hi @iyut, I noticed you are looking into this issue. We had a conversation with our postal service provider and I wanna add a few notes for you here:

- First class **mail** international has to be flat (envelopes). We should have an option (ie. `is_letter`) that sets this. We should also check if the person is shipping with envelopes or if they are shipping with parcels. One should not be getting parcel rates if they are using envelops:
![image](https://github.com/Automattic/woocommerce-services/assets/572862/3cf707ea-4621-420a-9b97-533a9ceb8877)
- If first class **mail** international is selected, then we can default it to "documents" because USPS is getting more strict on this and their validator won't pass otherwise. 
- If it's first class **mail** international, then we can also default value to "0". 
- For first class **package** international service, the value has to be greater than 0 so we should keep this check.

Feel free to ping us or let us know if you have any questions!

**Comment by ThisSucksWithWoo** [comment]
> > I am able to ship via First Class International by going to the Post Office, standing in line, and paying for First Class.
> 
> Hi @ThisSucksWithWoo, when you were at the post office and purchased "First Class International", did you purchase [First Class **Package** International Service](https://www.usps.com/international/first-class-package-international-service.htm) or [First-Class **Mail** International](https://www.usps.com/international/first-class-mail-international.htm)? First class **mail** requires flats. and the custom form should declare it as a document.

I use First Class International for flat envelopes. So I just paid for First Class International since the envelope was going to the UK from the US. And it's nuts that I could make First Class International work for an envelope at the PO, but can't print it out with WooCommerce.

**Comment by harriswong** [comment]
> I use First Class International for flat envelopes...I could make First Class International work for an envelope at the PO

If I am understanding this correctly, your local postal office lets you print "First-Class **Mail** International" with "merchandise" on your customs form, correct?

**Comment by asuh** [comment]
@harriswong Customs forms are optional, but what you add to the customs form, in theory, shouldn't affect the ability to use a letter, postcard or small envelope for FCMI.

**Comment by Darkearth10** [comment]
I am another one of the people who made a post on the wordpress support form. 

I ship a lot of postcards, in a postcard sizes envelope and have for years, I no longer can with this new bug that everyone is experiencing. If I go into the post office they will let me mail them as FCMI.

**Comment by ThisSucksWithWoo** [comment]
It's completely nutty.

**Comment by paulostp** [comment]
Just wanted to add for any merchants currently unable to buy labels for "First Class Mail International", that you might want to consider "First Class International Package" as a temporary alternative (or permanent, as it looks like USPS is pushing for [the FCMI content restrictions](https://faq.usps.com/s/article/First-Class-Mail-International) to be observed).

"First Class International Package" should be more affordable than the Priority/Express mail alternatives that are currently available. You will get access to USPS's package services if you create a custom "Box" type package with the same dimensions. If a package is set to "Envelope" type, then only envelope rates are returned. Please follow the link below for a guide on creating custom packages:
 
https://woo.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#manage-packages

**Comment by harriswong** [comment]
Thanks @asuh, @Darkearth10 for the details. We have no control over what USPS's validation does. If USPS decides to invalidate a customs form, then we will surface this error back to the client. That said, we are in conversation with the service provider and we are investigating what the issue is.

**Comment by asuh** [comment]
@harriswong Understood, but for the scope of this WooCommerce plugin issue, I'm not sure how a customs form would affect the outcome.

**Comment by harriswong** [comment]
> for the scope of this WooCommerce plugin issue, I'm not sure how a customs form would affect the outcome.

@asuh Thanks for asking. In WooCommerce Shipping & Tax, when you are shipping internationally, a customs form will show up and ask for your content type and value
![image](https://github.com/Automattic/woocommerce-services/assets/572862/a73561d9-fbf6-4cd7-91c8-bf1d2e26a554)

The plugin then sends this information to our provider to purchase a label. Under the hood, our provider/USPS will validate this input and if there is an error with **anything**, it won't purchase the label. 

Recently, these validations on "First Class Mail International" started to throw errors. We are not sure why and are investigating. Does the provider/USPS require more description or checkboxes? Are they more strict about certain package types? Is "First Class Mail International" no longer allowed unless the service is in an envelope (what about padded envelope)? etc etc. This is why we have reached out to our provider and we are investigating. 

Also, the plugin's code is open source. You are more than welcome to help us investigate and please share what you've found! 

Finally, the postal office person may not go through the same validation/purchasing protocol we go through. I am not sure why one can purchase certain labels over the counter with the same parameters but not with us. Again, we are investigating. I appreciate your patience.

**Comment by asuh** [comment]
Thank you for the detailed explanation, @harriswong! Apparently, this is one area of the process that is already valid with a green circle check when going through the process and I overlooked it.

After talking to my client, it appears that a local trip to the post office to send an standard sized envelope (the common Commercial sizes in the US) via FCMI does not require any discussion of a customs form. It's just a stamp.

That makes it interesting that this plugin requires the Customs form as a property of this transaction. Maybe USPS' API has this requirement for FCMI? I haven't researched what needs to be sent in order to fulfill this type of transaction.

**Comment by harriswong** [comment]
> a local trip to the post office to send an standard sized envelope (the common Commercial sizes in the US) via FCMI does not require any discussion of a customs form. It's just a stamp.

Thanks for sharing this! Maybe we can opt-out the customs form if it's an envelope/document (which makes sense actually). We will check if this is something we can do.

**Comment by Darkearth10** [comment]
@paulostp

To provide extra information, even doing this will not always work. 

For instance, there are documents that I send out internationally. 

Under previous settings of having the package type as Envelope you would get your standard shipping options. 
![image](https://github.com/Automattic/woocommerce-services/assets/49106450/0cee0843-1512-4b3f-b11d-e80382a36e39)

However, when changing the package type from Envelope to a Package and putting in the same box dimensions, it will throw this error of "Wrong Parameter Type" so you can't even ship using this method. 

![image](https://github.com/Automattic/woocommerce-services/assets/49106450/cb875284-555c-4135-8b2b-7e13716afa3e)


Additionally, in reference to what @harriswong was saying, I do not think that this problem has anything to do with the Customs form section. I can change the "Contents Type" field from Merchandise to "Gift" or "Document" and still get the shipping error about FCMI only being for documents
![error](https://github.com/Automattic/woocommerce-services/assets/49106450/0fc0fe80-0c35-4a72-9665-2d636e5c685e)

**Comment by rykener** [comment]
Hi, can we have an update on this ticket? is there an ETA?

**Comment by harriswong** [comment]
Hi @rykener, I do not have a timeline. We are investigating. I appreciate your patience.

**Comment by harriswong** [comment]
We adjusted the server to look at the provided customs form and skip it if the predefined package is 'Letter', 'Card', or 'Flat'. Please let us know if this does not resolve your issues. 

Marking this as resolved. Thank you for your patience.

**Comment by ThisSucksWithWoo** [comment]
Please fix woo. I now cannot print a label for a International Priority package nor can print a First Class International for a business envelope.  WHY is this happening?

**Comment by harriswong** [comment]
Hi, I am not sure why your specific website is not printing priority package labels. If you need further assistance, please leave a message in our forum or get in touch with us. More about that here:
https://woo.com/document/woocommerce-shipping-and-tax/woocommerce-shipping/#questions-and-support

You are welcome to open a new issue in the WooCommerce Shipping & Tax GitHub repository, the guideline can be found here https://github.com/Automattic/woocommerce-services/blob/2cdbabc6a542f5f6a0fedce36eaf9087f321f380/CONTRIBUTING.md#reporting-bugs-asking-questions-sending-suggestions. Please provide **clear steps** so we can reproduce the issue. Here is a good example of a bug report: https://github.com/Automattic/woocommerce-services/issues/2698. Thank you.

**Comment by ThisSucksWithWoo** [comment]
Uhhh, it's not "my specific website". It's WOO that is doing this after a long time of being able to print... just like Woo has been making it impossible to print a First Class international label for a business envelope.

And here's what I get when I try to print an International Prority label: Customs info error: missing required field for non-document shipment: customs_items.hs_tariff_number
