### ISSUE TITLE
When automated taxes are enabled, the order refund button will fail

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-services#2703]
**Describe the bug**

With automated taxes enabled the refund button in the order edit screen triggers a console error. This affects both manual and via payment provider refunds.

![8dLDeG.png](https://github.com/Automattic/woocommerce-services/assets/3624025/a720240d-6c23-455a-9c28-4c1be45017a8)

**To Reproduce**

1. Ensure automated taxes are enabled
2. Open an order
3. Attempt a refund

**Screenshots**

![8dLDeG.png](https://github.com/Automattic/woocommerce-services/assets/3624025/a720240d-6c23-455a-9c28-4c1be45017a8)

**Expected behavior**

Refund should go through

**Isolating the problem (mark completed items with an [x]):**
- [ x I have deactivated other plugins and confirmed this bug occurs when only the extension is active.
- [ x] I can reproduce this bug consistently using the steps above.

7382875-zd-a8c

**Comment by WillBrubaker** [comment]
7383273-zen
7382766-zen

**Comment by danielk-am** [comment]
7383346-zen
