### ISSUE TITLE
Incorrect tax rates for CO located merchants: city tax not calculated

### ISSUE THREAD

**Issue by wpshellbelle** [Automattic/woocommerce-services#2709]
I recently had a merchant reach out to let us know that taxes are not being calculated as expected for their store in Colorado. 

The merchant's store is located in: `80907` and the city tax is not added unless customer is is also located in `80907`. 

**Steps to replicate:**

1. Head to TaxJar Sales Tax Calculator to check the sales tax for Aurora, CO: https://www.taxjar.com/sales-tax-calculator
2. Find TaxJar shows a tax rate of 8.000% 
3. Enable automated taxes using WooCommerce Shipping & Tax and set shop location to Colorado Springs, CO (`80907`)
4. Add a product to you cart and head to the checkout page - enter an Aurora, CO address at checkout with zip code `80013`
5. Find tax rate seen at checkout is only `4.25%` (.25% county + 2.9% state + 1.1% special tax rate)

I ran the zip 80013 through the TaxJar sales tax calculator and I found the rate of 8.0%: 

<img width="865" alt="Screen Shot 2023-12-22 at 3 15 05 PM" src="https://github.com/Automattic/woocommerce-services/assets/77413972/b806d215-ab33-4a81-86ce-01749419352d">

 
TaxJar Sales Tax Calculator: https://www.taxjar.com/sales-tax-calculator

 
However, when I run the request using https://developers.taxjar.com/demo/ with the from zip code of 80907 to the zip code 80013, I see no city tax is calculated (the missing 3.75%): 
 
<img width="1408" alt="Screen Shot 2023-12-22 at 3 17 31 PM" src="https://github.com/Automattic/woocommerce-services/assets/77413972/df12802b-b356-4d15-9b46-3014bfbec6f5">

I believe this issue is with TaxJar, a 3rd party vendor, but I wanted to flag this here.

**Comment by paulostp** [comment]
Hey @wpshellbelle 👋 Thanks for raising this issue. For what it's worth, I'm getting similar results to what you describe with our AvaTax sandbox as well. 🤷 Sales tax can be messy — I can't say what would be the correct tax for this specific case.

I would recommend that the merchant checks with a tax specialist what taxes they actually need to collect beforehand. That knowledge will allow them to confidently pick the right automated taxes tool for their use case. For example, the automated taxes feature included in WooCommerce Shipping & Tax in particular has some limitations in some contexts, when compared with premium options like AvaTax.

In some cases, it might be easier to just manually add to WooCommerce a tax rate that's missing from the TaxJar API.

Internal reference: 7488695-zd-a8c

**Comment by kloon** [comment]
I have had some discussions with TaxJar about this and we have a solution we can roll out. Instead of passing the merchant store address in the `from_*` API fields, we should rather omit these fields completely and pass the merchant store address in the `nexus_address` object.

See [TaxJar API documentation](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order) for reference.
