### ISSUE TITLE
Customs info missing, but errors are unclear

### ISSUE THREAD

**Issue by ryanr14** [Automattic/woocommerce-services#2712]
I had a chatter yesterday who ran into the following error…

> Customs info error: missing required field for non-document shipment: customs_items.hs_tariff_number

![image](https://github.com/Automattic/woocommerce-services/assets/867748/be59e73f-b789-4d6b-ad58-142b209a39f5)

We were both a little confused at first by the message, as it isn't a friendly error message, but it also prompts you to go to your Credit Card settings.

We did eventually realize it's for the HS Tariff number in the Customs section of label creation. The other confusion is that the field is labeled as optional, but in this case was required for the label.

![image](https://github.com/Automattic/woocommerce-services/assets/867748/e0860f4e-4f99-4c3f-8bf1-f570a016bb8f)

We were then able to quickly find the HS Tariff number and get them on their way, but I'd promised them I'd follow up on this confusion and see how we can make this better for future scenarios like this for other merchants.

So first, when the HS Tariff number is required is it possible to show that for the field? And if this error is triggered, can we change that error message to better direct them on how to find their HS Tariff number(s) and update the Customs section?

**Comment by paulostp** [comment]
Thanks for reporting @ryanr14!

This also came up in #2697 so it might be another one of recent changes that EasyPost made to the USPS international services, but this one precedes the FCMI issues, as I can see tickets with that exact error message as far back as October 6, 2023.

**Comment by samnajian** [comment]
This seems to happen quit often and then results in `The request could not be understood by the server due to malformed syntax.` logged as well, escalating it.

```
{
    "event": "[request.app](http://request.app/)",
    "hostname": "[api.woocommerce.com](http://api.woocommerce.com/)",
    "path": "/shipping/label",
    "method": "post",
    "timestamp": 1720554200423,
    "tags": [
        "error"
    ],
    "data": {
        "userId": 22****802,
        "blogId": 216444771,
        "wcsVersion": "2.4.2",
        "wcShippingVersion": "VERSION_NOT_PROVIDED",
        "lastServicesUpdate": 1720552294,
        "url": "http://api.woocommerce.com/shipping/label",
        "realRemoteAddress": "18.***.*45.5",
        "realRemotePort": "443",
        "clientName": null,
        "clientVersion": null,
        "isRawError": true,
        "severity": "error",
        "message": "Error purchasing label 9***413: The request could not be understood by the server due to malformed syntax."
    },
    "pid": 88500
}
```

The error logged to DB is as follows:
`
Customs info error: missing required field for non-document shipment: customs_items.hs_tariff_number
`
We'd probably need to make sure our service provider validates the customs information when fetching rates as well and not only when trying to purchase it.

**Comment by iyut** [comment]
Based on [this issue](https://github.com/Automattic/woocommerce-services/issues/2720), it seems we will need to make the "HS Tariff Number" field to be required field if the destination country is within EU.

Will that be OK if we make condition that if the destination country is within EU, then the "HS Tariff Number" field will be mandatory field?

**Comment by samnajian** [comment]
> Will that be OK if we make condition that if the destination country is within EU, then the "HS Tariff Number" field will be mandatory field?

Yes, that's the way to check if it's required, we have the same logic in WC Shipping as implemented [here](https://github.com/woocommerce/woocommerce-shipping/pull/198/files) and improved later on.
