### ISSUE TITLE
Enforce HS Tariff code field requirement for EU countries in WCS&T UI

### ISSUE THREAD

**Issue by laurajohnsonwoo** [Automattic/woocommerce-services#2720]
We need to update the WCS&T label purchase customs section to meet updated EU customs requirements. 

For cross-border shipments bound for EU countries: 

1. Remove "Optional" language from HS Tariff code field 
2. Make field required 

**Reference**: 
> Per USPS, "Both HS code and country of origin (for commercial items) are conditional requirements of the destination countries. See IMM 123.711 for more details.
> 
> The HS Code is required by EU countries.  As an example, I have copied below the top of the Germany ICL which states this:
>  
> Country Conditions for Mailing — Germany
> 
> All items containing goods must include the corresponding 6-digit harmonized system code for each article listed on the customs declaration form. For more information, see 537 and the Observations section below."

- [Customs Forms and Online Shipping Labels](https://pe.usps.com/text/imm/immc1_009.htm)
- [International Mail Services](https://pe.usps.com/cpim/ftp/manuals/imm/immc1.pdf)
- [Harmonized Tariff Schedule page](https://hts.usitc.gov/)

Related PR https://github.com/woocommerce/woocommerce-shipping/pull/198

**Comment by paulostp** [comment]
I believe this is related: https://github.com/Automattic/woocommerce-services/issues/2712

**Comment by sophiegyo** [comment]
We may have a similar issue with Switzerland - this from 8272375-zen.
The merchant in that ticket shared this:
https://pe.usps.com/text/imm/immc5_010.htm

**Comment by iyut** [comment]
I will close this issue as [this PR](https://github.com/Automattic/woocommerce-services/pull/2764) has been merged.
