### ISSUE TITLE
Colorado tax applied without a Colorado nexus

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-services#2721]
Flagging this to @iyut and @dustinparker since y'all worked on #2716 and reverting to 2.5.1 resolves the issue.

With version 2.5.2 of Shipping & Tax active, a store with a location set outside of the state of Colorado will have taxes applied to customers from Colorado. 

To reproduce:
1. Set your store location to a U.S. state that is not CO at **WooCommerce > Settings > General**
- This was reported by a merchant in WA, but I could repro with a store in CA.
2. Enable automated taxes
3. Double-check that there are no CO tax rates at **WooCommerce > Settings > Tax > Standard rates**
4. Add a product to your cart
5. Add CO state details on the cart or checkout page to calculate tax (e.g., Denver, Colorado, USA 80014)
6. Note that taxes are added to the order.

![CleanShot 2024-03-08 at 15 23 06](https://github.com/Automattic/woocommerce-services/assets/82999806/8432db2f-8040-43b1-92b4-42e3f6a031a7)
![CleanShot 2024-03-08 at 15 22 45](https://github.com/Automattic/woocommerce-services/assets/82999806/be3f7b74-c56c-481b-8ca3-df33e64774ea)

This results in merchants charging taxes to customers in a region where they do not have a nexus.

**Comment by csmcneill** [comment]
Reported in 7859643-zen, discussed in p1709930531818689-slack-C3NCP7ZJ6

**Comment by maxlaf** [comment]
7848850-zen
