### ISSUE TITLE
Stop plugin execution when woocommerce-shipping or woocommerce-tax is active

### ISSUE THREAD

**Issue by kloon** [Automattic/woocommerce-services#2726]
In order to prepare for the separation of shipping and tax we need to add a check to ensure that WCS&T does not work when either `woocommerce-shipping` or `woocommerce-tax` are active.

We also need to display a message indicating that you cannot have WCS&T active alongside Woo Shipping or Woo Tax.

**Comment by waclawjacek** [comment]
The solution I ended up implementing is that WCS&T will display the notice and not activate itself if possible. If not, Woo Shipping will deactivate itself instead (to cover cases where a merchant is using an older version of WCS&T).

See the screenshots here: https://github.com/woocommerce/woocommerce-shipping/pull/345

**Comment by waclawjacek** [comment]
Added the same logic to Woo Tax: https://github.com/woocommerce/woocommerce-tax/pull/59
