### ISSUE TITLE
Update Jetpack method(s) to match latest connection package

### ISSUE THREAD

**Issue by kallehauge** [Automattic/woocommerce-services#2773]
Reported by @harriswong: https://github.com/Automattic/woocommerce-services/pull/2761#pullrequestreview-2183932054

>When both plugins are enabled, I noticed these errors on the UI. I am using PHP 8.2.7
>
>```
>Deprecated: Function is_staging_site is deprecated since version 3.3.0! Use in_safe_mode instead. in >/var/www/wordpress/wp-includes/functions.php on line 6085
>
>Deprecated: Function is_staging_site is deprecated since version 3.3.0! Use in_safe_mode instead. in /var/www/wordpress/wp-includes/functions.php on line 6085
>```

We're not in a rush, but like we did in https://github.com/woocommerce/woocommerce-shipping/pull/560, then we should update the method we use in WCS&T since later version of wither Jetpack or WC Shipping will include a version of the connection package that have completely removed the `is_staging_site` method.

**Comment by samnajian** [comment]
@kallehauge Seems like https://github.com/Automattic/woocommerce-services/pull/2785 addresses this issue as well, na?

**Comment by kallehauge** [comment]
Yup! You got it @samnajian 👏

**Comment by kallehauge** [comment]
Yup! You got it @samnajian 👏
