### ISSUE TITLE
Add service list filters to the shipping method UI

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#280]
Since USPS has so many services - it would be good to add some kind of optional + default filters in addition to https://github.com/Automattic/woocommerce-connect-client/issues/33 to cut down on the number of services a merchant needs to wade through.

cc @nabsul

**Comment by kellychoffman** [comment]
I was thinking that a filter bar would make the most sense here:

<img width="688" alt="screen shot 2016-05-05 at 10 54 41 am" src="https://cloud.githubusercontent.com/assets/5835847/15050719/990a3ce6-12b2-11e6-8348-e23be926a29c.png">

**Comment by allendav** [comment]
Moving this out of Alpha and into Beta

**Comment by allendav** [comment]
Nix popular for now

**Comment by jeffstieler** [comment]
@kellychoffman do you think this is still worth doing? _(I don't)_

**Comment by kellychoffman** [comment]
No, not unless user testing tells us the list is too overwhelming and they would like a way to filter.
