### ISSUE TITLE
BUG: Migrated packages not recorded in wcshipping_labels meta

### ISSUE THREAD

**Issue by samgerdt** [Automattic/woocommerce-services#2807]
Package templates migrated from Shipping & Tax are not being recognized in this check (lines 249-255, woocommerce-shipping/src/LabelPurchase/LabelPurchaseService.php):

`if ( 'individual' === $box_id ) {`
`$label_meta['package_name'] = __( 'Individual packaging', 'woocommerce-shipping' );`
`} elseif ( isset( $package_lookup[ $box_id ] ) ) {`
`$label_meta['package_name'] = $package_lookup[ $box_id ]['name'];`
`} else {`
`$label_meta['package_name'] = __( 'Unknown package', 'woocommerce-shipping' );`
`}`

All labels using migrated package settings are recording "Unknown package" in meta.

**Comment by kallehauge** [comment]
Hi @samgerdt! 👋 

Thank you for the report ❤️ 
We'll take a look and get back to you 👍

**Comment by kallehauge** [comment]
Howdy @samgerdt! I just wanted to let you know that I've created a patch that is in review, so hopefully it goes out with the next release, soon 😃
