### ISSUE TITLE
In self-help, also display warnings for any unacceptable shared settings

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#281]
_Previous content by @allendav_

> e.g. currency, dimension_unit, weight_unit
> 
> Once https://github.com/Automattic/woocommerce-connect-server/issues/219 and https://github.com/Automattic/woocommerce-connect-server/issues/217 are working

_Edited by @jeffstieler_

Surface `/services` request errors in the "health" section:

![screen shot 2017-12-15 at 11 23 12 am](https://user-images.githubusercontent.com/63922/34055005-990ea986-e18a-11e7-9ff6-929b9607adbc.png)

Example error:

`12-15-2017 @ 18:20:20 - wcc_server_error_response Error: The WooCommerce Services server returned: Bad Request child "settings" fails because [child "currency" fails because ["currency" needs to be a valid ISO 4217 currency code]] ( 400 ) (fetch_service_schemas_from_connect_server)`

**Comment by jeffstieler** [comment]
I'm not sure I understand what we'd show to a user in this scenario.

We're grabbing the values from WC core, so if they're invalid, the store owner will likely be having other problems - not just with WCC.

**Comment by allendav** [comment]
If they filter in a currency we don't grok, or they save a dimension unit or weight unit to options, we should tell them that. That said, we could forego doing this in validation and move it to self-help instead.

**Comment by jeffstieler** [comment]
> That said, we could forego doing this in validation and move it to self-help instead.

I think this makes the most sense.

**Comment by allendav** [comment]
Boom. You're off the hook :)

**Comment by laurendavissmith** [comment]
Closed and we'll come back around if this continues to frustrate the users
