### ISSUE TITLE
Console Error When Configuring Product Add-ons with WooCommerce Automated Taxes Enabled

### ISSUE THREAD

**Issue by daniyalahmadk** [Automattic/woocommerce-services#2824]
**Bug Report**

**Describe the bug**  
When WooCommerce Shipping and Tax is activated with "Automated tax" enabled, configuring product addons during manual order creation throws a JavaScript error in the console.

**Console Error**  
```
Uncaught TypeError: r.data.indexOf is not a function  
File: woocommerce-services-new-order-taxjar-2.8.2.js  
Line: if (r.data && r.data.indexOf("woocommerce_calc_line_taxes") > 0)
```

**To Reproduce**  
1. Install WooCommerce Product Add-ons and configure a global addon.
2. Go to **WooCommerce > Settings > Tax** and enable "Automated taxes."
3. Go to **WooCommerce > Orders > Add New**, add a line item, then click on the "Configure" button.
4. Fill in the addon field in the popup, click "Done," and observe the console error.

**Expected behavior**  
The product addon should be configured without errors, and the order process should continue without getting stuck on the loading icon.

**Screenshots**  

![https://d.pr/i/RAW1tf](https://d.pr/i/RAW1tf+) 
Full Size: https://d.pr/i/RAW1tf

**Comment by grig-23** [comment]
8898937-zen - I think this is where this was originally reported.

**Comment by rbgly** [comment]
9066631-zen

**Comment by nicdwilson** [comment]
Adding an additional entry here where a conflict occurred with Product Bundles with an explanation of the error

> Product Bundles uses a FormData object to set the ajax data, and not a generic object or array. FormData doesn’t have an indexOf  method. The same issue exists with Product Add-Ons and Composite Products and [edited] any other plugin that doesn’t use an array for the data

9131026-zd-a8c
