### ISSUE TITLE
Add php test coverage

### ISSUE THREAD

**Issue by jkudish** [Automattic/woocommerce-services#293]
PHPunit should be able to report our coverage percentage

Related: #234

**Comment by jeffstieler** [comment]
PHPUnit is capable of reporting code coverage as it sits now by using the `--coverage-html` argument. For example: `phpunit --coverage-html /tmp/coverage`.

Code coverage takes quite a bit of time to generate.. where do you see this fitting in to the test runner?

We might be able to use another service like [Coveralls](https://coveralls.io/), but we'd need to clear it with ops.

**Comment by jkudish** [comment]
Travis doesn't support code coverage reports?

**Comment by jeffstieler** [comment]
> Travis doesn't support code coverage reports?

Unfortunately, no, it doesn't. [Travis CI recommends Code Climate](https://docs.travis-ci.com/user/code-climate/), but this is another third party service.

**Comment by laurendavissmith** [comment]
Closed for now, we can revisit down the line when excellence is able to provide a direction on how we'll handle code coverage across all the repos
