### ISSUE TITLE
Handle the case where a method added to a zone no longer appears in services response

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#30]
This should not happen prior to Beta, but it will need to be resolved before Ready to Merge to WooCommerce Core.  For example, what if we decide to retire support for a method, or if a subscription to a premium method expires, etc?

Right now, you'll get something like this if a zone method is no longer found in the GET /services response:

```
Notice: Undefined index: canada-post in /home/allendav/public_html/wp-content/plugins/woocommerce/includes/class-wc-shipping-zone.php on line 228
Notice: Undefined offset: 30 in /home/allendav/public_html/wp-content/plugins/woocommerce/includes/class-wc-shipping-zone.php on line 246
```

**Comment by jeffstieler** [comment]
We can revisit this if we ever decide to sunset a shipping method.
