### ISSUE TITLE
[Labels] Expose tracking information to customer for their order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#391]
When available, expose at least the tracking number to the customer in the order details view, for orders where the merchant has used WCC to purchase a shipping label.

See also https://github.com/Automattic/woocommerce-connect-client/issues/390

**Comment by kellychoffman** [comment]
Would it be weird if it was added to the notes section? Weird because it wouldn't be an actual note that you added, but it feels like that makes the most contextual sense:

<img width="295" alt="screen shot 2016-06-24 at 12 28 53 pm" src="https://cloud.githubusercontent.com/assets/5835847/16343885/ac6b9588-3a07-11e6-9185-2f1da90dcc17.png">

**Comment by kellychoffman** [comment]
Another option would be to add it below the Order status because it would also make sense in that context:

<img width="787" alt="screen shot 2016-06-24 at 12 48 47 pm" src="https://cloud.githubusercontent.com/assets/5835847/16344313/0bad895a-3a0a-11e6-8f77-3d7a4bb9dba0.png">

**Comment by kellychoffman** [comment]
What do ya'll think?

**Comment by DanReyLop** [comment]
I'm ok having it as an Order Note, it seems the most straight-forward option to implement. The tracking number is not so important for the merchant anyway, it's more important how we present it to the customer.

**Comment by kellychoffman** [comment]
👍  Order Note sounds good to me. 

>  more important how we present it to the customer.

Agree

**Comment by kellychoffman** [comment]
Expose order/tracking ID in notes section too?

**Comment by allendav** [comment]
@kellychoffman @DanReyLop - all this is fine by me, but this issue is for the customer side (e.g. my-account) - this feedback is more appropriate in #482 , no?

**Comment by kellychoffman** [comment]
>  this issue is for the customer side

So it is. Will move design there and add a new design to this issue.

**Comment by allendav** [comment]
@DanReyLop @kellychoffman - let's put this on hold for the moment until we hear from marketing on whether this feature should be included in the MVP

I'm moving it from Sprint 4 to Sprint 6

cc @warrendholmes @avivapinchas

**Comment by kellychoffman** [comment]
We should add the ability for the merchant to send an email upon printing/purchasing a label, perhaps under the paper size picker:

<img width="301" alt="screen shot 2017-01-22 at 1 01 56 pm" src="https://cloud.githubusercontent.com/assets/5835847/22184183/04a9879a-e0a3-11e6-98c1-78c928cedbe6.png">

**Comment by jeffstieler** [comment]
I think we should revisit this.

We're currently showing a tracking link in the Labels metabox:
![](https://cldup.com/IqZZutuvLC.thumb.png)

**Comment by DanReyLop** [comment]
> We should add the ability for the merchant to send an email upon printing/purchasing a label, perhaps under the paper size picker:

Could we use instead the existing e-mail templates that are sent when the order transitions state?

**Comment by ahalekelly** [comment]
What's the status of this? It would be a great feature.

**Comment by JamesJosephFinn** [comment]
Tracking info can be exposed to the customer in `My Account dashboard >> Orders >> View order` by using the [WooCommerce Shipment Tracking](https://woocommerce.com/products/shipment-tracking/) (paid) plugin developed by the core team, *buuut....*

### Human input is an opportunity for human error

**Unfortunately**, the store operator has to manually paste in the tracking number on the order details page into the `woocommerce shipment tracking` widget, in order for the tracking number to be sent out to the customer as part of woocommerce's core `order complete` email.

I know that *WooCommerce Services* has [plans to add the automated sending of tracking info to the customer](https://docs.woocommerce.com/document/woocommerce-services-faq/?_ga=2.35978592.1312896509.1505233964-1835868703.1491410639#section-18), but *WooCommerce Shipment Tracking* is useful in other ways (e.g. the aforementioned `View order` page in the customer's My Account dashboard), so it would be nice if `Shipment Tracking` was fed this data automatically.

*WooCommerce Services* and *Shipment Tracking* are core WooCommerce products, and it would be great if they were integrated. The shipment tracking number WC Services generates as part of the label creation process should automatically be fed into `woocommerce shipment tracking`.

**Comment by joshuaja** [comment]
Having the tracking number included in the email that gets sent to the customer upon marking the order “Completed” would be the optimal user experience. Adding it as a customer note would send out an additional email that is unneeded.

**Comment by kellychoffman** [comment]
> Having the tracking number included in the email that gets sent to the customer upon marking the order “Completed” would be the optimal user experience.

This sounds like a good MVP for this. @DanReyLop: What do you think about this implementation?

**Comment by DanReyLop** [comment]
> This sounds like a good MVP for this. @DanReyLop: What do you think about this implementation?

@kellychoffman Sounds good, we'll tackle this as soon as we wrap up Q3 work.

> I'm working on a temporary fix for our site to be added to the customer-completed-order.php email template.

@joshuaja Thanks for your interest! It's not bad as a temporary fix, but `woocommerce-services` can't make any modifications to the `customer-completed-order.php` template directly, we would need to use a filter (which is already in place). If you want to try and submit a PR, we'll be happy to review it and get it merged. If not, we'll implement this feature as soon as we have time, it's something useful that has been missing from this plugin for far too long :)

**Comment by joshuaja** [comment]
@DanReyLop - I have some working code using `add_action` and am about to submit a Pull Request; however, where would be the best place to include the code?

[Here](https://github.com/Automattic/woocommerce-services/blob/8cdc1155956d711988c48b411c406ac87443a014/woocommerce-services.php#L429) or one of the individual classes?

![tracking-email](https://user-images.githubusercontent.com/9004029/31134476-3635122a-a830-11e7-84ca-a45a9439272f.png)

**Comment by kellychoffman** [comment]
That looks nice! 

Which reminds me, I want to nuke the table cell borders, they aren't really necessary.

**Comment by DanReyLop** [comment]
> In woocommerce-services.php or one of the individual classes?

In `woocommerce-services.php` is fine.

> Here's what it looks like for reference

Looks great! Just one thing, the `Track` link isn't needed, you can just make the Tracking Number a link. I think it would look better :)

**Comment by joshuaja** [comment]
@DanReyLop - thanks for the help. I've submitted a PR here: #1173.

**Comment by jeffstieler** [comment]
Considering this closed by https://github.com/Automattic/woocommerce-services/pull/1173.
