### ISSUE TITLE
Support optional per-service tooltips

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#405]
e.g. to display things like flat rate box dimensions for a service, or things like "Books and periodicals only" for media mail, etc.

Something like this (cc @kellychoffman for a proper calypso-y treatment)

![service-detail-tooltip](https://cloud.githubusercontent.com/assets/1595739/16059927/171bff9c-323a-11e6-9ef8-79b264903021.png)

This will also require a server side change to support adding the information to the service schema

**Comment by kellychoffman** [comment]
What does `Large Flat Rate Box A` mean in the example shown?

**Comment by kellychoffman** [comment]
Thinking something like this would work:

<img width="549" alt="screen shot 2016-06-16 at 3 58 17 pm" src="https://cloud.githubusercontent.com/assets/5835847/16131281/70f7d750-33db-11e6-88f4-ed136704ec74.png">

Uses `info popover` as seen here: https://wpcalypso.wordpress.com/devdocs/design/info-popover

**Comment by allendav** [comment]
I'm going to park this for consideration beyond MVP
