### ISSUE TITLE
Test for cron support on self-help page

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#406]
Some hosts may not support cron - this could be an issue for us since we rely on cron to fetch service schemas.

cc @mikejolley

**Comment by jeffstieler** [comment]
This exists on WooCommerce > Status in the "WordPress Environment" section:

![screen shot 2017-12-15 at 10 38 52 am](https://user-images.githubusercontent.com/63922/34053560-7f8d4112-e184-11e7-9910-6262f48dbc6a.png)
