### ISSUE TITLE
Add a test for calling "calculate_shipping" when no shipping services have been set up

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#407]
More context: https://github.com/Automattic/woocommerce-connect-client/pull/400/files#r67228965

Add a test for the `WC_Connect_Shipping_Method::calculate_shipping` method, for the case when the merchant hasn't correctly set up any services yet. The test should check that no action was taken and the debug log was called noting the error.

**Comment by laurendavissmith** [comment]
Closing, we'll revisit tests after the e2e integration is finished
