### ISSUE TITLE
For a given method, filter services shown based on Shipping Zone Regions

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#427]
- if the shipping zone region is United States (only) and the method is USPS, don't show USPS international services
- if the shipping zone region excludes the United States and the method is USPS, don't show USPS domestic services
- if the shipping zone region is Canada (only) and the method is Canada Post, don't show Canada Post international services
- if the shipping zone region excludes Canada and the method is Canada Post, don't show Canada Post domestic services

We may need to add a country code on the server for each method to say what it's domestic country code(s) is (e.g. US, PR, GU etc for USPS; CA for Canada Post).  Our methods' services already include an `international` flag iirc.

**Comment by allendav** [comment]
Oops. Dupe of #33 but this is more concrete, so keeping this one

**Comment by laurendavissmith** [comment]
Closed, not sure its valid as the extension is currently scoped to USPS ( US only )

**Comment by DanReyLop** [comment]
> the extension is currently scoped to USPS ( US only )

The origin can only be US, but the destination can be anywhere in the world, both for checkout rates and shipping labels.
