### ISSUE TITLE
Notify the merchant in Edit Order if a Fall Back Rate was used

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#440]
e.g. something like this:

<img width="767" alt="screen shot 2016-06-30 at 1 14 08 pm" src="https://cloud.githubusercontent.com/assets/1595739/16502709/8f391ad2-3ec4-11e6-9472-0d6ecb480b9b.png">

**Comment by laurendavissmith** [comment]
Closing, seems like this is very out of date at this point
