### ISSUE TITLE
[Labels] Warn the merchant if there's no credit card info stored for his/her account

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#447]
Design: TBD

If the merchant tries to print a shipping label, and we detect there's no credit card information stored in WCC server, a warning should appear, ideally with a link to https://wordpress.com/me/billing or wherever it's neccesary. That warning should specify that the site's owner must be the one who adds the credit card info, in case that the current user is not the owner.

At this point, it's unknown how to detect if the merchant doesn't have a credit card. Is it information we can get through Jetpack? Or do we need a separate service in the WCC server just to query this?

**Comment by allendav** [comment]
@DanReyLop - once #488 lands, we'll have an option that can be checked

**Comment by allendav** [comment]
We should also warn if the pmt mthd has expired.

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/issues/831.
