### ISSUE TITLE
[Labels] Packaging step: Allow the merchant to edit the packaging info

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#449]
Design: TBD

Our packing algorithm isn't perfect. Even if it was, it depends on the merchant creating the products with their exact dimensions. And even then, it wouldn't account for "flexible" objects or non-rectangular items.

The merchant should be allowed to change the packaging data completely before printing the shipping labels. This includes:
- [ ] Adding a new package of arbitrary dimensions (this package definition should ideally be remembered for the next time the merchant wants to add a package)
- [ ] Moving items between packages
- [ ] Removing a package
- [ ] Editing a package's dimensions

**Comment by allendav** [comment]
@DanReyLop - "Editing a package's dimensions" means just it's weight, right? (especially because we will probably be doing #476 )

**Comment by DanReyLop** [comment]
If we allow custom packages (as defined in #476), then you're right, editing the packages dimensions (height, width and length) makes no sense.

**Comment by allendav** [comment]
@kellychoffman - would you split out a separate design issue for this issue? ty!

**Comment by allendav** [comment]
@DanReyLop - please split this issue into separate issues for 1) moving items between packages, 2) adding a package, 3) removing a package and anything else that comes to mind

We need to make our issues more focused so we can better fit things in sprints.

**Comment by DanReyLop** [comment]
Done.

Should we close this? Adding this issue to our sprint would throw off our estimations.

**Comment by jeffstieler** [comment]
Considering this closed with https://github.com/Automattic/woocommerce-services/pull/1028.
