### ISSUE TITLE
[Labels] Explore DYMO Web service driver

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#459]
When installing the DYMO printer drivers, there is an optional installation called `DYMO Label Web Service`. It allows to use a JS library to print labels programatically in the browser, without using the OS "Print" dialog, selecting paper size, etc.

![dymo](https://cloud.githubusercontent.com/assets/1715800/16868417/ca4ccdf8-4a77-11e6-904f-7f58a6802509.png)

Sample (very old): http://developers.dymo.com/2011/11/17/javascript-library-samples-printers-and-multiple-labels-printing/

Worth taking a look, since the DYMO printers are really popular.

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of the feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38750437-add-support-for-dymo-label-web-service)
