### ISSUE TITLE
We need a "Refresh" button for service data

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#462]
This got missed in the original self-help impl.  Right now, if the schemas fail to fetch for whatever reason, I think you end up having to wait a day for a re-attempt.

<img width="892" alt="screen shot 2016-07-22 at 9 43 14 am" src="https://cloud.githubusercontent.com/assets/1595739/17064318/e7e90a2e-4ff0-11e6-8d41-e05d6e87c285.png">

**Comment by allendav** [comment]
Bumping this to higher since we could use it right now with a merchant facing problem

**Comment by nabsul** [comment]
I'm having the same problem on my test store:
![image](https://user-images.githubusercontent.com/11143071/29041132-9ec4c570-7b66-11e7-91df-d0dcbcfa59c5.png)

**Comment by brianpurkiss** [comment]
I'm running into the same issue. My WooCommerce Services Data is over five months old and I can't get it updated. And while it won't update, I can't use the USPS shipping. 

I'm unable to find any way to get it to update.

<img width="386" alt="screen shot 2017-11-01 at 8 34 02 pm" src="https://user-images.githubusercontent.com/887099/32305521-0cf83696-bf44-11e7-8349-77fa81ee97a7.png">
