### ISSUE TITLE
Display tracking information in Labels Meta Box in Edit Order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#482]
For orders where a label(s) has already been purchased, display tracking information for each purchased label in the order.

( Split out here from #390 )

**Comment by kellychoffman** [comment]
Originally posted https://github.com/Automattic/woocommerce-connect-client/issues/391#issuecomment-228394141

Was thinking it would be nice to expose the tracking number in the customer notes metabox:
![](https://cloud.githubusercontent.com/assets/5835847/16343885/ac6b9588-3a07-11e6-9185-2f1da90dcc17.png)

**Comment by allendav** [comment]
@robobot3000 - let's put this on hold for the moment until we hear from marketing on whether this feature should be included in the MVP

I'm moving it from Sprint 4 to Sprint 6

cc @warrendholmes @avivapinchas
