### ISSUE TITLE
If no packing solution from checkout, pack items as labels UI is loading

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#503]
This is not necessarily in scope for MVP.

If the customer is able to complete checkout with something like free shipping, we won't have a packing solution in order meta.  Ideally, if the merchant begins our shipping labels flow for that order, we should generate an initial packing solution for them instead of making them do it all.

We could potentially draw on the shared packages the merchant has defined, among other things.

This could potentially be designed to use a box packing service on our server.

**Comment by v18** [comment]
Related to #446

**Comment by v18** [comment]
Closing in favour of #446
