### ISSUE TITLE
Test/Support for WordPress multisite

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#508]
Have we tested for this yet?
Do we intend to support it?

@allendav

**Comment by allendav** [comment]
Possibly, but not for MVP. Putting this in the icebox for consideration later :)

**Comment by jconroy** [comment]
Closing in favor of tracking popularity of the feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747596-add-support-for-wordpress-multisite)
