### ISSUE TITLE
Promote label savings to merchant

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#524]
I like how eBay/Pitney Bowes does this, comparing retail prices to their (Commercial Base Price) price for the package. I think we should consider doing something similar, displaying the discount amount and percent:

![screen shot 2016-08-29 at 5 06 30 pm](https://cloud.githubusercontent.com/assets/1595739/18071477/0082a01c-6e0b-11e6-87f8-f2a53e575c34.png)

@jeffstieler - is both the retail rate AND the discounted rate (e.g. CBP/CPP) available?

@kellychoffman @avivapinchas - what do you think of promoting our beneift to the merchant this way? I'm thinking this would appear on the same side of the dialog as the preview box, possibly below it.

![screen shot 2016-08-29 at 5 08 01 pm](https://cloud.githubusercontent.com/assets/1595739/18071510/44276c9e-6e0b-11e6-9167-96a3f4f6426f.png)

**Comment by kellychoffman** [comment]
👍  sounds good to me.

I'll wait for the answer re: availability before mocking anything up.

**Comment by jeffstieler** [comment]
@allendav answer from Easypost:

> EasyPost will be returning your negotiated rate via the “rate” attribute and the Commercial Base Pricing via the “list_rate” attribute. We can also pass back the Commercial Plus rate too, however, that is not exposed via the API at the moment since that is normally passed back as the “rate”. The USPS retail rate can also be exposed. Our rating engine already generates those values but are not currently being passed back via the API. Implementing these two features won’t take much time. Once a service agreement is signed we can add those features.

**Comment by jeffstieler** [comment]
Closing in favor of https://github.com/Automattic/woocommerce-services/issues/819.
