### ISSUE TITLE
In a Purchase Label request, send the carrier ID selected by the user during checkout

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#525]
Right now, we are sending a hardcoded `"usps"` carrier ID when requesting address normalization, shipping rates or actually purchasing a label. When we support more shipping carriers, we will need to get the carrier to use from some place (order meta-data, WCC configuration, etc).

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/952
