### ISSUE TITLE
Now that we have a settings page, include a link to it from the plugin row

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#534]
![screen shot 2016-09-06 at 12 13 39 pm](https://cloud.githubusercontent.com/assets/1595739/18287325/89af678c-742b-11e6-9e0d-211526748e89.png)

**Comment by allendav** [comment]
In light of #655 let's point this at the payment method sub-tab

**Comment by jeffstieler** [comment]
Closing this - it become less obvious where to link "Settings" as we add more functionality (e.g. payments).
