### ISSUE TITLE
Connect status and Jetpack debug disagree on connection health

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#535]
![screen shot 2016-09-06 at 12 41 57 pm](https://cloud.githubusercontent.com/assets/1595739/18288270/87b8d216-742f-11e6-9e15-6829e4f3414f.png)

The particular problem is an identity crisis - the siteurl protocol mismatches:

```
Something has gotten mixed up in your Jetpack Connection!
IDENTITY_CRISIS:
Your `siteurl` option is set up as `https://connect.mystagingwebsite.com`, but your WordPress.com connection lists it as `http://connect.mystagingwebsite.com`!
Your `home` option is set up as `https://connect.mystagingwebsite.com`, but your WordPress.com connection lists it as `http://connect.mystagingwebsite.com`!
```

![screen shot 2016-09-06 at 12 41 19 pm](https://cloud.githubusercontent.com/assets/1595739/18288273/9154fb1a-742f-11e6-8794-2bf74b9f4cd4.png)

**Comment by allendav** [comment]
According to @kraftbj - this could be a false warning from Jetpack, as running the debug from jetpack.com reports the connection is quite alright.

**Comment by kraftbj** [comment]
Circling back to see if y'all need additional assistance on this? What is WCC using to poll the Jetpack status?

**Comment by jeffstieler** [comment]
_thread necro..._

@kraftbj we're using `Jetpack::is_active()`, see: https://github.com/Automattic/woocommerce-services/blob/master/classes/class-wc-connect-help-view.php#L93

**Comment by kraftbj** [comment]
I think that should be fine to use.
