### ISSUE TITLE
Labels: If an address is invalid, display the reason if known and highlight the invalid field(s)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#540]
e.g. highlight an invalid name, street address, city or postcode (for countries that require postcodes) _and_ mention it in the expander heading

e.g. "Invalid address - `city` is a required field" or "Invalid address - multiple fields are missing below" or "Invalid address - invalid postcode"

<img width="637" alt="screen shot 2016-09-07 at 1 56 07 pm" src="https://cloud.githubusercontent.com/assets/1595739/18328652/9bb663ac-7504-11e6-809e-5a8e8bac3090.png">

**Comment by kellychoffman** [comment]
If a required field is missing, there should also be a contextual error message around that field:

![screen shot 2016-09-07 at 3 10 31 pm](https://cloud.githubusercontent.com/assets/5835847/18328978/bd7dd772-750e-11e6-9d17-7b45129aa106.png)

**Comment by v18** [comment]
We should also report to the user what the error is, for example the error "This address is not recognized. Please try another." is shown when an apartment or suit number is needed, which is not obvious:

Error shown:
<img width="851" alt="screen shot 2017-03-22 at 7 51 32 am" src="https://cloud.githubusercontent.com/assets/11487924/24196580/a5ca721a-0ed4-11e7-8ac5-3fb29a60ec0e.png">

Verbose error:
<img width="452" alt="screen shot 2017-03-22 at 7 53 45 am" src="https://cloud.githubusercontent.com/assets/11487924/24196594/b34728f2-0ed4-11e7-8c5d-41c3bb1c0278.png">

**Comment by kellychoffman** [comment]
@v18: Agree! If we know the specific reason, we should state that. If not, we should expose the more general 'address not recognized' error.

**Comment by nabsul** [comment]
Sort of related to: #913 (or at least would make sense to fix in the same PR)
