### ISSUE TITLE
Labels: Rates UI - Show notice if customer's chosen rate isn't available

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#546]
Show a notice (see design below) if the rate chose by the customer at checkout isn't available during label purchase.

![](https://cloud.githubusercontent.com/assets/5835847/18020665/d152746a-6b9f-11e6-90bd-fd234e4d87b5.png)

**Comment by allendav** [comment]
@jeffstieler - assigning to you in order to get a fresh preliminary estimate... please update the estimate, or let me know if it is still 2

**Comment by jeffstieler** [comment]
@kellychoffman is this something we want to hook back up? _(in Calypso of course)_

**Comment by kellychoffman** [comment]
Yes, please.

**Comment by laurendavissmith** [comment]
Closed, not relevant given the new UI designs
