### ISSUE TITLE
Rates should be fetched even if the user doesn't click in the address "Confirm" button

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#547]
Expected behaviour: When an address is normalized, even if the user closes the step without clicking `Use selected address`, everything should work.

Current behaviour: The rates are not fetched until the user opens the address step and clicks `Use selected address`.

I think the "Confirm" buttons are a help for the user. Until this point, they are not mandatory, a label could be purchased just opening and closing steps, without clicking the steps' buttons. A step with status `Warning` should be treated as "Correct" by all the form logic.

See screenshot:
![rates](https://cloud.githubusercontent.com/assets/1715800/18369983/2e46b3ee-7621-11e6-9783-ce5e8202231b.png)

**Comment by laurendavissmith** [comment]
Closed, this will be addressed partially with the new design updates
