### ISSUE TITLE
Trying to buy a shipping label with no payment method selected

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#549]
I tried to buy a shipping label before selecting my payment method and the error message wasn't clear about that.

**Comment by allendav** [comment]
@kellychoffman - i think we should put a link in the Purchase Label meta box prompting them to select a payment method (or add one at wordpress.com if there is none) if no payment method is selected/available - what do you think?

**Comment by jeffstieler** [comment]
I think it makes sense to work https://github.com/Automattic/woocommerce-connect-client/issues/447 as part of this. I'll add it to the design ticket as well.

**Comment by jameskoster** [comment]
I'll work on this one on Monday

**Comment by v18** [comment]
@jeffstieler - should this be in Sprint 12 as well, because #588 was assigned to Sprint 12 yesterday, and they'll probably be worked on in tandem?

**Comment by jeffstieler** [comment]
> @jeffstieler - should this be in Sprint 12 as well, because #588 was assigned to Sprint 12 yesterday, and they'll probably be worked on in tandem?

@v18 we try to stagger the design and implementation issues by one sprint, so we have ample time to work through design without eating into all of the time to develop the feature. We will likely run into features that can be designed and developed in a single sprint, so let's just keep evaluating as we go.
