### ISSUE TITLE
If a merchant cancels an order for which they have already purchased a shipping label...

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#560]
would it be possible to automatically prompt them to initiate a refund of the shipping label (if within the 30 day limit - https://www.easypost.com/faq.html#how-do-refunds-work )

This idea came from Happiness Academy.

@kellychoffman - it could be interesting to see what s9n is proposing for order actions and how we might design this for wp-admin with that future in mind. cc @coderkevin

**Comment by kellychoffman** [comment]
> what s9n is proposing 

✨ magic ✨ 

Design in progress. Will mention you when posted.

**Comment by laurendavissmith** [comment]
Closing, not sure if a design ever ended up getting made for this one
