### ISSUE TITLE
Connect-a-thon: Do not allow labels to be purchased for cancelled orders

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#576]
and possibly other states?

**Comment by allendav** [comment]
Assigning for preliminary estimate, please.

**Comment by DanReyLop** [comment]
If this change were "just don't show the meta-box for cancelled orders", it would be trivial. **But**, if we want to show the meta-box if the order had some label purchased already, then this issue will involve a wee bit of JS.

**Comment by laurendavissmith** [comment]
Closing, we'll want to wait and see if store owners are being affected by this or if its an unintended feature
