### ISSUE TITLE
Connect-a-thon: Display delivery speed/date in labels UI for each service

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#577]
See also #561 

i.e. along the lines of "If there is a shipping option that’s faster than what the customer paid for and still cheaper or the same than what they paid for, we should prompt our users about that option. AKA faster shipping for still what the customer already paid for == happy customers." cc @mikeyarce

**Comment by laurendavissmith** [comment]
Closing, this won't be relevant for the new designs
