### ISSUE TITLE
Connect-a-thon: Red is jarring if no rate is available from checkout

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#578]
Could we use yellow or something else for this case?

i.e. "After validating destination address, you see red error message before you select the rate (first class, 2-day, etc.). The red is jarring." @nabsul 

@kellychoffman - needs design input first, then we'll roll this over for dev

**Comment by kellychoffman** [comment]
Question: Can the rate the customer chose at check out be automatically selected here? This should   allow the majority of users to not ever click into here. 

If that rate isn't available for some reason, we should have the store owner perform this task manually. In this case, this should be the error UI:

<img width="621" alt="screen shot 2016-12-14 at 4 46 51 pm" src="https://cloud.githubusercontent.com/assets/5835847/21206072/f84ec41e-c21c-11e6-9d09-928aeac11988.png">

**Comment by allendav** [comment]
> Question: Can the rate the customer chose at check out be automatically selected here?

Yes - that rate should be pre-selected when available.

> If that rate isn't available for some reason, we should have the store owner perform this task manually

Agreed - there is kind of a list we could work our way through:

- Did the customer select a USPS service during checkout?  If so, pre-select that service if available.
- Otherwise... does the selected packaging demand a specific service (e.g. Priority Mail Small Flat Rate Box)? If so, pre-select that service.
- Otherwise... has the merchant ever bought a label before? If so, pre-select that service if available.
- Otherwise... pre-select the least expensive service

How does that sound, @kellychoffman ?

**Comment by kellychoffman** [comment]
Sounds perfect.

**Comment by laurendavissmith** [comment]
Closing, this won't be relevant with the new design
