### ISSUE TITLE
Add insurance to labels UI

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#582]
Design the shipping label insurance flow.

Insurance is purchased for a dollar amount, and (currently) costs a fixed percentage of that insured amount, with a minimum cost.

_(edited by @jeffstieler)_

**Comment by allendav** [comment]
Also requested here: https://wordpress.org/support/topic/free-shipping-17/

**Comment by kellychoffman** [comment]
Input insurance in Rates section, surfaced in Summary in right sidebar section.

<img width="495" alt="screen shot 2017-03-07 at 11 23 03 pm" src="https://cloud.githubusercontent.com/assets/5835847/23692632/1f0d09b0-038d-11e7-92cb-478086dfc477.png">

**Comment by allendav** [comment]
Cool beans!

Idea: Use a checkbox, hidden text-input for insurance instead. Checking the checkbox should unhide the text-input. The text-input should be pre-filled with the cost of the items in the package. 

The checked/unchecked state of the checkbox could be used for subsequent labels and saved in the merchant's user's meta.

FWIW, some services include insurance anyways. It might be helpful, if the merchant checks the box, to let them know if additional insurance is not necessarily warranted.  With some exceptions, Priority Mail Express shipments include up to $100 of insurance and Priority Mail shipments may include up to $50.

**Comment by kellychoffman** [comment]
Just so I understand your reasoning behind a checkbox: Is it because some services provide a preset amount?

> Edit: Also, I'm not sure, but I think some services cannot be insured.

We can not display the insurance for those cases.

**Comment by allendav** [comment]
> Is it because some services provide a preset amount?

Nope - it was just to keep the UX cleaner by hiding the insurance text-input (and explanatory text, e.g. regarding insurance already included) for the vast majority of merchants (most merchant's packages do not take advantage of or require extra insurance.)

Ref: http://www.bankrate.com/finance/insurance/shipping-insurance.aspx

**Comment by allendav** [comment]
> We can not display the insurance for those cases.

Totes. Probably need a flag on the service from the server to know to suppress the insurance affordances when such services are SELECTed.

**Comment by kellychoffman** [comment]
> Regarding insurance already included

In these cases, can you add extra insurance on top of this or no?

**Comment by allendav** [comment]
> In these cases, can you add extra insurance on top of this or no?

Yes, up to some limit (like $3000 or something)

**Comment by kellychoffman** [comment]
Thanks, that changes things a bit. I shall iterate.

**Comment by jeffstieler** [comment]
> > Also, I'm not sure, but I think some services cannot be insured.
> We can not display the insurance for those cases.

The insurance we'll be using is through EasyPost, and not through each individual carrier. If EasyPost supports the carrier, we can insure the shipment. 👍

**Comment by kellychoffman** [comment]
No insurance included with service:
<img width="270" alt="screen shot 2017-03-08 at 10 02 28 pm" src="https://cloud.githubusercontent.com/assets/5835847/23736722/26249bc8-044b-11e7-8c94-1cd3113763f4.png">

Insurance included with service:
<img width="272" alt="screen shot 2017-03-08 at 10 02 36 pm" src="https://cloud.githubusercontent.com/assets/5835847/23736723/262a4730-044b-11e7-9998-0f1e0abcbd63.png">

**Comment by fhaps** [comment]
Reopening. User requesting this feature on this forum thread.: https://wordpress.org/support/topic/any-way-to-automatically-send-tracking-number-to-customer-upon-order-shipment/

**Comment by laurendavissmith** [comment]
Closing, we have a new design for this now
