### ISSUE TITLE
Design: Warn a user if they are flagged or blocked

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#589]
If a user gets flagged or blocked for abuse, we should warn them in the wp-admin page somehow. They should also be given instructions on how to appeal the process.

@mikeyarce @kellychoffman @allendav

**Comment by allendav** [comment]
Excellent idea

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by jeffstieler** [comment]
This is not a frequently occurring issue - closing.
