### ISSUE TITLE
Get Canadian French working

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#591]
What do we need to do to support US English and Français du Canada? Most of our stuff appears in English even when the site is set for French:

This is needed for Beta because we are offering Canada Post and merchants may have their sites set for French, especially in Quebec.

<img width="786" alt="screen shot 2016-09-28 at 5 57 11 pm" src="https://cloud.githubusercontent.com/assets/1595739/18937476/59cc59ae-85a5-11e6-9ec4-df797a2936e4.png">

**Comment by laurendavissmith** [comment]
Closing since we are not focusing on live rates at the moment
