### ISSUE TITLE
Increase tracks coverage to include rates setup, label use and more

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#596]
We already know we want to make sure we have tracks coverage for onboarding, and those issues have that mentioned explicitly.  Are there other areas in the client that would benefit and give us a better idea of product engagement?

I.e. can tracks capture things like # of connected sites and what features are being used - are there changes needed to the client to support that?

also, lets add tracks events to help us see where merchants might be getting stuck setting up a feature (ie they added live rates, but then got lost setting up labels or custom packages or something)?

After we identify what we want to add, we can use this issue to add the tracks events to the code

**Comment by jeffstieler** [comment]
Let's identify a few flows we'd like to have data on.

For example:
* User accepted TOS, added a shipping method, never saved it
* User configured shipping method, but never got rates
* User set everything up, got rates, and purchased a label

**Comment by laurendavissmith** [comment]
Closing, we'll revisit Tracks holistically with the new designs
