### ISSUE TITLE
Connect-a-thon: Use actual addresses for preview label 

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#598]
Not sure we can get this in MVP, but it was observed during Connect-a-thon that if you look really close at the preview label you can tell that the label isn't using the address of the store nor the customer.

Maybe we could be a little less fake :P 

cc @jameskoster

**Comment by DanReyLop** [comment]
Per https://github.com/Automattic/woocommerce-services/issues/819, Label Preview is gonna be removed, so closing this
