### ISSUE TITLE
Show a buy label / label bought button in the Actions on each row in the (Bulk) Orders page

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#601]
i.e. here:

![screen shot 2016-10-03 at 4 28 04 pm](https://cloud.githubusercontent.com/assets/1595739/19057708/ba567ee6-8986-11e6-859c-4742e32e2344.png)

**Comment by laurendavissmith** [comment]
@olaolusoga what are your thoughts on this one?

**Comment by olaolusoga** [comment]
We can close. Not the direction we would head for bulk shipping.
