### ISSUE TITLE
Connect-a-thon: Move Shipping Label box higher

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#602]
On many laptops/monitors, the Shipping Label box appears below the fold. Maybe it should be above Order Notes by default?

<img width="1076" alt="screen shot 2016-10-03 at 4 32 17 pm" src="https://cloud.githubusercontent.com/assets/1595739/19057786/4e123472-8987-11e6-9ef3-19cd3ae8cd59.png">

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/pull/801
