### ISSUE TITLE
Connect-a-thon: Do a little checking on custom package dimensions

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#607]
"Default box dimensions may be unrealistic, and exterior should be different than interior:"

<img width="532" alt="screen shot 2016-10-03 at 5 51 28 pm" src="https://cloud.githubusercontent.com/assets/1595739/19059107/09333c38-8992-11e6-975d-c17abf669d71.png">

By unrealistic, we allow the user to enter package sizes that are unsupported by any carrier :) 

Props @WPprodigy

**Comment by jeffstieler** [comment]
For USPS (https://pe.usps.com/text/dmm300/201.htm#ep1097220):

> No mailpiece may weigh more than 70 pounds.
> 
> parcels may not measure more than 130 inches in length and girth combined.

For Canada Post (https://www.canadapost.ca/tools/pg/manual/PGpscanada-e.asp#1431012):

>  min. | Length = 100 mm; Width = 70 mm; Height = 1 mm; Weight = None
> 
> max. | Length: 2 m; Length + Girth*: 3 m; Weight = 30 kg**

**Comment by laurendavissmith** [comment]
Closing, we'll revisit this after multi-carrier support since that could affect what's happening here
