### ISSUE TITLE
An empty response to get_payment_methods should at least log an error

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#616]
If `fetch_payment_methods_from_connect_server()` in `class-wc-connect-payment-methods-store.php` gets an empty response from `$this->api_client->get_payment_methods()` it should at least log an error and perhaps also clear all stored payment methods.

**Comment by dechov** [comment]
This is the error currently logged in this case:

```
03-02-2018 @ 22:04:27 - wcc_server_error_response Error: The WooCommerce Services server returned: Internal Server Error An internal server error occurred ( 500 ) (fetch_payment_methods_from_connect_server)
```

1. While this is kind of clear in the end about what it is that failed, the repetitive "server error" language obviously isn't helpful or friendly — we should log a better message.
2. We should probably render an error or warning notice in the client, either global or in context above the cards.
3. Clearing stored payment methods makes some sense to me, though I'm not sure if we should unnecessarily break the merchant's flow in the event the card they want to use was already fetched.

**Comment by laurendavissmith** [comment]
Closing, we'll reassess at a later date if it continues to be an issue
