### ISSUE TITLE
Add an npm task to submit a tagged release to the wordpress.org repo

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#636]
Possibly leverage https://github.com/mikejolley/github-to-wordpress-deploy-script

Basically use our `npm run release` task as a starting point and add an "upload to SVN" part

Don't save secrets in the repo of course :)

**Comment by allendav** [comment]
npm run release doesn't currently add readme.txt to the zip - it should

**Comment by jeffstieler** [comment]
Current process:

Releasing new plugin versions to WP.org
Hopefully this knowledge is wholly unneeded, but you never know.

1. Make sure master is up-to-date with all changes
2. Create a release branch, like `release/1.2.1`
3. Update the plugin version in: `package.json`, `woocommerce-services.php`, and `readme.txt`
4. Create a changelog section in `readme.txt`
5. Merge release branch into master
6. Run release task – `npm run release`
7. Checkout plugin from svn into a separate directory
8. Copy all files from `release/woocommerce-services` to svn trunk directory
9. Copy `readme.txt` to svn trunk directory
10. `svn commit -m "Updating trunk to latest." --username woothemes`
11. `svn cp trunk tags/1.2.1` – use correct version tag
12. `svn commit -m "Tagging version 1.2.1" --username woothemes` – use correct version tag
13. Check https://wordpress.org/plugins/woocommerce-services/ for the update

**Comment by laurendavissmith** [comment]
Closing as Extendables have a release script to handle this
