### ISSUE TITLE
Design: Tell users how to opt-out of connect (i.e. by uninstalling the plugin)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#643]
Needs design. Not sure how we want to approach this.  I see two possibilities:

1) Perhaps opt-out is implicit if the user de-activates the connect plugin. Question - would automatic updates trigger unwanted disconnects/re-prompts?

2) Perhaps opt-out is explicit - i.e. we expose a button somewhere to opt-out. Perhaps that button also immediately de-activates the plugin as well.

Either way, any subsequent re-activation of the plugin should prompt them to opt-in again.

@pesieminski @jennyzhu - preference?

**Comment by DanReyLop** [comment]
> Any subsequent re-activation of the plugin should prompt them to opt-in again.

Is this a legal requirement? The way I see it, Connect can be deactivated / uninstalled like any other plug-in. I remember that there are different hooks for when the plugin is deactivated, activated and uninstalled, so we have the means to clean-up an "I've already opted-in" flag if we want to.

> Would automatic updates trigger unwanted disconnects/re-prompts?

No, none of the hooks described above trigger when updating the plugin.

**Comment by pesieminski** [comment]
Would Connect effectively be un-usable without the connection? 

If so, then I think it's fine to just tell users how to uninstall the plugin, and as part of that the connection is broken. No need for a separate opt out button for the connection, separately.

If they then re-install, I think it makes sense to start fresh with a new authorization.

**Comment by allendav** [comment]
> Would Connect effectively be un-usable without the connection?

Yes

> If so, then I think it's fine to just tell users how to uninstall the plugin, and as part of that the connection is broken. No need for a separate opt out button for the connection.

OK, let's do this

> If they then re-install, I think it makes sense to start fresh with a new authorization.

OK. Let's also use this issue to clear the opt-in option on uninstall to force a fresh authorization on re-install

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by kellychoffman** [comment]
> If so, then I think it's fine to just tell users how to uninstall the plugin, and as part of that the connection is broken. No need for a separate opt out button for the connection.

Maybe we could add this to the health status page?

**Comment by jeffstieler** [comment]
We are now cleaning up plugin options on uninstall (https://github.com/Automattic/woocommerce-services/pull/880) - this removes the TOS acceptance flag.

> > If so, then I think it's fine to just tell users how to uninstall the plugin, and as part of that the connection is broken. No need for a separate opt out button for the connection.
> 
> Maybe we could add this to the health status page?

@kellychoffman I don't think users are likely to visit the health status page unless they are having problems. If they want to uninstall the plugin, they may never visit the health status page.

@pesieminski Do we really need to tell them that uninstalling the plugin opts them out? If they uninstall, then reinstall, they'll be prompted to accept the TOS again.

**Comment by kellychoffman** [comment]
> We are now cleaning up plugin options on uninstall (#880) - this removes the TOS acceptance flag.

Nice.

Is there any reason why we can't do what Jetpack does: Upon uninstall, the user is disconnected and the plugin options are cleaned up. There's no overt communication that opt-outing out of Jetpack means uninstalling the plugin.

**Comment by jeffstieler** [comment]
> Is there any reason why we can't do what Jetpack does: Upon uninstall, the user is disconnected and the plugin options are cleaned up. There's no overt communication that opt-outing out of Jetpack means uninstalling the plugin.

Nope - I think that's totally reasonable. Closing this.
