### ISSUE TITLE
Periodically refresh the refund status for a label in Edit Order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#645]
Right now, if a user requests a refund of a label, we hardcode `Refund submitted` and never check the status of the refund request again. We should fetch the status and update that, maybe on entering Edit Order or something.  We could show the date the refund was completed and the amount.

This is probably not necessary for MVP.

**Comment by DanReyLop** [comment]
Just adding to that:
When the Edit Order page is opened, there **is** already a request made to the WCC server for each purchased label. It just happens that in the returned data it's not included the `refund_status`. This issue should be a lot easier than it looks, probably worth it to squeeze it into MVP.

**Comment by allendav** [comment]
Sweet - we might not need a new endpoint then :) Let's consider this after all the higher priority issues first though

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/805
