### ISSUE TITLE
Shipping labels: Package errors when using woocommerce-2.7.0 dev version

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#653]
I'm using the latest dev version of woocommerce. I can receive rates at checkout no problem. The problem comes in when I go to the order and create a label. Here's what happens:
1. Create a label
2. This error message appears in the console: 
   https://cloudup.com/izaVN_XvCJk
3. Fill out and confirm address
4. Skips past an errored Packages step, opens up rates step instead
5. Manually open packages step, see message that says there are no items or packages (even though there is both)
   ![screen shot 2016-10-28 at 10 08 43 am](https://cloud.githubusercontent.com/assets/5835847/19819056/10de7d76-9d10-11e6-906e-98812a005c2a.png)
6. Add package big enough for item to fit into, see that there is still no item
   ![screen shot 2016-10-28 at 10 09 24 am](https://cloud.githubusercontent.com/assets/5835847/19819063/2406a5a4-9d10-11e6-9c31-0ccf33820975.png)
7. 😭 
8. (╯°□°）╯︵ ┻━┻
   ....
9. Delete the dev version and replace with woocommerce 2.6.7 
10. 😀  🎉

**Comment by robobot3000** [comment]
So this happens because for some reason WooCommerce plugin doesn't persist the `wc_connect_packages` field into the database. The console error is indirectly caused by that - i.e. we return an empty array when there are no packages/rates instead of an empty object.

**Comment by allendav** [comment]
Assigning for preliminary estimate, please :)

**Comment by allendav** [comment]
Also seeing this in Edit Order > Shipping Label with 2.7.0-dev 7 Nov 16:

```Notice: id was called incorrectly. Order properties should not be accessed directly. Please see Debugging in WordPress for more information. (This message was added in version 2.7.) in /Applications/MAMP/htdocs/wp-includes/functions.php on line 3996
```

**Comment by allendav** [comment]
Moving out of sprint 8 and into sprint 9

**Comment by allendav** [comment]
And now into sprint 10, as we await confirmation of The Direction

**Comment by allendav** [comment]
OK, since Connect is not going into WooCommerce core, and since WooCommerce 2.7 will not be released until next year, we need to have Connect support both 2.6 and 2.7

**Comment by DanReyLop** [comment]
Useful doc: https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes
