### ISSUE TITLE
Move Connect for WooCommerce Settings under Shipping instead

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#655]
Props @avivapinchas for the cool idea during today's sprint demos. Instead of having a separate tab devoted to Connect for WooCommerce, since we are emphasizing the services Connect for WooCommerce offers and NOT CfW itself, let's have the CfW sub-tabs under Shipping (and eventually other tabs as appropriate)

So... let's

- [ ] Get rid of the Connect for WooCommerce tab that we have under WooCommerce > Settings right now
- [ ] Rename the Account Settings sub-tab as "Shipping Labels" and move it under the Shipping tab
- [ ] Move the "Packaging Manager" sub-tab under the Shipping tab

I'm giving this a preliminary estimate of 2

**Comment by allendav** [comment]
Removing from sprint 10, as a result of The Direction chat. Will wait and see on this.

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/825
