### ISSUE TITLE
Warn the merchant if their refund request was rejected

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#662]
Both when initiating the refund and when reviewing that order later.  Display something like the following:

This label is not eligible for refund. This is usually because the label is too old or has already been used to ship a package. Please contact us if you believe this is in error.

The contact us should be a link that includes the receipt id somehow if possible.

**Comment by laurendavissmith** [comment]
Closing, not sure how relevant this is currently

**Comment by c-shultz** [comment]
This issue still exists. If I refund a label for a label that's marked as shipped, I get an unhelpful 500 error: 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/6209518/68808191-12a7e500-061e-11ea-8c9a-a66f468b156a.png">

The real reason appears in the connect server log:
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/6209518/68808282-3c610c00-061e-11ea-8875-60a5224cb678.png">

**Comment by iyut** [comment]
This issue might be fixed in this [PR](https://github.com/Automattic/woocommerce-connect-server/pull/1867). Feel free to re-open this issue if someone think otherwise.
