### ISSUE TITLE
woocommerceconnect_opted_in tracked before opt-in

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#665]
With WP_DEBUG on, the following is logged even before accepting our TOS

> [03-Nov-2016 22:01:22 UTC] Tracked the following event: woocommerceconnect_opted_in

It shouldn't be, at least not until they actually opt-in :)

**Comment by jeffstieler** [comment]
This is errantly attached to the plugin activation/deactivation hooks.
