### ISSUE TITLE
Improve the preview PDF rendering on all browsers

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#675]
In the "Purchase Label" UI, the little `PREVIEW` at the right side of the modal is a dynamically generated PDF, embedded in the page using an `<iframe>` tag. As these GIFs demonstrate, its presentation is very different across the different browsers:

Chrome:
![preview-header-and-scrolling](https://cloud.githubusercontent.com/assets/1595739/20072088/f3f07aa6-a4db-11e6-85dd-967ce8554bd7.gif)

Firefox:
![firefox-pdf-labels](https://cloud.githubusercontent.com/assets/1595739/20072395/00506094-a4dd-11e6-94ef-17494ad0f4a8.gif)

Safari:
![safari-pdf-labels](https://cloud.githubusercontent.com/assets/1595739/20072478/6aeddada-a4dd-11e6-8f45-0ba6124937da.gif)

How to fix:
* Some PDF viewers honor some specific arguments passed to the URL after the `#` delimiter. [Spec](http://partners.adobe.com/public/developer/en/acrobat/PDFOpenParameters.pdf). That can be a starting point, but not all PDF viewers respect that, and not all of those that do implement all the options.
* [PDF.js](https://mozilla.github.io/pdf.js/) is a pure JS library that allows rendering PDFs into a `<canvas>`. It's used as the base for the Firefox built-in PDF viewer. That means that we would have full control on its size, scroll position, no toolbars, etc. Maybe we should consider it as the last option, because it would add significant bloat to our app.
* Maybe we could do some trickery on the line of putting an invisible `<div>` on top of the PDF so the PDF won't receive `onmousemove` events and the zoom/toolbar controls won't show up (we would need to relay the scroll events, though).
* Since it's clear that PDFs are not made to be embedded in a page, we could use images instead. That would require that the server, when requested a `preview` PDF, it would generate the PDF, render it into an image (or one for each page I guess) and return *those* images to the client. To do that, there are quite a few options, but all of them involve installing, apart from an `npm` package, a graphics processing library, such as `cairo` or `imagemagick`. That would mean that the server wouldn't fully work with just a simple `npm install` anymore, and that makes kittens cry 😿

**Comment by allendav** [comment]
Thank you for writing this up @DanReyLop 

That last option does sound interesting - a preview image array - but let's not worry about this for Connect 1.0 - the meh experience is good enough for now and we'll have to do more work in this area for Connect 1.1 if/when international label and customs forms support gets added.

**Comment by DanReyLop** [comment]
Per https://github.com/Automattic/woocommerce-services/issues/819, Label Preview is gonna be removed, so closing this
