### ISSUE TITLE
Add USPS International Label Support

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#676]
This is an epic to allow merchants to purchase USPS labels for international shipments and assist them in completing customs forms for those shipments.

Not in scope for Connect 1.0. TBD program.

**Comment by DejaAugustine** [comment]
Just curious if this is something that will ever be added to WooCommerce Services?

The domestic labels are great, but about 1/4 of my order volume is international, but my overall volume isn't enough to justify buying two separate $75 plugins to be able to buy/print international postage via stamps.com

**Comment by rwaynick** [comment]
User was confused about why the Shipping Label meta box didn't appear on one of their orders to Canada in 1296790-zen. I linked them to the FAQ (https://docs.woocommerce.com/document/woocommerce-services/#section-10) and let them know that it's not available. But would it be possible to have the meta box with a message on the Order Detail page letting them know it's not available for International orders at the moment? Thanks :)

**Comment by laurendavissmith** [comment]
Closing, will reopen once we have plans in place to support USPS International
