### ISSUE TITLE
Enforce having parenthesis in the argument list of arrow functions

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#679]
ESLint rule: `'arrow-parens': 1`
Documentation: http://eslint.org/docs/rules/arrow-parens
It can be fixed automatically by ESLint.

This rule forces to add parenthesis to the arguments of an `=>` function, even if the function only has a single argument.

I don't see it enforced in `wp-calypso`, but I somehow remember that we have that rule. So this task is either to add this rule to `.eslint.js`, or if you decide it's not worth enforcing it, ping the entire team on this issue so we know it's permitted to omit parenthesis, and then close it.

Don't forget to change this in the server too.

**Comment by jeffstieler** [comment]
This is irrelevant now, eh @DanReyLop ?

**Comment by DanReyLop** [comment]
Yeah, in `wp-calypso` it isn't enforced and we don't have that "convention" in writing anywhere, so this can be closed :)
