### ISSUE TITLE
Blank Zip Code "Error" in shipping method instance settings is jarring

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#708]
When no postal code is given for a shipping method, you get much redness.

Maybe we could make this some kind of warning instead, and yet still prevent them from saving their settings without it.

See also https://github.com/Automattic/woocommerce-connect-client/issues/578

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/pull/809
