### ISSUE TITLE
On self-help, provide links for Jetpack and WooCommerce if they are not installed

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#710]
If not installed, the ideal link would direct the merchant to their own wp-admin > Plugins > Add New with the appropriate plugin pre-filled in the search box.

If installed but not activated, the ideal link would direct the merchant to their own wp-admin > Plugins page, with the errant plugin(s) highlighted.

**Comment by nabsul** [comment]
Shall we focus on sending them to install Jetpack only? It would be highly unlikely for someone to install Connect without having WooCommerce already...

**Comment by jeffstieler** [comment]
Closing - there is no self help page if WooCommerce isn't active, and we now have a big banner when Jetpack is inactive/missing/disconnected.
