### ISSUE TITLE
MIME type warning for label preview

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#718]
The following appears in the dev console during label preview:

<img width="748" alt="screen shot 2016-11-17 at 3 43 55 pm" src="https://cloud.githubusercontent.com/assets/1595739/20412637/e06c8e9e-acdc-11e6-9bf4-0a44a923b0f2.png">

**Comment by robobot3000** [comment]
Closing - see https://github.com/Automattic/woocommerce-connect-client/pull/766#issuecomment-270878404

**Comment by jeffstieler** [comment]
Reopening - while our current hack works, it's not 100% proper usage. Ideally we should be using `<embed>`.

This is definitely low priority though. See [this SO answer](https://stackoverflow.com/a/32215374) for ideas on solving the `<embed>` re-render at a later time.

**Comment by DanReyLop** [comment]
Per https://github.com/Automattic/woocommerce-services/issues/819, Label Preview is gonna be removed, so closing this
