### ISSUE TITLE
Should we allow packages with zero dimension value?

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#723]
![image](https://cloud.githubusercontent.com/assets/11143071/20544522/5252bdf4-b0bf-11e6-9094-be411c8b3255.png)

**Comment by jeffstieler** [comment]
No, we shouldn't.

**Comment by jeffstieler** [comment]
Let's not close this until the `wp-calypso` dependency has been updated.

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1268
