### ISSUE TITLE
Copy updates for the plugin description, etc

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#729]
Drop the word "free" from the plugin description.  Props @msdesign21 for the suggestion that the word free does not add value (by default, plugin behaviors, especially wordpress.org plugins, are free)

![screen shot 2016-11-23 at 1 29 44 pm](https://cloud.githubusercontent.com/assets/1595739/20579368/20821e42-b181-11e6-81eb-47ef15eba3c9.png)

cc @avivapinchas

**Comment by msdesign21** [comment]
> To use the features, simply install this plugin and activate the ones you want directly in your dashboard. 

Instead I was thinking it might be more clear to say: 

>To use the features, install this plugin and activate the **services** you want directly in your dashboard. 

Would it be more appropriate to say "in your **Connect** dashboard" ?
