### ISSUE TITLE
Update CREDITS.md

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#735]
It has not been updated since the start of the project. Let's:

- [ ] Identify things to add or remove
- [ ] Confirm our approach to npm modules is still appropriate - maybe we should actually come up with a way to list license notices from all the packages we use (and their packages) ?
- [ ] Scan our dependencies licenses to ensure they are compatible with ours

props @pesieminski @nabsul 

See also our "doing it right" thread

See also https://github.com/davglass/license-checker and https://github.com/pivotal/LicenseFinder

**Comment by laurendavissmith** [comment]
Closing, will revisit via p2
