### ISSUE TITLE
Design: Notify merchant when our terms of service or data policy have changed

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#736]
e.g. with a notice in wp-admin, e.g. something like the following (screen cap from a website):

<img width="377" alt="screen shot 2016-11-29 at 11 29 33 am" src="https://cloud.githubusercontent.com/assets/1595739/20725574/257283f6-b627-11e6-8f10-eee58a9c6974.png">

Maybe we can use a DATE field in the /services response to detect changes. See corresponding server issue.

cc @pesieminski @jennyzhu @kellychoffman

**Comment by jameskoster** [comment]
I'll take this one. 

Quick question though; what's the latest on how we refer to Connect in copy like this? IE we can't say "Our terms have changed" as "our" isn't specific enough. Should we just say "We see your using service X, the terms have changed" or is it OK to reference "Connect for WooCommerce"?

**Comment by kellychoffman** [comment]
Glad to see you're taking this on. We are not going to be referring to 'Connect for WooCommerce' anymore, instead with the specific service or group of services like you mentioned in your first example: 

> "We see your using service X, the terms have changed"

**Comment by jennyzhu** [comment]
We chatted with @allendav about this after he filed the issue; this type of notification would be  something we’d do once in a blue moon, when we make a material change. We do  immaterial updates pretty often and a notification to all users would be overkill.

Are you working on this just so we have it ready to go when we need it?

**Comment by kellychoffman** [comment]
> this type of notification would be something we’d do once in a blue moon, when we make a material change. We do immaterial updates pretty often and a notification to all users would be overkill.

👍 Totally agree. 

> Are you working on this just so we have it ready to go when we need it?

Yes, that is the idea.

**Comment by jameskoster** [comment]
Nothing particular exciting for this one I think :)

![tos-updated](https://cldup.com/jIJSLWcWx8.png)

Wasn't sure if we needed the title, but as this could be considered important information I figured it was probably warranted.

The notice will be dismissible like any other standard wp-admin notice. 

I should think it's obvious that if you don't agree with the new terms then you should disable the feature - or do we need to add some text to that effect?

**Comment by kellychoffman** [comment]
I think this looks good. The title is nice because it says it all at a quick glance. I don't think we need to add the disable text. I'd just add the `x` in there and change spelling to 'agreeing' and I say this good to go.

**Comment by jeffstieler** [comment]
Should this be shown everywhere an admin notice can be displayed, or just on specific screens?

For a v1, is anyone opposed to having the text on this notice be more generic and hardcoded?

Something akin to: "Connect for WooCommerce terms of service updated" (or whatever the user-facing name will be)

I don't think it's a ton of work to send down arbitrary notices, but I want to keep our options open for satisfying this feature.

**Comment by jameskoster** [comment]
> I'd just add the x or an Okay button to dismiss and change spelling to 'agreeing' and I say this good to go.

The `x` appears on hover (like other notices). OK button makes sense and I agree, will add that.

> Should this be shown everywhere an admin notice can be displayed, or just on specific screens?

I suspect this is probably important enough to be displayed globally. I wonder if there's any legal obligation? Updating terms _feels_ like the sort of thing one should make every effort to inform ones users about. Maybe @pesieminski can decide for us xD

> For a v1, is anyone opposed to having the text on this notice be more generic and hardcoded?

I asked a similar question earlier, the issue is that I don't think we want to refer to "Connect for WooCommerce" as a _thing_ at all [#](https://github.com/Automattic/woocommerce-connect-client/issues/736#issuecomment-270454552). If we want to be more generic I suppose we could say something like "The TOS for a Jetpack feature you're using have been updated".

**Comment by jameskoster** [comment]
Added the Okay button; feels like a more positive action to click that rather than the `x` to dismiss.

![okay](https://cldup.com/3CaDkpDwtL-3000x3000.png)

**Comment by jeffstieler** [comment]
> I suspect this is probably important enough to be displayed globally.
> Updating terms feels like the sort of thing one should make every effort to inform ones users about.

Agreed.

> I asked a similar question earlier, the issue is that I don't think we want to refer to "Connect for WooCommerce" as a thing at all #. If we want to be more generic I suppose we could say something like "The TOS for a Jetpack feature you're using have been updated".

We definitely don't want to refer to "Connect for WooCommerce", but I was under the impression that we'd have a more generic and friendly umbrella term, like "WooCommerce Cloud Extensions" or something to that effect.

Without having that generic catch-all name.. I think we need to be able to push down arbitrary messages from our server. It's more effort for sure, but probably the best place to start if we can't nail down generic enough language.

**Comment by jennyzhu** [comment]
> We are not going to be referring to 'Connect for WooCommerce' anymore, instead with the specific service or group of services 

Any more info/context anyone can provide on this? The [terms](https://woocommerce.com/terms-conditions/connect-terms/) and [privacy policy](https://woocommerce.com/terms-conditions/connect-privacy/) we created refer to "Connect for WooCommerce" so at the very least, that page that we push them to will have that name.

> Should this be shown everywhere an admin notice can be displayed, or just on specific screens?

When we display this notice (which won't be every time the TOS is updated) it should be shown everywhere an admin notice can be displayed.

Just a heads up that the text of the screen and button will depend on the scenario, but it'll probably be something more like:

> We’ve updated the Terms of Service [link]. Please give them a read and take a look at the revision history [link to Github comparison]. By using [product] after [DATE 30 days from now], you agree to the revisions.

Would it be possible to keep a log of when users dismiss the screen?

**Comment by v18** [comment]
> Would it be possible to keep a log of when users dismiss the screen?

I think, yes :)

Would we do anything if we don't hear back from the user that they have accepted? For example, re-sending the notice again?

**Comment by jeffstieler** [comment]
> Would we do anything if we don't hear back from the user that they have accepted? For example, re-sending the notice again?

**Comment by jennyzhu** [comment]
> I think we're fine just leaving the notice visible until they act on it. 

@jeffstieler Totally agree! The text could say something like:

> We’ve updated the Terms of Service [link]. Please give them a read and take a look at the revision history [link to Github comparison]. By Clicking Okay or using [product] after [DATE 30 days from now], you agree to the revisions.

Thanks all!
