### ISSUE TITLE
Microsoft Edge: TypeMismatchError when viewing orders with a purchased label

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#738]
The error appears briefly as a red notification...

![2016-11-29 3](https://cloud.githubusercontent.com/assets/1595739/20734400/14190f9a-b64e-11e6-95ca-757d5bcb9746.png)

then a moment later appears inline above the order details:

![2016-11-29 4](https://cloud.githubusercontent.com/assets/1595739/20734407/1a7499a4-b64e-11e6-9e99-f463e194d30a.png)

**Comment by DanReyLop** [comment]
Fixed by #884
