### ISSUE TITLE
Send how connect was discovered / installed to server 

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#742]
i.e. consider adding an option for whether the first install of connect occurred 1) as a result of a add-ons page prompt, 2) via jetpack manage, or 3) from a wp-admin plugins page search result

and send that value in requests to the server for inclusion in anonymized usage data

**Comment by nabsul** [comment]
It's probably better to implement this as a Tracks funnel. That way we don't end up with a mess of such options stored in the store's database.

**Comment by jeffstieler** [comment]
I believe the only installation methods that aren't tracked are .zip uploads and "add plugin" page installations. Do we still need additional tracking?

**Comment by laurendavissmith** [comment]
Closing for now
