### ISSUE TITLE
Debug log enable/disable not working on some sites

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#756]
On pressable sites, you can toggle debug logging to "enabled" on the self-help page but refresh the page and it shows disabled again even though the option (wcc_debug_logging_enabled) shows 1 when looking at it with connect helper.

I think the way options with values of 0 or 1 are saved might be causing some issues with the code here: https://github.com/Automattic/woocommerce-connect-client/releases/download/v0.9.4/connect-for-woocommerce.zip

**Comment by WPprodigy** [comment]
Experiencing this issue as well ^

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/commit/716047173b1f792f484d51936cef0cb44a89434f.
