### ISSUE TITLE
Add a way for merchants to contact us

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#760]
At least while we're still in Beta / MVP, it would be good to get the e-mails of merchants that will be open to give feedback about Connect. We can do it in various ways:

* Show a banner when Connect is installed for the first time, with a simple text among the lines of "Help us make this better! Click here to allow us to contact you by e-mail <Accept> <Dismiss>".
* Do that, plus ask permission to get statistics about the shop (volume, countries from/to is shipping, etc). This way, for example, when we are planning to implement the Customs form, we could interview only the merchants who make international orders.
* Make it super easy for the merchant to give us feedback (big `<textarea>` with a Send button and that's it) so we can contact him back by e-mail.

Maybe we should only do this if the merchant used Connect since it was a Beta version, because I think this could be too "pushy" and intrusive to the average merchant.

**Comment by jeffstieler** [comment]
Closing this in favor of directing people to support / forums. Will be taken care of in https://github.com/Automattic/woocommerce-services/issues/941.
