### ISSUE TITLE
Add Compatibility with Multiple Shipping Addresses Extension

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-services#762]
Not in scope for MVP.  To be considered for a later release.

https://github.com/woocommerce/woocommerce-shipping-multiple-addresses

**Comment by madeincosmos** [comment]
Just got a request about it from a user in 1409669-zen. Are there any plans to add it anytime soon?

**Comment by jconroy** [comment]
Closing in favor of tracking popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747548-add-compatibility-with-multiple-shipping-addresses)
