### ISSUE TITLE
Display an 'updated TOS' dismissible notice on demand

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#770]
The design conversation is happening in #736 

# Requirements:
- get notified by the server that a notice needs to be displayed
- display an entirely custom message, or a message with custom info:
  - TOS link
  - TOS GH changeset link
  - date
  - product name
- notice can be dismissed
- record when the date/time the notice is dismissed
- let the server know when the notice was dismissed

# Things we want to log (this is also related to the server)
- when a notice is sent to a site (server-related)
- when the site receives the notice (client-related)
- when the notice is dismissed (client-related)

# Possible approaches to receiving the updated TOS notice (no digging has yet been done on these):
1. Client asks server periodically if there are any notices to display. Every X days?
2. Client asks server if there are any notices to display based on user action (going to WCC screen, printing label, etc)
3. Server always sends notice-related data with all responses

# Possible approach to recording notice status:
- use a WordPress option called something like `wc_connect_updated_tos_notice` (since we already have `wc_connect_tos_accepted`), with this info:
  - the contents of message
  - a message slug or other ID
  - date of acceptance
- delete when notice dismissal successfully logged on the server

**Comment by v18** [comment]
Q: What happens when there are two or more notices in a row (unlikely scenario)?
A: probably the best move is to add to `wc_connect_updated_tos_notice` (in case we still have not finished recording the dismissal of the previous one) and display only the latest

Q: does accepting TOS depend on having a working JP connection?

**Comment by jeffstieler** [comment]
> Q: What happens when there are two or more notices in a row (unlikely scenario)?
A: probably the best move is to add to wc_connect_updated_tos_notice (in case we still have not finished recording the dismissal of the previous one) and display only the latest

Thinking about this like a generic notice system.. multiple simultaneous notices could be possible. (More so than a strictly ToS implementation)

Keeping with the generic idea.. perhaps not all notices need to have their dismissal/acceptance logged, and don't all need to be displayed on the same admin screens. We can certainly start with a "show all the notices everywhere we can" approach, but let's keep in mind a potential future where we're more selective about display.

> Q: does accepting TOS depend on having a working JP connection?

Currently, the banner is shown without checking for an active Jetpack. You can accept the ToS without JP, but we won't be able to track that action. Definitely an area we can focus some NUX love.

**Comment by v18** [comment]
Question: who should the TOS notice be displayed to? The store owner? Who is that - the person who accepted the TOS in the first place? user who made JP connection? someone else? multiple people?

**Comment by jeffstieler** [comment]
> Question: who should the TOS notice be displayed to? The store owner? Who is that - the person who accepted the TOS in the first place? user who made JP connection? someone else? multiple people?

Excellent question. The ToS should probably only be shown to the "owner" of the Jetpack connection. (cc @jennyzhu)

**Comment by jennyzhu** [comment]
Yeah, the closest thing to the account owner should see the notice, so I assume that's the "owner" of the Jetpack connection?

**Comment by v18** [comment]
thanks for the input!

@jeffstieler - If I understand things correctly, it seems like the original Jetpack user who made the connection to WCC is who we want, since this is the person WCC has the original agreement with. hopefully it'll be obvious to find them 👀

I wonder if there are any repercussions if this original user no longer connected to Jetpack - does it mean we may not be able to trust their consent? Or, do we still trust who they are because we know what their username is on their .org site?

I'm not super familiar yet with NUX to know how we'd react to a JP cxn drop, or switching JP users, so I'll do a few walkthroughs to see if that sheds some light :)

**Comment by jeffstieler** [comment]
> @jeffstieler - If I understand things correctly, it seems like the original Jetpack user who made the connection to WCC is who we want, since this is the person WCC has the original agreement with. hopefully it'll be obvious to find them 👀

@v18 - sorry I didn't elaborate on this - we're currently using the Jetpack "master user". See: https://github.com/Automattic/woocommerce-connect-client/blob/d7259a5fc24fc2063087f1ab0802bf71fc55196c/classes/class-wc-connect-settings-pages.php#L142

One issue we currently have is that we aren't only showing the ToS notice to that master user - anyone can accept it: https://github.com/Automattic/woocommerce-connect-client/blob/b24b15a3a06438ac52b0fffeaa75c61b41f45efb/woocommerce-connect-client.php#L664

I'll write this up ^^ as we'll want to make sure the connection "owner" is the only person who can accept the ToS.

> I wonder if there are any repercussions if this original user no longer connected to Jetpack - does it mean we may not be able to trust their consent? Or, do we still trust who they are because we know what their username is on their .org site?

We don't currently handle this, but we should be able to if/when it occurs on a site. Jetpack updates the `master_user` option, so we should be able to detect changes and prompt for ToS acceptance if we need to. (again, cc: @jennyzhu 👋 )

> I'm not super familiar yet with NUX to know how we'd react to a JP cxn drop, or switching JP users, so I'll do a few walkthroughs to see if that sheds some light :)

👍

**Comment by v18** [comment]
Ah, thanks for the notes @jeffstieler! I also chatted with @jennyzhu about this, and we're all set to use the `master_user` from a TOS perspective.

**Comment by jeffstieler** [comment]
Closing this now that we're directly using the WordPress.com TOS. Users get email notifications when terms change.
