### ISSUE TITLE
Label ID vs. Label Number

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#772]
In the client, the list of labels presented to the user are shown as follows:

![image](https://cloud.githubusercontent.com/assets/11143071/21914327/6819b6ec-d8e7-11e6-84e4-c9aaa94a397a.png)

This number that is displayed is actually the label's MySQL ID. How about we do one of the following:
- hide it altogether
- Presented it as a ID and not a number
- Show the easypost label ID instead of this integer value

**Comment by nabsul** [comment]
@kellychoffman for design input.

**Comment by jeffstieler** [comment]
It looks like the ID was added in the development part of this feature, not the design. See: https://github.com/Automattic/woocommerce-connect-client/pull/734#issuecomment-264846542

I think the intention is good, but the actual Label ID will grow to be quite large, and not really helpful (and likely not the way the merchant is thinking about this list of labels).

How about we just turn this into a count of labels on the order? Always 1 - N?

**Comment by nabsul** [comment]
> How about we just turn this into a count of labels on the order? Always 1 - N?

I think that's a great idea.  I would also add: Let's sort the labels by ID. That way it will be easy to map the 1-N number to the label in the backend.
