### ISSUE TITLE
Better handling of multiple label purchases

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#773]
When I purchase labels for multiple packages, the system is all-or-nothing. I can either buy a label for each of my packages, or no labels at all.

This is especially troublesome if I refund one of the labels and then try to go back and purchase it. Even though I can get refunds on individual labels, I can't go back and purchase a label for just that single package.

**Comment by jeffstieler** [comment]
> This is especially troublesome if I refund one of the labels and then try to go back and purchase it. Even though I can get refunds on individual labels, I can't go back and purchase a label for just that single package.

Can you not single out the item to be shipped, using the "save for later" mechanism?

**Comment by kenmg77** [comment]
I have the same issue - often times we must ship items that are instock ready to ship while other items may delay a day or two for customizations.  We need to be able to print the first label

**Comment by kenmg77** [comment]
@jeffstieler  where is this save for later mechanism?  When moving products out of the first package you can move them into a second package- but not save them for later... if you move them to a second package you're not allowed to save that package for later.

**Comment by kenmg77** [comment]
Thanks for the suggestion- the challenge with the solution below is that a
visitor cannot get a notification that one item has shipped while the other
has not... they cannot log into their account and see what has shipped.

Think about when you order multiple items on amazon.com - they often ship
in different boxes with different tracking numbers from different locations
and at different times.

**Comment by jeffstieler** [comment]
@kenmg77 thanks for the feedback - that sounds like a useful feature (one we don't currently have).

Would you mind opening an enhancement request with some more details on how you'd like "save for later" and/or the shipment details on the "my account" page to work? Thank you!

**Comment by kenmg77** [comment]
thanks @jeffstieler I'd be happy to- where would I do that? (DUH moment)

**Comment by jeffstieler** [comment]
@kenmg77 https://github.com/Automattic/woocommerce-services/issues/new :)

**Comment by v18** [comment]
Related: https://github.com/Automattic/woocommerce-services/issues/1449

**Comment by laurendavissmith** [comment]
Closing since its very similar to https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/33876214-bulk-printing-of-shipping-labels-in-woocommerce
