### ISSUE TITLE
Question: should we automatically store payment info on the Account Settings screen?

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#779]
Currently, when a merchant visits the "Account Settings" page (WooCommerce > Settings > Connect for WooCommerce) their WordPress.com saved payment methods are displayed.

If they only have one saved payment method, we automatically save it as the store's chosen method of payment for Connect services. Relevant code: https://github.com/Automattic/woocommerce-connect-client/blob/master/classes/class-wc-connect-payment-methods-store.php#L52-L80

While this payment method is their only choice in this scenario - the merchant hasn't explicitly chosen it. This doesn't feel right to me.

Thoughts @kellychoffman @jennyzhu ?

**Comment by kellychoffman** [comment]
> the merchant hasn't explicitly chosen it

Agree; it needs to be exposed during any purchase step, for example when printing a label.

**Comment by jennyzhu** [comment]
Thanks for the ping! Sorry, I'm not sure I understand the question -- do you mean that we shouldn't default to a payment method at all, and should always ask the merchant to add or select one? 

What are you suggesting we expose, @kellychoffman?

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1076
