### ISSUE TITLE
Make CI run with PHP7 and more versions of WordPress

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#780]
Right now, CI runs with the folowing versions of WordPress:
* 4.4
* LATEST

We should aim for it to run in all the major versions of WordPress we support (that is, 4.4, 4.5, 4.6 and LATEST [4.7]).

Also, CI runs with these versions of PHP:
* 5.2
* 5.3
* 5.4
* 5.5
* 5.6

We should add PHP 7.0 and 7.1.

There's no need to include all the combinations in the TravisCI `matrix`. I think a sensible list of runs will be something like this:
* PHP 5.2 - WP 4.4
* PHP 5.2 - WP 4.5
* PHP 5.2 - WP 4.6
* PHP 5.2 - WP 4.7
* PHP 5.3 - WP 4.7
* PHP 5.4 - WP 4.7
* PHP 5.5 - WP 4.7
* PHP 7.0 - WP 4.7
* PHP 7.1 - WP 4.7

**Comment by jeffstieler** [comment]
We also need to bump the WC version.
