### ISSUE TITLE
If order item quantity is changed, shipping label flow doesn't use that

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#785]

**Comment by jeffstieler** [comment]
I'm assuming this pertains to orders still in "pending" status that have their item quantities changed, and used a WCS shipping rate during checkout.

If so, I see two problems that need solutions:
1. The labels flow doesn't use the new order information after update (happens via AJAX)
1. The data cached at checkout isn't invalidated when the order is manually edited

Does this correctly capture what you observed @nabsul ?

**Comment by laurendavissmith** [comment]
Closing, not enough details to be actionable
