### ISSUE TITLE
Fix price display bug on label refund confirmation dialog

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#808]

**Comment by jeffstieler** [comment]
Please add some details to this. Is it a duplicate of https://github.com/Automattic/woocommerce-services/issues/788 ?

**Comment by nabsul** [comment]
Unfortunately, I don't remember what this was all about. I definitely need to make sure I fill in more details for things like this next time.

Closing for now since it's likely a duplicate.
