### ISSUE TITLE
Getting a server error: Automatically populating $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#810]
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />

**Comment by jeffstieler** [comment]
Closing - this was likely due to core WC's usage of it. WCS doesn't use it. 😄 

See: https://github.com/woocommerce/woocommerce/issues/8848
