### ISSUE TITLE
[Labels UI] You can trigger a rates request even with bogus addresses

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#811]
In the Purchase Label dialog, even if some of the addresses steps is wrong (empty ZIP, for example), you can trigger a rates request, which will fail with a nasty error:

![error](https://cloud.githubusercontent.com/assets/1715800/22178434/4dff4304-e00c-11e6-90d9-cd56e6120508.png)

For example, you can do that by clicking the "Use this package" button on the Packages step. Look for usages of `client/shipping-label/state/actions.js#getLabelRates`.

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/pull/881.
