### ISSUE TITLE
Shipping labels: promote savings to merchant 

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-services#819]
What benefit is it serving? Its too small to see, and the space could be better utilized. We can add a price summary there. Idea:

<img width="495" alt="screen shot 2017-01-22 at 1 20 21 pm" src="https://cloud.githubusercontent.com/assets/5835847/22184319/a24b4d10-e0a5-11e6-8e4d-3fee9909df81.png">

**Comment by DanReyLop** [comment]
Can we get an agreement on this one?

Originally the preview was implemented because "people want to see what they are about to buy", even if it's fake. Now, with the paper size selection it now shows how the labels fit into a page and how many pages it will be. I'm just stating what purpose does it serve, I'm not saying we should neccesarily keep it :)

If we axe this, we can get rid on some technical debt on this component: https://github.com/Automattic/woocommerce-services/issues/598 https://github.com/Automattic/woocommerce-services/issues/718 and specially https://github.com/Automattic/woocommerce-services/issues/675

cc/ @jeffstieler @nabsul @v18 @marcinbot

**Comment by kellychoffman** [comment]
Well, you know my opinion :)

> Now, with the paper size selection it now shows how the labels fit into a page and how many pages it will be

Good point, but this can also be served with the print dialog, which has a preview. And I would guess people aren't switching back and forth between different paper sizes per label. We could add that to a global setting that you set up initially, but one decision at a time 😀

**Comment by jeffstieler** [comment]
> Originally the preview was implemented because "people want to see what they are about to buy", even if it's fake.

I remember this being the motivation, but I don't remember it being backed by anything other than gut feel. Even our Stamps.com extension doesn't show a preview: https://docs.woocommerce.com/document/woocommerce-shipping-stamps/

The only tangible value I can come up with for a preview is to do a test print, but we aren't really facilitating that right now.

What about removing the "preview" from the label modal, and adding a "print test label" feature to the System Status page?

**Comment by kellychoffman** [comment]
That sounds like a plan to me.

**Comment by jeffstieler** [comment]
Giving this issue a kick 😄 ..

![](https://cloud.githubusercontent.com/assets/5835847/22184319/a24b4d10-e0a5-11e6-8e4d-3fee9909df81.png)

This reimagined use of the preview real estate is great - but we can't deliver all of it now, and there are some nuances to discuss.

1. We can't offer insurance (yet)
1. Not all shipping services can be offered to our customers at a discount (including USPS services)
1. We can't email the customer (yet)

In the short term, we could show the selected service, any discount that might apply (but plan for scenarios where no discount shows), and have the option to mark the order complete (though, we've yet to build that in).

@olaolusoga

**Comment by olaolusoga** [comment]
>In the short term, we could show the selected service, any discount that might apply (but plan for scenarios where no discount shows), and have the option to mark the order complete (though, we've yet to build that in).

That sounds fine as we work towards building in more of the features from the mock up.

For scenarios where discount isn't shown, we should remove the *total* row, and just show the selected service.

Having the option to mark the order complete also adds value to the right column. Reduces LOE for user.

**Comment by DanReyLop** [comment]
> In the short term, we could show the selected service [...]

Be aware that in an order with multiple packages, there can be labels from several different services. Even from different carriers (when we finish implementing that).

**Comment by jeffstieler** [comment]
Let's get this going again 😄 

For now, we can focus on the discount alone. Just omit insurance, and the checkboxes.

> Be aware that in an order with multiple packages, there can be labels from several different services. Even from different carriers (when we finish implementing that).

Good point. @kellychoffman what do you think about using language similar to eBay:

![](https://cloud.githubusercontent.com/assets/1595739/18071477/0082a01c-6e0b-11e6-87f8-f2a53e575c34.png)

Where we just say "Postage cost" and not list the service?

**Comment by kellychoffman** [comment]
@avivapinchas or @MarinaWoo: re: https://github.com/Automattic/woocommerce-services/issues/819#issuecomment-333194029. Any thoughts on wording?

**Comment by avivapinchas** [comment]
LGTM!

**Comment by jeffstieler** [comment]
@kellychoffman we're pretty close to a Calypso-first development approach for the labels modal. Can this issue be moved to https://github.com/Automattic/wp-calypso or will the savings mention not fly there for some reason?

**Comment by kellychoffman** [comment]
Yep, lets move it.

**Comment by jeffstieler** [comment]
Supplanted by https://github.com/Automattic/wp-calypso/issues/19935

**Comment by jeffstieler** [comment]
Reopening for easier tracking.

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1268
