### ISSUE TITLE
Update WordPress readme name and description

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#848]
We should change all instances of 'Connect for WooCommerce' and 'hosted services'.

**Comment by nabsul** [comment]
I THINK this was already done by @DanReyLop last night in https://github.com/Automattic/woocommerce-services/commit/9fa6a3739523bebd62d58847189380d1606cf968 . Was anything missed in that PR?

**Comment by v18** [comment]
@nabsul I thought the readme.txt was missing the new name, but I was mistaken! whoops, closing now :)
