### ISSUE TITLE
ERROR in Loader

### ISSUE THREAD

**Issue by syndia** [Automattic/woocommerce-services#852]
I get a message `ERROR in Loader`.

`ERROR in Loader /node_modules/wp-calypso/node_modules/eslint/lib/api.js didn't return a function
 @ ./~/wp-calypso/client/lib/warn/index.js 7:14-31`

I fix it in the webpack.config.js 

`		preLoaders: [
			{
				test: /\.jsx?$/,
				loader: 'eslint',
				include: path.resolve( __dirname, 'client' ), // eslint-disable-line no-undef
			},
		],
`

replaced it with:

`		preLoaders: [
			{
				test: /\.jsx?$/,
				loader: 'eslint-loader',
				include: path.resolve( __dirname, 'client' ), // eslint-disable-line no-undef
			},
		],
`

**Comment by DanReyLop** [comment]
Hi John, thanks for creating an issue!

We didn't have any problem like this, and we are locking our dependencies using `shinkwrap` so you should have exactly the same dependencies as us. Did you install `WebPack2`? With WebPack2, it's no longer allowed to omit the `-loader` suffix from a loader config, so `eslint` must be `eslint-loader` instead (exactly your change). That **shouldn't** affect us until we migrate to WebPack2, but if you didn't mess with the dependency versions, that's more troubling.

**Comment by DanReyLop** [comment]
I'm closing this for now, since we've just migrated to WebPack2 and we didn't run into this error. Please reopen if you keep getting the error.
