### ISSUE TITLE
Design Spike: Multiple Carriers in single Shipping Method Instance

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#892]
Investigate a WCS shipping method that contains all supported carriers in a single instance. For example: one settings form that has USPS, FedEx, and UPS configuration.

**Potential futures to keep in mind:**
* Removal of per-service adjustment fields ($/% based)
* Automatically filter the carriers in each instance based on the Shipping Zone region or instance settings _(e.g. test country/postcode to eliminate Canada Post)_

**Questions:**
* Does each carrier need it's own fallback rate?

**Comment by laurendavissmith** [comment]
Closing, this has been completed by @olaolusoga
