### ISSUE TITLE
On Opening Label Print: If communication with server fails, UI reports invalid address

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#913]
If the store cannot communicate with the server, the user sees an error indicating invalid address.

We should surface a different error so the user doesn't keep trying different addresses when the problem is actually something else.

**Comment by jeffstieler** [comment]
Let's expand this for all requests. If the server can't be reached, the error message should say something to that effect. e.g. "There was a problem contacting the server. Please try again later." or similar

**Comment by dechov** [comment]
Re-opening until this repository is updated with https://github.com/Automattic/wp-calypso/commit/8645a9a8816a92d3e675063f1a0b5fe3da6e2eba.
