### ISSUE TITLE
Add Notice That JetPack Install Is Mandatory For WooCommerce Services

### ISSUE THREAD

**Issue by harishankerr** [Automattic/woocommerce-services#915]
The extension does not work without JetPack installed. It's not mentioned in the plugin description in the WordPress.org listing, but it's mentioned in the installation instructions. It would make sense to:
1. Add a notice after the installation of the plugin to install and activate a JetPack connection (if not already present).
2. Add this in the plugin description in WordPress.org itself.

**Comment by jeffstieler** [comment]
Thanks for the issue @harishankerr!

**Comment by jeffstieler** [comment]
@kellychoffman - do you think any design is necessary for this? Can we perhaps repurpose the TOS notice?

**Comment by kellychoffman** [comment]
As a stop gap until a more robust reworking of our NUX is designed and implemented, adding copy to the TOS notice makes sense to me.

**Comment by jeffstieler** [comment]
> As a stop gap until a more robust reworking of our NUX is designed and implemented, adding copy to the TOS notice makes sense to me.

Sorry, I don't think I was clear enough. The TOS notice will only display to the Jetpack master user if Jetpack is already connected.

What I meant by "repurpose the TOS notice" is to reuse the design of the TOS notice to display a message about needed Jetpack.

**Comment by kellychoffman** [comment]
Gotchya! Thanks for clarifying. Yes, this makes sense to do until a more uniform NUX flow is designed and implemented.
