### ISSUE TITLE
Label Printing Options For Library Mail Missing

### ISSUE THREAD

**Issue by harishankerr** [Automattic/woocommerce-services#916]
While calculating shipping rates for USPS using the WooCommerce Plugin, `Library Rates` are being displayed as an option, as you can .

![Library Rates](http://cld.wthms.co/JKG6/1mYnBzRx+)
http://cld.wthms.co/JKG6/1mYnBzRx

Once this rate has been chosen, the purchase has been made, and when the store owner tries to print the labels, library rates are not available/missing, as you can see in this screenshot below:

![Library Mail Not Working](http://cld.wthms.co/EJ5q/2hyREaGK+)
http://cld.wthms.co/EJ5q/2hyREaGK

So, currently, you can't print shipping labels for Library Mail using WooCommerce Services.

**Comment by jeffstieler** [comment]
Library Mail is an extreme edge case for a "store" to use for shipping. We've removed it.
