### ISSUE TITLE
Order does not match the backend order

### ISSUE THREAD

**Issue by mikkamp** [Automattic/woocommerce-services#918]
When enabling Shipping Services for USPS they are shown in the following order on the backend:

![Backend](https://cloudup.com/cZnP6M0Dic0+)
Image link: https://cloudup.com/cZnP6M0Dic0

On the frontend they show up in a different order:

![Frontend](https://cloudup.com/cdRHWlYr4Zf+)
Image link: https://cloudup.com/cdRHWlYr4Zf

There doesn't seem to be any way to adjust this order.

**Comment by laurendavissmith** [comment]
Closing since we arent focusing on live rates at the moment
