### ISSUE TITLE
Shipping Label Preview is not being generated due to incorrect wcc_server_error_response

### ISSUE THREAD

**Issue by juliaamosova** [Automattic/woocommerce-services#919]
Shipping Label Preview is not being generated and throws error instead:

![](https://cloudup.com/cbOUqerQhVF+)
Image Link: https://cloudup.com/cbOUqerQhVF

**TESTING ENVIRONMENT:**

- WordPress - 4.7.2
- WooCommerce - 2.6.14
- Theme - Storefront
- Plugins enabled:

![](https://cloudup.com/c-ZrfYRGOF5+)
Image Link: https://cloudup.com/c-ZrfYRGOF5

Origin Address: 1480 York Ave, New York, NYC 10075
Shipping Address: 200 Collins Ave, Miami Beach, FL 33139

Same error happens if you add 3 items to the cart (shipped individually) or 1 item>

**3 ITEMS:**

![](https://cloudup.com/ch4lyDpNJ0Q+)
Image Link: https://cloudup.com/ch4lyDpNJ0Q

Shipping Address details:

![](https://cloudup.com/cWpp9_0xnY7+)
Image Link: https://cloudup.com/cWpp9_0xnY7

Tried different shipping address (different state) and same error show up. 

Error:

![](https://cloudup.com/c19pH3FeaHq+)
Image Link: https://cloudup.com/c19pH3FeaHq

Full Error Log: https://cloudup.com/cfergsKULfE

**Comment by jeffstieler** [comment]
Closing - this was likely a tempoarary server-side issue, and preview has been removed from the labels modal.
