### ISSUE TITLE
Package Weight vs Max Weight

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#935]
![http://cld.wthms.co/333u](http://cld.wthms.co/333u+)
Full Image: http://cld.wthms.co/333u+

It would be helpful to add a JS check (and notice) that compares the package weight to the max weight when creating a new box under **WooCommerce > Settings > Shipping > Packages > Add new package**.

**Comment by jeffstieler** [comment]
This was fixed in Version 1.11.0.
