### ISSUE TITLE
All Caps button

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#937]
![http://cld.wthms.co/OCEy](http://cld.wthms.co/OCEy+)
Full Image: http://cld.wthms.co/OCEy+

The upper case on the "ADD NEW PACKAGE" button should be reconsidered; This could be problematic with certain localisations and cultural norms, especially since it's added via CSS - meaning ALL localisations will ALWAYS be upper case.

**Comment by jeffstieler** [comment]
Closing - the "add a package" button is no longer all caps. 🎉
