### ISSUE TITLE
Do now allow user to set negative rates as a fallback

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#938]
![http://cld.wthms.co/1fNCl](http://cld.wthms.co/1fNCl+)
Full Image: http://cld.wthms.co/1fNCl+

I'm not sure of the intention here, but I can't immediately think of a reason why the store manager should be able to set negative values as fallback shipping rates.

**Comment by jeffstieler** [comment]
@DanReyLop let's take care of this as part of the work you're doing in Calypso.
