### ISSUE TITLE
Showing decimal examples for the fallback rates

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#939]
![http://cld.wthms.co/1hvQR](http://cld.wthms.co/1hvQR+)
Full Image: http://cld.wthms.co/1hvQR+

When setting a fallback rate containing a decimal value, it would be helpful to show examples of the format to be used.

Example:

* ```$10.99```; vs
* ```$10,99```

Notice the period vs comma. This will also change between localisations and is especially important when services expand to _other_ countries.

**Comment by laurendavissmith** [comment]
Closing since we are not focusing on live rates at the moment
