### ISSUE TITLE
Localhost warning

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#940]
I knew _nothing_ about WooCommerce Services requirements (coming in from a "cold" install) and initially tried to install it on MAMP, and then on Vagrant, while having Jetpack installed.

It took the helpful guidance of fellow teammates to point out that you need a _live_ server for it to work (30min later). It would have been helpful if this warning was evident on the dashboard. On Mamp/Vagrant, the plugin installed just fine but settings were nowhere to be found and there were no instructions on .org or the plugin documentation.

**Comment by laurendavissmith** [comment]
Closing, since ideally this would come from Jetpack
