### ISSUE TITLE
Add contextual plugin links

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#941]
![http://cld.wthms.co/lglA](http://cld.wthms.co/lglA+)
Full Image: http://cld.wthms.co/lglA+

It would be helpful to add direct links to plugin settings and the correct support channel at **Plugins > All Plugins > WooCommerce Services** (compare that with Jetpack and WooCommerce).

**Comment by jeffstieler** [comment]
I'm not sure where we'd link to for "Settings" - even in it's current shipping-only form, WCS has multiple intersection points with WC settings.

Where should we link to for "Support"?

**Comment by jeffstieler** [comment]
> Where should we link to for "Support"?

Following up - @shaunkuschel said point this to the ticket form here: https://woocommerce.com/my-account/create-a-ticket/?

We should also change the "report a bug" link on the System Status page to be "open a support ticket", or similar:

<img width="719" alt="screen shot 2017-03-28 at 3 57 44 pm" src="https://cloud.githubusercontent.com/assets/63922/24431160/942e5a82-13d7-11e7-8bff-baec5809affb.png">
