### ISSUE TITLE
Add "Copy Log" button in System Status

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#942]
![http://cld.wthms.co/SdZk](http://cld.wthms.co/SdZk+)
Full Image: http://cld.wthms.co/SdZk+

It would be nice if customers could easily copy the debug log from **WooCommerce > System Status > WooCommerce Services Debug**. This allows customers to quickly and easily copy a log, which can then be forwarded to support staff.

**Comment by jeffstieler** [comment]
This can use Calypso's `ClipboardButton` component. 👍
