### ISSUE TITLE
Shipping Labels settings refinement

### ISSUE THREAD

**Issue by jeffstieler** [Automattic/woocommerce-services#943]
Right now, the settings for "Shipping Labels" only contain payment method, without much explanation.

![screen shot 2017-03-21 at 12 26 56 pm](https://cloud.githubusercontent.com/assets/63922/24164256/b5482fb8-0e32-11e7-9207-aea408f8e20a.png)

The payment method setting is also only shown to the Jetpack connection owner, and not any Shop Manager who can manage other sensitive store settings (like Payment Gateways, etc).

![screen shot 2017-03-21 at 12 31 45 pm](https://cloud.githubusercontent.com/assets/63922/24164264/b8907ed2-0e32-11e7-9075-ca361561fb8d.png)

What can we do to improve this screen? @olaolusoga

**Comment by DanReyLop** [comment]
From the amazing "We met in Lisbon so naturally we ripped your plugin apart and found all the bugs" post, Shaun notes this concern:

> The “Shipping Labels” tab shows the payment methods available to purchase labels. Is this tab supposed to show purchased labels or should it be renamed to something else? 

So, while I get why it's named like that, as long as we only have 1 section there (Payment Method), it looks weird that the tab is called something completely different.

**Comment by jeffstieler** [comment]
Bumping this - perhaps we just need to use the version found in Store now:

![](https://cldup.com/jxpGNbxtgI-3000x3000.png)

**Comment by jeffstieler** [comment]
This is way out of date and will come full circle with https://github.com/Automattic/woocommerce-services/pull/1216
