### ISSUE TITLE
Copy/Transfer Zone settings

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#945]
![http://cld.wthms.co/DIVR](http://cld.wthms.co/DIVR+)
Full Image: http://cld.wthms.co/DIVR+

In the event that the user wants to add a markup cost to each of the rates returned, they're in for a world of setting-hurt. This is further exacerbated by each shipping zone they use WC Services for.

It would be nice to:
* Be able to copy/transfer rate settings between zones;
* Be able to bulk edit all rates _within_ the same shipping method

**Comment by laurendavissmith** [comment]
Closing since we are not focusing on live rates at the moment
