### ISSUE TITLE
Price adjustment field too small

### ISSUE THREAD

**Issue by RiaanKnoetze** [Automattic/woocommerce-services#946]
![http://cld.wthms.co/WgI6](http://cld.wthms.co/WgI6+)
Full Image: http://cld.wthms.co/WgI6+

The Price adjustment field only caters for double digits; Any more and it gets cut off. This is troublesome if:

* The user wants to use adjustments with decimals; OR 
* The user uses a currency where hundreds/thousands are the norm, e.g. Rupees or Ruble etc. (Not a major issue with the _current_ list of supported services)

**Comment by laurendavissmith** [comment]
Closing since we arent tackling rates work right now
