### ISSUE TITLE
Clarify the wording in the “Packing Method” section

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#947]
Please see the screenshot below:

![Screenshot](https://cloudup.com/cZiVlQ-MEar+)

Link to image: https://cloudup.com/cZiVlQ-MEar

Does the box packer know the cheapest method to pack into? How does it know when packing individually is cheaper?

**Comment by jeffstieler** [comment]
We actually aren't comparing the packed price to the individual. Perhaps this should say:

> When possible, pack multiple items in a single package.

^^ because not all orders will fit in one box.

**Comment by jeffstieler** [comment]
Proposing a different edit for this.. instead of:

> When possible, pack multiple items in a single package.

How about:

> Pack items together, in as few packages as possible.

?

**Comment by joelwills** [comment]
Sounds good to me!

**Comment by jeffstieler** [comment]
This should be fixed with the latest server deploy (5 days ago).
