### ISSUE TITLE
Clarify the wording of “Box Weight” and “Max Weight”

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#950]
We often see confusion over Max Weight with the user entering the weight of the box here again. This then means nothing can be packed into it leading to user frustration.

Suggestions:

"Max weight box can hold"

"Max weight of contents in box"

"Max weight of products in box"

**Comment by jeffstieler** [comment]
This will be resolved with https://github.com/Automattic/woocommerce-services/pull/1216.

Sneak peak:

![screen shot 2017-11-17 at 6 25 25 pm](https://user-images.githubusercontent.com/63922/32975488-c5c74900-cbc4-11e7-80ca-e1ae25798b92.png)

**Comment by joelwills** [comment]
Thanks @jeffstieler !

**Comment by jeffstieler** [comment]
Closed in https://github.com/Automattic/woocommerce-services/pull/1216

**Comment by dogstalker** [comment]
As a user this was still confusing.  It would have helped to know that the max isn't just the max weight the package can hold but also, the weight of the package. Maybe something like:

"Total max weight including both packaging and contents"

**Comment by jeffstieler** [comment]
@dogstalker - I've opened a pull request to change the labeling, see: https://github.com/Automattic/wp-calypso/pull/23512

We'll include that in the next version of WooCommerce Services. Thanks for your feedback!
