### ISSUE TITLE
Canada Post does not have “Predefined packages”

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#951]
Canada Post does not have “Predefined packages” it would need to use the “Custom packages” but this isn’t clear- especially when USPS is set up as well and all of the USPS Predefined packages show up.

![Screenshot](http://joelwills.com/4t42+)

Link to image: http://joelwills.com/4t42

Come clarity over that custom boxes need to be added for Canada Post during the setup would be great.

**Comment by laurendavissmith** [comment]
Closing since we are not focusing on live rates work at the moment
