### ISSUE TITLE
Custom package dimensions naming is inconsistent

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#954]
Should be either “Inner” and “Outer” or “Interior” and “Exterior”. 

Currently it is “Inner” and “Exterior”. 

In order to be consistent with the rest of the docs of other shipping extensions, we should have it as “Inner” and “Outer”: 

![Screenshot](https://cloudup.com/cLbbFLpgjRy+)

Link to image: https://cloudup.com/cLbbFLpgjRy

**Comment by laurendavissmith** [comment]
Closing since it looks like this has been updated since it was reported
