### ISSUE TITLE
Method name changes on new shipping service

### ISSUE THREAD

**Issue by joelwills** [Automattic/woocommerce-services#955]
After adding a service to a shipping zone, it starts out showing up as “USPS (WooCommerce Services)” and then changes to just say “USPS” later.

I assume it's because the Shipping method title when you edit is different to the original title. Then on saving it uses the "new" title, even though you haven't changed it. 

![Screenshot](https://cloudup.com/c8P-K-wmJUB+)

Link to image: https://cloudup.com/c8P-K-wmJUB

**Comment by laurendavissmith** [comment]
Closing since we are not focusing on live rates at the moment
