### ISSUE TITLE
[Labels UI] UI for selecting rates from multiple carriers

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#957]
In the "Rates" step of the "Purchase Label" modal, for each package we'll show *all* the available services that the merchant can use. Obviously there won't be rates from all the carriers (if there's a US domestic shipment I doubt we'll get rates from New Zealand Post), but there will be more than now.

We need to figure out how to show those rates to the user. The simplest option would be grouping them by carrier, using `<optgroup>` tags.

Side note: Maybe if the user selects rates from different carriers for different packages we should show a warning. I doubt that going to 2 postal offices for a single shipment is a desired use case 90% of the time.

**Comment by laurendavissmith** [comment]
Closing as this is work @olaolusoga has done and will be implemented in forthcoming issues
