### ISSUE TITLE
Design: Help users pick the services that suit them

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#965]
In our user tests, we noticed that users had a hard time picking which services suit them.

Some questions that came up:
- which packages fit me?
- what's the difference between these services?
- how do I tell which ones I need?
- can't it figure it out for me?

This was related to this list:

<img width="746" alt="screen shot 2017-03-28 at 11 28 59 pm copy" src="https://cloud.githubusercontent.com/assets/11487924/24460198/940fb5d4-146b-11e7-9f68-6ce186bff49b.png">

cc @olaolusoga 

#user-test-march-2017

**Comment by laurendavissmith** [comment]
@olaolusoga what are your thoughts on this one?
