### ISSUE TITLE
After a shipping method is added, open it immediately or nudge (Core?)

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#966]
In user tests, we noticed that after a shipping method is added, it's not clear what to do next.

The correct next step is to click the shipping method link to configure its settings.

Some ideas for how to solve it:
1) Open the shipping method settings page immediately after adding it (this might be a core fix)
2) Add a nudge/tooltip to indicate that the settings should be updated, with a link to the settings page
3) Make the method usable right after it's added by setting smart defaults

#user-test-march-2017

**Comment by jeffstieler** [comment]
> Open the shipping method settings page immediately after adding it (this might be a core fix)

After looking at the shipping zone UI changes in WC 3.0, I think this might be the only way to improve the 2.6 experience, and it would need to live in our plugin.

**Comment by v18** [comment]
@jeffstieler cool! Is there something similar that should be done for 3.0 or should we leave it as-is there?

**Comment by jeffstieler** [comment]
> Is there something similar that should be done for 3.0 or should we leave it as-is there?

The UI has some big improvements, largely reducing multiple paths to a settings screen down to one, and having much clearer instructions and calls to action. I'm inclined to see how new merchants get on with that UI without mucking with it.

**Comment by dechov** [comment]
In https://github.com/Automattic/wp-calypso/pull/20908, we are showing the settings right in the shipping method dialog before you've even saved it:

![calypso-shipping-method-settings](https://user-images.githubusercontent.com/1867547/36757793-75c663fc-1be0-11e8-8de2-002491031ece.png)

Would it be possible (and/or desirable) to hook into the wp-admin dialog to do the same?

**Comment by dechov** [comment]
As discussed in p1528234199000027-slack-hydra, the approach here should be considered in light of:
- appropriate defaults being set for each field (which wasn't true when this issue was opened)
- the shipping method settings not actually saving / begin working if the form is "pristine" (which could be filed as a separate bug).

Caveat to (a) is that it would open up a path to encountering the bug in https://github.com/Automattic/woocommerce-services/issues/1422, as @v18 has pointed out.

@DanReyLop reasoned that the method should work as soon as you create it – this could also be filed as a separate bug, and would at least somewhat decrease the need for alerting the user to the settings.

As it stands, we should certainly make it easier to get the method working with default settings. Any other ideas on how to proceed?

**Comment by v18** [comment]
> Caveat to (a) is that it will open up a path to encountering the bug in #1422, as @v18 has pointed out.

That may be a plus in this case, since the merchant will need to correct the zipcode before saving the shipping zone.

> As it stands, we should certainly make it easier to get the method working with default settings. Any other ideas on how to proceed?

A couple of ideas (mentioned in the OP, too):

- Redirect to the shipping method setting pages immediately after it's created (using a change to core, or in our plugin only for now)
- Show a tooltip to let the user know they should edit the shipping method

**Comment by DanReyLop** [comment]
> As it stands, we should certainly make it easier to get the method working with default settings. Any other ideas on how to proceed?

I'll throw another one: Make the method work without saving. When you create a Flat Rate / Free Shipping method you don't need to edit it and save it, so we should be able to do the same. At the moment of creation, just save it with the default values. Things would be more complicated in the case that the ZIP code is not valid though.

**Comment by v18** [comment]
I like it 🤔 I wonder what good default values would be:
zipcode: store's zipcode (should we worry about users who may be using different fulfillment centers than the address listed in their WC settings)
default shipping services: ?, maybe flat rate
price adjustment: $0
fallback rate: unsure about this one

**Comment by v18** [comment]
Another question to ponder: What do other 'more complicated' shipping methods do? Like table rates, for example.

**Comment by DanReyLop** [comment]
> default shipping services: ?, maybe flat rate

We already have "smart defaults". Create a new USPS shipping method and go to its configuration screen. You'll see that it has a few services enabled. Those defaults (including the ZIP code) come from the server:
https://github.com/Automattic/woocommerce-connect-server/blob/d41826fca7ac1ca4028c7411f2c056bc40c85b74/lib/shipping/usps/service-settings.js#L185
And every service has a "default" flag to indicate if they should be selected by default:
https://github.com/Automattic/woocommerce-connect-server/blob/93aa07fa5774904c085d97e49f3707b5915a9134/lib/shipping/usps/service-data.js#L18

So, apart from the bogus ZIP scenario, we're fine just auto-saving the shipping method when it's created.

> (should we worry about users who may be using different fulfillment centers than the address listed in their WC settings)

No, IMHO. This is a default, a best-effort kind of thing.

**Comment by jeffstieler** [comment]
+1 to auto-saving on create.

**Comment by v18** [comment]
@jeffstieler - what's your favourite way to solve the problem of a bad zip code when it's automatically created?

Steps to repro that:
1. enter a bad zipcode in WooCommerce > Settings
2. create a new WCS shipping method

**Comment by jeffstieler** [comment]
> what's your favourite way to solve the problem of a bad zip code when it's automatically created?

Can we just validate the postcode in the OBW?

**Comment by v18** [comment]
@jeffstieler sure! do you mean when they enter it on the first page? or do you mean when on the shipping page when adding the live rates shipping methods?

Note: technically we won't be able to validate using WCS if it's not installed yet.

There's another issue - merchants can enter a bad zipcode in WooCommerce > Settings as well. So we should handle that situation, too.

**Comment by jeffstieler** [comment]
> do you mean when they enter it on the first page?

Yep! I think we should fix this in WC core.
