### ISSUE TITLE
Fix NUX nudge to add a shipping service

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-services#967]
Make sure that our currently NUX tooltip works in all cases after installing the plugin. It should show up on WC 2.6 on the Shipping settings page.

<img src="https://cloud.githubusercontent.com/assets/11487924/22233966/6fd324a2-e1c2-11e6-8d2c-b609e3b3fb2a.png">

Related PR: https://github.com/Automattic/woocommerce-services/pull/843

#user-test-march-2017

**Comment by jeffstieler** [comment]
Fixed in https://github.com/Automattic/woocommerce-services/pull/843.
