### ISSUE TITLE
Add a "Test print" button in the labels purchase dialog

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#970]
For more context: https://github.com/Automattic/woocommerce-services/pull/928#issuecomment-289025115

There's already a "Test print" button in the self-help page, but we need another one in the purchase dialog, because they serve 2 different use-cases:
* The merchant wants to make sure everything works while configuring the store (self-help page)
* The merchant wants to check everything works before giving us money (label purchase dialog)

Proposed solution:
Add a button "Test" in the Purchase Label dialog sidebar, at the right of the "Paper size" dropdown, with the same UI and behaviour as in the System Status page. This would be fairly easy to implement and it doesn't add a lot of noise to the dialog.

That button should print "fake labels", but trying to be consistent with the selected rates. For example, if the order has 1 package with USPS and 2 with FedEx, the "Test" printing button should generate a PDF with 1 fake USPS label and 2 fake FedEx labels.

**Comment by jeffstieler** [comment]
@kellychoffman - if we want this, it will need to be done in Calypso. What do you think?

**Comment by jeffstieler** [comment]
If it's not something that feels needed for the Calypso side of the house, we don't need to make it a priority. 👍

**Comment by jconroy** [comment]
Closing in favor of tracking the popularity of this feature on the [ideas board](https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/38747509-add-a-test-print-button-in-the-labels-purchase-d)
