### ISSUE TITLE
Link to Zendesk instead of support forum

### ISSUE THREAD

**Issue by nabsul** [Automattic/woocommerce-services#972]
"Report a bug" below links to the support forum. Should we link directly to Zendesk?

![image](https://cloud.githubusercontent.com/assets/11143071/24553673/c29a3f3a-15df-11e7-86fe-975d179c364c.png)

**Comment by nabsul** [comment]
This is on the WooCommerce Services status page by the way.

**Comment by jeffstieler** [comment]
This is a duplicate of https://github.com/Automattic/woocommerce-services/issues/941, see comment: https://github.com/Automattic/woocommerce-services/issues/941#issuecomment-289930564
