### ISSUE TITLE
Error while buying label

### ISSUE THREAD

**Issue by ahalekelly** [Automattic/woocommerce-services#982]
Today I started getting Unexpected Server Error when I hit the Buy & Print button. I tried twice, and my card still got charged both times. Is there a way to check the logs and see what the error was? I installed a couple updates last night, including going from Woocommerce 3.0.1 to 3.0.2.

**Comment by DanReyLop** [comment]
Hi,

I can see that, as you said, the purchases went through in our system (I'll refund you the 2 purchases after this is sorted out). So, the error was somewhere between our server responding to your site, and your site actually showing the PDF to print.

With any luck, there will be something in the log on `WooCommerce -> System Status -> WooCommerce Services`.

Do you at least see the purchased labels in the `Order` page? So you can try to `Reprint` or `Refund`?

We've had some problems with compatibility with WooCommerce 3.0, but I don't see anything specific to `3.0.2` that would break the plugin. Until we release a fix, you'll need to turn `WP_DEBUG` off. Maybe you turned it on last night while you were updating things? That would solve this easily :)

**Comment by ahalekelly** [comment]
Alright, there's nothing in that log, and the labels don't show up on the order's page. I believe the only other plugins I updated were Jetpack and [Variation Swatches](https://wordpress.org/plugins/variation-swatches-for-woocommerce/). `WP_DEBUG` is off. I might revert to a backup and see if that fixes it.

**Comment by ahalekelly** [comment]
It appears to not be an issue with any update, but with creating a shipment that includes a product variation that no longer exists. Removing the item from the package when creating the label seems to solve the issue. Can someone confirm, and give me a refund for the many labels I've created in this debugging process?

And this might be unrelated, but my package contents list is also empty on every label that I create. Is this what it's supposed to look like?

![Contents list](https://cloud.githubusercontent.com/assets/7078138/25084907/3b8038b4-232d-11e7-9a3f-5d0014c87bb6.png)

**Comment by DanReyLop** [comment]
> It appears to not be an issue with any update, but with creating a shipment that includes a product variation that no longer exists. Removing the item from the package when creating the label seems to solve the issue. 

Thank you very much for tracking that down for us! :)
I've managed to reproduce the error, I'll solve it as soon as possible and update you on this issue when it's fixed.

> Can someone confirm, and give me a refund for the many labels I've created in this debugging process?

Of course! Just to confirm (I don't want to give much private information in a public GitHub issue), I can see that all your recent purchased labels come from a single Order. Do you want refund for all of those labels, or did the last one came through and you want to keep it? If you want to keep it, please give me the last 4 digits of the Tracking Number so I can identify it.

> And this might be unrelated, but my package contents list is also empty on every label that I create. Is this what it's supposed to look like?

It's definitely **not** supposed to look like that. I'll create a separate issue for that, it's probably related with WooCommerce 3.0 changes.

Thanks again for your effort!

**Comment by ahalekelly** [comment]
Thanks for being so responsive! I'm printing the one ending in 9585.

**Comment by DanReyLop** [comment]
Gotcha! I refunded the other labels (7 in total), you should get the money back in your account in a couple of days at most (it's in the hands of the banks now).

I'm keeping this issue open to notify you when we solve the issue for good.

**Comment by DanReyLop** [comment]
@ahalekelly Just a heads-up, we've just released a new version of the plugin (`1.4.1`) with this fix in it. I suspect this isn't a common problem and it's easy to avoid, but nevertheless, it will work as expected now :)
