### ISSUE TITLE
Label missing shipping details

### ISSUE THREAD

**Issue by ahalekelly** [Automattic/woocommerce-services#993]
Found another issue, which also seems to only occur with one order. The label buying process goes through fine, but the PDF generated is missing the USPS markings, tracking number, and bar code. The price of the label is abnormally low, and the tracking number given on the order page does not match the USPS tracking number format, being a 31 digit number starting in 00040897, and ending in the 9 digit zip code + 00, which is apparently the format that Endicia uses for it's internal shipment numbering. Here's a low-res screenshot of the label, I can send you the full version privately if you need it.

![image](https://cloud.githubusercontent.com/assets/7078138/25350203/625a83f2-28f2-11e7-993f-70efd7ac7804.png)

Inserting the address into another order seems to work fine, though I didn't actually order the package. Removing all the items from the broken order doesn't help.

I also just realized that this is the first time I've shipped multiple packages from different orders to the same address.

**Comment by ahalekelly** [comment]
I had a second order have this issue, and they were not a return customer. Can you look into this?

**Comment by DanReyLop** [comment]
Sorry for taking so long, I wanted to make sure everything was correct.

We've recently fixed an error that prevented merchants to get `First-Class Mail` for envelopes. So, until a week ago, you (and your clients) were paying for `First-Class Mail` as if it was sent in a box.

`First-Class Mail` for envelopes is a lot cheaper, but it doesn't provide tracking. The tracking number you received was bogus, next `First-Class Mail` labels for envelopes won't show any tracking number at all.

That kind of label is made to print directly in an envelope (that is, you feed the envelope to the printer), but we've been assured that it works as a regular label too. So, even if it looks different, you can print it, cut it and paste it in your envelope.

We've tweaked the PDF rendering code so the label is properly rotated and scaled, so you can click `Reprint` and print those labels any time you want.

Please tell us if you run into any more trouble.

**Comment by ahalekelly** [comment]
Alright thanks, sorry for the erroneous error report.

**Comment by DanReyLop** [comment]
> Alright thanks, sorry for the erroneous error report.

Oh, but there **was** an error in our side, the envelope labels were rotated incorrectly and the tracking number appeared even though it was bogus, so thanks for letting us know :)
