### ISSUE TITLE
[WCS in WPCOM] Refactor the client so the React app is entirely REST-driven

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-services#995]
Right now, when the PHP code enqueues our JS bundle for execution, it gives also a bunch of data in a global variable (`wcConnectData`) so the React code can use that to initialise itself.

When we move that code (or parts of it) to Calypso, we won't have that luxury. The React sub-applications need to be able to bootstrap themselves without relying on any data. Most of the time, that will mean creating a REST endpoint that will be called when the bundle is initialized, and that endpoint will return all the necessary information.

**Comment by jeffstieler** [comment]
Can this be closed now?

**Comment by DanReyLop** [comment]
Yep.
